### ISSUE TITLE
Refactor Type Script and Lock Script model

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#100]
The `TypeScript` and `LockScript` share the same fields, and they are both `Script` in CKB theories. 
And some models like `NrcFactoryCell` also include full fields of `Script`: `code_hash`, `hash_type`, `args`
These models should change to make association to `TypeScript` or `LockScript`

**Comment by Keith-CY** [comment]
This feature is expected to be done by 12/28, how is it going

**Comment by Keith-CY** [comment]
Got it, this issue will be marked as held on and re-enabled once you're available.
