### ISSUE TITLE
Sync rejected messages of historical transactions

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#101]
Now rejected transactions will be shown with their rejected message, but historical data are missing and need to be synced from the scratch.

Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/86#issuecomment-1294660310

**Comment by iamyates** [comment]
done, PR: https://github.com/nervosnetwork/ckb-explorer/pull/1053
