### ISSUE TITLE
Remove LocalCache from new_node_data_processor.rb

### ISSUE THREAD

**Issue by iamyates** [Magickbase/ckb-explorer-public-issues#105]
this is a sub issue from: #83 

use Rails.cache instead.

**Comment by Sven-TBD** [comment]
I'm going to close this issue, coz the PR is already finished. @zmcNotafraid

**Comment by zmcNotafraid** [comment]
> I'm going to close this issue, coz the PR is already finished. @zmcNotafraid

This issue is not finished.The related PR was closed.
