### ISSUE TITLE
Add an API to fetch nervos dao records by a specific address

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#110]
[Metaforo](https://metaforo.io/) is going to support DAO of Nervos and it evaluates users by their activities in the [Nervos DAO](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md)

For this target, Explorer is expected to provide an API to fetch activities of a specific address.

The following data are required

- address
- deposit capacity
- average deposit time
- activities
	- tx hash
	- from and to: in some cases `from` and `to` are different
	- block number
	- timestamp
	- type: deposit | withdraw_phase_1 | withdraw_phase_2
	- amount

**Comment by Keith-CY** [comment]
> is this API ok?
> 
> ### request:
> api URL: `/api/v2/dao_events`
> 
> example: `GET` `http://localhost:3000/api/v2/dao_events?address=ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvysl2s77qfcg77ncttwvuz27rrwpp73rsfkvu7x`
> 
> response example:
> 
> ```
> {
>     "data": {
>         "id": "829",
>         "type": "address_with_dao_events",
>         "attributes": {
>             "address": "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvysl2s77qfcg77ncttwvuz27rrwpp73rsfkvu7x",
>             "deposit_capacity": "800000000000",
>             "average_deposit_time": "",
>             "activities": [
>                 {
>                     "tx_hash": "0x6b55511f6985952ea53ed92e5fc23cf5d0fc646b94bf651e5b9014f64a546992",
>                     "from": "...TODO",
>                     "to": "TODO",
>                     "block_number": "147",
>                     "timestamp": "1573865614496",
>                     "type": "deposit_to_dao",
>                     "amount": "800000000000"
>                 },
>                 {
>                     "tx_hash": "0x6b55511f6985952ea53ed92e5fc23cf5d0fc646b94bf651e5b9014f64a546992",
>                     "from": "...TODO",
>                     "to": "TODO",
>                     "block_number": "147",
>                     "timestamp": "1573865614496",
>                     "type": "new_dao_depositor",
>                     "amount": "1"
>                 }
>             ]
>         }
>     }
> }
> ```

LGTM

**Comment by shaojunda** [comment]
> hi, I want to know the attribute `type` is mapping to which column of table `dao_events`,
> 
> ```
>   2   enum event_type: { deposit_to_dao: 0, new_dao_depositor: 1, withdraw_from_dao: 2, issue_interest: 3, take_away_all_deposit: 4 }
>   3   enum status: { pending: 0, processed: 1, reverted: 2 }
> ```
> 
> looks like it's mapping to `status`, am I right? @shaojunda thanks so much~

The type in the feature is not one-to-one with the event_type in dao_events.  dao_events is not includes `withdraw_phase_1` and  `withdraw_phase_2` for now.

**Comment by shaojunda** [comment]
> take_away_all_deposit

event_type is take_away_all_deposit and value is 1 means take_away_all_deposit event happen one time.

**Comment by Keith-CY** [comment]
> For the field `type`, it seems database currently only support `deposit` and `withdraw_phase_2` ( which means withdraw is done ) .

How is the `nervos_dao_withdrawing` cell marked in this transaction(https://explorer.nervos.org/transaction/0x03b92bf409b4e9af3e246a3f5d3fc06836b6765228c3b8e738b44f861192c0fc) if `withdraw_phase_1` is not supported in database?

**Comment by Keith-CY** [comment]
> Sorry I don't have permission to access our `production database`... I think @ShiningRay could help.
> 
> I am trying to establish my own `production database`, which may take long time.
> 
> > > For the field `type`, it seems database currently only support `deposit` and `withdraw_phase_2` ( which means withdraw is done ) .
> > 
> > 
> > How is the `nervos_dao_withdrawing` cell marked in this transaction([explorer.nervos.org/transaction/0x03b92bf409b4e9af3e246a3f5d3fc06836b6765228c3b8e738b44f861192c0fc](https://explorer.nervos.org/transaction/0x03b92bf409b4e9af3e246a3f5d3fc06836b6765228c3b8e738b44f861192c0fc)) if `withdraw_phase_1` is not supported in database?

Testnet/staging has a similar transaction https://pudge.explorer.nervos.org/transaction/0x5f23c2c9ab2648c76f7faf7c92315e63e7b6e1c40ffc03ae6b2cd94cfd848f45

**Comment by Keith-CY** [comment]
Backend PR: https://github.com/nervosnetwork/ckb-explorer/pull/1071

**Comment by Keith-CY** [comment]
Tried with
```bash
## Nervos DAO of an addr
curl "https://testnet-api.explorer.nervos.org/api/v2/dao_events?address=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e"
```

and got response

```json
{
  "data": {
    "id": 6864571,
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e",
    "deposit_capacity": "0",
    "average_deposit_time": "28.961762",
    "activities": [
      {
        "tx_hash": "0xedc7f9705290cfd65fbbacf65d1c9f2a4099b21b43459c012751acefb5661d3b",
        "from": [
          "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e"
        ],
        "to": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e",
        "block_number": "7182237",
        "timestamp": "1667117761919",
        "type": "deposit_to_dao",
        "amount": "10000000000000"
      },
      {
        "tx_hash": "0xb442946e675ec428adcb84271d64318f2b9e9d7ce66f501193fd53a6da430d05",
        "from": [
          "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e"
        ],
        "to": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e",
        "block_number": "7494604",
        "timestamp": "1669620058174",
        "type": "withdraw_from_dao",
        "amount": "10000000000000"
      }
    ]
  },
  "meta": {
    "total": 2,
    "page_size": 10
  }
}
```

where the first activity is 

```json
{
        "tx_hash": "0xedc7f9705290cfd65fbbacf65d1c9f2a4099b21b43459c012751acefb5661d3b",
        "from": [
          "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e"
        ],
        "to": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e",
        "block_number": "7182237",
        "timestamp": "1667117761919",
        "type": "deposit_to_dao",
        "amount": "10000000000000"
      },

```

however `ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e` doesn't exist in inputs of the transaction
https://pudge.explorer.nervos.org/transaction/0xedc7f9705290cfd65fbbacf65d1c9f2a4099b21b43459c012751acefb5661d3b

**Comment by Keith-CY** [comment]
> Tried with
> 
> ```shell
> ## Nervos DAO of an addr
> curl "https://testnet-api.explorer.nervos.org/api/v2/dao_events?address=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e"
> ```
> 
> and got response
> 
> ```json
> {
>   "data": {
>     "id": 6864571,
>     "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e",
>     "deposit_capacity": "0",
>     "average_deposit_time": "28.961762",
>     "activities": [
>       {
>         "tx_hash": "0xedc7f9705290cfd65fbbacf65d1c9f2a4099b21b43459c012751acefb5661d3b",
>         "from": [
>           "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e"
>         ],
>         "to": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e",
>         "block_number": "7182237",
>         "timestamp": "1667117761919",
>         "type": "deposit_to_dao",
>         "amount": "10000000000000"
>       },
>       {
>         "tx_hash": "0xb442946e675ec428adcb84271d64318f2b9e9d7ce66f501193fd53a6da430d05",
>         "from": [
>           "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e"
>         ],
>         "to": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e",
>         "block_number": "7494604",
>         "timestamp": "1669620058174",
>         "type": "withdraw_from_dao",
>         "amount": "10000000000000"
>       }
>     ]
>   },
>   "meta": {
>     "total": 2,
>     "page_size": 10
>   }
> }
> ```
> 
> where the first activity is
> 
> ```json
> {
>         "tx_hash": "0xedc7f9705290cfd65fbbacf65d1c9f2a4099b21b43459c012751acefb5661d3b",
>         "from": [
>           "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e"
>         ],
>         "to": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e",
>         "block_number": "7182237",
>         "timestamp": "1667117761919",
>         "type": "deposit_to_dao",
>         "amount": "10000000000000"
>       },
> ```
> 
> however `ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e` doesn't exist in inputs of the transaction [pudge.explorer.nervos.org/transaction/0xedc7f9705290cfd65fbbacf65d1c9f2a4099b21b43459c012751acefb5661d3b](https://pudge.explorer.nervos.org/transaction/0xedc7f9705290cfd65fbbacf65d1c9f2a4099b21b43459c012751acefb5661d3b)

This transaction contains 5 inputs and almost all of them deposited to `ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg8e9ne6mr8j0lxmqcfg24v9l7v4w38wwcg4s54e`, so they should be listed in the `from` field

**Comment by Keith-CY** [comment]
Example:

Explorer: https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfuemlpjk23a2nr6huseyp9vrlv52us3xq3md38u

```sh
## Nervos DAO of an addr
curl "https://mainnet-api.explorer.nervos.org/api/v2/dao_events?address=ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfuemlpjk23a2nr6huseyp9vrlv52us3xq3md38u"
```

```json
## Response
{
  "data": {
    "id": 888726,
    "address": "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfuemlpjk23a2nr6huseyp9vrlv52us3xq3md38u",
    "deposit_capacity": "",
    "average_deposit_time": "176.702339",
    "activities": [
      {
        "tx_hash": "0x1c533b4533e94e1ad38e53382c7da2afdc6035b4f3b2d2861e9b24764b0af72c",
        "from": [
          "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvrj9xu5du2d59a3zjf3ma3y8getdp2rvsj2qnmr",
          "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq26kgczzucfs0zsymuj6l5l6dcfgpth6fq6sneea",
          "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqf920qzaxtag2v936lzaj29pta80g8a2kgyyfqns",
          "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdgeyajdwyrn8ypex7atyqzj7dkj70623q976kdw"
        ],
        "to": "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfuemlpjk23a2nr6huseyp9vrlv52us3xq3md38u",
        "block_number": "7305918",
        "timestamp": "1654139061683",
        "type": "deposit_to_dao",
        "amount": "554000000000000"
      },
      {
        "tx_hash": "0x4317b0f3a0e91c59fa730d71d671b77bfd226070c1a25d559fa53d1338d6cef0",
        "from": [
          "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfuemlpjk23a2nr6huseyp9vrlv52us3xq3md38u"
        ],
        "to": "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfuemlpjk23a2nr6huseyp9vrlv52us3xq3md38u",
        "block_number": "8613426",
        "timestamp": "1669818008363",
        "type": "issue_interest",
        "amount": "7392730644674"
      },
      {
        "tx_hash": "0x6df0b3fa5eb881910d9490b0983bac5531ba631dd93d2cc5fb6d6bdb8fa03479",
        "from": [
          "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfuemlpjk23a2nr6huseyp9vrlv52us3xq3md38u"
        ],
        "to": "ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfuemlpjk23a2nr6huseyp9vrlv52us3xq3md38u",
        "block_number": "8576902",
        "timestamp": "1669406143799",
        "type": "withdraw_from_dao",
        "amount": "554000000000000"
      }
    ]
  },
  "meta": {
    "total": 3,
    "page_size": 10
  }
}
```

There're 3 kinds(https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md#deposit) of activities

1. deposit
  - from: an array of addresses sends CKB into the `to` address, could be multiple addresses
  - type: `deposit_to_dao`
  - e.g. https://explorer.nervos.org/transaction/0x1c533b4533e94e1ad38e53382c7da2afdc6035b4f3b2d2861e9b24764b0af72c

2. withdraw_phase_1
  - from: an array of addresses requests withdrawal of CKB from the nervos dao, only one address would be in the array because the transformation of nervos dao cell is from a `deposit cell` into a `withdrawing cell`(https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0023-dao-deposit-withdraw/0023-dao-deposit-withdraw.md#withdraw-phase-1)
  - type: `withdraw_from_dao`
  - e.g. https://explorer.nervos.org/transaction/0x6df0b3fa5eb881910d9490b0983bac5531ba631dd93d2cc5fb6d6bdb8fa03479

3. withdraw_phase_2
  - from: an array of addresses finishes withdrawal of CKB from the nervos dao, it could include multiple addresses because unlocking several nervos dao cells is possible but usually it only has one address
  - type: `nervos_dao_withdrawing`
  - e.g. https://explorer.nervos.org/transaction/0x4317b0f3a0e91c59fa730d71d671b77bfd226070c1a25d559fa53d1338d6cef0

**Comment by Keith-CY** [comment]
```bash
curl "https://mainnet-api.explorer.nervos.org/api/v2/dao_events?address=ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqd6ft377wctkyzgafzvd0ntw7v6gq47uxss0dz0x"
```

returns 502 error

And I found this address has a special nervos dao transaction that includes 2 nervos dao cells

**Comment by Keith-CY** [comment]
> after discussion, the new response format looks like:
> 
> GET [ckb-explorer-api.staging.layerview.io/api/v2/dao_events?address=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgvtprgmzeur3kf70e5cmvf3yzjlmjdlnsc2q6es](https://ckb-explorer-api.staging.layerview.io/api/v2/dao_events?address=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgvtprgmzeur3kf70e5cmvf3yzjlmjdlnsc2q6es)
> 
> ```
> {
>     "data":{
>         "id":4927756,
>         "address":"ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgvtprgmzeur3kf70e5cmvf3yzjlmjdlnsc2q6es",
>         "deposit_capacity":"",
>         "average_deposit_time":"0.000817",
>         "activities":[
>             {
>                 "transaction_hash":"0x88821aaa0e86137c64b5945cfdd39a012342d4dc86969fd1eb2061ecd7034dba",
>                 "block_number":"5918808",
>                 "block_timestamp":"1656991435839",
>                 "display_inputs":[
>                     {
>                         "id":"59561528",
>                         "from_cellbase":false,
>                         "capacity":"1000000000000.0",
>                         "address_hash":"ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdjf5wcpsdd2x9wcr62t867y0scjwttdsgd7k4pq",
>                         "generated_tx_hash":"0x6db0eadfa17904eb6bc54c2f8ed19c3910d227e2258122acaac8c77931b48bad",
>                         "cell_index":"8",
>                         "cell_type":"normal",
>                         "since":{
>                             "raw":"0x0000000000000000",
>                             "median_timestamp":"0"
>                         }
>                     }
>                 ],
>                 "display_outputs":[
>                     {
>                         "id":"59561658",
>                         "capacity":"500000000000.0",
>                         "address_hash":"ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgvtprgmzeur3kf70e5cmvf3yzjlmjdlnsc2q6es",
>                         "status":"dead",
>                         "consumed_tx_hash":"0x5e9c3740b18ec7521bf35040a4332af1f6643e0162a0a55e93baba5e3a9adc14",
>                         "cell_type":"nervos_dao_deposit"
>                     },
>                     {
>                         "id":"59561659",
>                         "capacity":"499999943800.0",
>                         "address_hash":"ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdjf5wcpsdd2x9wcr62t867y0scjwttdsgd7k4pq",
>                         "status":"dead",
>                         "consumed_tx_hash":"0x5e9c3740b18ec7521bf35040a4332af1f6643e0162a0a55e93baba5e3a9adc14",
>                         "cell_type":"normal"
>                     }
>                 ]
>             }
>         ]
>     },
>     "meta":{
>         "total":3,
>         "page_size":10
>     }
> }
> ```

There are two major changes:
1. `from` and `to` are replaced with `display_inputs` and `display_outputs`
2. `activity type` and `amount` are removed

These changes are made because we detected some complex nervos dao transactions on the chain that a transaction may contain multiple actions/activities.

With the new API, the activity type is determined by the composition of transaction inputs and outputs.

There's a field `cell_type` in `display_input/display_output` which has three values:
1. normal
2. nervos_dao_deposit
3. nervos_dao_withdrawing

The lifeline of a cell in nervos dao is as follows:

```
normal cell  --(deposit)--> nervos_dao_deposit cell --(request withdrawal)--> nervos_dao_withdrawing cell --(finish withdrawal)--> normal cell
```

There're three activities
- Deposit: `normal cell` in inputs and `nervos_dao_deposit cell` in outputs
- Request withdrawal, viz. Withdraw phase 1: `nervos_dao_deposit cell` in inputs and `nervos_dao_withdrawing cell` in outputs
- Finish withdrawal, viz. Withdraw phase 2: `nervos_dao_withdrawing cell` in inputs and `normal cell` in outputs

Please notice there could be multiple activities in one transaction, e.g. https://explorer.nervos.org/transaction/0x849344fb19994c00f18809078b720525e32701ba9b81988bbe992fa322e10152
