### ISSUE TITLE
Incorrect nft action

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#114]
https://pudge.explorer.nervos.org/nft-collections/18068
![image](https://user-images.githubusercontent.com/7271329/204483276-71fdeed9-7b09-483f-89b6-0687e99445f3.png)
The action is not recognized correctly

**Comment by ShiningRay** [comment]
The tx type field returned by cota aggregator RPC is different from its document.
I've submitted a issue.
 https://github.com/nervina-labs/cota-aggregator/issues/138

**Comment by ShiningRay** [comment]
Compatible fix: https://github.com/nervosnetwork/ckb-explorer/pull/1109
