### ISSUE TITLE
[block/list] the last button doesn't work

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/ckb-explorer-public-issues#116]
### https://pudge.explorer.nervos.org/block/list
click the `last` button  , but no response
<img width="718" alt="image" src="https://user-images.githubusercontent.com/32102187/206145146-ddc7297d-98f8-4de7-8453-24b82f93f5b5.png">

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1188
