### ISSUE TITLE
[discord]The invitation is invalid

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/ckb-explorer-public-issues#117]
<img width="1330" alt="image" src="https://user-images.githubusercontent.com/32102187/206152049-aaba4fe9-1567-41f5-9a7c-997ce23a4493.png">
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/32102187/206152163-4c6c6228-837e-4b10-8c11-3d9931230333.png">

**Comment by Keith-CY** [comment]
It's been fixed by https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1140
