### ISSUE TITLE
Add script info of joyid

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#123]
Add the script info of joy id on https://explorer.nervos.org/scripts

Info:
1. cell info as follows
```
{
  "code_hash": "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e",
  "hash_type": "type",
  "out_point": {
    "tx_hash": "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c",
    "index": "0x2"
  },
  "dep_type": "code"
}
```
2. RFC or document
3. Source code
4. Website

**Comment by Keith-CY** [comment]
Need help from @duanyytop and @shaojunda about points 1(cell info) and 3(source code)

**Comment by duanyytop** [comment]
The JoyID contract is still under development and has only been deployed on the Testnet. It is recommended not to display it on explorer.

**Comment by Keith-CY** [comment]
> The JoyID contract is still under development and has only been deployed on the Testnet. It is recommended not to display it on explorer.

Got it. Please let me know once it's ready, thanks in advance.

**Comment by ShiningRay** [comment]
We shall save contract information and labels in database.

**Comment by Keith-CY** [comment]
Joy ID has been officially deployed on the mainnet, script Info are as follows:
Lock hash: 0xd00c84f0ec8fd441c38bc3f87a371f547190f2fcff88e642bc5bf54b9e318323
Address: ckb1qrgqep8saj8agswr30pls73hra28ry8jlnlc3ejzh3dl2ju7xxpjxqgqqxeatgq4dlfducznmfeffs9cu034x9248qv4wayg

**Comment by duanyytop** [comment]
### Deployment

```
lock.code_hash: 0xd00c84f0ec8fd441c38bc3f87a371f547190f2fcff88e642bc5bf54b9e318323
lock.hash_type: type

cell_dep.tx_hash: 0xf05188e5f3a6767fc4687faf45ba5f1a6e25d3ada6129dae8722cb282f262493
index: 0x0
cell_dep.dep_type: dep_group
```

**Comment by duanyytop** [comment]
- JoyID Docs:  https://docs.joy.id/
- Source code has not been open-source
- website: https://joy.id/

**Comment by zhangyouxin** [comment]
frontend pr: https://github.com/Magickbase/ckb-explorer-frontend/pull/130

**Comment by duanyytop** [comment]
> > The JoyID contract is still under development and has only been deployed on the Testnet. It is recommended not to display it on explorer.
> 
> Got it. Please let me know once it's ready, thanks in advance.

### lock script
```
code_hash: 0xd23761b364210735c19c60561d213fb3beae2fd6172743719eff6920e020baac
hash_type: type
args: 
```

### cell_deps
```
tx_hash: 0x4dcf3f3b09efac8995d6cbee87c5345e812d310094651e0c3d9a730f32dc9263
index: 0x0
dep_type: dep_group
```

**Comment by Keith-CY** [comment]
Testnet deployment should be added by https://github.com/Magickbase/ckb-explorer-frontend/pull/141

**Comment by Keith-CY** [comment]
Deployed https://pudge.explorer.nervos.org/scripts#JoyID
