### ISSUE TITLE
[scripts] some code not registered，but show in transaction

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/ckb-explorer-public-issues#127]
### cota
https://explorer.nervos.org/transaction/0x29afd939d5733762a45b7b26671122df722835dd723dc5746c1ce0a2a802c05a
<img width="662" alt="image" src="https://user-images.githubusercontent.com/32102187/208818008-a340ed6f-f31d-4766-a3b4-2571f43897ed.png">
click cota，but not found cota code in scripts
https://explorer.nervos.org/scripts#cota
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/32102187/208818078-54f2f219-8c50-4d8b-a317-d6cacdd2f293.png">

**Comment by gpBlockchain** [comment]
### pwlock-k1-acpl
https://explorer.nervos.org/transaction/0xcc97dccd89eb8ba57f8bc195b38808e752391fe478144f9dcd63c67493cb9235
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/32102187/208818211-5fcb14ba-202b-4f3b-b238-a21c806ffe54.png">

url: https://explorer.nervos.org/scripts#pwlock-k1-acpl
click `pwlock-k1-acpl`，but not found `pwlock-k1-acpl` code in scripts
<img width="1069" alt="image" src="https://user-images.githubusercontent.com/32102187/208818259-76b5ba31-06a9-4724-823f-e13c35a4e738.png">

**Comment by Keith-CY** [comment]
Is the code of CoTA contract open-sourced? I didn't find it in https://github.com/orgs/nervina-labs/repositories?q=cota @duanyytop

**Comment by duanyytop** [comment]
> Is the code of CoTA contract open-sourced? I didn't find it in https://github.com/orgs/nervina-labs/repositories?q=cota @duanyytop

The CoTA contract code is not open-sourced now and we will open source after code audit

**Comment by Keith-CY** [comment]
> > Is the code of CoTA contract open-sourced? I didn't find it in [github.com/orgs/nervina-labs/repositories?q=cota](https://github.com/orgs/nervina-labs/repositories?q=cota) @duanyytop
> 
> The CoTA contract code is not open-sourced now and we will open source after code audit

Got it

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1155

**Comment by Keith-CY** [comment]
cota: https://explorer.nervos.org/scripts#cota
cota registry: https://explorer.nervos.org/scripts#cota_registry
pwlock-k1-acpl: https://explorer.nervos.org/scripts#pwlock-k1-acpl

**Comment by gpBlockchain** [comment]
> cota: https://explorer.nervos.org/scripts#cota cota registry: https://explorer.nervos.org/scripts#cota_registry pwlock-k1-acpl: https://explorer.nervos.org/scripts#pwlock-k1-acpl

cota cell is died？

**Comment by duanyytop** [comment]
> > cota: https://explorer.nervos.org/scripts#cota cota registry: https://explorer.nervos.org/scripts#cota_registry pwlock-k1-acpl: https://explorer.nervos.org/scripts#pwlock-k1-acpl
> 
> cota cell is died？

https://www.cotadev.io/docs/guides/contract-deployment

**Comment by Keith-CY** [comment]
> > > cota: [explorer.nervos.org/scripts#cota](https://explorer.nervos.org/scripts#cota) cota registry: [explorer.nervos.org/scripts#cota_registry](https://explorer.nervos.org/scripts#cota_registry) pwlock-k1-acpl: [explorer.nervos.org/scripts#pwlock-k1-acpl](https://explorer.nervos.org/scripts#pwlock-k1-acpl)
> > 
> > 
> > cota cell is died？
> 
> [cotadev.io/docs/guides/contract-deployment](https://www.cotadev.io/docs/guides/contract-deployment)

Was it mistakenly recorded, or have the cells been updated?

The PR added cota cells is https://github.com/nervosnetwork/ckb-explorer-frontend/pull/895, and it indicates data a from [nervina-labs/ckb-cota-scripts/wiki/Lina-Mainnet-deployment](https://github.com/nervina-labs/ckb-cota-scripts/wiki/Lina-Mainnet-deployment) but the link is broken.

Should I append the new cells or fix the existing ones?

**Comment by duanyytop** [comment]
The contract had been upgraded and the [deployment information](https://www.cotadev.io/docs/guides/contract-deployment) is up to date

**Comment by Keith-CY** [comment]
> The contract had been upgraded and the [deployment information](https://www.cotadev.io/docs/guides/contract-deployment) is up to date

Got it, I'll append the new ones

**Comment by Keith-CY** [comment]
PR to update the deployed cells: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1157
