### ISSUE TITLE
How to initialize environment variables on building pages

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#129]
This issue comes from https://github.com/nervosnetwork/ckb-explorer-frontend/actions/runs/3756424279/jobs/6382484224#step:3:153

The CI blamed 

```
#15 65.05 Error: Cannot find module '/app/scripts/prepare.js'
```

because `./scripts/prepare.js` was not copied into the container at this step https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/Dockerfile#L18.

It could be fixed by adding a new line

```dockerfile
COPY scripts ./
```

but I found the environmental variables are introduced by https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/Dockerfile#L3-L7 as

```dockerfile
ARG API_URL=https://testnet-api.explorer.nervos.org/
ARG CHAIN_TYPE=testnet
ARG GA_ID=G-F4MS15DMS6
ARG MAINNET_URL=https://explorer.nervos.org/
ARG TESTNET_NAME=pudge
```
then I think maybe we can remove `prepare.js` and allow users to import variables in their own way

Any idea from @WhiteMinds

**Comment by WhiteMinds** [comment]
> then I think maybe we can remove `prepare.js` and allow users to import variables in their own way

At present 'prepare.js' is just to reduce manual copy work, since it causes trouble so can be removed.

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1154
