### ISSUE TITLE
Show pending transactions

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#130]
This issue comes from https://github.com/Magickbase/ckb-explorer-public-issues/issues/99 and is about showing the pending transaction list on the `transaction page`(https://explorer.nervos.org/transaction/list) and `account page`(https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwrx5jg84qlp5lfdr3u9nvv95agj346usckujtcq)

A pending transaction is a transaction broadcast to the CKB node but has not been packaged into a new block yet. This kind of transaction will be kept in the transaction pool and wait for a miner to include it in the next block.

### Transaction page(https://explorer.nervos.org/transaction/list)

Current, the transaction list page only covers transactions which have been packaged into a block. The list has 4 fields
1. transaction hash: hash of the transaction
2. height: the number of a block in which the transaction is packaged
3. capacity: total capacity of inputs of the transaction, meaning the total capacity influenced by the transaction
4. time: timestamp of the block 

Now we are going to add a new list to cover transactions submitted but not included in a block, namely the pending transaction list.

The pending transaction list will be added by a new tab `Pending Transaction(1000)` where `1000` is the count of pending transactions.

The pending transaction list also has 4 fields, but some fields have different meanings:
1. transaction hash: hash of the transaction
2. capacity: total capacity of inputs of the transaction
3. time: time of the transaction was added into the transaction pool. A pending transaction is not packaged into a block so it doesn't have a determined timestamp of a block
4. transaction fee: the fee will be paid to a miner if this transaction is packaged into a block

![image](https://user-images.githubusercontent.com/7271329/209461818-bc4ce079-3383-4680-8523-4697fa971b07.png)

PRD: https://2rhjg8.axshare.com/#id=3xglgd&p=transaction_list_page

### Account page

Similarly, a pending transaction list will be added on the account page(https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwrx5jg84qlp5lfdr3u9nvv95agj346usckujtcq)

It would be almost the same as the transaction list on the account page, except that the `block number/timestamp` at the top right corner of a record has different behavior.

In the transaction list, `block number/timestamp` comes from the block which includes the transaction. But a pending transaction doesn't belong to a block, then the `block number/timestamp` is empty. Instead, the timestamp of when the transaction is submitted into the pool will be displayed at the cornor.

![image](https://user-images.githubusercontent.com/7271329/209462343-6440a81c-d4ba-4a2f-bed7-a1b1f8da98e9.png)

PRD: https://2rhjg8.axshare.com/#id=qmchwz&p=account_page&g=1

**Comment by Keith-CY** [comment]
The PRD of pending transaction list has been updated, please have a review @ShiningRay @iamyates @WhiteMinds @jiangxianliang007

**Comment by Keith-CY** [comment]
UI Design will be updated in https://github.com/Magickbase/visual-style-guide/issues/17

**Comment by Keith-CY** [comment]
Could you take over this issue @WhiteMinds by this you can get familiar with transactions on CKB

**Comment by WhiteMinds** [comment]
> Could you take over this issue @WhiteMinds by this you can get familiar with transactions on CKB

Ok, is there already an update for the corresponding backend API?

**Comment by Keith-CY** [comment]
> > Could you take over this issue @WhiteMinds by this you can get familiar with transactions on CKB
> 
> Ok, is there already an update for the corresponding backend API?

Not yet, we can open two new issues for implementation of front-end and backend and reference this issue in those two. @WhiteMinds @iamyates 

The API schema could be defined before writing code in the backend issue and UI could be started with mock data
