### ISSUE TITLE
[nft-collections] burn nft , but the number of nfts has not declined

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/ckb-explorer-public-issues#133]

**Comment by gpBlockchain** [comment]
nft:https://pudge.explorer.nervos.org/nft-collections/0x642faa83f2851b57c2e702f19b0454a6736bd21e2b3cf1319a187ffab93dad86?tab=transfers
brun action: https://pudge.explorer.nervos.org/transaction/0x33fb0bca806af8969873b040b56f9a0a9e86d0a6edd7ae45c3b9ef07135af64c
show in nft-collctions:
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/32102187/209512731-8ef32a0a-71de-4f9b-a966-78a8aca77e14.png">
but quantity of nfts has not declined
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/32102187/209512787-730fbd73-acc8-4960-835b-a68133a8c800.png">

burn nft Owner has not changed:
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/32102187/209512918-0895d8a8-6639-4d9c-be5c-9d76b0e6d627.png">

**Comment by Keith-CY** [comment]
Please append the related code here @iamyates

**Comment by Keith-CY** [comment]
> related code:
> 
> [nervosnetwork/ckb-explorer@`30af8a0`/app/models/ckb_sync/new_node_data_processor.rb#L813](https://github.com/nervosnetwork/ckb-explorer/blob/30af8a0b1276464f5652ddc211286521605bc75f/app/models/ckb_sync/new_node_data_processor.rb#L813)
> 
> ```
>  812             elsif cell_type.in?(%w(m_nft_token nrc_721_token))
>  813               TokenTransferDetectWorker.perform_async(ckb_txs[tx_index]["id"])
>  814             end
> ```
> 
> [nervosnetwork/ckb-explorer@`30af8a0`/app/models/ckb_sync/new_node_data_processor.rb#L885](https://github.com/nervosnetwork/ckb-explorer/blob/30af8a0b1276464f5652ddc211286521605bc75f/app/models/ckb_sync/new_node_data_processor.rb#L885)
> 
> ```
>  884           elsif attr[:cell_type].in?(%w(m_nft_token nrc_721_token))
>  885             TokenTransferDetectWorker.perform_async(ckb_txs[tx_index]["id"])
>  886           end
> ```
> 
> and [nervosnetwork/ckb-explorer@`30af8a0`/app/workers/token_transfer_detect_worker.rb#L43-L48](https://github.com/nervosnetwork/ckb-explorer/blob/30af8a0b1276464f5652ddc211286521605bc75f/app/workers/token_transfer_detect_worker.rb#L43-L48):
> 
> ```
>     source_tokens.each do |type_script_id, cell|
>       item = TokenItem.find_by type_script_id: type_script_id
>       t = TokenTransfer.
>         create_with(action: :destruction, from_id: cell.address_id).
>         find_or_create_by(item_id: item.id, transaction_id: tx.id)
>     end
> ```

According to the code https://github.com/nervosnetwork/ckb-explorer/blob/30af8a0b1276464f5652ddc211286521605bc75f/app/workers/token_transfer_detect_worker.rb#L43-L48 referenced above, a `destruction` record will be added in the history but the statistics data are not updated correspondingly, so holder count and minted count mismatch the on-chain data.

**Comment by Keith-CY** [comment]
Token id 1 was burnt, and the holder count was updated, but the minted count is still incorrect and listed in the inventory list.

![Image](https://user-images.githubusercontent.com/7271329/214080644-2b7f3638-f0cc-4145-8147-ee7541f4960a.png)



![Image](https://user-images.githubusercontent.com/7271329/214080658-b6d11117-0038-453e-bc1d-f406e43ed32a.png)
