### ISSUE TITLE
[nft-collections] show duplicate data

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/ckb-explorer-public-issues#136]
url: https://explorer.nervos.org/nft-collections/0xd36e37bfd20c064e6167d05ccec47b2ab54e15b241c611410ba4f915a9da4f19
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/32102187/209524987-4e4e698a-77e4-4a90-813e-fa3ed33aa142.png">
https://explorer.nervos.org/nft-info/0xd36e37bfd20c064e6167d05ccec47b2ab54e15b241c611410ba4f915a9da4f19/186
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/32102187/209525037-bf3f46a3-f4fa-4ca7-9949-261d56dd57a9.png">
https://explorer.nervos.org/nft-info/0x9dd31f2cfcc5734e04873c7ef8514646e454438af93b808422eacbcbf1d58d26/1
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/32102187/209526660-c9d5d198-3d35-4dc5-941d-0c8a64ea697a.png">

**Comment by ShiningRay** [comment]
resolved in https://github.com/Magickbase/ckb-explorer-public-issues/issues/147
