### ISSUE TITLE
Error in the number of nft holders

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/ckb-explorer-public-issues#139]
url： https://explorer.nervos.org/nft-collections/0xf7874f30334806e5b0dc7518d763dce6447d389859a52a40ce1ca34712119d79?tab=holders

Error description： Holder shows Minted

![image](https://user-images.githubusercontent.com/77844990/209628220-f1aaeb2c-680e-4e6b-a775-0e352e506faa.png)

**Comment by ShiningRay** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1116

**Comment by Keith-CY** [comment]
After the fix, the holder count is still incorrect
![image](https://user-images.githubusercontent.com/7271329/211271683-6570d83a-2db1-420d-99a6-a9221e72e83f.png)
The first 2 addresses hold 92 nfts

**Comment by Keith-CY** [comment]
Figure out that the fix was deployed to testnet but not deployed to mainnet yet
