### ISSUE TITLE
The transaction order of the nft Activity list is displayed incorrectly

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/ckb-explorer-public-issues#140]
url: https://explorer.nervos.org/nft-collections/0xa611be57582043f57fddd296faf1fca6b4c2bdd99a8ca518c4c8dcbed222e8ee

![image](https://user-images.githubusercontent.com/77844990/209629519-55dcae27-45b7-40fd-aedf-e61dd7736e5e.png)

**Comment by ShiningRay** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1140
