### ISSUE TITLE
Incorrect record of cota

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#143]
![image](https://user-images.githubusercontent.com/7271329/210032613-e5734018-ce01-4362-aa09-9d36a3639f45.png)

NFT on token city explorer: https://ckb-nft-explorer.staging.token.city/nft/36675f76-b44f-4e66-93d0-b8570cf3a76a
NFT on ckb explorer: https://pudge.explorer.nervos.org/nft-collections/18155?tab=holders
Transfer on token city explorer: https://ckb-nft-explorer.staging.token.city/transaction/dd03fb8f-7ddd-4af5-abdc-3f3df33ea71b
Transfer on ckb explorer: https://pudge.explorer.nervos.org/transaction/0x1ce1b8d51f0bfeeba6f3b6a4f8e7023533e76dacee3973d2a9666f447e68462b

Address ends with `m4fj` is the deprecated format of address ends with `t5pg`

There're 2 errors

1. NFT image and name are not parsed
2. NFT doesn't appear on holder's page https://pudge.explorer.nervos.org/nft-collections/18155?tab=inventory

**Comment by ShiningRay** [comment]
The information of cota_id `0xd38e8afa9a28b497957cf4cdb15566621f2ff718` get from CoTA Aggregator is empty.
I'm contacting CoTA team to verify this data.

**Comment by Keith-CY** [comment]
Is this issue resolved after cota-aggregator was re-synced?

**Comment by ShiningRay** [comment]
I built a newly synced CoTA node, and tried to reprocess the CoTA transactions from that node, but unfortunately, after lots of blocks processed, the data in database lost again.
I'm trying to resync the node again, and build another CoTA node separately on a single EC.
