### ISSUE TITLE
Register scripts of godwoken

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#145]
There're 2 pages displaying token info

1. script list page(https://explorer.nervos.org/scripts), the content of script list is at https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/pages/ScriptList/index.tsx#L13-L103
![image](https://user-images.githubusercontent.com/7271329/210304755-ee7ace3b-cf91-41f6-af8b-3f58e7a773f9.png)

2. script tag in cell info on the transaction page(https://explorer.nervos.org/transaction/0x0d3ceb3c364e84e0bc0a87487cc62afa0f0a65be02edb6cd96382bf4832b5358), the content of script tag is at https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/constants/scripts.ts
![image](https://user-images.githubusercontent.com/7271329/210304811-0d65dc33-726c-4a4f-b077-5ccc1b7dde35.png)

---

This issue is to add scripts used in godwoken

1. scripts used in godwoken: https://github.com/godwokenrises/godwoken-info/blob/main/testnet_v1_1/scripts-deploy-result.json
2. source code of these scripts: https://github.com/godwokenrises/godwoken/tree/develop/gwos

Caveat: omnilock used in godwoken is v1 while omnilock displayed in RFC(https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0042-omnilock/0042-omnilock.md#notes) is v2, so 2 omnilock cells should be added

**Comment by Keith-CY** [comment]
@WhiteMinds could you take over this issue? By this you can get familiar with the concept of script in CKB and common scripts used in the community

**Comment by WhiteMinds** [comment]
> @WhiteMinds could you take over this issue? By this you can get familiar with the concept of script in CKB and common scripts used in the community

ok

**Comment by WhiteMinds** [comment]
I can't seem to get the `category` and `hashType` needed for the interface `ContractHashTag` from `scripts-deploy-result.json`, where do I get or derive these two properties from?

Do I search for the `description` of each script and put it in?

**Comment by Keith-CY** [comment]
> I can't seem to get the `category` and `hashType` needed for the interface `ContractHashTag` from `scripts-deploy-result.json`, where do I get or derive these two properties from?
> 
> Do I search for the `description` of each script and put it in?

`category` is an enum of two variants: `lock` and `type`, it indicates that if the `script` is a `lock script` or a `type script`, the concept could be learned from https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0019-data-structures/0019-data-structures.md#description

Scripts in the list with name ending with `lock` are obviously `lock script`, those with name ending with `validator` may be `type script`, need confirmation from @Flouse 

A brief description of each `script` is also desirable @Flouse

The `omnilock` is special, it's not specific to this project and was added in RFC(https://github.com/nervosnetwork/rfcs/tree/master/rfcs/0042-omnilock)


---

`hashType` is also an enum of two variants: `type` and `data`, it's defined in `script` structure and reveals how the `script.code_hash` comes. If `code_hash` is the hash of a cell's `data`, the value is `data` while if the `code_hash` is the hash of a cell's `type script`, the value is `type`, it is about how to reference a `cell` as a dependency and can be learned from https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0019-data-structures/0019-data-structures.md#script

**Comment by Flouse** [comment]
> Scripts in the list with name ending with `lock` are obviously `lock script`, those with name ending with `validator` may be `type script`, need confirmation from @Flouse

Since there is no complete challenge mechanism for Godwoken at current stage, I suggest the the following scripts/validator could be ignored:
- meta_contract_validator
- l2_sudt_validator
- polyjuice_validator
- eth_addr_reg_validator

**Comment by WhiteMinds** [comment]
> `category` is an enum of two variants: `lock` and `type`, it indicates that if the `script` is a `lock script` or a `type script`, the concept could be learned from https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0019-data-structures/0019-data-structures.md#description
> `hashType` is also an enum of two variants: `type` and `data`, it's defined in `script` structure and reveals how the `script.code_hash` comes. If `code_hash` is the hash of a cell's `data`, the value is `data` while if the `code_hash` is the hash of a cell's `type script`, the value is `type`, it is about how to reference a `cell` as a dependency and can be learned from https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0019-data-structures/0019-data-structures.md#script

After a day's study, I have generally understood the relationship between tx and lock script and type script.

What remains unclear is how do I determine which scripts will have a `hashType` value of `data`?
@Keith-CY From what I've learned so far, it looks like this should be determined when the transaction is created rather than when the script is created, so I can't get this information directly from `scripts-deploy-result.json` unless having a `script_type_hash` field means that `hashType` is `type`.

**Comment by Keith-CY** [comment]
> > `category` is an enum of two variants: `lock` and `type`, it indicates that if the `script` is a `lock script` or a `type script`, the concept could be learned from [nervosnetwork/rfcs@`master`/rfcs/0019-data-structures/0019-data-structures.md#description](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0019-data-structures/0019-data-structures.md?rgh-link-date=2023-01-06T05%3A54%3A59Z#description)
> > `hashType` is also an enum of two variants: `type` and `data`, it's defined in `script` structure and reveals how the `script.code_hash` comes. If `code_hash` is the hash of a cell's `data`, the value is `data` while if the `code_hash` is the hash of a cell's `type script`, the value is `type`, it is about how to reference a `cell` as a dependency and can be learned from [nervosnetwork/rfcs@`master`/rfcs/0019-data-structures/0019-data-structures.md#script](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0019-data-structures/0019-data-structures.md?rgh-link-date=2023-01-06T05%3A54%3A59Z#script)
> 
> After a day's study, I have generally understood the relationship between tx and lock script and type script.
> 
> What remains unclear is how do I determine which scripts will have a `hashType` value of `data`? @Keith-CY From what I've learned so far, it looks like this should be determined when the transaction is created rather than when the script is created, so I can't get this information directly from `scripts-deploy-result.json` unless having a `script_type_hash` field means that `hashType` is `type`.

You're right, `script_type_hash` implies that script has `hash type: type`

Now, most of the scripts on CKB are deployed with a special script named `type id`(https://github.com/Magickbase/ckb-wallet-and-explorer/wiki/type-id-%E5%90%88%E7%BA%A6), the type id script is also a `type script` and it requires a unique `id` as its `script.args`.

With a unique id, each `type id` `type script` could be hashed to a unique hex string.

In this list, `script_type_hash` is the hex string hashed from `type id` `type script` of the cell deploying the business script.

**Comment by WhiteMinds** [comment]
https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1167

**Comment by Keith-CY** [comment]
> [nervosnetwork/ckb-explorer-frontend#1167](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1167)

@Flouse @gpBlockchain please have a review

**Comment by Flouse** [comment]
Do we need to add `Godwoken/gw` prefix to the script names?

**Comment by Keith-CY** [comment]
> Do we need to add `Godwoken/gw` prefix to the script names?

Prefix `Godwoken` was added as https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1167/files#diff-5636bb1b68c18c68892b6c62dfc3f46f9af26639e920bf49902e70156eedc2a1R165
