### ISSUE TITLE
String is truncated improper on homepage

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#152]
![image](https://user-images.githubusercontent.com/7271329/211282391-8ffdb416-d630-4335-9a03-661e5905855b.png)
Environment: develop branch dev mode locally

**Comment by Keith-CY** [comment]
Happens on the address page too
![image](https://user-images.githubusercontent.com/7271329/211282750-0174c923-93db-4e4a-9769-b218cc9055e5.png)

**Comment by Keith-CY** [comment]
Address is too long in a transaction record on the address page, which makes the `unspent` icon overlapped
![image](https://user-images.githubusercontent.com/7271329/211283039-449a36c0-141e-43c4-884b-ff1dc4039e97.png)

**Comment by WhiteMinds** [comment]
Fixed PR https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1168
