### ISSUE TITLE
"CKB v0.105.* have bugs. Please upgrade to the latest version."

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#166]
Weird alert appears on testnet
![image](https://user-images.githubusercontent.com/7271329/212835654-33a93d71-2ddb-4324-90a4-7e81bf9cd4e3.png)
Link: https://pudge.explorer.nervos.org/

Trying to find out which API throws it

**Comment by Keith-CY** [comment]
From API https://testnet-api.explorer.nervos.org/api/v1/statistics/blockchain_info
![image](https://user-images.githubusercontent.com/7271329/212836102-afd7474c-23bd-4e80-a855-487031ce52da.png)

**Comment by Keith-CY** [comment]
This message will be filtered out by the backend

**Comment by Keith-CY** [comment]
> related PR: [nervosnetwork/ckb-explorer#1135](https://github.com/nervosnetwork/ckb-explorer/pull/1135)

The alert message is still returned in the API, it was fixed in the front-end temporarily

**Comment by Keith-CY** [comment]
Confirmed that the `alerts` is empty
![image](https://user-images.githubusercontent.com/7271329/213083237-7800da7f-4fc0-4d8a-a544-d69f05adec59.png)

**Comment by doitian** [comment]
Fixed in https://github.com/nervosnetwork/ckb/releases/tag/v0.107.0
