### ISSUE TITLE
[address] the icons  overlap occurs

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/ckb-explorer-public-issues#172]
the icons no dynamic adjustment when the browser width becomes longer
https://pudge.explorer.nervos.org/address/ckt1qyqd5eyygtdmwdr7ge736zw6z0ju6wsw7rssu8fcve 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/32102187/215237708-9cd5c9a7-c7b6-45dc-8f69-a592b035dd4f.png">

**Comment by WhiteMinds** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1190
