### ISSUE TITLE
Enrich the PRD

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#174]
Now there's a concise text PRD of CKB Explorer https://github.com/Magickbase/ckb-explorer-public-issues/blob/main/PRD.md with each field briefly explained.

Please go through it and add a detailed explanation if necessary.

And add a wireframe for future updates.

**Comment by Danie0918** [comment]
Sorry for the delay of 1 day due to the wireframe taking longer than expected.

Please review the adjusted documentation and suggest if there are deficiencies. @Keith-CY 

[https://github.com/Magickbase/ckb-explorer-public-issues/blob/main/PRD.md](url)

**Comment by Keith-CY** [comment]
I forgot to check where the wireframe is shared @Danie0918

**Comment by Danie0918** [comment]
> I forgot to check where the wireframe is shared @Danie0918

Currently the wireframe is attached to the document[https://github.com/Magickbase/ckb-explorer-public-issues/blob/main/PRD.md](url)

**Comment by Danie0918** [comment]
Wireframe is shared here:[https://x2mnhs.axshare.com](url)
