### ISSUE TITLE
API docs should be updated in English

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#183]
API docs: https://www.apifox.cn/apidoc/project-962207/api-20171162

A user was blocked by translation on using the docs. Besides, we should keep all documents/materials in English for wide-scope usage.

**Comment by ShiningRay** [comment]
OK, we will setup a document page under explorer's domain

**Comment by Keith-CY** [comment]
It's been transaction and ready to deploy
Preview: https://onnhbgvkmy.apifox.cn/api-61180125

**Comment by Keith-CY** [comment]
Deployed: https://nervosnetwork.github.io/ckb-explorer/public/api_doc.html
