### ISSUE TITLE
Deploy to mainnet, 2023-02-08 

### ISSUE THREAD

**Issue by iamyates** [Magickbase/ckb-explorer-public-issues#186]
This is a memo for the deployment. 

1. please deploy to :  (1) `ckb-explorer-api` (2) `ckb-explorer-syncer`
2. login to either of the servers ,  run:  `bundle exec rails console`
3. run `Block.set_ckb_node_versions_from_miner_message`  , so that the last 100k blocks' version information will be updated . 

![image](https://user-images.githubusercontent.com/105087155/217416094-22684c61-bf24-4f0a-935a-4cf63f1de4de.png)

**Comment by Keith-CY** [comment]
The mainnet was deployed, please execute the command @mdzh521
