### ISSUE TITLE
How to support customers and developers/operators better

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#189]
Currently, CKB Explorer is full of technical details, terms, and data, which are too abstract to customers who just want to check their balance, transactions.

For example, the following is the screenshot of the transaction page
![image](https://user-images.githubusercontent.com/7271329/218014598-12182826-7734-4ed8-bdf9-c2c55a0cf88e.png)
There're many technical terms: `size`, `cycles`, `input`, `output`, and `capacity`, they are almost interpreted from data structure directly and are friendly to developers. But to customers, they are meaningless and distracting.

As a customer, the most important info should be `how many I've sent` or `how many I've received`

To flatter these two groups, we may redesign the UI/UX from two perspectives, like reorganizing the page by different URL parameters or providing 2 pages for the same transaction.

Any idea for the balance between **to c** and **to d**? @Danie0918 

Some feedback can be found at https://www.figma.com/file/DpUABTmxAam9BZWByzS0uc/benchmark-research?node-id=694%3A311&t=GnVoLW593m5KBUjq-0

**Comment by Danie0918** [comment]
For now, mainstream blockchain explorers are geared towards developers.This is limited by the current user group and technical limitations. 

So,I think now is not the right time to consider C-end users. Instead of adjusting the product, it is better to add documentation for novices to help them get started.

**Comment by Keith-CY** [comment]
> For now, mainstream blockchain explorers are geared towards developers.This is limited by the current user group and technical limitations.
> 
> So,I think now is not the right time to consider C-end users. Instead of adjusting the product, it is better to add documentation for novices to help them get started.

A huge difference between CKB and mainstream blockchains is the mental model. That a transaction in CKB consists of Cells/UTXOs, very abstract to users familiar to the account model used in Ethereum, which is intuitive.

The `from`, `to`, and `value` of an eth transaction is clear, but in a transaction of CKB, we've to do a computation to get the transferred value of a specific address by `input_of_address - output_of_address`. Maybe we could start by providing a similar UX to that of an ethereum explorer, which is more acceptable to users from other blockchains.

**Comment by Danie0918** [comment]
Ok,I will consider it in subsequent explorer optimization.

**Comment by Kirl70** [comment]
Based on the prototype:
https://vs0cjf.axshare.com/#id=3giphq&p=_189_how_to_support_customers_and_developers_opera&g=1

PC Design(1-9~1-11):
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=13042%3A37425&t=lriivPlPTOL3A8WN-1
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/106060898/233823147-9cb6ba3c-9b50-4ca1-94fb-81204be0fb95.png">

Mobile Design:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=13054%3A38361&t=lriivPlPTOL3A8WN-1
<img width="297" alt="image" src="https://user-images.githubusercontent.com/106060898/233823187-d6219d64-cbff-49f6-8dec-81367152b9b6.png">

**Comment by zhb666** [comment]
https://github.com/Magickbase/ckb-explorer-public-issues/assets/18475950/b6510a50-8a40-41d8-ac75-e96941ac16d3

**Comment by rabbitz** [comment]
Related PRs: https://github.com/nervosnetwork/ckb-explorer/pull/1384

@zhangyouxin

**Comment by Keith-CY** [comment]
Frontend PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/25
