### ISSUE TITLE
Access to specific transaction links will got blank page

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/ckb-explorer-public-issues#200]
Like: https://pudge.explorer.nervos.org/address/0x3627e79ea00e02dd5da974d61ad41ae53cf547494d54b528ddd79f144116aa48

Need the frontend to handle the error correctly and the backend to verify that the error is justified.

![image](https://user-images.githubusercontent.com/9160743/219252370-36ed0ec7-ab28-4082-b90f-4e9a1bc6afc4.png)

**Comment by Keith-CY** [comment]
@ShiningRay please have a look at this error from das service

**Comment by ShiningRay** [comment]
This page  use lock hash as address query parameter, and pass lock has to das index service so caused error
Please convert lock hash to normal ckb address and pass ckb address to das index service @Keith-CY

**Comment by WhiteMinds** [comment]
> Please convert lock hash to normal ckb address and pass ckb address to das index service
OK, i will change it.

However, the current page crash is not caused by an error in the DAS API, but by the fact that the `v1/addresses` API returns a result that is inconsistent with the frontend type expectations.

The frontend type expects that the interface must provide the `udtAccounts` field, but in fact when called with lock_hash as the address, the interface does not have this field.

@ShiningRay I need to confirm that this is consistent with the interface design, and if so, I will modify the type of the front-end AddressState to match, and if not, I will need to add this field on the backend.

**Comment by WhiteMinds** [comment]
> if the address in parameter is not QueryKeyUtils.valid_hex? , the json doesn NOT have udtAccounts fields. else, it has these fields.

OK, looks like this is an expected behavior.

Frontend fix PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1221

**Comment by WhiteMinds** [comment]
> This page use lock hash as address query parameter, and pass lock has to das index service so caused error Please convert lock hash to normal ckb address and pass ckb address to das index service

PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1222
