### ISSUE TITLE
The chart cache is now localstroage-based and needs to be fully refactored to http-based

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/ckb-explorer-public-issues#202]
This has several benefits:
1. The server has full control over the caching policy, and a standardized implementation facilitates leveraging the community ecosystem, such as various server-side middleware.
1. No longer depends on and consumes a lot of localstroage space.

**Comment by WhiteMinds** [comment]
I tested it, the frontend can be changed as long as a small amount of code, mainly the backend to adjust the corresponding interface http caching policy @iamyates @ShiningRay .

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1489

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/135
