### ISSUE TITLE
Provide an error page when a page crashes irretrievably

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/ckb-explorer-public-issues#205]
I could simply add an ErrorBoundary to display the error instead of a blank page, but this may not be friendly enough for the general user, so I need a designer to provide a design for the error page.

The effect of using ErrorBoundary directly:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/9160743/219293604-9d65afdd-08e4-421b-b96a-6d28a21b8faa.png">

@Keith-CY @Kirl70

**Comment by Keith-CY** [comment]
Adding an error page for uncaught errors is a good idea, could you update the PRD for this feature @Danie0918

**Comment by WhiteMinds** [comment]
There are a few things I expect to achieve with this page:
1. the page will display at least part of the error message, so that we can get the key error message when the user provide a screenshot.
1. a button on the page to copy the error message and prompt the user to copy it to the developer (this button can be removed after we re-enable sentry).

**Comment by Kirl70** [comment]
Now there is a 404 error page on the design draft, I think we can directly use this page as a generic error page :

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5755%3A26830&t=AC0TLsiTVztxJZxK-1
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/106060898/219301822-524cb854-e04e-498b-9614-65b6554dd330.png">

**Comment by Danie0918** [comment]
If the page fails to load due to service reasons or user parameter input errors, I think it is possible to use the 404 page as a general error page display.

The error message can be displayed on the page.But I think the copy button is unnecessary, it will make the function more complicated, the user can manually copy the information

So, the 404 error page can be used in the current situation.

**Comment by WhiteMinds** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1223

Effect:

![image](https://user-images.githubusercontent.com/9160743/220308394-5c8b0d6a-3c19-4e40-82d7-a276f2552779.png)

**Comment by Danie0918** [comment]
Generally speaking, we don't need to inform the user of the details of the error which will cause confusion for users.

Can we omit the error details or replace it with the error number？

**Comment by WhiteMinds** [comment]
> Can we omit the error details or replace it with the error number？

Not very feasible, as this page will only appear when a crash occurs that we don't expect, and ordinary errors are reasonably handled.

**Comment by Danie0918** [comment]
Ok,if this is not a usual error that's fine.

**Comment by WhiteMinds** [comment]
@Danie0918 By the way, for additional background, our current sentry is temporarily deactivated (seemingly due to some unanticipated large number of error requests), which is why we need user report error details for such unexpected crashes.

Later, if sentry is restored, we can remove the error details.

@Keith-CY Am I right?

**Comment by Keith-CY** [comment]
> @Danie0918 By the way, for additional background, our current sentry is temporarily deactivated (seemingly due to some unanticipated large number of error requests), which is why we need user report error details for such unexpected crashes.
> 
> Later, if sentry is restored, we can remove the error details.
> 
> @Keith-CY Am I right?

Only the backend was connected to sentry, it’s deactivated to switch another monitoring. And errors on page are not collected.

**Comment by WhiteMinds** [comment]
> Only the backend was connected to sentry, it’s deactivated to switch another monitoring. And errors on page are not collected.

Oh, then I guess we need to connect sentry service to the frontend as well.

**Comment by Keith-CY** [comment]
> > Only the backend was connected to sentry, it’s deactivated to switch another monitoring. And errors on page are not collected.
> 
> Oh, then I guess we need to connect sentry service to the frontend as well. Otherwise, we would rely on the user to report the error details.

A specific issue(https://github.com/Magickbase/ckb-explorer-public-issues/issues/208) was opened for this function
