### ISSUE TITLE
Add error tracking on page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#208]
This issue comes from https://github.com/Magickbase/ckb-explorer-public-issues/issues/205#issuecomment-1439406370, a suggestion to enable sentry to collect errors in the front-end.

We have active plans in [Sentry](https://sentry.io/) and [new relic](https://newrelic.com/), which one would you prefer @WhiteMinds

**Comment by WhiteMinds** [comment]
I have not used new relic before, and from what I have retrieved so far, it is a more capable but heavyweight tool than sentry.

In the current situation, I would prefer the lightweight sentry.

**Comment by Keith-CY** [comment]
> I have not used new relic before, and from what I have retrieved so far, it is a more capable but heavyweight tool than sentry.
> 
> In the current situation, I would prefer the lightweight sentry.

Cool, let’s pick sentry for it. I’ll add you in sentry team later.

**Comment by WhiteMinds** [comment]
PR https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1224
