### ISSUE TITLE
Support searching type id

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#210]
Type ID is a special contract on CKB blockchain. When we talk about a type id script, we're talking about a type script used to reference a contract. The type script is so special because it refers to an embedded contract, unlike those are deployed by cells. And the only factor is **args** in the type script.

The **args** in a type script is used to differentiate contracts indexed by type id because all type id scripts share the same code hash and hash type

```
code hash: 0x00000000000000000000000000000000000000000000000000545950455f4944
hash type: type
```

The feature request is about the **args**, when the **args** is being searched, and if a script referenced by it is found, the page should be navigated to the corresponding script page.

Ref: 
type id(concise): https://github.com/Magickbase/shaping/wiki/type-id-%E5%90%88%E7%BA%A6
type id: https://xuejie.space/2020_02_03_introduction_to_ckb_script_programming_type_id/
RFC: https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0024-ckb-genesis-script-list/0024-ckb-genesis-script-list.md#type-id

**Comment by Keith-CY** [comment]
How is it going

**Comment by Danie0918** [comment]
It hasn't started yet, I'll move it into the planning.

**Comment by Sven-TBD** [comment]
Associated feature #383

**Comment by Sven-TBD** [comment]
返回Args,跳转Scrpts 页面

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1530

Response:

```json
{
  "data": {
    "args": "0xc109c97ed0cea4c3ed46c4b5907d282ef8c0bb0742aa7acff438b25a1ca2e7c6"
  }
}
```

**Comment by zhangyouxin** [comment]
frontend pr: https://github.com/Magickbase/ckb-explorer-frontend/pull/176
