### ISSUE TITLE
Incorrect page navigation

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#211]
https://user-images.githubusercontent.com/7271329/222342627-203f3e67-2bdf-463d-a58b-6a081d4f2203.mov

1. Visit https://pudge.explorer.nervos.org/charts/address-balance-rank
2. click on a bar to the address page
3. navigate back, expect to the chart page, but 404 page is arrived at.
4. navigate back, the chart page appears

**Comment by pygman** [comment]
fix PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1230
