### ISSUE TITLE
The new banner animation's performance issue

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#218]
![image](https://user-images.githubusercontent.com/7271329/223601265-6952f6ee-1b89-45a1-a3ac-bb7fed73ec00.png)
![image](https://user-images.githubusercontent.com/7271329/223601283-7f2e863e-f5c3-4ab2-939f-73dbd10e85ca.png)

Platform: Macbook Pro 2017, i5 and i7
Browser: Chrome 110

The system hangs on opening the page with chrome/safari, but it's ok to open it with firefox

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/223601703-7d2c0858-7469-4c8e-9c1f-aa755003a737.png)
Macbook Pro 2016 faces the same issue

**Comment by pygman** [comment]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/7877698/226231542-a292d064-2ceb-4f72-9663-f05854e72b7d.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/7877698/226231704-4f01fe5d-6a62-40db-9e94-756937404246.png">
<img width="119" alt="image" src="https://user-images.githubusercontent.com/7877698/226231774-5f8e8e28-6c12-4150-8088-a3f446ec361a.png">

> This issue does not occur with the macbook that is almost the same as above

---

### It is not sure whether the system hangs is when entering the page or when the new block is animated
[draft optimizing pr](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1235)
#### suppose that it's hangs when banner is initializing
<img width="631" alt="image" src="https://user-images.githubusercontent.com/7877698/226233468-ef74bf49-0b63-43f9-96d7-64680c9830c8.png">

Create all cubes at the same time may cause high CPU usage, It could sleep for a short time between each cube's creation, and show a `loading` before cubes are all loaded

#### suppose that it's hangs when the wave animation is playing
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/7877698/226233233-3df78430-d619-48f6-a649-965b010938d8.png">

By observing the performance monitor of the banner page in chrome, you can see that the CPU will increase a lot during the wave animation, and at the same time, the `animation frame fired recurring handler` time out, for animation we can do the following optimizations
1. reduce FPS (useful, 30fps, 15fps undetectable by naked eyes)
2. https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/pages/Home/Banner/anime.ts#L27 Promise.all(), too many cubes are controlled at the same time. we can reduce it by merging geometries
    - `textCubes` are easy to merge
    - `normalCubes` can be divided into about 20 groups by distance from the center
    - because it can't be operated separately after merging, the operation of `dataCubes` is a little difficult, because the number of `dataCube` is same to the tx count of current block, we can pre-create enough cubes (or gradient increment creation), blink move to random positions at `normalCubes` before every the animation loop starts, and then playing.(remainingg blocks are placed below all `normalCubes`)
3. creation of floatCube use 8ms, we can use the same one globally (blink move).(not very useful)

**Comment by pygman** [comment]
I developed 8 different versions of the banner page in https://github.com/pygman/ckb-explorer-frontend/tree/tttt
and published to gh-pages
> remove annimate
https://ckb.biangdiang.wang/1

> remove annimate, highlight2, highlight3
https://ckb.biangdiang.wang/2

> remove annimate, highlight2, highlight3, normalCubes
https://ckb.biangdiang.wang/3

> remove annimate, all Cubes, all highlight
https://ckb.biangdiang.wang/4

> only camera and sence
https://ckb.biangdiang.wang/5

> remove shader
https://ckb.biangdiang.wang/6

> only sence
https://ckb.biangdiang.wang/7

> only import threejs
https://ckb.biangdiang.wang/8

@stone_king replied that 6,3,2,1 hangs yet, the rest are black scence,
3 is better but it is also hangs.
waiting for his reply whether the 4,5,7,8 black screen will cause his computer hangs

**Comment by pygman** [comment]
> @stone_king replied that 6,3,2,1 hangs yet, the rest are black scence, 3 is better but it is also hangs. waiting for his reply whether the 4,5,7,8 black screen will cause his computer hangs

4，5，7，8 does not hangs.
It seems to be caused by cubes, the more cubes the more serious, the less the smoother, it is perfectly smooth with no cubes.
Combined with disable hardware acceleration can make it smooth, it is very confusing. I even want to develop it using 2d engine to simulate 3d visuals

**Comment by Keith-CY** [comment]
> * Disable hardware acceleration,  apple chip may cause 404, intel chip cause stucks
> * We guess the hangs is the graphics driver or chromium kernel bugs, most likely browser rendering bugs, not easy to verify
> * Requires a computer that can be frequently tested and adjusted to continue to advance the progress.
> * Or display different banner between old and new, according to the first screen rendering time or CPU usage

The 404 issue was patched by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/bb40574dc5eb161734db34310edbe6f1eaa5f3ab, the banner fallbacks to the static image if banner throws

**Comment by pygman** [comment]
Display different banner according to the rendering time of a `tinyTestSceneRender` at pr https://github.com/Magickbase/ckb-explorer-frontend/pull/2, and deployed to https://ckb.biangdiang.wang/

In my chrome the rendering of the `tinyTestSceneRender` takes about 40ms.

@stone_king replied that It can display the old banner successfully and the render takes 238ms, but when click `Tokens` page and back to `Home` the render takes 109ms.
<img width="877" alt="image" src="https://user-images.githubusercontent.com/7877698/232405946-c5e3a86b-77eb-4512-885d-c97112ac57a1.png">
<img width="853" alt="image" src="https://user-images.githubusercontent.com/7877698/232406019-61b2652f-d674-427b-89e1-fbba34420e8a.png">

So, how about setting the rendering threshold to 60ms?

https://github.com/Magickbase/ckb-explorer-frontend/blob/107c1d7fbc864cc54998952f1c00d5e2d8574e4c/src/pages/Home/Banner/index.tsx#L22

**Comment by Keith-CY** [comment]
> Display different banner according to the rendering time of a `tinyTestSceneRender` at pr [Magickbase/ckb-explorer-frontend#2](https://github.com/Magickbase/ckb-explorer-frontend/pull/2), and deployed to [ckb.biangdiang.wang](https://ckb.biangdiang.wang/)
> 
> In my chrome the rendering of the `tinyTestSceneRender` takes about 40ms.
> 
> @stone_king replied that It can display the old banner successfully and the render takes 238ms, but when click `Tokens` page and back to `Home` the render takes 109ms. <img alt="image" width="877" src="https://user-images.githubusercontent.com/7877698/232405946-c5e3a86b-77eb-4512-885d-c97112ac57a1.png"> <img alt="image" width="853" src="https://user-images.githubusercontent.com/7877698/232406019-61b2652f-d674-427b-89e1-fbba34420e8a.png">
> 
> So, how about setting the rendering threshold to 60ms?
> 
> [Magickbase/ckb-explorer-frontend@`107c1d7`/src/pages/Home/Banner/index.tsx#L22](https://github.com/Magickbase/ckb-explorer-frontend/blob/107c1d7fbc864cc54998952f1c00d5e2d8574e4c/src/pages/Home/Banner/index.tsx#L22)

How about trying various thresholds and deploying them on vercel, and request feedbacks from several users.

**Comment by pygman** [comment]
> How about trying various thresholds and deploying them on vercel, and request feedbacks from several users.

the pr for test https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1249

How can we find some testers, or send `https://ckb-explorer-n3xjuue6s-magickbase.vercel.app/` to @stone_king ask for his department to help test it?

**Comment by Keith-CY** [comment]
> > How about trying various thresholds and deploying them on vercel, and request feedbacks from several users.
> 
> the pr for test [nervosnetwork/ckb-explorer-frontend#1249](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1249)
> 
> How can we find some testers, or send `https://ckb-explorer-n3xjuue6s-magickbase.vercel.app/` to @stone_king ask for his department to help test it?

I'll contact some users for tests

**Comment by Keith-CY** [comment]
Performance on Edge for MacOS

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/b942466b-2ca4-4895-9687-d5ecd6936dee)

Edge Version 114.0.1823.41 (Official build) (x86_64)

**Comment by Keith-CY** [comment]
> Performance on Edge for MacOS
> 
> ![image](https://user-images.githubusercontent.com/7271329/244278566-b942466b-2ca4-4895-9687-d5ecd6936dee.png)
> 
> Edge Version 114.0.1823.41 (Official build) (x86_64)

Detection of GPU was supported by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/6486893f374d05aabe15bef24cccd733f8f06648, does it work in your case? @doitian

**Comment by doitian** [comment]
> https://ckb-explorer-n3xjuue6s-magickbase.vercel.app/

<img width="2032" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/35768/4daa6e43-2a9a-414c-8cae-9c290b75de1a">

**Comment by Keith-CY** [comment]
> > [ckb-explorer-n3xjuue6s-magickbase.vercel.app](https://ckb-explorer-n3xjuue6s-magickbase.vercel.app/)
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/35768/248600385-4daa6e43-2a9a-414c-8cae-9c290b75de1a.png">

My bad, the detection of gpu was deployed to the testnet, and please verify if it works at https://pudge.explorer.nervos.org/

GPU was arranged into 4 tiers, and the animation of banner shows when GPU is of the highest 2 tiers, while the static banner shows when GPU is of the other tiers.

---

Link https://ckb-explorer-n3xjuue6s-magickbase.vercel.app/30 was a preview link for a threshold of 30fps as the condition.

**Comment by doitian** [comment]
The browser is still stucked when opening https://pudge.explorer.nervos.org/
