### ISSUE TITLE
click to turn the page, but the page redirection is incorrect

### ISSUE THREAD

**Issue by gpBlockchain** [Magickbase/ckb-explorer-public-issues#219]
https://pudge.explorer.nervos.org/address/ckt1qqpph0gxhfpr2xrlvzwk0cw4u5wx30xdchtdvhp3p3703dzwh4n8jqtp3jrcqfq3jkktjqd5x055au078s36enqc3l9u4?page=37&size=10 

<img width="793" alt="image" src="https://user-images.githubusercontent.com/32102187/223765737-47880824-1af0-43ce-9d4e-65548bba91f7.png">

**Comment by FrederLu** [comment]
Hi@gpBlockchain，Judging from the link you shared, the pagination exception you mentioned has not been reproduced. I don’t know if your side is normal now. Or do you have any pre-operations before this happens?
