### ISSUE TITLE
Pending transaction list on address page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#220]
A sub feature from https://github.com/Magickbase/ckb-explorer-public-issues/issues/130

**Comment by Keith-CY** [comment]
This issue was blocked by the architecture of backend, and we had started refactoring. How is the refactoring going now @zmcNotafraid @rabbitz

**Comment by rabbitz** [comment]
> This issue was blocked by the architecture of backend, and we had started refactoring. How is the refactoring going now @zmcNotafraid @rabbitz

The refactoring of pending transactions has been completed. Only an additional interface for account pending transactions is needed.

**Comment by Keith-CY** [comment]
> > This issue was blocked by the architecture of backend, and we had started refactoring. How is the refactoring going now @zmcNotafraid @rabbitz
> 
> The refactoring of pending transactions has been completed. Only an additional interface for account pending transactions is needed.

Nice, so we can arrange this one now

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1514

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/175
