### ISSUE TITLE
Label in chart is overlapped

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#229]
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/7271329/226509091-5b415ba8-c1f2-4126-9a0f-2272a8a426cb.png">

ref: https://explorer.nervos.org/charts/total-dao-deposit

Please fix it based on the main branch @pygman

**Comment by pygman** [comment]
fix PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1236

**Comment by Keith-CY** [comment]
Verified on mainnet
