### ISSUE TITLE
Register NRC 721 Factory from Kollect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#24]
Kollect's Factory code Hash mainnet:
0xedc72bff387ab07ddb8dbabe0a98e458e9e8e97bf262c3391f670a0edcc76096

Kollect's Factory code Hash testnet:
0xf31f9c3241043976c93db9f203d765ce2c1d96465c918b93fbb117cd35bcfb98

**Comment by Keith-CY** [comment]
We may need a documentation about how to registering a 721 nrc token @zmcNotafraid

**Comment by zmcNotafraid** [comment]
`RAILS_ENV=production bundle exec rake migration:update_nrc_721_token_info[factory_code_hash, factory_hash_type, factory_args]`
