### ISSUE TITLE
[Frontend]export to csv

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#243]
PRD: https://o093j5.axshare.com/#id=9ug42i&p=_41%E5%8E%9F%E5%9E%8B-%E6%95%B0%E6%8D%AE%E5%AF%BC%E5%87%BA&g=1

Front end work of issue #41

**Comment by pygman** [comment]
Frontend PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1247

**Comment by WhiteMinds** [comment]
> Frontend PR: [nervosnetwork/ckb-explorer-frontend#1247](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1247)

It has now been moved to https://github.com/Magickbase/ckb-explorer-frontend/pull/9

**Comment by FrederLu** [comment]
The testnet adapts abnormally on the mobile terminal (including the "Download" page).
https://pudge.explorer.nervos.org/export-transactions?type=address_transactions&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgy2q6qz79wyaexr2pcez0eejmk5xgw6jcfw7zmg



![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/5b273f51-ca46-4a0a-b476-c395c559b9c6)


![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b1d4a011-8700-4c62-98b3-b0084968828f)

**Comment by zhangyouxin** [comment]
> @zhangyouxin The testnet adapts abnormally on the mobile terminal (including the "Download" page). https://pudge.explorer.nervos.org/export-transactions?type=address_transactions&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgy2q6qz79wyaexr2pcez0eejmk5xgw6jcfw7zmg
> 
> ![Image](https://user-images.githubusercontent.com/25676576/262325512-5b273f51-ca46-4a0a-b476-c395c559b9c6.png)
> 
> ![Image](https://user-images.githubusercontent.com/25676576/262324739-b1d4a011-8700-4c62-98b3-b0084968828f.png)

will be resolved by： https://github.com/Magickbase/ckb-explorer-frontend/pull/53

**Comment by FrederLu** [comment]
Verified.
