### ISSUE TITLE
[Frontend]data sorting/filtering

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#244]
PRD: https://o093j5.axshare.com/#id=gausgg&p=_42%E5%8E%9F%E5%9E%8B-%E9%A1%B5%E9%9D%A2%E5%A2%9E%E5%8A%A0%E7%AD%9B%E9%80%89%E5%92%8C%E6%8E%92%E5%BA%8F&g=1

Front end part of issue #42  <- click to see more info

**Comment by pygman** [comment]
Frontend PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1243

**Comment by WhiteMinds** [comment]
> Frontend PR: [nervosnetwork/ckb-explorer-frontend#1243](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1243)

It has now been moved to https://github.com/Magickbase/ckb-explorer-frontend/pull/8

**Comment by Keith-CY** [comment]
Online preview can be found at https://ckb-explorer-git-data-sorting-filtering-magickbase.vercel.app/


The following APIs are still required:

1. address page
	- transaction list can be filtered by
		- income
		- outcome
2. block page
	- transaction list can be filtered by
		- tx hash
3. transaction list page
	- slow: need improvement of UX or performance
	- same APIs work with committed transactions, but not work with pending transactions
4. sudt list page
	- sorted by 24hrs transaction count
5. sudt token page
	- transfer list
		- filtered by
			- tx
6. nft collection list page
	- sorted by
		- holder/minted
		- 24hrs transaction count
	- filtered by
		- nft type
7. nft item page

**Comment by rabbitz** [comment]
1. The address page transaction list does not support parameter filtering of outgoing and incoming parameters

**Comment by rabbitz** [comment]
1. token holders click the sort button to send two consecutive requests, please check
2. dao transactions list `tx_hash` and `address_hash` parameter filtering are processed in interface `/api/v1/contract_transactions/nervos_dao`

**Comment by Keith-CY** [comment]
> [nervosnetwork/ckb-explorer#1331](https://github.com/nervosnetwork/ckb-explorer/pull/1331)
> 
> 1. The address transactions list does not support `income` and `outcome` filtering
> 2. block transactions support `tx_hash` and `address_hash` parameter filtering
> 3. Pending transactions support `sort=capacity` parameter sorting
> 4. sudt list supports `sort=transactions` parameter sorting
> 5. Sudt token transactions support `tx_hash` and `address_hash` parameter filtering
> 6. token collections support parameter `sort=holder|minted|transactions` parameter sorting, support `type` parameter filtering
> 7. token holders support `sort=quantity` parameter sorting and `address_hash` parameter filtering
> 8. token inventory supports `token_id` parameter filtering
> 9. dao transactions support `tx_hash` and `address_hash` parameter filtering
> 
> Remark:
> 
> If dao transactions needs to support deposit and interest filtering, it can be realized by joining the dao_events table, but now the data on the testnet is abnormal
> 
> ```shell
> irb(main):006:0> dao_contract = DaoContract.default_contract
> irb(main):007:0> transactions_count = dao_contract.ckb_transactions.tx_committed.recent.count
> => 7140
> ```
> 
> ```shell
> irb(main):010:0> DaoEvent.distinct.count(:ckb_transaction_id)
> => 6892
> ```
> 
> The number of transactions is inconsistent, you need to find the reason before you can add filtering
> 
> @Keith-CY

For the `pending transactions`,
https://testnet-api.explorer.nervos.org/api/v1/transactions?page=1&page_size=25&sort=capacity.asc works but https://testnet-api.explorer.nervos.org/api/v2/pending_transactions?page=1&page_size=25&sort=capacity.asc doesn't work

**Comment by Keith-CY** [comment]
> > [nervosnetwork/ckb-explorer#1331](https://github.com/nervosnetwork/ckb-explorer/pull/1331)
> > 
> > 1. The address transactions list does not support `income` and `outcome` filtering
> > 2. block transactions support `tx_hash` and `address_hash` parameter filtering
> > 3. Pending transactions support `sort=capacity` parameter sorting
> > 4. sudt list supports `sort=transactions` parameter sorting
> > 5. Sudt token transactions support `tx_hash` and `address_hash` parameter filtering
> > 6. token collections support parameter `sort=holder|minted|transactions` parameter sorting, support `type` parameter filtering
> > 7. token holders support `sort=quantity` parameter sorting and `address_hash` parameter filtering
> > 8. token inventory supports `token_id` parameter filtering
> > 9. dao transactions support `tx_hash` and `address_hash` parameter filtering
> > 
> > Remark:
> > If dao transactions needs to support deposit and interest filtering, it can be realized by joining the dao_events table, but now the data on the testnet is abnormal
> > ```shell
> > irb(main):006:0> dao_contract = DaoContract.default_contract
> > irb(main):007:0> transactions_count = dao_contract.ckb_transactions.tx_committed.recent.count
> > => 7140
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > irb(main):010:0> DaoEvent.distinct.count(:ckb_transaction_id)
> > => 6892
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The number of transactions is inconsistent, you need to find the reason before you can add filtering
> > @Keith-CY
> 
> For the `pending transactions`, [testnet-api.explorer.nervos.org/api/v1/transactions?page=1&page_size=25&sort=capacity.asc](https://testnet-api.explorer.nervos.org/api/v1/transactions?page=1&page_size=25&sort=capacity.asc) works but [testnet-api.explorer.nervos.org/api/v2/pending_transactions?page=1&page_size=25&sort=capacity.asc](https://testnet-api.explorer.nervos.org/api/v2/pending_transactions?page=1&page_size=25&sort=capacity.asc) doesn't work

My bad, they may be only available on staging

**Comment by Keith-CY** [comment]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/54f8ab53-f2a5-4ba5-929b-1553ee8c23ee)
https://o093j5.axshare.com/#id=gausgg&p=_42%E5%8E%9F%E5%9E%8B-%E9%A1%B5%E9%9D%A2%E5%A2%9E%E5%8A%A0%E7%AD%9B%E9%80%89%E5%92%8C%E6%8E%92%E5%BA%8F&g=1

A feature of filtering nft item transfers by type(mint, transfer, burn) was lost in our discussion and implementation

**Comment by rabbitz** [comment]
NFT transfers now have a filtering parameter `transfer_action`, which can be set to `normal`, `mint`, or `destruction`.

**Comment by Keith-CY** [comment]
> NFT transfers now have a filtering parameter `transfer_action`, which can be set to `normal`, `mint`, or `destruction`.

Token Detail Page requires the same filter, so I used the same field `transfer_action: mint | normal | desctruction`

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/44d58f24-97fa-41a1-b0f7-7ddee6c77573)

**Comment by rabbitz** [comment]
Because synchronous transactions do not process udt similarly to nft's transfer action, so it is temporarily impossible to filter through transfer_action

@Keith-CY

**Comment by Keith-CY** [comment]
> Because synchronous transactions do not process udt similarly to nft's transfer action, so it is temporarily impossible to filter through `transfer_action`.
> 
> @Keith-CY

Got it, I'll hide the filter options on the sudt detail page
cc @Danie0918 @Sven-TBD @FrederLu @silySuper

**Comment by FrederLu** [comment]
The Depositors page style of Nervos Dao needs to be adjusted on the mobile terminal.
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/876fb5d6-4476-4349-9795-c7f8ad65bbe8)

**Comment by FrederLu** [comment]
The address data that can be previewed on Nervos Dao's Transactions cannot be searched for the corresponding information.

`Request URL: https://testnet-api.explorer.nervos.org/api/v1/contract_transactions/nervos_dao?page=1&page_size=10&address_hash=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfk34txzcadvnl6v7lgadrl7llvz3k6hscj3tu02`



![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/f9902a78-1798-41c5-a747-d3b2277f4b34)


![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7779f9df-eb8b-4002-9f93-16a9d7215ac1)

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1411

**Comment by FrederLu** [comment]
> @Keith-CY The Depositors page style of Nervos Dao needs to be adjusted on the mobile terminal. ![Image](https://user-images.githubusercontent.com/25676576/263586441-876fb5d6-4476-4349-9795-c7f8ad65bbe8.png)

@Keith-CY 
You need to look at the above problem. 
At the same time, when you click on `Nervos DAO` on the homepage, the url lacks `tab=transactions`, which makes `tab=undefined` affect the search results displayed on the page when you search directly.

https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/02561f6a-7b5d-46c7-a464-28de40f13906

**Comment by Keith-CY** [comment]
> > @Keith-CY The Depositors page style of Nervos Dao needs to be adjusted on the mobile terminal. ![Image](https://user-images.githubusercontent.com/25676576/263586441-876fb5d6-4476-4349-9795-c7f8ad65bbe8.png)
> 
> @Keith-CY You need to look at the above problem. At the same time, when you click on `Nervos DAO` on the homepage, the url lacks `tab=transactions`, which makes `tab=undefined` affect the search results displayed on the page when you search directly.
> 
>  2023-08-29.11.32.31.mov

It should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/83

**Comment by FrederLu** [comment]
Style pr  https://github.com/Magickbase/ckb-explorer-frontend/pull/93

**Comment by FrederLu** [comment]
Verified.
