### ISSUE TITLE
Refactor the `Address` to use lock_hash as the primary key

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#245]
The lock hash is the script hash of lock script.
The CKB address is computed based on lock hash.
But the CKB address has serveral different format and may be confused for internal use.
So we shall stick to use the lock hash as the primary key of Address.

**Comment by Sven-TBD** [comment]
@rabbitz  Hi Nan, 
Could you please check the priority of this issue?

I think its a change to a table. If possible, the name of the table or main usage could also be detailed here.

**Comment by rabbitz** [comment]
This issue has been completed, related pr: https://github.com/nervosnetwork/ckb-explorer/pull/932

@Sven-TBD
