### ISSUE TITLE
[Frontend] Always use lock hash to interact with API

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#246]
The CKB address has serveral different format due to history reason.
But these formats are all computed based on lock hash -- the script hash of lock script.
So it's safe to use lock hash instead of address hash when communicating with server side.
And this will enable user to switch the format he/she wants on client side.
- [ ] generate address hash based on lock hash and show
- [ ] send lock hash instead of address hash .

**Comment by Sven-TBD** [comment]
Updated from mingchang:
It seems the impact is minimal, so no adjustments are needed.

So I put this into hold on and adjust its priority
