### ISSUE TITLE
Squash database migration scripts 

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#247]
There are too many database migration scripts.
We should set up a snapshot and remove the old ones

**Comment by ShiningRay** [comment]
Lets do this after `ckb_transactions` and `pool_transaction_entries` are merged

**Comment by Sven-TBD** [comment]
Hi Nan @rabbitz  , If possible , please check if those scripts are finished or not when you're free.

**Comment by rabbitz** [comment]
> Hi Nan @rabbitz , If possible , please check if those scripts are finished or not when you're free.

Squash database migration scripts have not been processed yet.

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1519
