### ISSUE TITLE
Set an alert on rate limited so users won't be misunderstood

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#25]
Simple use window.alert since this case should happen rarely.

`Too many requests, please try later/请求次数过多, 请稍后再试`

**Comment by Keith-CY** [comment]
I found a component(https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/components/Alert/index.tsx) could be pinned in top to show error message, we can reuse it if possible.

**Comment by yanguoyu** [comment]
@ShiningRay 限流了会返回 429 吗？

**Comment by Keith-CY** [comment]
> @ShiningRay 限流了会返回 429 吗？

会的，我在接口返回结果中看到过几次

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/ckb-explorer-frontend/pull/980
