### ISSUE TITLE
Sort NFT collections by hot

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#266]
This feature is requested by the community.

As we're going to support sorting SUDTs by **24hrs transactions**
![image](https://user-images.githubusercontent.com/7271329/230793692-60e6229e-a7fa-4af5-8b39-219ff7b21ca7.png)
Ref: https://github.com/Magickbase/ckb-explorer-public-issues/issues/42#event-8848678096

Which helpers users find vivid projects. I got some feedback that `nft collections` should also be sorted by hot, so users can have a glance at the ecosystem and decide which project to invest.

**Comment by Sven-TBD** [comment]
This feature has been included in #42 ,  and has been done by @pygman , click [here](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1243) to see the pr and latest status.

**Comment by Sven-TBD** [comment]
This feature has been included in #42 ,  and has been done by @pygman , click [here](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1243) to see the pr and latest status.

**Comment by Sven-TBD** [comment]
Prototype: https://o093j5.axshare.com/#id=h3q2kx&p=_266_sort_nft_collections_by_hot&g=1

**Comment by Keith-CY** [comment]
Online: https://explorer.nervos.org/nft-collections
