### ISSUE TITLE
Check CoTA Aggregator's sync state before fetch information.

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#267]
The CoTA Aggregator won't return error when fetch a unsynced block.
So we must first check and then fetch.

And move CoTA sync to a separate process, use its own cursor.

Fetch CoTA aggregator sync info via this API：

https://github.com/nervina-labs/cota-aggregator/tree/develop#get_aggregator_info

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1280
