### ISSUE TITLE
Add field annotation

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#269]
There're many technical terms on the Explorer, as
![image](https://user-images.githubusercontent.com/7271329/231064372-59dbb7ca-d665-4b27-9145-6a2313c86f9b.png)

The definition of `occupied`, `deposit`, `compensation` are used widely in CKB ecosystem but are not clear to newcomers.

The idea of this issue is to add field annotation as

![image](https://user-images.githubusercontent.com/7271329/231064293-82a7146b-29b1-4dcf-8983-5df64bd0b5a0.png)

next to each field, with a link to their origins. With that newcomers can get the meaning of metric quickly.

**Comment by silySuper** [comment]
网上搜索到的部分字段定义：
【矿工详情】下包含：
Nervos DAO 锁定金额：指的是持有者将他们的 CKB 存入 Nervos DAO 中的数量，其中Nervos DAO 是一种定期存款，存在一个最短存款期限（会按照区块计算）——180 Epoch（约 30 天）。如果用户连续在多个存期锁入 CKB 通证，那么 Nervos DAO 的收益将以复利滚动计息。
Nervos 锁定补贴：指的是持有者将他们的 CKB 存入 Nervos DAO 中的所产生的收益

【交易】下包含：
交易栏可以查询该CKB地址下每笔交易的交易号、交易金额、转账地址（输入）和收款地址（输出）等
Cellbase for Block #区块高度N，该区块高度的奖励是在N+11区块中获得，及=交易详情页的高度。CKB 的区块奖励主要会被分成四个部分的：基础/二级/提案/提交奖励

【区块详情】下包含：
叔块数：在比特币协议中，最长的链被认为是绝对的正确。如果一个块不是最长链的一部分，那么它被称为是“孤块”。一个孤立的块是一个块，它也是合法的，但是发现的稍晚，或者是网络传输稍慢，而没有能成为最长的链的一部分，在以太坊中，孤块被称为“叔块”(uncle block)，它们可以为主链的安全作出贡献。
Epoch：搜索到的是Epoch 即周期，CKB 上挖矿难度调节的时间单位，1 个 epoch ≈ 4 小时，挖矿难度每隔一个 Epoch 调整一次，具体这个epoch数字代表了什么含义？与挖矿难度那个数值具体关系是？

【其他】
挖矿算力：
算力反映的是挖矿硬件的性能，网络算力利用当前网络难度、加密货币网络设定的平均区块查找时间和/或最新区块的有效区块查找时间计算得出。计算公式？

以上是部分字段理解，有些可能理解的不对或者不全，欢迎一起探讨和指点～

**Comment by Keith-CY** [comment]
> Shall we add a "more/details" button/link in the tip to link to some term list/glossary page or RFC document?

Sure, a link(if there is one) will be included in the tooltip, as tooltip of cellbase on the testnet

![image](https://user-images.githubusercontent.com/7271329/231126630-3c42a90d-999e-444c-afaa-2fd810d19181.png)

**Comment by Keith-CY** [comment]
The definition of `occupied` on the address page has a different meaning from what is defined in CKB context

`occupied` on the page: https://github.com/Magickbase/ckb-explorer-public-issues/blob/main/PRD.md

```
Occupied: A cell is consideres as "occupied" if the type script of this cell is not empty or the data field of this cell is not empty. Here "occupied" represents the total capacity of all occupied cells belongs to the address.
```

`occupied` in CKB context: https://github.com/nervosnetwork/ckb/wiki/Occupied-Capacity

**Comment by Keith-CY** [comment]
We can start design the necessary annotation if there's no more unsure definition

**Comment by Sven-TBD** [comment]
Add 2 hint types for annotation. @Kirl70 
https://vs0cjf.axshare.com/#id=4wptw3&p=_269_add_field_annotation&g=1

**Comment by Keith-CY** [comment]
Glossary can also be imported into readme.io for API document

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/26b04aa5-48b1-4798-897b-e6e86dea8923)

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/22

**Comment by Sven-TBD** [comment]
Glossary has been imported to Readme.io. @Keith-CY 
[Link here](https://dash.readme.com/project/ckb-explorer/v1.0/glossary-definitions)
https://github.com/Magickbase/ckb-explorer-public-issues/issues/269#issuecomment-1655484664

**Comment by FrederLu** [comment]
1、`Estimated APC` prompts that there is an update to the copywriting requirements, and the copywriting needs to be updated.

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/43f66499-2237-4660-8319-b80e96d3e40a)


![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/5ebc71db-ed71-4764-9f2d-f70bbaccef17)


---
2、There are 3 prompts on the NervosDAO page, "APC/Secondary Issuance Expected/Addresses".
Now there is a prompt when the mouse hovers over the field. It needs to be in a unified form. There is ‘?’ icon behind the field. 

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b2a12946-0c9d-4c69-9df5-d5000ce152b7)

**Comment by WhiteMinds** [comment]
> 1、`Estimated APC` prompts that there is an update to the copywriting requirements, and the copywriting needs to be updated.
> 
> ![Image](https://user-images.githubusercontent.com/25676576/265871356-43f66499-2237-4660-8319-b80e96d3e40a.png)
> 
> https://github.com/Magickbase/ckb-explorer-public-issues/blob/glossary/CKB-Explorer-PRDs/Glossary/Ongoing.md ![Image](https://user-images.githubusercontent.com/25676576/265871306-5ebc71db-ed71-4764-9f2d-f70bbaccef17.png)
> 
> 2、There are 3 prompts on the NervosDAO page, "Estimated APC/Secondary Issuance/Addresses". Now there is a prompt when the mouse hovers over the field. It needs to be in a unified form. There is ‘?’ icon behind the field.
> 
> ![Image](https://user-images.githubusercontent.com/25676576/265871674-b2a12946-0c9d-4c69-9df5-d5000ce152b7.png)

PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/102

**Comment by FrederLu** [comment]
> > 1、`Estimated APC` prompts that there is an update to the copywriting requirements, and the copywriting needs to be updated.
> > ![Image](https://user-images.githubusercontent.com/25676576/265871356-43f66499-2237-4660-8319-b80e96d3e40a.png)
> > https://github.com/Magickbase/ckb-explorer-public-issues/blob/glossary/CKB-Explorer-PRDs/Glossary/Ongoing.md ![Image](https://user-images.githubusercontent.com/25676576/265871306-5ebc71db-ed71-4764-9f2d-f70bbaccef17.png)
> > 2、There are 3 prompts on the NervosDAO page, "Estimated APC/Secondary Issuance/Addresses". Now there is a prompt when the mouse hovers over the field. It needs to be in a unified form. There is ‘?’ icon behind the field.
> > ![Image](https://user-images.githubusercontent.com/25676576/265871674-b2a12946-0c9d-4c69-9df5-d5000ce152b7.png)
> 
> PR: [Magickbase/ckb-explorer-frontend#102](https://github.com/Magickbase/ckb-explorer-frontend/pull/102)

Verified.
