### ISSUE TITLE
Refactor DAO Deposit models

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#272]
The current calculation of DAO's properties like `interest` `compensation` will require fetch related cell outputs record and do on-site computation, so the process is slow.
Now we should design a model for storing a logical DAO deposit to track the lifecycle, which will ease the calculation of the properties mentioned above.

## `dao_deposits` table:
- `status`: enum of (locked, withdrawing, unlocked)
- `deposit_address_id`
- deposit cell:
  - `deposit_at_block_id`
  - `deposit_at_tx_id`
  - `deposit_at_cell_index`
- `deposit_at` (timestamp of related block)
- withdrawing cell:
  - `withdraw_at_block_id`
  - `withdraw_at_tx_id`
  - `withdraw_at_cell_index`
- `withdraw_at` (timestamp of related block)
- `interest_address_id`
- interest 
  - `interest_at_block_id`
  - `interest_at_tx_id`
  - `interest_at_cell_index`
- `interest_at` (timestamp of related block)
- `capacity`
- `interest`

### relationship
Add `deposit_id` in `dao_events` table to associate relationship between `dao_deposits` and `dao_events`

## statistics

**Comment by zmcNotafraid** [comment]
- DaoContractUnclaimedCompensationGenerator
- average_deposit_time
