### ISSUE TITLE
Determine the label according to the length of args

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/ckb-explorer-public-issues#274]
According to the length of args, it should be just a simple multi-signature

![Image](https://user-images.githubusercontent.com/122437870/231342114-0b23ca7d-f8c6-4632-9a87-7d7c6161c9d0.png)

https://pudge.explorer.nervos.org/address/ckt1qpw9q60tppt7l3j7r09qcp7lxnp3vcanvgha8pmvsa3jplykxn32sq2pwwfl04kygck3vl5yx5d076tkm9t2zagdn3zeq

**Comment by Danie0918** [comment]
Lockscript has 3 modes
1. Single-signature locking: Unlocked with one private key
2. Multi-signature locking: requires multiple private keys to unlock
3. Multi-signature locking with time limit: unlock after a specified on-chain time (timestamp, block)

The args length is 20bytes without time lock, and 28bytes with time lock. Args length in this issue does not match the time lock case, so the label is not needed.

**Comment by pygman** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1262

**Comment by FrederLu** [comment]
Verified.
