### ISSUE TITLE
[operation] add monitor for daily_statistics

### ISSUE THREAD

**Issue by iamyates** [Magickbase/ckb-explorer-public-issues#280]
after PR : https://github.com/nervosnetwork/ckb-explorer/pull/1222 merged, please config to monitor this daily_statistics API.

```
GET /api/v2/monitors/daily_statistics
```
response body: 

- 'ok' :  means `yesterday data` is correctly generated. 
- 'error':  means yesterday data is not generated

**Comment by ShiningRay** [comment]
done
