### ISSUE TITLE
script's transactions info can't display .( interface always in loading status  )

### ISSUE THREAD

**Issue by littleLip520** [Magickbase/ckb-explorer-public-issues#287]
interface：testnet-api.explorer.nervos.org/api/v1/statistics
transaction info URL:
https://pudge.explorer.nervos.org/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type

**Comment by littleLip520** [comment]
step1: choose 1 transaction,and click cellinfo
<img width="1525" alt="image" src="https://user-images.githubusercontent.com/26523791/232658221-de1df4d9-713f-4190-9f3a-3af5b7b50841.png">

**Comment by littleLip520** [comment]
step 2: click script button
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/26523791/232658429-c3cb36e4-2e82-4879-9ce5-49b7175646f3.png">
setp 3:wait till transactions data display,but got interface timeout 
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/26523791/232658586-1a58ccaa-b351-47dc-9c72-9079983b261b.png">

**Comment by zmcNotafraid** [comment]
<img width="760" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/7d748012-89b6-489a-be71-5eee58184923">
Current can display txs.Seems it was fixed.
