### ISSUE TITLE
The relative time on the develop branch is not updated correctly

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/ckb-explorer-public-issues#290]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/9160743/232687875-e60227a9-7f9e-4991-bea9-b6c18c8d1076.png">

This was caused by a previous performance optimization I did, as the previous update of this relative time actually relied implicitly on a timed global state update to trigger a re-render. The performance pressure from that timed global state update was too high, so I refactored it.

**Comment by FrederLu** [comment]
https://pudge.explorer.nervos.org/
Now the block time is updated normally, and the verification is passed.
