### ISSUE TITLE
The rate page prompts 404.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#292]
After clicking the rate, the page loads the data and displays 404.
https://pudge.explorer.nervos.org/fee-rate-tracker
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/25676576/232708050-f42421a4-7197-464a-ba07-320ee4ca5c9d.png">

**Comment by Danie0918** [comment]
Not reproduced
