### ISSUE TITLE
The title is abnormal when switching Chinese/English.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#295]
When the page is switched between Chinese and English, the title lacks an automatic switching function, and the page needs to be manually refreshed.
https://pudge.explorer.nervos.org/
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/25676576/232723548-8de28c7e-37ce-4384-bba6-f5bd01070821.png">

**Comment by Sven-TBD** [comment]
This bug had been fixed now, I closed this issue.
