### ISSUE TITLE
Duplicated data in statistics should be cleared

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#296]
![image](https://user-images.githubusercontent.com/7271329/232736841-77653e83-b90e-432a-a40c-45c048cc797f.png)
![image](https://user-images.githubusercontent.com/7271329/232736900-37b0bb37-69c1-4c8b-876a-d2c7741fb301.png)

The script has been fixed by https://github.com/Magickbase/ckb-explorer-public-issues/issues/240

But the historical data are still incorrect

**Comment by zmcNotafraid** [comment]
After query data, near 2022-12-03 we found these data.
```
irb(main):013:0> Time.at(1670025900)
=> 2022-12-03 00:05:00 +0000
irb(main):014:0> Time.at(1670112300)
=> 2022-12-04 00:05:00 +0000
irb(main):015:0> Time.at(1670169600)
=> 2022-12-04 16:00:00 +0000
```

**Comment by zmcNotafraid** [comment]
- [ ] use task to update daily_statistics table's total_dao_deposit value

**Comment by zmcNotafraid** [comment]
> https://bugs.ruby-lang.org/issues/18604
![image](https://user-images.githubusercontent.com/12708910/233570653-bd27a913-959a-4499-8909-e35f77e98561.png)
When run task have bug, need to update `bigdecimal` gem
