### ISSUE TITLE
Negative live cell count 

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#30]
This page shows the address has negative live cell count -5. 
https://pudge.explorer.nervos.org/address/ckt1qyqf3xlyd4tr55sc95efgatcfgj6988s3yusmatxk4

**Comment by Keith-CY** [comment]
Any update on this issue?

**Comment by ShiningRay** [comment]
目前对线上环境的数据进行了订正
根据已有的 live_cells_count 为负的地址进行了一些排查
发现这类地址的特点是交易数量非常大，而且数量越大，live cell count绝对值越大
例如 (ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwyt2p74pg74ccrqll50yvv50fd4098u5sq3q7ue)[https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwyt2p74pg74ccrqll50yvv50fd4098u5sq3q7ue] 在订正之前是 -184

**Comment by ShiningRay** [comment]
该地址 [ckb1qrlsyt24ztfatlvkznxxatg3pyja0gu73yttdvwg6kt8s3hy6vnnxq2q6uls60zkrl92uvcw40qrpkxed2ws4umdp3g3fzpktz34pju780nv00huharf0ud8lrcyl7uduu04xpyzdtmmln37f5ukfqlfxkpq5wghqsqqqqqqqq9g8prq](https://explorer.nervos.org/address/ckb1qrlsyt24ztfatlvkznxxatg3pyja0gu73yttdvwg6kt8s3hy6vnnxq2q6uls60zkrl92uvcw40qrpkxed2ws4umdp3g3fzpktz34pju780nv00huharf0ud8lrcyl7uduu04xpyzdtmmln37f5ukfqlfxkpq5wghqsqqqqqqqq9g8prq) 上的余额和 live_cells_count 为负
并且只有 2 个交易
这两个交易各有两个特点：一个交易cell inputs 中没有自己地址上的cell，一个交易outputs 中没有自己地址上的cell
所以初步怀疑，这个live cells 为负的情况和余额为负，是因为cell inputs 或 outputs 中缺少自己的地址，导致同步进程没有将其统计进去。

**Comment by ShiningRay** [comment]
在 staging 环境中对于块处理进行了一些调试和追踪，发现主要的负数问题还是脏数据造成的——有部分地址的 balance 与 live cell 的总和不对应。
计划先根据 live cell 对地址进行数据订正，然后在观察和追踪是否会出现再出现不对应的情况。
后续会考虑对 balance 逻辑进行修改，比如由数据库层面，通过 trigger 进行余额的维护，以更好的保证数据的完整性。

**Comment by ShiningRay** [comment]
Staging 环境中，我将所有的地址的余额都进行了修复，然后又发现了新的脏数据
该地址
[ckt1qr6k6tltndf5kh09zl4p63wju9cejya9mangkkns3aaugkm6mm8tgq2vctn9ycsy4e4zar70ztm663e0gxskqm2mjcjta67jzhtcpqyldff9d38e4h6hpw6rvzjvtg29mtjjr69dzwpedzjdayled8ufjr2lj8prqcqqqqqqqqncxlmv](https://pudge.explorer.nervos.org/address/ckt1qr6k6tltndf5kh09zl4p63wju9cejya9mangkkns3aaugkm6mm8tgq2vctn9ycsy4e4zar70ztm663e0gxskqm2mjcjta67jzhtcpqyldff9d38e4h6hpw6rvzjvtg29mtjjr69dzwpedzjdayled8ufjr2lj8prqcqqqqqqqqncxlmv)
只有两笔交易，第一笔转入的交易产生的 CellOutput，在数据库中并不存在，所以在后面一个交易中，导致了余额变成了负数。
现在需要了解为何前一笔交易没有成功创建 CellOutput

**Comment by ShiningRay** [comment]
balance 的问题是原有的数据更新都是在rails层完成的，而且是每个块根据 cell outputs 进行一次批量操作，存在一些难以捕获的bug。我的计划是，在cell_outputs表中，使用数据库的 trigger 来维护 address 的 balance，当插入cell记录或者 live dead 状态转换的时候直接更新，保证数据一致性，以防止rails层出错。这个整体可能需要一周的时间来做改造

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/175196465-1d47aab1-957a-4144-b2c8-81098ce1f416.png)
Left: fixed in staging
Right: testnet production
