### ISSUE TITLE
Update `tasks` in https://github.com/Magickbase/infra/issues automatically

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#300]
Each PR of CKB Explorer may require running a task on server manually, and now these tasks will be opened in https://github.com/Magickbase/infra/issues manually, e.g. https://github.com/Magickbase/infra/issues/35

This progress requires extra communication and is not reliable so that it should be processed automatically.

Here are the steps
1. add the task description in PR comment, will be designed at https://github.com/Magickbase/shaping/issues/44
2. create the task issue in https://github.com/Magickbase/infra/issues when the PR is merged, will be designed at https://github.com/Magickbase/shaping/issues/45
3. update the task issues' status when these features are deployed to testnet, mainnet, will be designed at https://github.com/Magickbase/shaping/issues/45

**Comment by Sven-TBD** [comment]
This feature has been achieved in the current work flow, so I am closing it now
