### ISSUE TITLE
The script page style is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#302]
Link https://temp.main.layerview.io/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type/deployed_cells?page=1&size=10
1、Tooltip styling is missing on mouseover.
> <img width="1266" alt="image" src="https://user-images.githubusercontent.com/25676576/233987826-dc6caffb-5201-4265-a176-fd770068205c.png">

2、When adjusting the screen size, the right alignment of complex icons is abnormal.
> <img width="1262" alt="image" src="https://user-images.githubusercontent.com/25676576/233988440-06f88f35-b415-430f-8449-7e633fc528a5.png">
> <img width="965" alt="image" src="https://user-images.githubusercontent.com/25676576/233989033-5e8bc53f-2417-44ea-945a-262fb8077a20.png">

3、Page elements are shifted.
> Steps:
> a. Click the cell information icon in the lower right corner of the script page;
> b. Change the page size;
> c. Switch pages and change the page size;
> <img width="846" alt="image" src="https://user-images.githubusercontent.com/25676576/233990536-b0fe67cd-d662-42f0-85ec-17a676432f01.png">
> <img width="726" alt="image" src="https://user-images.githubusercontent.com/25676576/233990709-829fd072-c9a2-406b-9b41-f5e18e09d4e2.png">
> <img width="711" alt="image" src="https://user-images.githubusercontent.com/25676576/233990872-1dfd4c4b-c8d4-43f0-adae-66614883d8ea.png">

**Comment by zhb666** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1263
