### ISSUE TITLE
Sort transactions of a specific script in desc by time

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#303]
![image](https://user-images.githubusercontent.com/7271329/234288396-0c723b47-a809-4fe1-a0bd-f3ee466a25f8.png)
It's ordered ascendingly by time, which is reverted compared to other pages

**Comment by Danie0918** [comment]
@ShiningRay Please add the PR and close this issue.

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1285
