### ISSUE TITLE
Incorrect occupied ckb on address page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#307]
This is the screenshot provided by user
![image](https://user-images.githubusercontent.com/7271329/236630349-4a0be9ce-d66a-4304-9f87-c548c13bc9d7.png)

Notice that `occupied` is `4476241.84249564`.

After a fix, the `occupied` turned into `3849740.00000000`

![image](https://user-images.githubusercontent.com/7271329/236630420-7735e8f4-edc7-4d0a-83ea-526a242bdf05.png)

The diff is `4476241.84249564 - 3849740.00000000 = 626501.84249564`

And 2 transactions were found in the tx history that have the same value

![236630529-af0077a2-a757-438e-8ed4-68214e20b4b3](https://user-images.githubusercontent.com/7271329/236630690-7fa21e4f-35a4-4101-9a3a-5de84d47990e.png)
![image](https://user-images.githubusercontent.com/7271329/236630771-0cec670b-4c60-4cab-8267-cce4dfcb5643.png)

One of them is not counted correctly

**Comment by zmcNotafraid** [comment]
From current research, to calculate occuiped needs increase outputs capacity and decrease inputs capacity if these cell data is not 0x.For this examaple, I guess it add wrong data. Maybe not check outputs cell data or in that time the cell data is not 0x.

**Comment by zmcNotafraid** [comment]
link: https://github.com/nervosnetwork/ckb-explorer/pull/1268
