### ISSUE TITLE
Negative CKB capacity of some addresses

### ISSUE THREAD

**Issue by Flouse** [Magickbase/ckb-explorer-public-issues#31]
<img width="860" alt="image" src="https://user-images.githubusercontent.com/1297478/169931202-050d9ac1-82c8-422d-a088-f1f90c7be26e.png">
https://pudge.explorer.nervos.org/address/ckt1qyqr5jd078v0euv3fjjptj7wjmlsh8lpkr8sqmxnea

**Comment by Keith-CY** [comment]
Will be fixed by this PR https://github.com/nervosnetwork/ckb-explorer/pull/918

**Comment by Keith-CY** [comment]
PR has been merged and deployed to testnet, but the balance is still negative. Should we trigger a job for history data? @ShiningRay

**Comment by ShiningRay** [comment]
最新进展 https://github.com/Magickbase/ckb-explorer-public-issues/issues/30#issuecomment-1151907009

**Comment by ShiningRay** [comment]
https://github.com/Magickbase/ckb-explorer-public-issues/issues/30#issuecomment-1162173730

**Comment by Keith-CY** [comment]
Inputs are not covered on recovering addresses' balances when rollback happens, so capacities consumed in the rollbacked blocks are all double spent.

Ref: https://github.com/nervosnetwork/ckb-explorer/pull/906/files#diff-43d8e74cf1f6b77effa014acbe073983b6408419d11c711b89e6fc677b1a13edR1046
