### ISSUE TITLE
Change daily statistic generator to trigger by block processing

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#314]
Currently, the daily statistic generator is triggered by cronjob, which runs at specific time every day.
But in edge case, the blocks yesterday has not been fully processed yet, or there was revertion on chain, the daily statistic may not cover all the block datas in one day.
So we should trigger daily statistic generator when new day's block committed.

**Comment by zmcNotafraid** [comment]
I think thiese statistic move to block process is do more harm than good.Because block node process is more important and the process speed will limit by these logic.
