### ISSUE TITLE
Need a standard for backend API. need a meeting for both backend and frontend developers.

### ISSUE THREAD

**Issue by iamyates** [Magickbase/ckb-explorer-public-issues#315]
currently we have below as backend API standards:  

# 需要制定一个前后端的接口开发规范。为了不引起歧义，我就直接用中文写了：（回头需要更新到github 的wiki上）

1. 数字就返回数字，不再返回 "1234" 这样的字符串  .e.g    

```
{
   number: 10   // 而不是  number: "10"
}
```

2. 每个json的key都存在，就是没意义的时候，返回 "" 

```
{
   result_type: "type1",
   type_1_field: "x",  // 该field仅仅在 type1 的时候会有值
   type_2_field: "",  // 该field仅仅在 type2 的时候会有值， 因为当前的result_type == 'type1', 所以该field为 ""
}
```

3. 接口的访问形式，就是 /api/v2 开头的前缀

之前的老接口都是 /api/v1, 新接口都使用 /api/v2

5. 在前端和后端商量好接口的格式后, 后端同学会把它更新到我们的apifox上，都时候就有文档了。

6. json 中的key使用驼峰表达式的风格

7. （需讨论）目前 /api/v1 返回的json格式， 都是 id, attribute 这样的属性，而  /api/v2则是前端需要什么，就返回什么，
不会把值包裹在 attribute这个field 中。这里是否需要更改？

**Comment by zhb666** [comment]
目前V1接口和v2接口返回的格式不一致，如果需要改的话，前端也需要把V2的接口统一处理，好处是对后续代码的健壮性包括前端定位报错原因也是比较好的
