### ISSUE TITLE
Optimize the current address highlighting style

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/ckb-explorer-public-issues#317]
The currently highlighted address is in gray style, which is not obvious compared to the normal address, which is easy to cause user misunderstanding and needs to be optimized

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/122437870/3cdb935f-f7a2-49ef-a1ff-13e9e7aa9b2e)

**Comment by Sven-TBD** [comment]
@Kirl70  We could do a few interaction optimizations. For example, highlight the transaction result, that's +0.0000 CKB, as same as the current address which is highlighted by grey background color.
My proposal is here. https://vs0cjf.axshare.com/#id=uoozvs&p=_317_optimize_the_current_address_highlighting_sty&g=1
FYI

**Comment by Kirl70** [comment]
Change the difference value to the same style as the main address and separate it from the address information with a separator line.

Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679%3A26337&t=XsesYbk4rV7Iql9U-1
<img width="1515" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/817eb09d-5e16-42b1-a423-f6efd1fde51c">

**Comment by Kirl70** [comment]
Add an icon after the selected address and hover over it to show a hint. Use normal color for unselected addresses, and change color on mouse hover to indicate that users can click to jump.
Please confirm the adjustment program @Danie0918 @Sven-TBD 

<img width="1348" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/543e5340-5611-4cac-b1e7-cfb89d063bcb">

**Comment by Danie0918** [comment]
> Add an icon after the selected address and hover over it to show a hint. Use normal color for unselected addresses, and change color on mouse hover to indicate that users can click to jump. Please confirm the adjustment program @Danie0918 @Sven-TBD
> 
> <img alt="image" width="1348" src="https://user-images.githubusercontent.com/106060898/238513002-543e5340-5611-4cac-b1e7-cfb89d063bcb.png">

I think the icon can be omitted, which will increase the user's understanding cost.Others are fine, @Sven-TBD you decide the final plan.

**Comment by Sven-TBD** [comment]
I'm ok with that , although I'd like to switch an icon that may represent "the current one" @Kirl70

**Comment by Kirl70** [comment]
> Is this a `home` icon? For me, it's more like `up`

Yes, this is an upward-facing icon, indicating that this address is the top header address of the page. However, with your reminder, I have a new idea. Which icon do you think better represents the current address meaning?

<img width="870" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/1357b669-78ca-42e5-b127-ab973526273a">

**Comment by Keith-CY** [comment]
> > Is this a `home` icon? For me, it's more like `up`
> 
> Yes, this is an upward-facing icon, indicating that this address is the top header address of the page. However, with your reminder, I have a new idea. Which icon do you think better represents the current address meaning?
> 
> <img alt="image" width="870" src="https://user-images.githubusercontent.com/106060898/239116371-1357b669-78ca-42e5-b127-ab973526273a.png">

I think the `home` is cool, because addresses are highlighted on `address detail page`, kind like a `homepage of an address`

The `bookmark` icon can be used in the future, like features of viewing address collection.

**Comment by Kirl70** [comment]
> > > Is this a `home` icon? For me, it's more like `up`
> > 
> > 
> > Yes, this is an upward-facing icon, indicating that this address is the top header address of the page. However, with your reminder, I have a new idea. Which icon do you think better represents the current address meaning?
> > <img alt="image" width="870" src="https://user-images.githubusercontent.com/106060898/239116371-1357b669-78ca-42e5-b127-ab973526273a.png">
> 
> I think the `home` is cool, because addresses are highlighted on `address detail page`, kind like a `homepage of an address`
> 
> The `bookmark` icon can be used in the future, like features of viewing address collection.

Got it, the design draft has been changed to a `home` icon.

**Comment by zhb666** [comment]
PR:https://github.com/Magickbase/ckb-explorer-frontend/pull/10
