### ISSUE TITLE
The `Cell Count` chart data is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#318]
https://explorer.nervos.org/charts/cell-count
<img width="1225" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e1302ea6-043e-4199-92ba-94994830ff84">

Need to confirm: from the code point of view, are the curves respectively `live cells` and `dead cells`?
If `all cells` = `live cells` + `dead cells`, then all cells should always be greater than live cells, then there is a problem with the position of the curve on the screenshot.

**Comment by ShiningRay** [comment]
The frontend requests the live cells and dead cells count.

`https://ckb-explorer-api.temp.layerview.io/api/v1/daily_statistics/live_cells_count-dead_cells_count`

**Comment by Keith-CY** [comment]
> The frontend requests the live cells and dead cells count.
> 
> `https://ckb-explorer-api.temp.layerview.io/api/v1/daily_statistics/live_cells_count-dead_cells_count`

So these 2 line represent `live cells` and `dead cells` in fact, the label `all cells` is imprecise.

Should we update the label or update the chart, or we change it to a stacked chart as https://echarts.apache.org/examples/en/editor.html?c=area-stack with three labels(live, dead, all) @Danie0918 @Sven-TBD

**Comment by Danie0918** [comment]
I think the chart with three labels(live, dead, all) is better. The live cells are the unspent cells, the dead cells are the spent cells, and all can reflect the history of the whole chain.

**Comment by zhb666** [comment]
### PR:https://github.com/Magickbase/ckb-explorer-frontend/pull/11

**Comment by FrederLu** [comment]
Link：https://github.com/Magickbase/ckb-explorer-public-issues/issues/347
