### ISSUE TITLE
Design NFT List and NFT Detail Page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#32]
## NFT Collection List
- collection name
- creator address
- standard: m-nft, cota, nrc-721
- holder count/minted count;

## NFT Collection Detail
- standard: m-nft, cota, nrc-721
- creator address
- inventory
  - unique index
  - owner address
  - image url

- holder list
  - owner address
  - quantity of this collection

- transfers
  - tx hash
  - age
  - from address
  - to address
  - unique index
  - image url
  - type: mint, transfer

## NFT Item Detail
- standard: m-nft, cota, nrc-721
- image url
- unique index
- owner address
- creator address
- transfers
  - tx hash
  - age
  - from address
  - to address
  - type: mint, transfer

**Comment by Keith-CY** [comment]
@ShiningRay @shaojunda any advice on the draft of NFT's list/detail

**Comment by Keith-CY** [comment]
Transfers of a specific CoTA NFT

Fields of a transfer record
1. tx hash
2. age
3. from address
4. to address
5. type: mint/transfer

`Output index` could be used on navigating to the transaction page to locate the corresponding output.

**Comment by Keith-CY** [comment]
> > Transfers of a specific CoTA NFT
> > Fields of a transfer record
> > 
> > 1. tx hash
> > 2. age
> > 3. from address
> > 4. to address
> > 5. type: mint/transfer
> > 
> > `Output index` could be used on navigating to the transaction page to locate the corresponding output.
> 
> 1. What does the `age` mean?
> 2. Do you need the `Output index` filed? If you need it, Why is it not on the list?

`age` could be calculated from `timestamp` of the block and is usually displayed as `xx mins ago` instead of `xxxx-xx-xx`

`output index` is not mandatory, only fields in the last are required since they will be displayed in the UI

**Comment by duanyytop** [comment]
Considering that the address has multiple formats, would it be better to provide serialized lock scripts for `from` and `to`?

**Comment by Keith-CY** [comment]
> Considering that the address has multiple formats, would it be better to provide serialized lock scripts for `from` and `to`?

All addresses will be reformed in front-end, but it's a good idea to return lock scripts since APIs of backend are all going to be updated to return scripts.

**Comment by Keith-CY** [comment]
API Docs: https://www.apifox.cn/web/project/962207

**Comment by Keith-CY** [comment]
> > > Considering that the address has multiple formats, would it be better to provide serialized lock scripts for `from` and `to`?
> > 
> > 
> > All addresses will be reformed in front-end, but it's a good idea to return lock scripts since APIs of backend are all going to be updated to return scripts.
> 
> In order to make dApps development more friendly, we decided to provide the new full addresses for `to` and `from` cc @Keith-CY

That's fine

**Comment by Keith-CY** [comment]
Front-end https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1008

**Comment by Keith-CY** [comment]
API ready in stg

**Comment by Keith-CY** [comment]
@duanyytop how is cota service going

**Comment by duanyytop** [comment]
> @duanyytop how is cota service going

We have released the CoTA services with the `cota-aggregator` and `cota-nft-entries-syncer`. 

Please use [cota-nft-entries-syncer](https://github.com/nervina-labs/cota-nft-entries-syncer) with commit_id d1699465abde8cdaf7c5d50225882f3dfb34b079 and [cota-aggregator](https://github.com/nervina-labs/cota-aggregator/releases/tag/v0.6.7) v0.6.7 .

You can visit the [CoTA services deployment document](https://www.cotadev.io/docs/guides/quick-deployment) and the aggregator [RPC APIs](https://github.com/nervina-labs/cota-aggregator#apis)

**Comment by Keith-CY** [comment]
> > @duanyytop how is cota service going
> 
> We have released the CoTA services with the `cota-aggregator` and `cota-nft-entries-syncer`.
> 
> Please use [cota-nft-entries-syncer](https://github.com/nervina-labs/cota-nft-entries-syncer) with commit_id [d1699465abde8cdaf7c5d50225882f3dfb34b079](https://github.com/nervina-labs/cota-nft-entries-syncer/commit/d1699465abde8cdaf7c5d50225882f3dfb34b079) and [cota-aggregator](https://github.com/nervina-labs/cota-aggregator/releases/tag/v0.6.7) v0.6.7 .
> 
> You can visit the [CoTA services deployment document](https://www.cotadev.io/docs/guides/quick-deployment) and the aggregator [RPC APIs](https://github.com/nervina-labs/cota-aggregator#apis)

cc @ShiningRay

**Comment by ShiningRay** [comment]
According to our NFT model and data synchronization mechanism, we need some a RPC API in COTA Aggregator:

Providing a "block number" parameter, the API will return all the CoTA NFT transactions in corresponding block.
And the result returned by the API should contain: 
1. the related cota_id
2. token_index
3. block number
4. tx hash
5. from
6. to
7. type

**Comment by duanyytop** [comment]
> 

https://github.com/nervina-labs/cota-aggregator/pull/115 I have added the `get_transactions_by_block_number` rpc

**Comment by duanyytop** [comment]
@ShiningRay I wonder if these RPCs are enough for you.

**Comment by duanyytop** [comment]
https://github.com/nervina-labs/cota-aggregator/releases/tag/v0.6.8
