### ISSUE TITLE
No way to jump out an error-caught page until refresh it

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#321]
Visit https://explorer.nervos.org/transaction/0x205689d5cd1fd1a29b49a88ba7284c1c04f7311f21b45e69cc505c3b63fc5de8

and get a page as follows
https://explorer.nervos.org/transaction/0x205689d5cd1fd1a29b49a88ba7284c1c04f7311f21b45e69cc505c3b63fc5de8

Now click any links in the navigator will not go to other pages

https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/f055f7d9-9554-4909-8995-10cef16745c8

**Comment by zhb666** [comment]
The issue has not been successfully reproduced. Could you please provide more triggering conditions?

https://github.com/Magickbase/ckb-explorer-public-issues/assets/18475950/6266ad49-44fc-4c58-b6b9-907d8b77ffc0

**Comment by Keith-CY** [comment]
> The issue has not been successfully reproduced. Could you please provide more triggering conditions?
> 
>  2023-05-19.10.35.16.mov

The error made the page blank was fixed by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/87aaf3fce50ed408f09ff35e471549dfd3c29619, so the page is rendered correctly.

It can be reproduced by throwing an error manually in development mode

**Comment by zhb666** [comment]
PR ：https://github.com/Magickbase/ckb-explorer-frontend/pull/7
