### ISSUE TITLE
in unit test , the factory: block.rb always has a block-timestamp with :  1683971683, but in real env, the timestamp is  1683971683000, do we need to handle this?

### ISSUE THREAD

**Issue by iamyates** [Magickbase/ckb-explorer-public-issues#322]

**Comment by rabbitz** [comment]
The timestamp of the factory creation block has been corrected here:

https://github.com/nervosnetwork/ckb-explorer/pull/1301/files#diff-a251ed6a1e398a4e49ac08b5fe431abfee8476ef5d585f7061838f4ba7d4caa2L8
