### ISSUE TITLE
The `Average Block Time` data on the homepage is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#323]
During the period from 5/13 to 5/16, the data on the `Average Block Time` graph on the home page looked abnormal.
https://explorer.nervos.org/
<img width="673" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/2fc27194-213f-4515-b25b-b7c2566f386f">

Data source:
https://explorer.nervos.org/charts/average-block-time
<img width="783" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/ab98d385-414c-4e87-9b14-593081bf34d3">

**Comment by ShiningRay** [comment]
This is because the data recrods returned by server is not order by timestamp
https://github.com/nervosnetwork/ckb-explorer/pull/1281
