### ISSUE TITLE
Synchronize CoTA NFTs

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#33]
Append CoTA NFT in the `User Defined Token` with type `CoTA`
![image](https://user-images.githubusercontent.com/7271329/169942462-3f7f0d8d-e8e0-448b-9de2-33462484d249.png)

**Comment by Keith-CY** [comment]
It's been done in https://github.com/nervina-labs/cota-aggregator

**Comment by Keith-CY** [comment]
Two services are required
1. https://github.com/nervina-labs/cota-aggregator
2. https://github.com/nervina-labs/cota-nft-entries-syncer

Service of 2CPUs, 4GB is required

**Comment by Keith-CY** [comment]
Docs from nervina: https://gist.github.com/duanyytop/b44652f8cda5f6e75ed2f94d067da01b

**Comment by Keith-CY** [comment]
Expected to be done by Sep.

**Comment by Keith-CY** [comment]
Checking API document of CoTA aggregator

**Comment by Keith-CY** [comment]
PRC APIs not good enough for us

**Comment by ShiningRay** [comment]
最早是打算通过RPC API将数据同步到ckb explorer的数据库中。然而ckb explorer是通过扫块来同步数据，aggregator的RPC接口并没有提供与特定块相关的查询，只能通过特定的地址或者特定的cota id进行查询，所以无法实现同步。
后来研究了cota nft syncer（没有对外接口） 的数据库结构，但是发现模型结构与ckb explorer的模型存在一些出入，导致开发进度较慢。
由于考虑到cota本身信息其实存储在链下，所以此处决定不进行全量同步，而试当用户访问的时候才将相关请求转发到cota aggregator，以降低开发成本。

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1002
