### ISSUE TITLE
Faucet page style optimization

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#335]
https://faucet.nervos.org/
<img width="617" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7fa445df-4814-4cd8-81cf-4695c6bb0d27">

- [ ] 1. Reserve the location of the abnormal prompt information to avoid pressing it when the amount line information appears;
- [ ] 2. `Remaining: 30,000 CKB` When there is a value, continue to display on one line without wrapping;

The specific style is subject to the design draft.

**Comment by IronLu233** [comment]
https://github.com/Magickbase/ckb-testnet-faucet/pull/13
But due to the issue of frontend code builder, the UI is not updated after code changes. Some UI is not same as the design.

**Comment by IronLu233** [comment]
https://github.com/Magickbase/ckb-testnet-faucet-frontend a new repo is here.

**Comment by Keith-CY** [comment]
There are 2 details to update

1. External link should be navigated to a new tab, including `tx hash` and `address` in the list
2. `label` like `process` should be capitalized

**Comment by IronLu233** [comment]
> There are 2 details to update
> 
> 1. External link should be navigated to a new tab, including `tx hash` and `address` in the list
> 2. `label` like `process` should be capitalized

A new PR for these issues established. 

https://github.com/Magickbase/ckb-testnet-faucet-frontend/pull/10

**Comment by Keith-CY** [comment]
Has been deployed to https://faucet.nervos.org
