### ISSUE TITLE
Improving Supplementary Test Cases

### ISSUE THREAD

**Issue by rabbitz** [Magickbase/ckb-explorer-public-issues#339]

**Comment by Keith-CY** [comment]
> The statistics for test coverage seem a bit off. The comparison is between the differences of commits 92915ff and 8110b1f. I checked and 92915ff was submitted three weeks ago. Could this be a configuration issue?
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/594db715-6b98-47c3-8e55-30de50076732)

Relevant PR: https://github.com/nervosnetwork/ckb-explorer/pull/1299

**Comment by rabbitz** [comment]
Codecov Report test coverage comparison is a comparison between the current branch and the target branch, and each branch has a record of the corresponding branch after running the test.

The codecov report of the develop branch is https://app.codecov.io/gh/nervosnetwork/ckb-explorer/commits?branch=develop
The codecov report of the update-reviewers branch is https://app.codecov.io/gh/nervosnetwork/ckb-explorer/commits?branch=update-reviewers

Since there has been no commit on develop, the codecov report of the develop branch has always been the record of the commit `92915fff`.

Merge the develop branch into other branches, run the test of the develop branch, and update the codecov report of its corresponding branch.

@Keith-CY

**Comment by rabbitz** [comment]
The codecov report corresponds to the head ref, not the base ref, because dvelop is a base ref, so it will not be updated. If dvelop is used as a head ref and merged into testnet or other branches, then the report on https://app.codecov.io/gh/nervosnetwork/ckb-explorer/commits?branch=develop will be updated.

**Comment by rabbitz** [comment]
now there is another problem

https://app.codecov.io/gh/nervosnetwork/ckb-explorer/commits?branch=fix%2Fblock_factory_timestamp

The corresponding PR is https://github.com/nervosnetwork/ckb-explorer/pull/1311

https://app.codecov.io/gh/nervosnetwork/ckb-explorer/commits?branch=refactor%2Fremove_cap_files

The corresponding PR is

https://github.com/nervosnetwork/ckb-explorer/pull/1308


These have reports but are not displayed on the github pull request page. We need to look at the reason again.
