### ISSUE TITLE
Support exporting transaction in CKB data structure

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#34]
![image](https://user-images.githubusercontent.com/7271329/169943758-6ac86130-a7bd-4645-808b-57a41661e133.png)

**Comment by Keith-CY** [comment]
Including hex string data

**Comment by Keith-CY** [comment]
This feature is strongly required by users so we are going to support it before the UI re-design

Please add a download button on the block page(https://explorer.nervos.org/block/7918709) and the transaction page(https://explorer.nervos.org/transaction/0x5fafeeabbc4bfd9b04f670707b316168d808b236209754ee927173f05606a993) to download raw data of the corresponding block or transaction. @Kirl70

**Comment by Kirl70** [comment]
Block Page:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4340%3A19953
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/106060898/186155233-51b597c6-1efc-4001-877e-edeb4a3b6974.png">

Transaction Page:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=4341%3A20129
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/106060898/186155605-b59a8dbf-0777-40de-9a5b-07b6fb23dcab.png">

**Comment by Keith-CY** [comment]
Backend PR: https://github.com/nervosnetwork/ckb-explorer/pull/1003

**Comment by Keith-CY** [comment]
Exporting a transaction has been supported
![image](https://user-images.githubusercontent.com/7271329/190468328-76883d52-4d5d-4469-ad55-4ca58d5eda84.png)

**Comment by Keith-CY** [comment]
> Exporting a transaction has been supported ![image](https://user-images.githubusercontent.com/7271329/190468328-76883d52-4d5d-4469-ad55-4ca58d5eda84.png)

@doitian
