### ISSUE TITLE
The Cell info pop-up information display is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#341]
After clicking `Cell info` on the transaction page, after switching tabs on the pop-up window, loading is displayed for a long time, triggering a sentry error report, and the console prompts `TypeError: Cannot read properties of undefined (reading 'lock')`.

https://pudge.explorer.nervos.org/transaction/0x643edf3271569def307e226ccb86fe228054674f7c3a3aea51c7b6c08aeaa528
<img width="1424" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7e476073-04fa-49c3-9c4a-88213d9ef343">

https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/97df629f-c916-4714-9c62-f9ddf50b6357

**Comment by rabbitz** [comment]
#### Reason:

The `tx_status` returned by transaction ·0x643edf3271569def307e226ccb86fe228054674f7c3a3aea51c7b6c08aeaa528· is `rejected`, but
https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/pages/Transaction/TransactionCellScript/index.tsx#L72 The value of `cell_info` is taken here, and the interface does not return `cell_info`, so an error is reported.

**Comment by zhb666** [comment]
PR:https://github.com/Magickbase/ckb-explorer-frontend/pull/12

**Comment by rabbitz** [comment]
> PR:[Magickbase/ckb-explorer-frontend#12](https://github.com/Magickbase/ckb-explorer-frontend/pull/12)

The `cell_info` attribute of the cell is no longer returned, and calling `cell.cell_info` in other places should also need to be adjusted. e.g: https://github.com/Magickbase/ckb-explorer-frontend/blob/a0839d08355e25a9933c1c4757950acb5e2ba22e/src/pages/Transaction/TransactionCellScript/index.tsx#L80
