### ISSUE TITLE
Transactions with pending status appear in the list of transactions on the home page

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/ckb-explorer-public-issues#344]
This issue was discovered by @yanguoyu  and confirmed by @ShiningRay 
In the list of transactions and the list of all transactions on the front page, from time to time, there are transactions with block height 0, which are actually pending transactions. Now we have suspended the synchronization of pending transactions to avoid these data from appearing on the front page

**Comment by ShiningRay** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1306
