### ISSUE TITLE
Confirm the accuracy of the cell count data.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#347]
Now the cell count uses a stacked graph, but the background data seems to be abnormal, which leads to controversial results, and the background needs to confirm the accuracy of the data.

https://ckb-explorer-git-fork-zhb666-fix-chart-data-abnormal-magickbase.vercel.app/charts/cell-count

<img width="1207" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/619064c1-5a41-4369-81d9-d49dc7c1505b">

**Comment by zhb666** [comment]
The value of all is obtained by adding live and dead together.

**Comment by zhb666** [comment]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/18475950/3392dc23-983f-4638-9478-3b6dba15b0a7)
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/18475950/e5827362-935c-483c-82ce-e05bd01abef2)
This is the data from the main network.

**Comment by FrederLu** [comment]
Verified.
