### ISSUE TITLE
Historical pending transactions are not cleared periodically

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#348]
https://explorer.nervos.org/transaction/list?page=14&tab=pending
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/6bd03255-4444-4811-83cb-14b37b5c8d83)

https://pudge.explorer.nervos.org/transaction/list?page=5000&tab=pending
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/e7ba426e-d581-466a-a956-8fffd640353d)

**Comment by ShiningRay** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1328

**Comment by Danie0918** [comment]
#380 https://github.com/Magickbase/ckb-explorer-public-issues/issues/380

The unexpected behavior is still there.

**Comment by rabbitz** [comment]
Pending transactions before August 10th are cleaned up
