### ISSUE TITLE
Statuses of transactions are not updated correctly

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#349]
https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/65b36c68-8454-4499-8a76-5ce1a23d1bd6

Recent transactions are resolved on-chain, but their statuses are not updated correctly and `pending` is displayed on the detail page

**Comment by ShiningRay** [comment]
Fixed in https://github.com/nervosnetwork/ckb-explorer/pull/1316
