### ISSUE TITLE
Use `AttrLogic` to refactor `DailyStatistic` and `DailyStatisticGenerator`

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#350]
I now suggest we move the per-attribute generation logics into model file, thus we can make data correction and processing more flexible.

We can refer the usage of `AttrLogic` in the `statistic_info.rb`

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1321
