### ISSUE TITLE
Algorithm of page count should be refactored in UI

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#356]
Now the `page size` in query parameter is used to calculate the total page count by `total count / page size`.

But the `page size` in query parameter is unreliable that may be ignored by the service; say, a query with `page size = 10` returns `20` entries per page.

So the `page size` to calculate the `page count` should be obtained from the response.

**Comment by zhb666** [comment]
It was noticed that the pageSize parameter in the pagination on the page is defined as a constant and won't change. If there's a need to modify it, it would likely be done by passing the desired pageSize as a parameter along with the totalCount.

**Comment by Keith-CY** [comment]
> It was noticed that the pageSize parameter in the pagination on the page is defined as a constant and won't change. If there's a need to modify it, it would likely be done by passing the desired pageSize as a parameter along with the totalCount.

The `page size` to calculate `total page` should be from `response` of the list. So that incorrect `page size` in query won't lead to incorrect `total page`.

Say, UI request a list with `page size = 25`, but `page size` is discarded in backend, and it returns `total count = 100, page size = 10`. The `total page` should be `100 / 10` instead of `100 / 25`.

**Comment by IronLu233** [comment]
Hi, @Keith-CY Can I continue to this task?

**Comment by Keith-CY** [comment]
> Hi, @Keith-CY Can I continue to work on this task?

This task was assigned to @zhb666 by @Danie0918

**Comment by IronLu233** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/14
