### ISSUE TITLE
[bug] Spent Transaction Outputs are marked as `Unspent`

### ISSUE THREAD

**Issue by Flouse** [Magickbase/ckb-explorer-public-issues#359]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/1297478/6fd21d9f-2b38-425a-88c5-4375e438f187)
https://explorer.nervos.org/address/ckb1qrlkqfvp7pmx0mh4ggeve6zse09zcsvtxsvxz8qn9l9gf8g7mnth2qgu5dwttldyh42zuuweffk47nqdy4wk6ma6w0zpeazay6f7txesw25sqqqqzsqqqqp5qqqqp8gqqqq22qqqqrqs6pw3tk83cs54mak4sjwx5xnd46lyfzadrk90skqrqhv5s2jus6gqqqqpqqqqqqcqqqqqxyqqqqqfdhexfuu0lurl8txnrzv440pvwxhqu5zqxmlr90pc6kmqxumy6sqngqqqqqw2xh94lkjt64pww8v55m2lfsxj2htdd7a883qu73wjdyl9nvc895tx0jl3e3sd49xpeakfe7exrecmvprl0qp6pyqqqqqqcqpqqqqq5yxra8

**Comment by zhb666** [comment]
It looks like there might be an issue with the returned data. @Danie0918 
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/18475950/643d578a-a6d4-403c-865b-82aa473716c6)
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/18475950/81118e9c-5df0-44c8-8dee-4ec9e9bd41cf)

**Comment by ShiningRay** [comment]
This is because the cache is not cleared correctly

**Comment by ShiningRay** [comment]
https://github.com/Magickbase/ckb-explorer-public-issues/issues/66

**Comment by zmcNotafraid** [comment]
<img width="1509" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/d773415d-63b2-484e-b9a8-e42b61f64f2b">

**Comment by Flouse** [comment]
### https://explorer.nervos.org/transaction/0x5bbedb2bc032685ff4a969b8a37c4eb7b44d7761eaa1b4901de4486f933d3e12#0

<img width="1293" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/1297478/259647c8-7095-4a6e-855c-585f814aeb20">

The output#0 was spent, but it is marked as `Unspent`.
