### ISSUE TITLE
SubDiD should be resolved to the correct page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#361]
This issue comes from https://github.com/Magickbase/godwoken_explorer/issues/1465 and may happen on CKB Explorer too, should be confirmed or updated

**Comment by WhiteMinds** [comment]
This issue is currently blocked by https://github.com/Magickbase/ckb-explorer-public-issues/issues/369 because I cannot construct a convenient testing environment.

Additionally, based on the return type of the `das_accounts` interface, this issue may need to be handled by the backend?

**Comment by Keith-CY** [comment]
> This issue is currently blocked by #369 because I cannot construct a convenient testing environment.
> 
> Additionally, based on the return type of the `das_accounts` interface, this issue may need to be handled by the backend? Or the structure of the interface return type may need to be adjusted.

It was fixed by the backend in godwoken explorer because it's found that `run.ckbees.bit` and `ckbees.bit#run` are both returned from the .bit service but `ckbees.bit#run` is returned from the backend service.

It's a problem of .bit service that it returns subdid in two different formats.

```bash
curl -X POST https://indexer-v1.did.id/v1/sub/account/list -d'{"account":"ckbees.bit","page":1,"size":20}'
{"errno":0,"errmsg":"","data":{"account":"ckbees.bit","account_id_hex":"0xb3d0842e7fb28a2ceacfd04ed6a623be74f7bb83","enable_sub_account":1,"sub_account_total":1,"sub_account_list":[{"account":"run.ckbees.bit","account_id_hex":"0x45248da1c175632ec1cecd8e58ea70a5d69cf408","create_at_unix":1687613929,"expired_at_unix":1719149929,"owner_algorithm_id":5,"owner_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897","manager_algorithm_id":5,"manager_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}]}}%
```

```bash
 curl -X POST https://indexer-v1.did.id/v1/batch/reverse/record -d'{"batch_key_info":[{"type": "blockchain","key_info":{"coin_type": "60","key": "0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}}]}'

{"errno":0,"errmsg":"","data":{"list":[{"account":"run.ckbees.bit","account_alias":"ckbees#run.bit","err_msg":""}]}}% 
```

Notice that `ckbees#run.bit` is returned as `account_alias` from the endpoint `reverse/record`

In ckb explorer, the request is made from the front-end, so it should be handled in the front-end.

**Comment by WhiteMinds** [comment]
> In ckb explorer, the request is made from the front-end, so it should be handled in the front-end.

Currently, the front-end actually gets the `indexer-basic` data through the `das_accounts` interface on the back-end.

https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/contexts/providers/dasQuery.tsx#L29C67-L29C79

https://github.com/nervosnetwork/ckb-explorer/blob/97bb61726c59cc890c6967a18cb9a3c7e8e4b12a/app/services/das_indexer_service.rb#L3

**Comment by Keith-CY** [comment]
> > This issue is currently blocked by #369 because I cannot construct a convenient testing environment.
> > Additionally, based on the return type of the `das_accounts` interface, this issue may need to be handled by the backend? Or the structure of the interface return type may need to be adjusted.
> 
> It was fixed by the backend in godwoken explorer because it's found that `run.ckbees.bit` and `ckbees.bit#run` are both returned from the .bit service but `ckbees.bit#run` is returned from the backend service.
> 
> It's a problem of .bit service that it returns subdid in two different formats.
> 
> ```shell
> curl -X POST https://indexer-v1.did.id/v1/sub/account/list -d'{"account":"ckbees.bit","page":1,"size":20}'
> {"errno":0,"errmsg":"","data":{"account":"ckbees.bit","account_id_hex":"0xb3d0842e7fb28a2ceacfd04ed6a623be74f7bb83","enable_sub_account":1,"sub_account_total":1,"sub_account_list":[{"account":"run.ckbees.bit","account_id_hex":"0x45248da1c175632ec1cecd8e58ea70a5d69cf408","create_at_unix":1687613929,"expired_at_unix":1719149929,"owner_algorithm_id":5,"owner_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897","manager_algorithm_id":5,"manager_key":"0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}]}}%
> ```
> 
> ```shell
>  curl -X POST https://indexer-v1.did.id/v1/batch/reverse/record -d'{"batch_key_info":[{"type": "blockchain","key_info":{"coin_type": "60","key": "0x0ad1e5ed9dcf2af5753060a7e34eeec80e608897"}}]}'
> 
> {"errno":0,"errmsg":"","data":{"list":[{"account":"run.ckbees.bit","account_alias":"ckbees#run.bit","err_msg":""}]}}% 
> ```
> 
> Notice that `ckbees#run.bit` is returned as `account_alias` from the endpoint `reverse/record` while `run.ckbees.bit` is returned as `account`
> 
> In ckb explorer, the request is made from the front-end, so it should be handled in the front-end.

Has confirmed with .bit team that the format of `account_alias` is not defined in the protocol and is custom by the service.

**Comment by WhiteMinds** [comment]
According to the testing in https://github.com/Magickbase/ckb-explorer-public-issues/issues/369#issuecomment-1643694476, this issue does not exist in explorer, so closing this issue.
