### ISSUE TITLE
Use `time added to pool`  to refactor confirmation time

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#362]

**Comment by Keith-CY** [comment]
This feature is enabled in CKB@v0.110.0

Ref: https://github.com/nervosnetwork/ckb/releases/tag/v0.110.0

**Comment by zmcNotafraid** [comment]
```
curl -X POST --header "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"get_transaction","params":["0xd78052fb92d5724d920c38dad95bafc62ddbf00ffd18041c0b34be993796f6a6"],"id":1}' https://mainnet.ckb.dev/
{"jsonrpc":"2.0","result":{"cycles":"0x19636b","time_added_to_pool":"0x1891b5a18fd","transaction":{"cell_deps":[{"dep_type":"dep_group","out_point":{"index":"0x0","tx_hash":"0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c"}}],"hash":"0xd78052fb92d5724d920c38dad95bafc62ddbf00ffd18041c0b34be993796f6a6","header_deps":[],"inputs":[{"previous_output":{"index":"0x0","tx_hash":"0x987a8b939d674060640d90d0f60a89bbac18fa00d2f98d8c46d2d31d351cb840"},"since":"0x0"}],"outputs":[{"capacity":"0x2540be400","lock":{"args":"0xb881d7366be16683bc3bd38aef67533789e6942e","code_hash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","hash_type":"type"},"type":null},{"capacity":"0xb132359f729","lock":{"args":"0xd25cf7ff6e7c20e4b8c23fe6c57e3b9b0e0866fc","code_hash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","hash_type":"type"},"type":null}],"outputs_data":["0x","0x"],"version":"0x0","witnesses":["0x55000000100000005500000055000000410000009392fa68d3bc8c07f6192029a9ceff9a0d2c65748b6159f619ea6f5936d433d22d2b0d563808fcda12767c78f676ab96d1b6d4fc31eb0b03383451d538f6975c01"]},"tx_status":{"block_hash":null,"reason":null,"status":"pending"}},"id":1}
```

**Comment by Keith-CY** [comment]
Empty data of fee rate will be fixed along with this feature

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/9df02afa-b3d0-48e9-a592-9ccf10eec19d)

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1336

**Comment by zmcNotafraid** [comment]
> Empty data of fee rate will be fixed along with this feature
> 
> ![image](https://user-images.githubusercontent.com/7271329/251406016-9df02afa-b3d0-48e9-a592-9ccf10eec19d.png)

Current ckb transactions, we have two process two handle them.First for committed tx, we use get_block rpc to fetch and these txs we don't know these pool timestamp.Second for pending tx, we use websocket to fetch and know these enter pool timestamp.
But in above page's query, they query all tx include commited tx, so the confirmation time returns 0.After fix, we will only fetch tx that confirmation time greater than 0.

**Comment by zmcNotafraid** [comment]
<img width="1382" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/aadf36a7-c21e-4dbf-b669-87dab8a139ef">
testnet fixed

**Comment by Keith-CY** [comment]
Data on mainnet should be fixed too.
https://explorer.nervos.org/fee-rate-tracker

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/97653b36-56dd-47a7-a87b-6570bd358446)
