### ISSUE TITLE
Migrate API document from API Fox to ReadMe

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#363]
There are 3 reasons to migrate API Fox to ReadMe(https://readme.com/)

1. `Try it out` doesn't work because API Fox proxies requests on the page via their own server, while the service is deployed aboard that cannot be reached from a domestic server;
2. API Fox is limited to API reference that only fields in queries can be annotated, fields in responses are not annotated;
3. ReadMe supports a markdown-supported guide as a tutorial of the service.

Point 1 is the main reason of switching to ReadMe

**Comment by zmcNotafraid** [comment]
We should use browser agent 
<img width="538" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/8423813f-e1ea-4cbe-9604-15a187fc2fd2">

**Comment by Keith-CY** [comment]
> We should use browser agent <img alt="image" width="538" src="https://user-images.githubusercontent.com/12708910/256103024-8423813f-e1ea-4cbe-9604-15a187fc2fd2.png">

It requires an additional extension, which is not user-friendly.
TBH, the case that it requires an extension to send requests from browser directly is very suspicious

**Comment by zmcNotafraid** [comment]
There are two ways to pass version to path.
First use server's enum variables, like this need user to select.
<img width="534" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/6390ced0-c087-414e-a0e5-dd425f1d17af">
Second we split current api doc into two. One is `/v1,` another is `/v2`

**Comment by Keith-CY** [comment]
> There are two ways to pass version to path. First use server's enum variables, like this need user to select. <img alt="image" width="534" src="https://user-images.githubusercontent.com/12708910/256400363-6390ced0-c087-414e-a0e5-dd425f1d17af.png"> Second we split current api doc into two. One is `/v1,` another is `/v2`

I would suggest grouping them in separate `endpoint`, the `version` is not a configurable field for users

By putting `version` in the `endpoint`, it can be set easily in the editor


https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/521380ce-15b8-419b-840b-3760f1dd8a6b

**Comment by Keith-CY** [comment]
> > There are two ways to pass version to path. First use server's enum variables, like this need user to select. <img alt="image" width="534" src="https://user-images.githubusercontent.com/12708910/256400363-6390ced0-c087-414e-a0e5-dd425f1d17af.png"> Second we split current api doc into two. One is `/v1,` another is `/v2`
> 
> I would suggest grouping them in separate `endpoint`, the `version` is not a configurable field for users
> 
> By putting `version` in the `endpoint`, it can be set easily in the editor
> 
>  Screen.Recording.2023-07-27.at.10.30.50.mov

And along with API migration, apis in `v1` will all be replaced by apis in `v2`

**Comment by zmcNotafraid** [comment]
Doc has updated to readme.

**Comment by Keith-CY** [comment]
Preview of the API document: https://ckb-explorer.readme.io/reference/transaction

**Comment by Keith-CY** [comment]
Updated in the readme at https://github.com/nervosnetwork/ckb-explorer#api-documentation
