### ISSUE TITLE
CkbTransactionSerializer cache problem

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/ckb-explorer-public-issues#364]
The current CkbTransactionSerializer has a large cache of display input and output, and uses N+1 queries, resulting in slow queries and address transactions not being queried correctly.

**Comment by rabbitz** [comment]
##### Reason:

There are too many nested queries in the attributes `display_inputs` and `display_outs` of ckb_transaction, and there are a large number of subqueries, but indexes are basically used. Some ckb_transactions have a lot of cells. For example, https://pudge.explorer.nervos.org/transaction/0x9810a6e97a5858192993d4aad28a974646868d84597e5ae5b2ca41f09712bbd1 and the number of `display_outputs` is 202. A large number of similar cells causes the query time to be too long.

##### Possible Solution:

1. Transactions list, a transaction can display up to 10 cells, so the interface can return less?

2. The transaction show page is now a scrolling display. Can I change a separate interface to obtain cells?


@Keith-CY @zmcNotafraid Any suggestions?

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1496

**Comment by zhangyouxin** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/177
