### ISSUE TITLE
Halving countdown on the homepage

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#365]
It was expected to be displayed by the animation of banner.

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/ffee60e0-1006-4f1c-a8a4-aae9adaaaffe)

But it may be blocked by the performance issue mentioned at https://github.com/Magickbase/ckb-explorer-public-issues/issues/218

A fallback is required.

---

Halving info can be found at https://docs.nervos.org/docs/reference/halving/ 

The first halving is expected on 19th Nov. 2023, at epoch 8,760.

Halving sites
- https://nervoshalving.com/
- https://ckbdapps.com/halving

**Comment by Keith-CY** [comment]
Any update on this?

**Comment by Danie0918** [comment]
> Any update on this?

It's not started yet, I'll take it over, expect it to be done next week.

**Comment by Danie0918** [comment]
PRD：[https://u5lfe1.axshare.com](https://u5lfe1.axshare.com) @Keith-CY @Sven-TBD

**Comment by Keith-CY** [comment]
> PRD：[u5lfe1.axshare.com](https://u5lfe1.axshare.com) @Keith-CY @Sven-TBD

I guess the countdown page is permanent and for next halving events, so it keeps updating the next countdown.

There's a progress bar on that page
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/aa7822fa-c755-4d19-a4a4-578b4d33aaac)
And it turns into `activated` once halving happens. At this moment, the countdown for the next halving starts, how long should `activated` be there for the past halving events.

**Comment by Danie0918** [comment]
> > PRD：[u5lfe1.axshare.com](https://u5lfe1.axshare.com) @Keith-CY @Sven-TBD
> 
> I guess the countdown page is permanent and for next halving events, so it keeps updating the next countdown.
> 
> There's a progress bar on that page ![image](https://user-images.githubusercontent.com/7271329/258017917-aa7822fa-c755-4d19-a4a4-578b4d33aaac.png) And it turns into `activated` once halving happens. At this moment, the countdown for the next halving starts, how long should `activated` be there for the past halving events.

Because the halving event occurs once every 4 years, we usually inform users about the banner and feature page a few months before the halving event. As for the fixed countdown to the halving, we can put it on the chart page and add a countdown to show it.

**Comment by Sven-TBD** [comment]
> PRD：https://u5lfe1.axshare.com @Keith-CY @Sven-TBD

"Epoch" is translated into different Chinese words.

<img width="714" alt="纪元" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/6c3810e2-e71e-4e8f-a86a-0848ee7bb719">

**Comment by Keith-CY** [comment]
> > PRD：[u5lfe1.axshare.com](https://u5lfe1.axshare.com) @Keith-CY @Sven-TBD
> 
> "Epoch" is translated into different Chinese words. I think we can keep using "Epoch" or unify with "纪元".
> 
> <img alt="纪元" width="714" src="https://user-images.githubusercontent.com/85155313/258027986-6c3810e2-e71e-4e8f-a86a-0848ee7bb719.png">

The term can be left for a precise expression
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/adaee86b-46d5-4a07-a087-ce9b9fb417aa)

**Comment by Keith-CY** [comment]
> > > > > PRD：[u5lfe1.axshare.com](https://u5lfe1.axshare.com) @Keith-CY @Sven-TBD
> > > > 
> > > > 
> > > > I guess the countdown page is permanent and for next halving events, so it keeps updating the next countdown.
> > > > There's a progress bar on that page ![image](https://user-images.githubusercontent.com/7271329/258017917-aa7822fa-c755-4d19-a4a4-578b4d33aaac.png) And it turns into `activated` once halving happens. At this moment, the countdown for the next halving starts, how long should `activated` be there for the past halving events.
> > > 
> > > 
> > > Because the halving event occurs once every 4 years, we usually inform users about the banner and feature page a few months before the halving event. As for the fixed countdown to the halving, we can put it on the chart page and add a countdown to show it.
> > 
> > 
> > The point may be misunderstood.
> > Say the 1st halving happens on block 1000, so the progress should be 100%, and `halving activated` appears when the block number reaches 1000.
> > After then, the block number goes to 1001, and the 2nd halving cycle starts. Should `halving activated` still be there?
> 
> Here it is specifically meant to be the first halving.

What should it be when the first halving finishes and the second halving cycle starts

**Comment by Danie0918** [comment]
> The point may be misunderstood.
> Say the 1st halving happens on block 1000, so the progress should be 100%, and `halving activated` appears when the block number reaches 1000.
> After then, the block number goes to 1001, and the 2nd halving cycle starts. Should `halving activated` still be there?

It's still 100%, and I have a note in the text that it's the first time it's been halved. I will consider removing the percentage progress bar if there still may be a misunderstanding.

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/122437870/76426fa0-7174-4a49-bc4c-df690b353d70)

**Comment by Keith-CY** [comment]
> > The point may be misunderstood.
> > Say the 1st halving happens on block 1000, so the progress should be 100%, and `halving activated` appears when the block number reaches 1000.
> > After then, the block number goes to 1001, and the 2nd halving cycle starts. Should `halving activated` still be there?
> 
> It's still 100%, and I have a note in the text that it's the first time it's been halved. I will consider removing the percentage progress bar if there still may be a misunderstanding.
> 
> ![image](https://user-images.githubusercontent.com/122437870/258050925-76426fa0-7174-4a49-bc4c-df690b353d70.png)

So when the second halving cycle starts, the progress is still 100% and `first halving activated` is still displayed because both of them are only for the first halving event?

When will the progress be reset for the second halving cycle

**Comment by Danie0918** [comment]
> > > The point may be misunderstood.
> > > Say the 1st halving happens on block 1000, so the progress should be 100%, and `halving activated` appears when the block number reaches 1000.
> > > After then, the block number goes to 1001, and the 2nd halving cycle starts. Should `halving activated` still be there?
> > 
> > 
> > It's still 100%, and I have a note in the text that it's the first time it's been halved. I will consider removing the percentage progress bar if there still may be a misunderstanding.
> > ![image](https://user-images.githubusercontent.com/122437870/258050925-76426fa0-7174-4a49-bc4c-df690b353d70.png)
> 
> So when the second halving cycle starts, the progress is still 100% and `first halving activated` is still displayed because both of them are only for the first halving event?
> 
> When will the progress be reset for the second halving cycle

It's currently designed as a short-term event page, and if it needs to be permanent, I'll consider compatibility with subsequent half-off events.

**Comment by Keith-CY** [comment]
> > > > The point may be misunderstood.
> > > > Say the 1st halving happens on block 1000, so the progress should be 100%, and `halving activated` appears when the block number reaches 1000.
> > > > After then, the block number goes to 1001, and the 2nd halving cycle starts. Should `halving activated` still be there?
> > > 
> > > 
> > > It's still 100%, and I have a note in the text that it's the first time it's been halved. I will consider removing the percentage progress bar if there still may be a misunderstanding.
> > > ![image](https://user-images.githubusercontent.com/122437870/258050925-76426fa0-7174-4a49-bc4c-df690b353d70.png)
> > 
> > 
> > So when the second halving cycle starts, the progress is still 100% and `first halving activated` is still displayed because both of them are only for the first halving event?
> > When will the progress be reset for the second halving cycle
> 
> It's currently designed as a short-term event page, and if it needs to be permanent, I'll consider compatibility with subsequent half-off events.

We can deliver the short-term page first, and enhance it before the second one starts

**Comment by Danie0918** [comment]
> PRD：https://u5lfe1.axshare.com @Keith-CY @Sven-TBD

I updated the PRD and added a new permanent page type.

**Comment by Keith-CY** [comment]
> > PRD：[u5lfe1.axshare.com](https://u5lfe1.axshare.com) @Keith-CY @Sven-TBD
> 
> I updated the PRD and added a new permanent page type.

LGTM

**Comment by Danie0918** [comment]
> > > PRD：[u5lfe1.axshare.com](https://u5lfe1.axshare.com) @Keith-CY @Sven-TBD
> > 
> > 
> > I updated the PRD and added a new permanent page type.
> 
> LGTM

So can we start moving forward with the design by following the Permanent Page model?

**Comment by Keith-CY** [comment]
> > > > PRD：[u5lfe1.axshare.com](https://u5lfe1.axshare.com) @Keith-CY @Sven-TBD
> > > 
> > > 
> > > I updated the PRD and added a new permanent page type.
> > 
> > 
> > LGTM
> 
> So can we start moving forward with the design by following the Permanent Page model?

Sure, besides the functionality, an east egg effect could be considered to celebrate the halving.

**Comment by PainterPuppets** [comment]
pr: https://github.com/Magickbase/ckb-explorer-frontend/pull/101

**Comment by Keith-CY** [comment]
I slightly changed the text in banner, it was "Nervos CKB Layer 1 Halving", and was changed to "Nervos CKB First Halving" because "CKB" is the layer one of Nervos, so "Nervos CKB Layer 1" is  improper.
