### ISSUE TITLE
The export file interface is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#366]
When verifying in the export file pr, click the `Download` button, the interface prompts 500.
pr link  https://github.com/Magickbase/ckb-explorer-frontend/pull/9#issuecomment-1614162458
Validate url in pr:
https://ckb-explorer-cpmn4h6o6-magickbase.vercel.app/export-transactions?end-date=2023-06-30&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqtsm4z8rqkt060h3ugwyvfhvyc8qqsf5vsh59ey9&start-date=2023-06-29&type=address_transactions
<img width="1323" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/479d4fd8-9c03-4bc7-b9f0-0794057344cf">

**Comment by zhb666** [comment]
@FrederLu @Danie0918  @rabbitz  Testing revealed an issue with the current wallet address data, but when I switched to a different account, exporting was successful. It appears to be an error on the backend as the server is returning a 500 error.
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/18475950/554a6bd9-8d23-44b0-9583-8a9bd60f2e24)
<img width="774" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/18475950/273ec47f-59e9-4483-8809-d6c5da0b07b9">
https://ckb-explorer-cpmn4h6o6-magickbase.vercel.app/export-transactions?end-date=2023-07-02&id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpqepftenqdl2wnnq64pfvkwpzu6yjlqhuqq32jpkk&start-date=2023-07-01&type=address_transactions

**Comment by rabbitz** [comment]
#### Related PRs :

https://github.com/nervosnetwork/ckb-explorer/pull/1334

**Comment by FrederLu** [comment]
Verified.
