### ISSUE TITLE
Some addresses that have already bound to .bit names cannot be correctly queried on the explorer with the .bit name

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/ckb-explorer-public-issues#369]
The addresses bound to the following two .bit accounts cannot be displayed correctly on the explorer:
https://data.did.id/whitemind.bit
https://data.did.id/test.whitemind.bit

Example:

https://explorer.nervos.org/address/ckb1qjl58smqy32hnrq6vxjedcxe2fugvnz497h7yvwqvwel40uh4rltcwn7wuy06uhp5edwvnrfwd2wkjdqyy7h7gc7fz7

<img width="1920" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/9160743/0f4a648e-a71a-49fa-b11c-8a75915f4f87">

**Comment by zmcNotafraid** [comment]
We can only query your owner address or manager address
<img width="368" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/8219cc1c-889e-4992-87f5-1d777c321544">

**Comment by WhiteMinds** [comment]
I asked the das team and it turns out the alias should be set through https://app.did.id/alias instead of in https://data.did.id/.

Now it can resolve correctly.

<img width="1702" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/9160743/da6edaf5-3497-4f8a-b4b8-2b2f21b14468">

<img width="891" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/9160743/c02e186a-09e1-4b6c-820e-3cc0e1e78535">
