### ISSUE TITLE
Balance is not correct

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#37]
https://explorer.nervos.org/address/ckb1qpzuzykljldwecnuftaq9vjtzhmygqaal4z6ktsw3rylk23y09436q2q6uls60zkrl92uvcw40qrpkxed2ws4umdp3g3fzpktz34pju78wjsqqqqzqqqqqraqqqqp8gqqqqx6qqqqqgqqqqqxqqqqqr9qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqx5qqqqqsqqqqqvqqqqqrzqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq04v8fa

![image](https://user-images.githubusercontent.com/7271329/170425164-914c811e-aab6-44e9-98c2-03af1b51dcef.png)

Since there're several cases about incorrect balance, count of live cells, we may have to go through the corresponding code to reorg it.

**Comment by ShiningRay** [comment]
参考 https://github.com/Magickbase/ckb-explorer-public-issues/issues/30#issuecomment-1140949710

出错的地方应该是在一起的，都是 `addr_changes` 出错导致数据更新出错。

根据进一步的分析和讨论，判断有一定可能性是因为新旧版本地址的问题，导致数据更新出错，这点还要进一步确认。

**Comment by ShiningRay** [comment]
该地址已经修复。
我在数据库中查找了所有live cell count、balance为负的地址，对live cells进行了进行，订正了已有数据
