### ISSUE TITLE
Unique Addresses Use Curve Abnorma.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#370]
The `Unique Addresses Used` curve should be increasing in one direction, and now there are several places where the data fluctuates abnormally.
https://pudge.explorer.nervos.org/charts/address-count
<img width="1299" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e450396a-ce4b-40a5-8854-2b3524010462">

**Comment by zmcNotafraid** [comment]
Data have fixed.
