### ISSUE TITLE
Unexpected number and block range in export file.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#373]
https://ckb-explorer-owetxsuyq-magickbase.vercel.app/address/ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c&from_number=10000&to_number=10001`

[exported-txs-address_transactions-ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c-10000-10001.csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/12000536/exported-txs-address_transactions-ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c-10000-10001.csv)

<img width="1081" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/76650e81-e1fc-47db-bfb4-d72d42f5cfa4">

<img width="1110" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e4c4df81-4d09-49fa-afab-c6acdfc6c9f4">

1. The block information in the exported csv file is not as expected.
2. The export information does not match the quantity of the prompt "The earliest 5000 records in the selected range will be exported".

**Comment by rabbitz** [comment]
The api parameter is wrong, the time range parameter is `start_time` and `end_time`, the block range parameter is `start_number` and `end_number`

**Comment by zhangyouxin** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/17

**Comment by FrederLu** [comment]
> PR: [Magickbase/ckb-explorer-frontend#17](https://github.com/Magickbase/ckb-explorer-frontend/pull/17)

Request by date
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c&start_time=2023-07-23&end_time=2023-07-24`

Request by block number
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c&start_number=10061900&end_number=10062000`

The front-end request has been modified and the verification is passed.
