### ISSUE TITLE
Add API for Token information

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#374]
Currently, the browser provides a method for developers to upload Token Info via email to the developer community. However, this method is no longer sufficient to meet the needs of new frameworks like Kuai for SUDT development. Instead, an API for Token Info uploading should be introduced as a replacement.

### Current way

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/60c68695-471e-4c85-ae69-4d190f5d8291)

### Related part in Kuai 

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/6a8a8fcc-42df-40a7-9d11-82fac8ccbee6)

- [ ] Also a workflow are supposed be added to ensure the TokenInfo can only be modified to the Token creator.

**Comment by zmcNotafraid** [comment]
1. Is anyone can use this api to upload udt info? or only used by KUAI?
2. Upload info has limit or not? Such every day once ..
3. Uplaod info is updated immediately or needs admin to approve?

**Comment by Sven-TBD** [comment]
> 1. Is anyone can use this api to upload udt info? or only used by KUAI?

It's better to open it only for KUAI first. 

> 2. Upload info has limit or not? Such every day once ..

No limit.

> 3. Uplaod info is updated immediately or needs admin to approve?

No approve. 

cc @Keith-CY

**Comment by Keith-CY** [comment]
> It's better to open it only for KUAI first.

I doubt if it's feasible to only support for Kuai, because it's impossible to differentiate requests from projects built by kuai.

> No limit.

If the request is not limited by some rule, it will be used to attack the service. E.g., sending 100,000 requests in a minute

> No approve.

If the submission is not audited, it will be used to harm the service, e.g. update the `decimal` to make transfer amount 10x than it's, so the attacker can cheat others by claiming that he/she has sent 10x sudt.

**Comment by Keith-CY** [comment]
> I have added a workflow for verifying the creator's email. Please check this [link](https://vs0cjf.axshare.com/?g=14&id=yim3e9&p=tokenapiauditflow) @Keith-CY

A `Report` button can be placed next to the `verification code` if the creator is forestalled by the attacker.

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/bb72a5fe-5bdf-4ef2-bd21-a38c0b72da0d)

**Comment by zhangyouxin** [comment]
pr： https://github.com/Magickbase/ckb-explorer-frontend/pull/127

**Comment by Sven-TBD** [comment]
Report wording：https://vs0cjf.axshare.com/?id=ujekkc&p=_____token_api_email_report&g=1
NFT proposal : https://vs0cjf.axshare.com/?id=t9j7vc&p=%E8%A1%A5%E5%85%85%E6%8F%90%E8%AE%AE%EF%BC%9A%E4%B8%BAnft%E5%A2%9E%E5%8A%A0api%E6%8F%90%E4%BA%A4%E6%B8%A0%E9%81%93&g=1

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1555

**Comment by Keith-CY** [comment]
I found the UI design is slightly different from the PRD

In PRD, there is a dialog with options `submit token info` and `modify token info` for the next step, but the dialog is missing in the design.

Another question is about `Report` mentioned at https://github.com/Magickbase/ckb-explorer-public-issues/issues/374#issuecomment-1686688163 it's neither mentioned in the PRD nor the design.

Please check @Sven-TBD

Besides, I would suggest adding a button on the token detail page for users to submit a modification.

**Comment by Sven-TBD** [comment]
> I found the UI design is slightly different from the PRD
> 
> In PRD, there is a dialog with options `submit token info` and `modify token info` for the next step, but the dialog is missing in the design.
> 
> Another question is about `Report` mentioned at [#374 (comment)](https://github.com/Magickbase/ckb-explorer-public-issues/issues/374#issuecomment-1686688163) it's neither mentioned in the PRD nor the design.
> 
> Please check @Sven-TBD
> 
> Besides, I would suggest adding a button on the token detail page for users to submit a modification.

I guess this is because I made two version, the one with dialog is on the original version and is deleted after a meeting. And I put the report button on the original version which should be on the latest one. BTW, do we still need the dialog?  Based on the last meeting we had about the Token API things, the dialog should be deleted because the user could modify the Token Info only on the Token Information page.

The [PRD](https://vs0cjf.axshare.com/?id=2g7bmp&g=14&p=token_api_audit_flow__modified_) has been updated, and I put the report button here.
<img width="987" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/783c9408-3b9a-4026-a86a-6b3df84a1a1d">

**Comment by Keith-CY** [comment]
> > I found the UI design is slightly different from the PRD
> > In PRD, there is a dialog with options `submit token info` and `modify token info` for the next step, but the dialog is missing in the design.
> > Another question is about `Report` mentioned at [#374 (comment)](https://github.com/Magickbase/ckb-explorer-public-issues/issues/374#issuecomment-1686688163) it's neither mentioned in the PRD nor the design.
> > Please check @Sven-TBD
> > Besides, I would suggest adding a button on the token detail page for users to submit a modification.
> 
> I guess this is because I made two version, the one with dialog is on the original version and is deleted after a meeting. And I put the report button on the original version which should be on the latest one. BTW, do we still need the dialog? Based on the last meeting we had about the Token API things, the dialog should be deleted because the user could modify the Token Info only on the Token Information page.
> 
> The [PRD](https://vs0cjf.axshare.com/?id=2g7bmp&g=14&p=token_api_audit_flow__modified_) has been updated, and I put the report button here. <img alt="image" width="987" src="https://private-user-images.githubusercontent.com/85155313/298375058-783c9408-3b9a-4026-a86a-6b3df84a1a1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MzIyOTksIm5iZiI6MTcwNTgzMTk5OSwicGF0aCI6Ii84NTE1NTMxMy8yOTgzNzUwNTgtNzgzYzk0MDgtM2I5YS00MDI2LWE4NmEtNmIzZGY4NGExYTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDEwMTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZTYxNjA4MzZiMGI3Mzc2ZDVlYzkwZDg0MzdhNWU2NjAzMzM0MDBmMThjYTlmODM0YzFmOTY0M2ZhZjUxNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oPZIn-KW_VrJFdydLJNmavdcsWJ7Ti_9Ao9FBF9QI_E">

Got it, I think the dialog for choosing the next step is unnecessary if they can modify token info on the token detail page

**Comment by Keith-CY** [comment]
Before modifying the info of a token, its original info is expected to be filled in the dialog. So all fields of `token info` are expected to be returned in API as `https://testnet-api.explorer.nervos.org/api/v1/udts/0x5a2051e1289743e5878e8045e277500c3c105a4b60faa50c91054a32490ce24b`

Now `website` and `creator email` are missing in the response, need support for @zmcNotafraid

**Comment by Keith-CY** [comment]
> Before modifying the info of a token, its original info is expected to be filled in the form. So all fields of `token info` are expected to be returned in API as `https://testnet-api.explorer.nervos.org/api/v1/udts/0x5a2051e1289743e5878e8045e277500c3c105a4b60faa50c91054a32490ce24b`
> 
> Now `website` is missing in the response, need support for @zmcNotafraid
> 
> Besides, I found that `creator email` is not necessary in the `modify token info` dialog because it's private information, and getting veri-code doesn't require it to be on the page. @Sven-TBD

According to the discussion yesterday, I need 2 more fields returned in the SUDT info API
1. `website`, which is submitted when token info is updated
2. `creator email`, which is submitted when the token info is initialized, and the email address should be protected by concealing some chars
@zmcNotafraid

**Comment by zmcNotafraid** [comment]
returns `operator_website` and `email` in udt show api

> > Before modifying the info of a token, its original info is expected to be filled in the form. So all fields of `token info` are expected to be returned in API as `https://testnet-api.explorer.nervos.org/api/v1/udts/0x5a2051e1289743e5878e8045e277500c3c105a4b60faa50c91054a32490ce24b`
> > Now `website` is missing in the response, need support for @zmcNotafraid
> > Besides, I found that `creator email` is not necessary in the `modify token info` dialog because it's private information, and getting veri-code doesn't require it to be on the page. @Sven-TBD
> 
> According to the discussion yesterday, I need 2 more fields returned in the SUDT info API
> 
> 1. `website`, which is submitted when token info is updated
> 2. `creator email`, which is submitted when the token info is initialized, and the email address should be protected by concealing some chars, e.g. abc***ail.com
>    @zmcNotafraid

**Comment by Keith-CY** [comment]
I found a typo in PRD that `MagickBase` should be `MagiCKBase`, it's a combination of `Magi` and `CKBase`, it will be fixed in code directly, but please update the PRD and design later
cc @Sven-TBD @FrederLu 
![7 (1)](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/4bb45bac-c379-48b0-bc67-5553a2d56a91)

**Comment by zmcNotafraid** [comment]
Ignore total_amount update PR: https://github.com/nervosnetwork/ckb-explorer/pull/1615

**Comment by FrederLu** [comment]
https://pudge.explorer.nervos.org/sudt/0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/04cdf41e-bfc1-49f6-8b15-be6bffecdde7)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a63d2a2f-edc5-411c-b999-026332432ba1)

`usdt (deprecated)` prompts an exception when entering the verification code to submit. It is expected that the data was submitted according to `sUDT`.

**Comment by Keith-CY** [comment]
> [pudge.explorer.nervos.org/sudt/0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa](https://pudge.explorer.nervos.org/sudt/0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa)
> 
> ![Image](https://private-user-images.githubusercontent.com/25676576/302228489-04cdf41e-bfc1-49f6-8b15-be6bffecdde7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjU5MTUsIm5iZiI6MTcwNzEyNTYxNSwicGF0aCI6Ii8yNTY3NjU3Ni8zMDIyMjg0ODktMDRjZGY0MWUtYmZjMS00OWY2LThiMTUtYmU2YmZmZWNkZGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA5MzMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZTk1YWExNjcyMTFmNjYyNWYyMzExMTZiODhkMTk3YjA1MzI5ZTcyNDc5YWJjZDQyMTZiNTI1NTQxYTk0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J-7H3_GmpKJ9pKvNGX1JPFS_Y-E7cBE40wahOz1m2c0) ![Image](https://private-user-images.githubusercontent.com/25676576/302229414-a63d2a2f-edc5-411c-b999-026332432ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjU5MTUsIm5iZiI6MTcwNzEyNTYxNSwicGF0aCI6Ii8yNTY3NjU3Ni8zMDIyMjk0MTQtYTYzZDJhMmYtZWRjNS00MTFjLWI5OTktMDI2MzMyNDMyYmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDA5MzMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4M2FkZWE0ZWI3ZmIyYzc0MWQ0ZDg4NTMyYTIxODgyMWNhOWRkZTI2YWVkN2MxMjI4ZDExMDVmMzkxNDg5OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-kauU91U57kyrsRWCRfiTBZw2zBd9V1WXG68gCP3Q-4)
> 
> `usdt (deprecated)` prompts an exception when entering the verification code to submit. It is expected that the data was submitted according to `sUDT`.

It should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/249

The mismatched `typehash` comes from computation with default parameters, but it can be read from the url when it's the token detail page.

**Comment by FrederLu** [comment]
Verified.
