### ISSUE TITLE
Wrong time for exported data.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#375]
https://ckb-explorer-owetxsuyq-magickbase.vercel.app/address/ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c&start_date=2023-07-01&end_date=2023-07-02`

1. The start and end time of the exported data is not the expected time.
<img width="474" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/98cd27a7-fdde-47b8-a1c9-6aaa3d00e70e">

<img width="1035" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/34a5e6ab-48ae-4ebf-9789-a0bb4e9d0dae">
<img width="1041" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/15a3d103-8865-4f15-a027-89f7bd2f59da">

[exported-txs-address_transactions-ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c-2023-07-01-2023-07-02.csv](https://github.com/Magickbase/ckb-explorer-public-issues/files/12010253/exported-txs-address_transactions-ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c-2023-07-01-2023-07-02.csv)

2. If the above time range is correct, the exported data volume is less than 5000. At the same time, there is also a problem with the interception of the initial data time point at the bottom of the file (`2023-07-02 00:01:25 +0800` is the first data at the beginning, and the earliest 5000 data are obtained sequentially).
<img width="1060" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/aabc0d05-63e4-43be-ab05-4fedee9ba04a">

**Comment by rabbitz** [comment]
#### Related PRs:

https://github.com/nervosnetwork/ckb-explorer/pull/1334

#### Reason:

The data is filtered according to the block timestamp, but the format of the last column of the exported csv is wrong.

**Comment by FrederLu** [comment]
> #### Related PRs :
> [nervosnetwork/ckb-explorer#1334](https://github.com/nervosnetwork/ckb-explorer/pull/1334)
> 
> #### Reason :
> The data is filtered according to the block timestamp, but the format of the last column of the exported csv is wrong.

@rabbitz @Sven-TBD 
Confirm, is the exported CSV data the latest template? Now the export template has been adjusted.

**Comment by Sven-TBD** [comment]
Yes, this is the latest one.

**Comment by rabbitz** [comment]
> > #### Related PRs :
> > [nervosnetwork/ckb-explorer#1334](https://github.com/nervosnetwork/ckb-explorer/pull/1334)
> > #### Reason :
> > The data is filtered according to the block timestamp, but the format of the last column of the exported csv is wrong.
> 
> @rabbitz @Sven-TBD Confirm, is the exported CSV data the latest template? Now the export template has been adjusted. <img alt="image" width="957" src="https://user-images.githubusercontent.com/25676576/253151531-95c03f60-ed00-40f7-9031-75d44827e587.png">

Related PRs :

https://github.com/nervosnetwork/ckb-explorer/pull/1344

**Comment by FrederLu** [comment]
Now the staging environment cannot download data using the new link, and the interface always displays the pending status.
https://ckb-explorer-gatfx00fi-magickbase.vercel.app/export-transactions?end-date=2023-07-02&id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c&start-date=2023-07-01&type=address_transactions
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?start_date=2023-07-01&end_date=2023-07-02&id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c`


![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/84a244f1-f7c4-4b13-90a1-0a03b8b9cc67)

**Comment by zhangyouxin** [comment]
> @rabbitz @zhangyouxin Now the staging environment cannot download data using the new link, and the interface always displays the pending status. https://ckb-explorer-gatfx00fi-magickbase.vercel.app/export-transactions?end-date=2023-07-02&id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c&start-date=2023-07-01&type=address_transactions `Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?start_date=2023-07-01&end_date=2023-07-02&id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c`
> 
> ![Image](https://user-images.githubusercontent.com/25676576/260354528-84a244f1-f7c4-4b13-90a1-0a03b8b9cc67.png)

The called API is: 
https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?start_date=2023-07-01&end_date=2023-07-02&id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgpv638z4tfcywpkuluzsjee5qjg6j0w4kgqqdnc40c

please check on this @rabbitz

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1390
