### ISSUE TITLE
The address page is missing transaction records.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#376]
https://pudge.explorer.nervos.org/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqqxlcr9n725qq22ad2uwe7dxuw35rj5kxn5zlfvcw
<img width="1330" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/0f0940fb-b61b-4ec0-b82c-9d49688e78ac">

Address：`ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqqxlcr9n725qq22ad2uwe7dxuw35rj5kxn5zlfvcw`
There are no transaction(`0xc2c092867b776732c19efe3c95c0eedf0aa4a0180218c575a3dd80dfdf15a3bf`)records for the following address on the above address page.

https://pudge.explorer.nervos.org/transaction/0xc2c092867b776732c19efe3c95c0eedf0aa4a0180218c575a3dd80dfdf15a3bf
<img width="1334" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/68cf2518-8a35-4e83-83bf-cf836aa365a5">

**Comment by rabbitz** [comment]
#### Reason:

In the api, the address is queried through the https://github.com/nervosnetwork/ckb-explorer/blob/develop/app/models/address.rb#L127 `find_address!` method, which has a cache. Incorrect cached data causes associated transactions queries to fail.

#### Solve:

Delete error cache manually

**Comment by FrederLu** [comment]
> #### Reason:
> In the api, the address is queried through the https://github.com/nervosnetwork/ckb-explorer/blob/develop/app/models/address.rb#L127 `find_address!` method, which has a cache. Incorrect cached data causes associated transactions queries to fail.
> 
> #### Solve:
> Delete error cache manually

Data exceptions caused by caching are now handled manually. There were similar problems caused by caching before. Can we handle them uniformly to avoid caching problems later on?

**Comment by rabbitz** [comment]
The current reason may be that in order to repair the wrong data, the connection to the database was switched. This bug can be fixed in two ways:
1. Currently the cache does not expire, you can set an expiration time
2. Modify and optimize the query method of Address address in api

I'll see which way is better later, and then adjust.
