### ISSUE TITLE
The CSV export entry is missing at the bottom of the page.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#377]
Token Details Page
https://ckb-explorer-owetxsuyq-magickbase.vercel.app/sudt/0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa
<img width="1297" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/76ada0d8-76c9-4418-901c-930ed748c6e2">
<img width="849" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/0c71902f-0548-46a6-b74e-21fe56fa8bee">

**Comment by zhangyouxin** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/16
