### ISSUE TITLE
Export problem interface exception on NFC page.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#378]
https://ckb-explorer-owetxsuyq-magickbase.vercel.app/export-transactions?end-date=2023-07-04&id=0x052889c80db3cab7520ae95d699ecaa40dbfcb088c23fb7cd2ba89e66ad22df6&start-date=2023-06-29&type=nft
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/nft/download_csv?id=0x052889c80db3cab7520ae95d699ecaa40dbfcb088c23fb7cd2ba89e66ad22df6&start_date=2023-06-29&end_date=2023-07-04`
<img width="1329" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/9d92ec45-6881-478a-a195-606447fc4935">

`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/nft/download_csv?id=0x052889c80db3cab7520ae95d699ecaa40dbfcb088c23fb7cd2ba89e66ad22df6&from_number=9803628&to_number=9803645`
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/6d369574-30ba-407d-938e-1f0c37410f07">

Prompt 404 when exporting CSV in the page by time range.
https://ckb-explorer-owetxsuyq-magickbase.vercel.app/nft-collections/0x052889c80db3cab7520ae95d699ecaa40dbfcb088c23fb7cd2ba89e66ad22df6

**Comment by rabbitz** [comment]
The endpoint is `https://ckb-explorer-api.staging.layerview.io/api/v2/nft/transfers/download_csv?collection_id=0x052889c80db3cab7520ae95d699ecaa40dbfcb088c23fb7cd2ba89e66ad22df6`
