### ISSUE TITLE
COTA sync errors

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#379]
1. Address `ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8685h4qdkdfup5c5tzkgctnk22es8xx7yux20ul` holds 3 COTA NFTs(https://ckb-nft-explorer.staging.token.city/holder/tokens/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8685h4qdkdfup5c5tzkgctnk22es8xx7yux20ul)
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/98bd8627-475a-4d60-b332-2ad978379243)
But none of is displayed on CKB Explorer(https://pudge.explorer.nervos.org/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8685h4qdkdfup5c5tzkgctnk22es8xx7yux20ul)

2. `一卡通 AIGC` has released several items but only 2 were detected on CKB Explorer
https://pudge.explorer.nervos.org/nft-collections/18360?tab=inventory
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/095ec4ea-cd58-4265-976a-30c693156f29)

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/ee03d35e-715a-4780-81ee-d142f2241e8d)
https://ckb-nft-explorer.staging.token.city/nft/3f31c553-8ac7-42d5-a28c-7cbd6840d456/78

**Comment by zmcNotafraid** [comment]
Our testnet's cota node  have some problem, can't be used any more.So we need to switch to public node.

**Comment by rabbitz** [comment]
The testnet ckb-explorer-worker database configuration connection error caused partial data synchronization to stop

**Comment by rabbitz** [comment]
Cota worker has now synced block `9797533` to the latest. So the `一卡通 AIGC` nft items have been fully synchronized.

--- 

But the address `ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8685h4qdkdfup5c5tzkgctnk22es8xx7yux20ul` has a new Cota nft, and it is found that it has not been synchronized. After checking the cota aggregator interface returns an error

https://ckb-nft-explorer.staging.token.city/holder/tokens/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8685h4qdkdfup5c5tzkgctnk22es8xx7yux20ul

<img width="1101" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/990650/011f67fb-1f06-4e37-a052-d18b81b8dd2c">


https://ckb-nft-explorer.staging.token.city/transaction/b7aa95ce-a779-4469-9031-71480ad9e99a

<img width="1245" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/990650/c2afff0a-0909-422d-84db-adab71b04bce">

#### Request transactions

```bash
echo '{
    "id":2,
    "jsonrpc":"2.0",
    "method":"get_transactions_by_block_number",
    "params":{
        "block_number": "9998568"
    }
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
https://cota.nervina.dev/aggregator
```

#### Response

```json
{
  "jsonrpc": "2.0",
  "result": {
    "block_number": 10005465,
    "transactions": [
      {
        "block_number": 9998568,
        "cota_id": "0x8810e6f59832465af03a2aaf0f52402e139b9951",
        "from": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfpgx54dw8snpk370h204q8qyzdqkdmjtq048nku",
        "to": "ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8685h4qdkdfup5c5tzkgctnk22es8xx7yux20ul",
        "token_index": "0x00000003",
        "tx_hash": "0xa656fb3cfb3a1e0a00e12403400d30af2552f78c4d8b63bb30c39123e0c0e0c1",
        "tx_type": "mint"
      },
      {
        "block_number": 9998568,
        "cota_id": "0x8810e6f59832465af03a2aaf0f52402e139b9951",
        "from": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfpgx54dw8snpk370h204q8qyzdqkdmjtq048nku",
        "to": "ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8tw4n493wrfsqyeu9hhm2xkpe3ch5tdzc4fw5p4",
        "token_index": "0x00000004",
        "tx_hash": "0xa656fb3cfb3a1e0a00e12403400d30af2552f78c4d8b63bb30c39123e0c0e0c1",
        "tx_type": "mint"
      },
      {
        "block_number": 9998568,
        "cota_id": "0x8810e6f59832465af03a2aaf0f52402e139b9951",
        "from": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfpgx54dw8snpk370h204q8qyzdqkdmjtq048nku",
        "to": "ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8tw4n493wrfsqyeu9hhm2xkpe3ch5tdzc4fw5p4",
        "token_index": "0x00000005",
        "tx_hash": "0xa656fb3cfb3a1e0a00e12403400d30af2552f78c4d8b63bb30c39123e0c0e0c1",
        "tx_type": "mint"
      },
      {
        "block_number": 9998568,
        "cota_id": "0x8810e6f59832465af03a2aaf0f52402e139b9951",
        "from": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfpgx54dw8snpk370h204q8qyzdqkdmjtq048nku",
        "to": "ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8tw4n493wrfsqyeu9hhm2xkpe3ch5tdzc4fw5p4",
        "token_index": "0x00000006",
        "tx_hash": "0xa656fb3cfb3a1e0a00e12403400d30af2552f78c4d8b63bb30c39123e0c0e0c1",
        "tx_type": "mint"
      },
      {
        "block_number": 9998568,
        "cota_id": "0x8810e6f59832465af03a2aaf0f52402e139b9951",
        "from": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfpgx54dw8snpk370h204q8qyzdqkdmjtq048nku",
        "to": "ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq8tw4n493wrfsqyeu9hhm2xkpe3ch5tdzc4fw5p4",
        "token_index": "0x00000007",
        "tx_hash": "0xa656fb3cfb3a1e0a00e12403400d30af2552f78c4d8b63bb30c39123e0c0e0c1",
        "tx_type": "mint"
      }
    ]
  },
  "id": 2
}
```

#### Request define info

```bash
echo '{
    "id":2,
    "jsonrpc":"2.0",
    "method":"get_define_info",
    "params":{
        "cota_id":"0x8810e6f59832465af03a2aaf0f52402e139b9951"
    }
}' \
| tr -d '\n' \
| curl -H 'content-type: application/json' -d @- \
https://cota.nervina.dev/aggregator
```

#### Response

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32602,
    "message": "Database query error: Table 'cota_entries.token_class_audios' doesn't exist"
  },
  "id": 2
}
```

Collection creation failed because of this error.

**Comment by shaojunda** [comment]
> "Database query error: Table 'cota_entries.token_class_audios' doesn't exist"

you need to use the latest version of cota-syncer and cota-aggregator.

**Comment by shaojunda** [comment]
> The testnet ckb-explorer-worker database configuration connection error caused partial data synchronization to stop

The syncer version has been updated. Please try again.

**Comment by rabbitz** [comment]
The interface is OK, synced from block 9797533 to latest
