### ISSUE TITLE
Change the KB, MB, and GB units in the chart to the more familiar K, M, and B.

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/ckb-explorer-public-issues#381]
[Confusion from users to be optimized](https://github.com/nervosnetwork/ckb-explorer-frontend/issues/1289#issue-1813377354)

Currently we have KB, MB, GB units in our charts, which are not easy for users to understand, so we suggest replacing them with K, M, G.

**Comment by Danie0918** [comment]
There are 3 charts to adjust here, Balance Ranking, Total Deposit, and Daily Deposit.
[[URL]](https://explorer.nervos.org/charts)

[Balance Ranking]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/122437870/4b0549a2-af55-44ce-83d8-65b66a3839f9)

[Nervos DAO]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/122437870/aedc2e8f-2ebc-4bac-b813-581a92945bcb)

**Comment by yixyxiu** [comment]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/87553548/50646486-3eb9-4013-8a59-b41f01251f43)
 
FYI: **These 2 charts also need to be adjusted.**

**Comment by PainterPuppets** [comment]
> ![image](https://user-images.githubusercontent.com/87553548/256419622-50646486-3eb9-4013-8a59-b41f01251f43.png)
> 
> FYI: **These 2 charts also need to be adjusted.**

This seems to be already displayed as K/M/G, what should it be adjusted to?

**Comment by Danie0918** [comment]
> > ![image](https://user-images.githubusercontent.com/87553548/256419622-50646486-3eb9-4013-8a59-b41f01251f43.png)
> > FYI: **These 2 charts also need to be adjusted.**
> 
> This seems to be already displayed as K/M/G, what should it be adjusted to?

Also included here are click-to-zoom charts, with the charts marked in red clicking to zoom in to see KB/MB/GB.

**Comment by PainterPuppets** [comment]
> > > ![image](https://user-images.githubusercontent.com/87553548/256419622-50646486-3eb9-4013-8a59-b41f01251f43.png)
> > > FYI: **These 2 charts also need to be adjusted.**
> > 
> > 
> > This seems to be already displayed as K/M/G, what should it be adjusted to?
> 
> Also included here are click-to-zoom charts, with the charts marked in red clicking to zoom in to see KB/MB/GB.

<img width="1068" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/22258327/bf99466a-699e-47db-93d9-9fd26cd4e631">

I don't seem to see KB/MG/GB when I zoom in either, maybe I'm not looking in the right place, can you help with a screenshot or link?

**Comment by Danie0918** [comment]
> I don't seem to see KB/MG/GB when I zoom in either, maybe I'm not looking in the right place, can you help with a screenshot or link?

It's already G here, any other adjustments  needed? @yixyxiu

**Comment by yixyxiu** [comment]
> > I don't seem to see KB/MG/GB when I zoom in either, maybe I'm not looking in the right place, can you help with a screenshot or link?
> 
> It's already G here, any other adjustments needed? @yixyxiu

**G -> B, GB->B**。When the value reaches 1 billion, both Binance and CoinMarketCap (CMC) display it as "B." If we define 1G as 1 billion, displaying "B" as the unit is recommended. **Additionally, for the adjustment of units, if previously 1MB = 1024 K = 1024 * 1024 CKByte, the adjusted unit should be 1M = 1000 K = 1000 * 1000 CKB。**

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/87553548/6a6b1403-3294-4d40-b13b-fd6dee113c69)

@Danie0918

**Comment by PainterPuppets** [comment]
Got it. Already changed the code.
