### ISSUE TITLE
Pending transactions on mainnet are lost

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#382]
https://explorer.nervos.org/transaction/list?tab=pending
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/6e99f7a3-b955-4730-b29c-04875cf2fd45)
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/03f0c90d-4ed6-452b-88bf-2126e36c87b9)

**Comment by rabbitz** [comment]
The reason may be that the mainnet code needs to be updated, pending transactions are updated in poolsyncer.

**Comment by zmcNotafraid** [comment]
<img width="1474" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/c4b8f349-aa00-4325-a22d-d89b816a2116">

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1348
