### ISSUE TITLE
Support searching token by name, including sudt and nft

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#383]
This feature request comes from the community that want to find a specific token by name easily.

The entry could be in the search field 
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/ef895679-83d0-45d1-8b5a-a18f68899879)

But it's slightly different from other keywords like `block`, `transaction hash` because they match 1 record at most, while `token name` may hit several records.

So the UX may be different when it's recognized to search a token.

The simplest solution is to pop up a list of hit tokens as
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/58d101c1-ed6d-4430-92bf-08310d50cea8)

Any idea from @Danie0918 @Sven-TBD

**Comment by Sven-TBD** [comment]
I think a pop-up list is suitable in this case, we could promote with this.

**Comment by Danie0918** [comment]
Based on the current interactions, pop up a list is one way to do this, although dynamically making a selection for the user would be an easy scenario to misuse. We could consider adding a search card for related names on the token page, similar to the wikipedia synonyms.

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/122437870/1a78e950-e8fe-4458-9b26-2cb62612f591)

**Comment by Danie0918** [comment]
> > Based on the current interactions, pop up a list is one way to do this, although dynamically making a selection for the user would be an easy scenario to misuse. We could consider adding a search card for related names on the token page, similar to the wikipedia synonyms.
> > ![image](https://user-images.githubusercontent.com/122437870/260382403-1a78e950-e8fe-4458-9b26-2cb62612f591.png)
> 
> Could you post a screenshot of Wikipedia synonyms for us to have a peek at

Similar to Categories, we can list other related token names.

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/122437870/33fa693b-1356-429e-89d2-28fdd643f705)

**Comment by Keith-CY** [comment]
> > > Based on the current interactions, pop up a list is one way to do this, although dynamically making a selection for the user would be an easy scenario to misuse. We could consider adding a search card for related names on the token page, similar to the wikipedia synonyms.
> > > ![image](https://user-images.githubusercontent.com/122437870/260382403-1a78e950-e8fe-4458-9b26-2cb62612f591.png)
> > 
> > 
> > Could you post a screenshot of Wikipedia synonyms for us to have a peek at
> 
> Similar to Categories, we can list other related token names.
> 
> ![image](https://user-images.githubusercontent.com/122437870/261227383-33fa693b-1356-429e-89d2-28fdd643f705.png)

Got the interaction, but how to define `related token names`, based on fuzzy search?

**Comment by Danie0918** [comment]
> Got the interaction, but how to define `related token names`, based on fuzzy search?

Initially, we can recommend based on the relevant pairs of names, and subsequently we can add token tags and categories to match.

**Comment by Keith-CY** [comment]
How is it going？

**Comment by Sven-TBD** [comment]
I will promote this issue and distribute the work before next Monday.

**Comment by Sven-TBD** [comment]
Add some notes for searching by name.
https://vs0cjf.axshare.com/?id=1hl6lb&p=_383_support_searching_token_by_name__including_su&g=1
@Keith-CY @Danie0918

**Comment by zmcNotafraid** [comment]
### API
`GET /v1/udt_queries?q=xxxx`
```
response: 
{
  data: [
    {
      full_name: "Nervos Token",
      symbol: "CKB",
      type_hash: xxxx,
      icon_file: xxxx
    },
   {
      full_name: "Nervos New Token",
      symbol: "NCKB",
      type_hash: xxxx,
      icon_file: xxxx
   }
  ]
}
```
If no udt match, returns
```
{
  data: []
}
```

**Comment by WhiteMinds** [comment]
It doesn't seem very convenient.

Should we consider letting the frontend decide which API to use based on the format of the input keyword?

For example, pure numbers would use searchBlock, less than a certain length would search for token name, and other cases would be hash (or strictly judge the hash format).

**Comment by zhangyouxin** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/131

**Comment by Sven-TBD** [comment]
@WhiteMinds How's it going?  https://github.com/Magickbase/ckb-explorer-frontend/pull/131

A new feature will be added to it this week. #210

**Comment by Sven-TBD** [comment]
It seems there is still a bug while display the tag "by name"

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/30c76fda-577e-472b-9600-bdd55d959777)

**Comment by Sven-TBD** [comment]
@Kirl70 @WhiteMinds  And also a loading status should be added to .

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/6b26b73d-777c-4055-955c-9a0f094b8a2a)

And the rounded corners here should be handled better.

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/22616aff-53d7-457b-8cc9-345ce462a8e6)

**Comment by Kirl70** [comment]
> @Kirl70 @zhangyouxin And also a loading status should be added to .
> 
> ![Image](https://private-user-images.githubusercontent.com/85155313/286501617-6b26b73d-777c-4055-955c-9a0f094b8a2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDE0MzksIm5iZiI6MTcwMTI0MTEzOSwicGF0aCI6Ii84NTE1NTMxMy8yODY1MDE2MTctNmIyNmI3M2QtNzc3Yy00MDU1LTk1NWMtOWEwZjA5NGI4YTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA2NTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMDM4NGZiM2MwZmE1YzlmZTRiNmY4NWU0Yjk4OGM4YzZmMzI3NTM0MDE4ZDFmZjMwZmYyOGMyNzljYzFkYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1SFCMw_n1ljk7IyLNnWq4IfbnVBqnImPAfAM18R0oM4)
> 
> And the rounded corners here should be handled better.
> 
> ![Image](https://private-user-images.githubusercontent.com/85155313/286501705-22616aff-53d7-457b-8cc9-345ce462a8e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDE0MzksIm5iZiI6MTcwMTI0MTEzOSwicGF0aCI6Ii84NTE1NTMxMy8yODY1MDE3MDUtMjI2MTZhZmYtNTNkNy00NTdiLThjYzktMzQ1Y2U0NjJhOGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA2NTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MTU4YzQ0MDMwOTU2YTM4ZDE3YmFlNDZhMTE5MmNiYmFjY2E5MDBjYTMxOTFlZDQwNmMzY2I5YmRmOWIxZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eWEmuJBZ2zTzsN7IQ_0_Uw69UV5xC_DLKkDpNAFRl6Q)

Loading status:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=29729%3A17995&mode=design&t=Ac3kRdWmVpbbpmls-1
<img width="450" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/b1549795-e667-4048-9777-9b388c1d7e9e">

The effect needs to be consistent with the current online version.

https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/bea5e929-36ab-4f0f-935e-ed3bea56c933
