### ISSUE TITLE
The blockno of the exported data is wrong.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#384]
https://ckb-explorer-l6boamisl-magickbase.vercel.app/export-transactions?from-height=10099000&tab=height&to-height=10104000&type=blocks
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/blocks/download_csv?start_number=10099000&end_number=10104000`

The first request to use the parameter `start_number=10099001&end_number=10104000` to export the CSV data range is normal, and the second request to use `start_number=10099000&end_number=10104000` to export the data is the same as the first time. Is there a cache problem in the backend?
Blockno is not expected data.

Change a set of data:
https://ckb-explorer-l6boamisl-magickbase.vercel.app/export-transactions?from-height=10099002&tab=height&to-height=10104002&type=blocks
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/blocks/download_csv?start_number=10099002&end_number=10104002`
<img width="1100" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/f41b5912-0d69-46c0-b4a8-fae0236011b5">
<img width="1106" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/af5f4ad2-0e97-4eb6-8080-44254cee2654">

**Comment by rabbitz** [comment]
Related PRs: https://github.com/nervosnetwork/ckb-explorer/pull/1367

**Comment by FrederLu** [comment]
Verified.
