### ISSUE TITLE
The timing of exporting data is not as expected.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#385]
https://ckb-explorer-l6boamisl-magickbase.vercel.app/export-transactions?end-date=2023-07-26&start-date=2023-07-25&tab=date&type=blocks
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/blocks/download_csv?start_time=2023-07-25&end_time=2023-07-26`

Exporting data by time range, the data time does not meet the expected range.

<img width="1076" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/76733f22-bed8-4604-beb6-4afccc781204">
<img width="1085" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/46974963-e8bf-4ce1-aa6c-2781f54f1f22">

**Comment by rabbitz** [comment]
https://github.com/Magickbase/ckb-explorer-public-issues/issues/378#issuecomment-1641303907

download csv params should be `state_date`, `end_date`, `start_number` and `end_number`

**Comment by zhangyouxin** [comment]
pr: https://github.com/Magickbase/ckb-explorer-frontend/pull/20

**Comment by FrederLu** [comment]
Verified.
