### ISSUE TITLE
Upgrade SDK for the upcoming hardfork

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#386]
Ref: 
- Ruby SDK: https://github.com/nervosnetwork/ckb-sdk-ruby/pull/311
- Change of hardfork: https://github.com/nervosnetwork/ckb-sdk-ruby/issues/310

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1396
