### ISSUE TITLE
An exception occurred in the request export interface.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#387]
Address：Interface request no response
https://ckb-explorer-l6boamisl-magickbase.vercel.app/export-transactions?end-date=2023-07-26&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqw6vjzy9kahx3lyvlgap8dp8ewd8g80pcgcexzrj&start-date=2023-07-25&tab=date&type=address_transactions

`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqw6vjzy9kahx3lyvlgap8dp8ewd8g80pcgcexzrj&start_time=2023-07-25&end_time=2023-07-26`

---
NFT details page：status code 404 
https://ckb-explorer-l6boamisl-magickbase.vercel.app/nft-collections/0x3386c3bc03f7ecc1d1dbd8e9dd3e8a26ec7d45b65c8fa5833ffb4354532cb39c?tab=transfers&page=1
<img width="1234" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/f337ff0b-c6ea-4327-b06a-e05415525a27">

https://ckb-explorer-l6boamisl-magickbase.vercel.app/export-transactions?end-date=2023-06-30&id=0x3386c3bc03f7ecc1d1dbd8e9dd3e8a26ec7d45b65c8fa5833ffb4354532cb39c&start-date=2023-06-01&type=nft

`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/nft/download_csv?id=0x3386c3bc03f7ecc1d1dbd8e9dd3e8a26ec7d45b65c8fa5833ffb4354532cb39c&start_time=2023-06-01&end_time=2023-06-30`
<img width="1262" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/80e14ae6-10c8-49fe-a327-1ff2abf26f6e">

`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/nft/download_csv?id=0x3386c3bc03f7ecc1d1dbd8e9dd3e8a26ec7d45b65c8fa5833ffb4354532cb39c&start_number=9848283&end_number=9848386`
<img width="1266" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/bf7113be-1892-41b8-9a2c-f2ef8958e725">

**Comment by rabbitz** [comment]
nft transactions download url should be 

`/api/v2/nft/transfers/download_csv` the version is `v2`

**Comment by zhangyouxin** [comment]
pr: https://github.com/Magickbase/ckb-explorer-frontend/pull/21

**Comment by FrederLu** [comment]
>pr: https://github.com/Magickbase/ckb-explorer-frontend/pull/21

>>Address：Interface request no response
https://ckb-explorer-l6boamisl-magickbase.vercel.app/export-transactions?end-date=2023-07-26&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqw6vjzy9kahx3lyvlgap8dp8ewd8g80pcgcexzrj&start-date=2023-07-25&tab=date&type=address_transactions
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqw6vjzy9kahx3lyvlgap8dp8ewd8g80pcgcexzrj&start_time=2023-07-25&end_time=2023-07-26`

@zhangyouxin 
The current issue contains 2 problems, `NFT details page: status code 404` has been resolved, but the problem of `Address` still exists in pr.
https://ckb-explorer-i9spxijks-magickbase.vercel.app/export-transactions?end-date=2023-07-26&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqw6vjzy9kahx3lyvlgap8dp8ewd8g80pcgcexzrj&start-date=2023-07-25&tab=date&type=address_transactions
`Request URL: https://ckb-explorer-api.staging.layerview.io//api/v1/address_transactions/download_csv?start_date=2023-07-25&end_date=2023-07-26&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqw6vjzy9kahx3lyvlgap8dp8ewd8g80pcgcexzrj`
Please confirm again.

**Comment by zhangyouxin** [comment]
@FrederLu Please use the preview page here: https://github.com/Magickbase/ckb-explorer-frontend/pull/9#issuecomment-1566345198

didn't see the  `Address：Interface request no response` , but download request pending problem exists, this is tracked by another issue

**Comment by FrederLu** [comment]
> @FrederLu Please use the preview page here: [Magickbase/ckb-explorer-frontend#9 (comment)](https://github.com/Magickbase/ckb-explorer-frontend/pull/9#issuecomment-1566345198)
> 
> didn't see the `Address：Interface request no response` , but download request pending problem exists, this is tracked by another issue

By using the address in pr that you said, it seems that the situation is still the same, and the api has remained in the pending state.
Here's the address, take a look.
https://ckb-explorer-git-export-to-csv-magickbase.vercel.app/export-transactions?end-date=2023-07-26&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqw6vjzy9kahx3lyvlgap8dp8ewd8g80pcgcexzrj&start-date=2023-07-25&tab=date&type=address_transactions

**Comment by FrederLu** [comment]
Verifed.
