### ISSUE TITLE
The data exported from the address details page is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#388]
https://ckb-explorer-l6boamisl-magickbase.vercel.app/address/ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgptwhwz8gvgsu58afu2sp5j739scvse674qq7wgcfq?page=7
<img width="1275" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/fa02d0b8-17b0-4111-b9a3-da5799c20543">

Specific transaction details：
https://ckb-explorer-l6boamisl-magickbase.vercel.app/transaction/0xb35a9ae68b1403db78d14d756185bfe6c5945c2c7ed56c4f48baa5c8a47cbd0f
<img width="1269" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/957f5f03-6dc4-406a-a873-571b34fef2bb">

The actual data:
<img width="1324" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/fdbe62ea-7bd5-4373-802f-4da44ef6c70a">
Expected data:
<img width="1429" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/82be199c-428e-4212-82aa-8cb627259cfb">

1. There are 2 pieces of data in the export, one should be CKB and one should be sudt.
2. The Token name should be divided into CKB and unknown asset #62bc (the name depends on whether the user uploads sudt information)
3. The Balance change of CKB is: 0, Fee is 0.00000886
4. The token in and token out of `unknown asset #62bc` need to be parsed and displayed from the `data` of `cell info`, instead of using `Capacity: 400 CKB` to display directly, and the Fee is "/".

**Comment by rabbitz** [comment]
Related PRs: https://github.com/nervosnetwork/ckb-explorer/pull/1367

**Comment by FrederLu** [comment]
@zhangyouxin 
The exported CSV file has only one piece of data, and the interface returns more than one piece of data.
https://ckb-explorer-aikwmkafr-magickbase.vercel.app/export-transactions?from-height=10309000&id=ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgptwhwz8gvgsu58afu2sp5j739scvse674qq7wgcfq&tab=height&to-height=10309400&type=address_transactions


![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/69ec16b9-9fcb-4b28-8f5f-e837c83b541f)



![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e4c1a4b1-7e9e-49fc-86b1-ad0fff01a780)

**Comment by FrederLu** [comment]
@rabbitz 
When there are no two kinds of tokens in the transaction, the data needs to display the rate information.
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/264b9c9a-fa03-462a-83a6-b34da78a1b81)

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1390

**Comment by FrederLu** [comment]
Verified.
