### ISSUE TITLE
Statistical data of 2023/07/29 are lost

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#390]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/f3488a09-6dcf-4fee-a94d-5bd4b05beaf8)

1. difficulty
2. hash rate
3. uncle rate
4. transaction count
5. unique addresses used
6. cell count
7. total supply

**Comment by zmcNotafraid** [comment]
[137647f6-1777-4e19-b14c-24879d1ca1f9] NoMethodError (undefined method `truncate' for nil:NilClass
    object.circulation_ratio.truncate(4).to_s

**Comment by zmcNotafraid** [comment]
08/01's data was not generate successfully.We need to watch next days data.
