### ISSUE TITLE
Abnormal data on godwoken v1 assets deposit address

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#392]
Address: https://explorer.nervos.org/address/ckb1qqqqlpcx9gh7nw62dnz82gfw5ygpfwzdavewqd67u50xa39920sqjqgu5dwttldyh42zuuweffk47nqdy4wk6ma6w0zpeazay6f7txesw2ksqqqqzqqqqqpsqqqqqwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq82qqqqq2qqqqqxsqqqqrfqqqqqugqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp4qqqqqyqqqqqrqqqqqqcsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqh6ry0r

It shows 0 USDC.ckb|fb.eth
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/b8e65d37-0817-49e5-99a7-7ca9c2648209)

It was `1661438.89135` on 7/30, and unexpected to be 0 today. Please confirm.

**Comment by Keith-CY** [comment]
USDC.ckb|fb.eth on godwoken explorer at https://v1.gwscan.com/zh-CN/token/69?tab=holders

**Comment by Flouse** [comment]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/1297478/3b4357ec-3fc1-4085-bdd5-d85907f1148c)


There is an unspent USDC cell https://explorer.nervos.org/transaction/0x21bacd7221ea89586cae8dfaaf0bcd2b4e4738c1ffffc27014bff5fdde8dee9d, which seems to be not calculated in `godwoken_custodian_lock`.

**Comment by Keith-CY** [comment]
> ![image](https://user-images.githubusercontent.com/1297478/257389235-3b4357ec-3fc1-4085-bdd5-d85907f1148c.png)
> 
> There is an unspent `USDC.ckb | fb.eth` cell [explorer.nervos.org/transaction/0x21bacd7221ea89586cae8dfaaf0bcd2b4e4738c1ffffc27014bff5fdde8dee9d](https://explorer.nervos.org/transaction/0x21bacd7221ea89586cae8dfaaf0bcd2b4e4738c1ffffc27014bff5fdde8dee9d), which seems to be not calculated in `godwoken_custodian_lock`.

It's possibly caused by the `incorrectly handled pending outputs` too.

The cell above is

```
  {
          "id": "42235292",
          "capacity": "32700000000.0",
          "address_hash": "ckb1qqqqlpcx9gh7nw62dnz82gfw5ygpfwzdavewqd67u50xa39920sqjqgu5dwttldyh42zuuweffk47nqdy4wk6ma6w0zpeazay6f7txesw2ksqqqqzqqqqqpsqqqqqwqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq82qqqqq2qqqqqxsqqqqrfqqqqqugqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqp4qqqqqyqqqqqrqqqqqqcsqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqh6ry0r",
          "status": "pending",
          "consumed_tx_hash": "",
          "cell_type": "udt",
        },
```
It's marked `pending` for a long time

**Comment by Flouse** [comment]
## Transaction records of USDC.ckb|fb.eth
https://explorer.nervos.org/sudt/0x797bfd0b7b883bc9dba43678e285999507c6d0b971a2740c76623f70636f4080

**Comment by Flouse** [comment]
I think the problem has been fixed.
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/1297478/cf53a8b2-058b-48e8-b0d2-6bbec503b9f6)
