### ISSUE TITLE
Spore Cell support

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/ckb-explorer-public-issues#395]
https://github.com/Magickbase/neuron-public-issues/issues/252

**Comment by zmcNotafraid** [comment]
- [ ] input/output type
- [ ] address's udt list
- [ ] nft collection page list
- [ ] nft detail

**Comment by zmcNotafraid** [comment]
- Create cluster tx: [0xdd169db0980631ab796a49b3223cd1422425ea0964245ceaa0ca1e409ee6ce31](https://pudge.explorer.nervos.org/transaction/0xdd169db0980631ab796a49b3223cd1422425ea0964245ceaa0ca1e409ee6ce31)
- Create cell tx: 0x711aadb466e3452f3d1778e3379c8b28611be54cbca8748287bd9529f54de7f0

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1391

**Comment by Danie0918** [comment]
PRD:[https://10x1hg.axshare.com/#g=1&p=ckb_explorer](https://10x1hg.axshare.com/#g=1&p=ckb_explorer)

**Comment by zmcNotafraid** [comment]
1. cell_type added `spore_cluster` and `spore_cell` types
2. For token item, added `standard` and `cell_data` columns.So if standard is spore_cell, frontend needs parse cell data to get content_type and content
