### ISSUE TITLE
On the 'block list page', the range exported by block number is incorrect.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#402]
https://ckb-explorer-jgdu8v6m4-magickbase.vercel.app/export-transactions?from-height=10099000&tab=height&to-height=10104000&type=blocks
<img width="1169" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/5ff2b2e2-77e1-4600-8470-aea51b8c26f7">
<img width="1172" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/2f76d152-69aa-41b9-826d-162be04976b8">
<img width="786" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/85e3e58a-198b-415b-9ab8-b1abc495d8e0">
On the 'block list page', the data exported according to the block number range does not match the page prompt.
After checking the data, it is found that the blockno range for actually exporting CSV data is 10099000~10103999. According to the prompt on the page "This will export the earliest 5000 records in the selected range", the range allowed to be submitted should be [10099000, 10103999], if you follow the requirements of [10099000, 10104000], there should be an error. There is a prompt on the front end.

**Comment by zhangyouxin** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/9/commits/851bee5d0ad35d282012a09eeeb7dc3fe7ed588c

**Comment by FrederLu** [comment]
Verified.
