### ISSUE TITLE
CKB transaction information is missing.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#403]
Address
https://ckb-explorer-7ubvd8yyz-magickbase.vercel.app/address/ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vq2h6yqcajnqw725djufrduxf83vz70wenczt0ygc?page=3
Hash 0x9300c6de69b3401023d888bc0f1643c2e5f5140e22ee227b9640f3c192a3209c

https://ckb-explorer-7ubvd8yyz-magickbase.vercel.app/export-transactions?end-date=2020-12-31&id=ckt1qq6pngwqn6e9vlm92th84rk0l4jp2h8lurchjmnwv8kq3rt5psf4vq2h6yqcajnqw725djufrduxf83vz70wenczt0ygc&start-date=2020-10-01&type=address_transactions
<img width="1436" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/da65028e-2aa8-476b-872e-77dc6dd2fa62">

The initiator used ckb to pay the transaction fee during the token transaction process, but the change of ckb was not reflected in the exported CSV.

**Comment by rabbitz** [comment]
address_transactions only export the specified address associated transactions

**Comment by FrederLu** [comment]
>address_transactions only export the specified address associated transactions

Confirm that the exported data needs to be related to the current address.
Verified.
