### ISSUE TITLE
Changed data needs to be reflected in CSV.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#404]
Address
https://ckb-explorer-7ubvd8yyz-magickbase.vercel.app/address/ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgscpamwvj6q3mj257umtsy0pu6prtnupqfcn26a
Hash 0xd7a1262f14f5c3af00e5d86957a51332c4653b8c358939c881dc39c6f5868376
<img width="900" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/956c73fd-7d1a-4759-83ca-c81210a9b293">
<img width="945" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b9f2c7e6-ac7a-4d94-bfa3-e7c1f2757a5c">
<img width="878" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b529e285-3d65-4b72-86df-d0cf25450402">

Download Data
https://ckb-explorer-7ubvd8yyz-magickbase.vercel.app/export-transactions?end-date=2022-03-31&id=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgscpamwvj6q3mj257umtsy0pu6prtnupqfcn26a&start-date=2021-03-01&type=address_transactions

<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/adefdd8b-4d8d-4ace-b37a-b116d73c1340">

`Unknown asset #cbee` has data changes in the transaction, but it is not reflected in the CSV.

**Comment by rabbitz** [comment]
https://ckb-explorer-7ubvd8yyz-magickbase.vercel.app/transaction/0xd7a1262f14f5c3af00e5d86957a51332c4653b8c358939c881dc39c6f5868376

<img width="878" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/990650/f910d17e-09ff-4505-9450-2da97f45d879">

Because the decimal in udt info is empty, an exception is thrown when formatting the asset value. The default value is 0.

**Comment by Sven-TBD** [comment]
If the decimal is missing, we could just use the decoded raw data to calculate and display, and append a note to this kind of data in the csv like "300 (raw)"

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1405

**Comment by FrederLu** [comment]
>Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1405

The modification still needs to be verified on testnet, but this part of the code seems to be together with the spore function.

**Comment by FrederLu** [comment]
Verified.
