### ISSUE TITLE
The time in the CSV file is inconsistent with that on the page.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#406]
It is found that the "time stamp" on the page does not correspond to the "date (UTC)" in the CSV file, and the time difference needs to be dealt with uniformly.
It should be consistent with the time on the page, so as to avoid doubts after the user enters the time search.
<img width="1223" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/25ac203d-e4ae-4663-b9d2-27de0449d8e6">
<img width="1287" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/fad3647b-afa9-4dcb-9d40-c6177d2b3a3e">

---
https://ckb-explorer-7ubvd8yyz-magickbase.vercel.app/transaction/0x62145846e479ffa523b353bd0d5f8bcc68d6cbca6298cee331f6f2761789c4da
<img width="1326" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/88aa6899-d8c7-4fc8-bc8c-4db64a24556a">
<img width="1154" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/61faebef-7e25-4d5d-aa19-68aef3bce357">

**Comment by rabbitz** [comment]
The page shows the local time, and the exported time is the utc block timestamp, which doesn’t have to be the same.

https://vs0cjf.axshare.com/?id=9ug42i&p=_41原型-数据导出&g=1&sc=3

csv header is date utc

**Comment by FrederLu** [comment]
>The page shows the local time, and the exported time is the utc block timestamp, which doesn’t have to be the same.
>
>[https://vs0cjf.axshare.com/?id=9ug42i&p=_41原型-数据导出&g=1&sc=3](https://vs0cjf.axshare.com/?id=9ug42i&p=_41%E5%8E%9F%E5%9E%8B-%E6%95%B0%E6%8D%AE%E5%AF%BC%E5%87%BA&g=1&sc=3)
>
>csv header is date utc

Verified.
