### ISSUE TITLE
The data is abnormal when the transaction involves mint.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#408]
From the perspective of the transaction, this is a `mint` operation, there are problems with `method` and `token from`.
https://ckb-explorer-7ubvd8yyz-magickbase.vercel.app/sudt/0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa
<img width="1312" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/dba1b76b-53e1-4177-9b5d-536f8bfafa8f">
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/3d9b6fdf-e42e-4ab3-8be8-65218a55068e">

Download Data
https://ckb-explorer-7ubvd8yyz-magickbase.vercel.app/export-transactions?from-height=344500&id=0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa&tab=height&to-height=344600&type=udts

**Comment by rabbitz** [comment]
1. If the asset change is 0, then the method should be `PAYMENT RECEIVED` ?
2. The token from should be the address of the current asset change, because it is 0 here, so it is impossible to confirm where it came from?

@Sven-TBD @Danie0918

**Comment by Sven-TBD** [comment]
1. If the asset change is 0, then the method should be PAYMENT RECEIVED ?
Yes, 0 should be displayed as PAYMENT RECEIVE.
2. The token from should be the address of the current asset change, because it is 0 here, so it is impossible to confirm where it came from?
Yes. Current asset is OK, this is like a MINT function, though we didnt split PAYMENT RECEIVED into RECEIVE and MINT.

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1394

**Comment by FrederLu** [comment]
>Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1394

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a6faf363-d432-452e-979e-807d74bf3777)

The `Mint` method is now handled as `PAYMENT RECEIVED`.
Verified.

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1405
