### ISSUE TITLE
Address is lost on navigating to export-transaction page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#409]
Visit an address page and click the `CSV export` button at the bottom when the `overview` section  is loading
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/641a769e-7497-467c-a314-864002cb6d01)

The URL of the target page will be `https://pudge.explorer.nervos.org/export-transactions?type=address_transactions`, notice that `address` is lost, which leads to the failure of an API request

**Comment by zhangyouxin** [comment]
I didn't reproduce a scenario when `section` is loading and `transactions` section is succesfully loaded, can you provide a video to exemplify? and paste the address

**Comment by Keith-CY** [comment]
> I didn't reproduce a scenario when `section` is loading and `transactions` section is succesfully loaded, can you provide a video to exemplify? and paste the address


https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/e6a4c223-e823-44d0-8d63-cfdffbc7c8d2

**Comment by zhangyouxin** [comment]
will be resolved by: https://github.com/Magickbase/ckb-explorer-frontend/pull/51
