### ISSUE TITLE
export to csv

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#41]
PRD: https://o093j5.axshare.com/#id=9ug42i&p=_41%E5%8E%9F%E5%9E%8B-%E6%95%B0%E6%8D%AE%E5%AF%BC%E5%87%BA&g=1

**Comment by Kirl70** [comment]
Export button has been added to the corresponding list page：
<img width="1321" alt="2886c45381f7e4b6ce1372173f1005b5" src="https://user-images.githubusercontent.com/106060898/227825764-f5f8d94a-cf6b-4a66-a61b-cfe4718c190d.png">

SCV Download Page 8-2 —— 8-6 
PC: 
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=11995-34713&t=8AH6DCCVVtWxYVxw-11
<img width="1454" alt="26c88c77f3228f91d1587acc35312439" src="https://user-images.githubusercontent.com/106060898/227825858-c6569a3e-3eb9-46ba-89e2-fb3be8be0cc6.png">

Mobile:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=12019%3A36963&t=FHS9vkp4C7wHJqIJ-1
<img width="222" alt="9f871b06988a4f4bcfde07c8ec7e11e2" src="https://user-images.githubusercontent.com/106060898/227825916-3a6b0102-6e78-4bab-b2fe-721271463476.png">

**Comment by pygman** [comment]
Frontend PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1247

**Comment by WhiteMinds** [comment]
> Frontend PR: [nervosnetwork/ckb-explorer-frontend#1247](https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1247)

It has now been moved to https://github.com/Magickbase/ckb-explorer-frontend/pull/9
