### ISSUE TITLE
The sudt page lacks an export button when there is little data.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#413]
https://pudge.explorer.nervos.org/sudt/0xf0f17a8ab6a76b6024e860f6169839141af8848fe07b2b3eff44a5406b807d0e
https://pudge.explorer.nervos.org/sudt/0x1f1bf5dde941e0bc384defcd2c7f139f59082f735cdea7c2625f77c680f4644a
<img width="1307" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/1a53f6b3-c943-4523-9d8f-176be9519400">

**Comment by zhangyouxin** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/74
