### ISSUE TITLE
When there is a problem with the data in the transaction list.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#415]
There is a problem with the first 3 data in the reverse transaction list.
https://pudge.explorer.nervos.org/transaction/list?sort=capacity.desc
<img width="1307" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a46eca77-fb43-454a-a642-d774910c93c0">

**Comment by zmcNotafraid** [comment]
Query same tx from staging environment, the capacity is not 0. So this is a sync bug, needs fix.
<img width="444" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/3e42b3e9-dc66-4806-b2d5-d48ae7dba163">
