### ISSUE TITLE
node data synchronization failed, the balance of address is not rolled back

### ISSUE THREAD

**Issue by rabbitz** [Magickbase/ckb-explorer-public-issues#417]
# Reason
When synchronizing missing transactions, the address balance will be recalculated, but this problem has been solved.

# Related Pr
https://github.com/nervosnetwork/ckb-explorer/commit/436011ab3066037ddb23a190d02ca604b1285edb
https://github.com/nervosnetwork/ckb-explorer/commit/9c54fed2a15d4c15ead937d36e52275a73e1c5e9

**Comment by Sven-TBD** [comment]
@rabbitz Hi Nan, Could you please provide more detail or context about this issue and its impact?

**Comment by rabbitz** [comment]
#### Reason

When synchronizing missing transactions, the address balance will be recalculated, but this problem has been solved.

#### Related Pr

https://github.com/nervosnetwork/ckb-explorer/commit/436011ab3066037ddb23a190d02ca604b1285edb
https://github.com/nervosnetwork/ckb-explorer/commit/9c54fed2a15d4c15ead937d36e52275a73e1c5e9

@Sven-TBD
