### ISSUE TITLE
Some data cannot be searched.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#420]
I found that some data can be previewed but not searched.
https://explorer.nervos.org/sudt/0x73cb97e31030f26299f73d4afb38e4b8ab241adad11c8f1b8fd81727ea3b6b36?filter=ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvygddfu2tjlrzzcy520zsv892h53gy82g6hgxv7
<img width="1269" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e8f5c9ae-65d4-42ed-9edf-bc25cb675e3e">
<img width="1367" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/fb49c4c6-7c41-441c-ae47-e7c0d50d8efa">

https://pudge.explorer.nervos.org/sudt/0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa?filter=ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0pxawrxpmjk9rxs4x2r0wtc5funvdhfugy7glu0

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1425

**Comment by FrederLu** [comment]
Testnet verified.
