### ISSUE TITLE
Missing prompt text.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#421]
When the token page displays Chinese, the prompt copy of `交易` is missing in the search box.
https://pudge.explorer.nervos.org/sudt/0xe3be4fb98ec914886c6525abac97e1f8769c59492636a1d35955e9163ef46efa
<img width="1271" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/137ad2c1-d8e4-4f48-919b-9a70c499ec40">
<img width="1274" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/153293a4-5917-4ce5-bb3e-27fe5fff2549">

**Comment by Keith-CY** [comment]
Should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/94

**Comment by FrederLu** [comment]
Verified.
