### ISSUE TITLE
Explorer Faucet Claiming error

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#425]
### Issue Description
An address ,ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqqywd55cq3fps05tnwsdxrhk4egadqmffdulvrahc , reported that he can not claim from the CKB Faucet(https://faucet.nervos.org/).

Based on the faucet claim rules, any address could be able to claim 300,000 CKB in a month. 

After being checked by @zmcNotafraid , this happened due to a error was raised by front-end before the api return value.

### Related material from Discord

ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqqywd55cq3fps05tnwsdxrhk4egadqmffdulvrahc
这个地址在 faucet 领取测试代币被提示超出了30w，但是浏览器上它最近的交易是7月底的，麻烦 @zmcNotafraid 看下水龙头的数据

这里是这个问题，这个用户5月份领取了30w，所以他的balance 余额是30w。正常来说用户再领取一次会直接把他的余额清零，就可以领取的。但是 api 这时候返回他的remaing 是0，前端输入地址直接就报错了。这里建议是把这个错误去掉，而是等用户领取的时候根据后端返回的错误再展示这个错误。 

![Image](https://user-images.githubusercontent.com/85155313/266525253-5a963c0f-5099-4a92-a3d4-df6d09c2dc0a.png)

现在用户重置领取的逻辑是写在领取service的前置，而不是用worker 每月1号定期去清理的。

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-testnet-faucet-frontend/pull/13
