### ISSUE TITLE
Every CoTA Transaction seems to be marked with MINT in NFT Collection Page

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#427]
- Source: https://pudge.explorer.nervos.org/nft-collections/18388

Every CoTA Transaction seems to be marked with MINT in NFT Collection Page
![Image](https://user-images.githubusercontent.com/85155313/266888465-b6f3573a-b0ec-42d9-b673-409ce013b2e0.png)

However, it looks like a normal transaction.
![Image](https://user-images.githubusercontent.com/85155313/266888502-ac95da23-4b6e-43d8-8267-581255759dbb.png)

**Comment by zmcNotafraid** [comment]
When we fetch data from rpc, we can see that the type was `mint`.
<img width="981" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/132217e7-6a18-4774-8b06-7dcc9f0f3037">
