### ISSUE TITLE
The data under `Deployed Cells` needs to be filtered.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#431]
This displays the cell information of `Live`. The cell information of `Dead` state needs to be filtered and not displayed here.
https://explorer.nervos.org/script/0xd01f5152c267b7f33b9795140c2467742e8424e49ebe2331caec197f7281b60a/type/deployed_cells?page=1&size=10
<img width="1307" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/2c04d572-de32-4b50-83fb-f96141f9be5c">

Testnet
https://ckb-explorer-frontend-in-magickbase-repo-26zthunlq-magickbase.vercel.app/script/0x3e1eb7ed4809b2d60650be96a40abfbdafb3fb942b7b37ec7709e64e2cd0a783/type/deployed_cells?page=1&size=10
<img width="1285" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/65fb5c23-1d46-4f9c-991f-a0d64a771ab0">

**Comment by rabbitz** [comment]
related pr: https://github.com/nervosnetwork/ckb-explorer/pull/1456

**Comment by FrederLu** [comment]
> related pr: https://github.com/nervosnetwork/ckb-explorer/pull/1456 

 Verified.
