### ISSUE TITLE
Refactor: Use i18n through a react hook

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/ckb-explorer-public-issues#435]
Currently, i18n is not being used through a hook, but the page can still change normally after switching languages. This is because some code triggers a full page re-render periodically, which is not expected behavior and may be fixed in the future. Therefore, i18n still needs to be refactored to be based on a hook.

**Comment by zhangyouxin** [comment]
Will be resolved by: https://github.com/Magickbase/ckb-explorer-frontend/pull/116
