### ISSUE TITLE
Data in brackets is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#437]
There is data in the tab list on the script page, but 0 is displayed in the brackets.
https://pudge.explorer.nervos.org/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type?page=1&size=10
<img width="1266" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7d4d5bb1-4246-44b3-89d2-fd6169939748">
<img width="1263" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e057344e-5605-4055-bf5f-5549783d5bdb">
<img width="1288" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/ddc68f51-b7c5-43bf-8db4-dad9d99731d1">

**Comment by rabbitz** [comment]
The `general_info` interface statistics time is too long, causing the displayed value to be empty. Fields have now been added and recorded through regularly updated statistics, which has been deployed in the staging.

**Comment by FrederLu** [comment]
> The `general_info` interface statistics time is too long, causing the displayed value to be empty. Fields have now been added and recorded through regularly updated statistics, which has been deployed in the staging.


Does this data require front-end processing if it uses cached data?
It is normal to open `https://pudge.explorer.nervos.org/script/0xc5e5dcf215925f7ef4dfaf5f4b4f105bc321c02776d6e7d52a1db3fcd9d011a4/type` in the same way. Has the cached data been used?

**Comment by rabbitz** [comment]
The current statistical values are `ckb_transactions_count`, `deployed_cells_count`, `referring_cells_count`, `total_deployed_cells_capacity`, `total_referring_cells_capacity`. The statistics refresh is 1 hour. If you feel it is too slow, scheduled tasks can be adjusted. `ckb_transactions_count`, `deployed_cells_count`, `referring_cells_count` also have corresponding `total_count` in the separate interface return, which can also be taken from it.

<img width="748" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/990650/c1806100-162c-4e85-bd5b-e5cc216280cc">

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1456

**Comment by FrederLu** [comment]
> Related PR: [nervosnetwork/ckb-explorer#1456](https://github.com/nervosnetwork/ckb-explorer/pull/1456)

Verified.
