### ISSUE TITLE
Need to optimize the interface query data time.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#438]
When the amount of queried data is too large, a 502 exception occurs after the page waits for a long time.
https://pudge.explorer.nervos.org/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type/referring_cells?page=1&size=10
<img width="1438" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/9eb1e7d1-b235-4cba-9e9d-9d87864f38c2">

`irb(main):001:0> CellDependency.count
=> 176374895 `

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1461
