### ISSUE TITLE
The interface returns no data and the page is still waiting.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#439]
When no data is returned from the interface, the page can directly prompt that there is no data. There is no need to wait for the interface to api 404 and the page is still loading data.
https://pudge.explorer.nervos.org/script/0x5a86c3bf1e8648b6a6f8abe6875720ccf9745ab225b68fa7c195f9d6635dea80/type?page=1&size=10
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/1dad0766-421a-4357-9df1-b3bcb4555cd7">

https://pudge.explorer.nervos.org/script/0x07521d0aa8e66ef441ebc31204d86bb23fc83e9edc58c19dbb1b0ebe64336ec0/type
<img width="1437" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/66f9c5ca-841c-4394-ac41-edcdeb15d089">

**Comment by Daryl-L** [comment]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/5457564/2c0d47cc-6df9-4a8d-808a-5cefdb34084a)

The "Not Found Page" already exists. The page will reload when the page is focused again (including from the dev tools to the page) with loading view, whether the data exists or not.

I don't know how the design is before and why to do like this, and there is a solution to solve this if it is a bug, just not to reload the data. But another problem will come to us, that we don't know whether the data will exist or not at the next time to query the API, if so, the data will not be loaded unless uses refresh the page themselves.t

**Comment by Keith-CY** [comment]
> The page will reload when the page is focused again (including from the dev tools to the page) with loading view, whether the data exists or not.

It's a feature of `react-query` and can be disabled on condition, e.g. 404 was returned

Ref: 
- refetch on focus: https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching

**Comment by Daryl-L** [comment]
> > The page will reload when the page is focused again (including from the dev tools to the page) with loading view, whether the data exists or not.
> 
> It's a feature of `react-query` and can be disabled on condition, e.g. 404 was returned
> 
> Ref:
> 
> * refetch on focus: https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching

So it's not a feature from us, just feature from react-query, right? If so, I will try to disable this.

**Comment by Keith-CY** [comment]
> > > The page will reload when the page is focused again (including from the dev tools to the page) with loading view, whether the data exists or not.
> > 
> > 
> > It's a feature of `react-query` and can be disabled on condition, e.g. 404 was returned
> > Ref:
> > 
> > * refetch on focus: [tanstack.com/query/v4/docs/react/guides/window-focus-refetching](https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching)
> 
> So it's not a feature from us, just a feature from react-query, right? If so, I will try to disable this.

This feature was used in some pages, like refresh list on focus to keep displayed data up to date. So don't disable it arbitrarily, disable it on specific condition, e.g. it's confirmed the API will return constant response.

**Comment by Daryl-L** [comment]
> > > > The page will reload when the page is focused again (including from the dev tools to the page) with loading view, whether the data exists or not.
> > > 
> > > 
> > > It's a feature of `react-query` and can be disabled on condition, e.g. 404 was returned
> > > Ref:
> > > 
> > > * refetch on focus: [tanstack.com/query/v4/docs/react/guides/window-focus-refetching](https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching)
> > 
> > 
> > So it's not a feature from us, just a feature from react-query, right? If so, I will try to disable this.
> 
> This feature was used on some pages, like refreshing list on focus to keep displayed data up to date. So don't disable it arbitrarily, disable it on specific conditions, e.g. it's confirmed the API will return a constant response.

OK, but I have one more question, in this page, if the data shows up after while which not exists before, the up to date data will now be displayed if I disable the feature unless uses to refresh the page manually, isn't it ok? Because we can never know whether the data of the script will be created or not.

**Comment by Keith-CY** [comment]
> > > > > The page will reload when the page is focused again (including from the dev tools to the page) with loading view, whether the data exists or not.
> > > > 
> > > > 
> > > > It's a feature of `react-query` and can be disabled on condition, e.g. 404 was returned
> > > > Ref:
> > > > 
> > > > * refetch on focus: [tanstack.com/query/v4/docs/react/guides/window-focus-refetching](https://tanstack.com/query/v4/docs/react/guides/window-focus-refetching)
> > > 
> > > 
> > > So it's not a feature from us, just a feature from react-query, right? If so, I will try to disable this.
> > 
> > 
> > This feature was used on some pages, like refreshing list on focus to keep displayed data up to date. So don't disable it arbitrarily, disable it on specific conditions, e.g. it's confirmed the API will return a constant response.
> 
> OK, but I have one more question, in this page, if the data shows up after while which not exists before, the up to date data will now be displayed if I disable the feature unless uses to refresh the page manually, isn't it ok? Because we can never know whether the data of the script will be created or not.

I think this case is acceptable, refresh on focus is an optimization, but a basic requirement

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/118

**Comment by WhiteMinds** [comment]
Disabling automatic refetching in some cases can be a temporary solution, but I think it is correct to refetch on focus. However, we currently lack a reasonable design.

During the refetching process, the previous data and errors should still be displayed, and an additional loading indicator should be added, rather than replacing the previous results with a loading indicator.

**Comment by Keith-CY** [comment]
> Disabling automatic refetching in some cases can be a temporary solution, but I think it is correct to refetch on focus. However, we currently lack a reasonable design.
> 
> During the refetching process, the previous data and errors should still be displayed, and an additional loading indicator should be added, rather than replacing the previous results with a loading indicator.

Sound great

**Comment by FrederLu** [comment]
There is an interface prompt 404 on the testnet.
https://pudge.explorer.nervos.org/script/0x07521d0aa8e66ef441ebc31204d86bb23fc83e9edc58c19dbb1b0ebe64336ec0/type/referring_cells?page=1&size=10


https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/2bd8b8a3-a138-41bf-95a5-9c4c9cd7c432

**Comment by rabbitz** [comment]
> There is an interface prompt 404 on the testnet. https://pudge.explorer.nervos.org/script/0x07521d0aa8e66ef441ebc31204d86bb23fc83e9edc58c19dbb1b0ebe64336ec0/type/referring_cells?page=1&size=10
> 
>  2024-01-02.14.16.04.mov

There is no corresponding transaction under this contract

**Comment by FrederLu** [comment]
> > There is an interface prompt 404 on the testnet. https://pudge.explorer.nervos.org/script/0x07521d0aa8e66ef441ebc31204d86bb23fc83e9edc58c19dbb1b0ebe64336ec0/type/referring_cells?page=1&size=10
> > 2024-01-02.14.16.04.mov
> 
> There is no corresponding transaction under this contract

Verified.
