### ISSUE TITLE
Pagination action items are missing at the bottom.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#440]
Paging operations are missing at the bottom of Transactions, Deployed Cells and Referring Cells.
https://pudge.explorer.nervos.org/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type?page=1&size=10
<img width="1283" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/eb97497e-17e3-4750-af06-f09b485e32e0">
<img width="1328" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/d431fbf8-44e5-4d79-b8c9-c84814bfc64b">

UI view
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=11517-43224&mode=design&t=M4aMUdstkVFBHg80-0

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/113

**Comment by FrederLu** [comment]
Verified.
