### ISSUE TITLE
Replace twitter with X

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#441]
Twitter has been renamed to X, so the name, logo and URL should be updated.

**Comment by Keith-CY** [comment]
The logo in explorer(https://explorer.nervos.org/) footer is not a general icon, so I need help from @Kirl70 to transform the logo of X(https://about.twitter.com/en/who-we-are/brand-toolkit) into the same style.
<img width="69" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/7138d50d-8faa-48cf-b70e-3ac5dcec245b">

**Comment by Kirl70** [comment]
The logo in the design draft has been updated:

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5653%3A23133&mode=design&t=cYJ6dOhKyp1jNNtS-1
<img width="104" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/5166260c-834e-4645-8a45-8117bbfa4a78">

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/109
