### ISSUE TITLE
Refactor: Standardize the naming conventions for classnames

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/ckb-explorer-public-issues#442]
The specific naming conventions are yet to be determined. When using CSS modules, I prefer simpler rules and may consider the default rules of stylelint.

**Comment by PainterPuppets** [comment]
I'm a little confused as to what exactly this issue means.
Is it something like tailwind adding semantic global css or?

**Comment by WhiteMinds** [comment]
> I'm a little confused as to what exactly this issue means. Is it something like tailwind adding semantic global css or?

Oh, the description was not clear enough. This issue was raised here: https://github.com/Magickbase/ckb-explorer-frontend/pull/103#discussion_r1334199174

Our current naming conventions seem to fall into the following categories:
1. `.sortIcon`
2. `.SortIcon`
3. `.sort__icon`

**Comment by PainterPuppets** [comment]
> > I'm a little confused as to what exactly this issue means. Is it something like tailwind adding semantic global css or?
> 
> Oh, the description was not clear enough. This issue was raised here: [Magickbase/ckb-explorer-frontend#103 (comment)](https://github.com/Magickbase/ckb-explorer-frontend/pull/103#discussion_r1334199174)
> 
> Our current naming conventions seem to fall into the following categories:
> 
> 1. `.sortIcon`
> 2. `.SortIcon`
> 3. `.sort__icon`

Indeed, any suggestions on what style to use?

**Comment by WhiteMinds** [comment]
> Indeed, any suggestions on what style to use?

I've thought about it, and I want it to be simple, common, and easy to use, so I'm ruling out more complex options like BEM and less user-friendly options like kebab-case (which is the default mode in stylelint).

You can do some research to see if there are any suitable naming conventions. I guess it might be something like `.sortIcon` or a simplified version of BEM.

Alternatively, we could make the hyphen in kebab-case easier to type in JS files. It's currently inconvenient to manually enclose it in square brackets, like `styles['sort-icon']`.

**Comment by Keith-CY** [comment]
> > Indeed, any suggestions on what style to use?
> 
> I've thought about it, and I want it to be simple, common, and easy to use, so I'm ruling out more complex options like BEM and less user-friendly options like kebab-case (which is the default mode in stylelint).
> 
> You can do some research to see if there are any suitable naming conventions. I guess it might be something like `.sortIcon` or a simplified version of BEM.
> 
> Alternatively, we could make the hyphen in kebab-case easier to type in JS files. It's currently inconvenient to manually enclose it in square brackets, like `styles['sort-icon']`.

`.sortIcon` looks good to me because it follows the naming convention of JavaScript to make a reference, such as `styles.sortIcon`, looks natural and I don't have to consider if it's a JavaScript variable or CSS name, it's just a reference.

Besides, `jump to definition` is supported by some vscode plugin(in my memory) on `styles.sortIcon` but not on `styles['sort-icon']`. I'm not sure about this argument because I haven't used vscode for a long time.
