### ISSUE TITLE
Referring cells of Nervos DAO is empty

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#445]
<img width="1593" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/890af0fe-d98b-4786-a72a-1fd48b55c2e9">

Link: https://explorer.nervos.org/script/0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e/type/referring_cells?page=1&size=10

**Comment by zmcNotafraid** [comment]
<img width="602" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/e97ea24e-1f6c-4914-aeb6-02daf027f0b8">
Current exist two datas of type contract and lock contract

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1472
https://github.com/nervosnetwork/ckb-explorer/pull/1475
https://github.com/nervosnetwork/ckb-explorer/pull/1476
https://github.com/nervosnetwork/ckb-explorer/pull/1477
https://github.com/nervosnetwork/ckb-explorer/pull/1481
