### ISSUE TITLE
Cell info-Clicking on the capacity tab will request data

### ISSUE THREAD

**Issue by Danie0918** [Magickbase/ckb-explorer-public-issues#446]
Clicking on the Capacity usage tab will bring up the Output Data is Too Large prompt, which will confuse the user.

[Transaction](https://pudge.explorer.nervos.org/transaction/0x316a3fc06bc94572f6ab5fd65b4b79163b3e07689bceb988675ce747dcb93caa)

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/122437870/6da73f56-095a-4b6a-a592-cd5c010bb41b)

This tab actually displays two capacities
1. [declared capacity] which is the value corresponding to the capacity field
2. [occupied capacity] which is the actual space occupied by the data in this cell
The occupied capacity is calculated by the frontend after getting the cell, so the data is requested once.

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1474

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/123
