### ISSUE TITLE
portfolio account connect

### ISSUE THREAD

**Issue by rabbitz** [Magickbase/ckb-explorer-public-issues#447]
## Register or sign in via ckb address

```http
POST /api/v2/portfolio/sessions
```

**Request Parameters**

| Parameter | Required | Type      | Description               |
|-----------|----------|-----------|---------------------------|
| address   | yes      | String | user ckb address          |
| message   | yes      | String | wallet conenct message    |
| signature | yes      | String | wallet conenct signature  |
| pub_key   | false    | String | user signature public key |

**Request Example**

```bash
curl --location --request POST 'http://localhost:3000/api/v2/portfolio/sessions' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: localhost:3000' \
--header 'Connection: keep-alive' \
--data-raw '{
    "message": "0x95e919c41e1ae7593730097e9bb1185787b046ae9f47b4a10ff4e22f9c3e3eab",
    "signature": "0x1e94db61cff452639cf7dd991cf0c856923dcf74af24b6f575b91479ad2c8ef40769812d1cf1fd1a15d2f6cb9ef3d91260ef27e65e1f9be399887e9a5447786301",
    "address": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfkcv576ccddnn4quf2ga65xee2m26h7nq4sds0r",
    "pub_key": null
}'
```

**Response Example**

```json
{
    "name": "test",
    "jwt": "eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiZWY0ZTU5ZTAtMGJiMi00N2U5LWE2ZjctOGQxYTQ1NWY3OGZhIiwiZXhwIjoxNjk5ODU4MjY3fQ.r7QyrOPX5_mQsxkzQq86Xi_l4vvCCDZx5jU3MRHSlDY"
}
```

## Update user name

```http
PUT /api/v2/portfolio/user
```

**Request Parameters**

| Parameter | Required | Type      | Description               |
|-----------|----------|-----------|---------------------------|
| name      | yes      | String | user name                 |

**Request Example**

```bash
curl --location --request PUT 'http://localhost:3000/api/v2/portfolio/user' \
--header 'Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiZWY0ZTU5ZTAtMGJiMi00N2U5LWE2ZjctOGQxYTQ1NWY3OGZhIiwiZXhwIjoxNjk5ODU4MjI4fQ.WlHxTpGOaw1fLGTwO-r_Fg1C32xjDu3YsVw_0oBqztA' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: localhost:3000' \
--header 'Connection: keep-alive' \
--data-raw '{
    "name": "nametest"
}'
```

**Response Example**

```bash
Http Status 204
```

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1484

**Comment by FrederLu** [comment]
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a4ac0556-13f6-42c1-a6d1-28b4f7030de3)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/0f402127-7652-4f4a-afff-05c17eccde35)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/1c343390-02a8-45bd-98d7-a8393204c29b)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/199063a2-12b9-4eda-8692-f5d615935cfa)
If the type exception is missing, 500 is returned.

---
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a3dd1906-5dcd-486d-a7aa-69cff9e374e6)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/dbdfdd09-5c1e-4837-908b-51465314e7cf)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/460fd9f2-5b4d-41ae-894d-cb620d9534a7)
The parameters are not filled in or the wrong type is missing validation.

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1609

**Comment by FrederLu** [comment]
> [nervosnetwork/ckb-explorer#1609](https://github.com/nervosnetwork/ckb-explorer/pull/1609)

Verified.
