### ISSUE TITLE
portfolio sync addresses

### ISSUE THREAD

**Issue by rabbitz** [Magickbase/ckb-explorer-public-issues#448]
## User ckb statistic

```http
GET /api/v2/portfolio/statistics
```

**Request Parameters**

| Parameter | Required | Type   | Description          |
|-----------|----------|--------|----------------------|
| latest_address | yes      | String | frontend latest address |

**Request Example**

```bash
curl --location --request GET 'http://localhost:3000/api/v2/portfolio/statistics?latest_address=%E5%95%A5%E5%9C%B0%E6%96%B9' \
--header 'Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiYjhjZjkwNjAtYTk5Ni00OWUyLWE5ZjItZTdjZjliYzY1NzU1IiwiZXhwIjoxNzA3ODg3MDg4fQ.gRpZ9crgkDVXsfEDFgCXeIGGz3MfCNjKSs3RtDAkIW8' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Accept: */*' \
--header 'Host: localhost:3000' 
--header 'Connection: keep-alive'
```

**Response Example**

```json
{
  "data": {
    "balance": "0",
    "balance_occupied": "0",
    "dao_deposit": "0",
    "interest": "0",
    "dao_compensation": "0"
  }
}
```

## Sync frontend latest addresses

```http
POST /api/v2/portfolio/addresses
```

**Request Parameters**

| Parameter | Required | Type     | Description           |
|-----------|----------|----------|-----------------------|
| addresses | yes      | []String | user wallet addresses |

**Request Example**

```bash
curl --location --request POST 'http://localhost:3000/api/v2/portfolio/addresses' \
--header 'Authorization: eyJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiZWY0ZTU5ZTAtMGJiMi00N2U5LWE2ZjctOGQxYTQ1NWY3OGZhIiwiZXhwIjoxNjk5ODU4MjY3fQ.r7QyrOPX5_mQsxkzQq86Xi_l4vvCCDZx5jU3MRHSlDY' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Host: localhost:3000' \
--header 'Connection: keep-alive' \
--data-raw '{
    "addresses": [
        "ckt1q3w9q60tppt7l3j7r09qcp7lxnp3vcanvgha8pmvsa3jplykxn323k5v49yzmvm0q0kfqw0hk0kyal6z32nwjvcqqr7qyzq8yqtec2wj"
    ]
}'
```

**Response Example**

```bash
Http Status 204
```

**Comment by FrederLu** [comment]
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/c31b7dc9-843c-47ff-bd93-b523815c2871)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b86cd748-8627-4b07-94d9-7e38f0701da0)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/cb3ca5b5-1e26-40ef-9ac5-491a6a43741f)

The parameters are not filled in or the wrong type is missing validation.

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1609
