### ISSUE TITLE
测试网存在一些dao_deposit值为负的地址

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#45]
https://github.com/nervosnetwork/ckb-explorer/issues/936

根据调研，`addresses.dao_deposit` 理因可以从 `dao_events` 表中重建数据，但是似乎 `dao_events` 中的记录不全，重新计算仍是负值

**Comment by ShiningRay** [comment]
因为 DAO 的 Deposit 和 Withdraw 也是 Cell
用户地址上持有的 DAO Cell，可以以 Withdraw Cell 转让给另外一个地址
所以这里会出现存款地址 和 提现地址不一致的情况
DaoEvent表中，只出现了一个address id ，没有考虑这种不一致的情况
数据同步代码中，这个address id只考虑了cell所属地址
这导致dao deposit的计算错误，如果要完全修正，会需要对之前的dao events做全部的重新处理。

**Comment by Keith-CY** [comment]
> 因为 DAO 的 Deposit 和 Withdraw 也是 Cell 用户地址上持有的 DAO Cell，可以以 Withdraw Cell 转让给另外一个地址 所以这里会出现存款地址 和 提现地址不一致的情况 DaoEvent表中，只出现了一个address id ，没有考虑这种不一致的情况 数据同步代码中，这个address id只考虑了cell所属地址 这导致dao deposit的计算错误，如果要完全修正，会需要对之前的dao events做全部的重新处理。

这个修复, 预计需要多少时间呢

**Comment by ShiningRay** [comment]
如果只是改正确逻辑，我估计两三天
但遗留的脏数据我还不知道如何处理比较好

**Comment by Keith-CY** [comment]
> 如果只是改正确逻辑，我估计两三天 但遗留的脏数据我还不知道如何处理比较好

那还是先把逻辑修复吧, 主网上进行 dao 操作, 基本只有 neuron 和 pw, 有问题的数据应该比较少

**Comment by Keith-CY** [comment]
Ref:
Input and output have the same lock in deposit: https://pudge.explorer.nervos.org/transaction/0xdb189a3e2106f7a1b0373d6365571bae14c9af17d0d21290a47d428f570ad0a7
Input and output have different locks in deposit: https://pudge.explorer.nervos.org/transaction/0xb62b90f81d251d1001a041434a966da7b8793b01e31c7ec5f76e4031154db0f9#0

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/937

**Comment by Keith-CY** [comment]
https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-calculate_dao_maximum_withdraw
