### ISSUE TITLE
"Capacity Usage" tab style displays abnormally

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#450]
On the cell info pop-up window of the mobile terminal script details page, the `Capacity Usage` tab displays abnormally.
https://pudge.explorer.nervos.org/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type/referring_cells?page=1&size=10
<img width="310" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e1f49bde-f54f-45b1-9632-c5564853ea26">
<img width="321" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/baf7ef94-0493-471d-a1db-6c5bdde9bb06">

**Comment by Sven-TBD** [comment]
When the header length of the table exceeds the external border, a sliding solution should be adopted. This strategy is applicable to all such cases, based on [this design](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=6230-30977&mode=design&t=1GhZBsx8dFEvVXt1-4)

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/145
