### ISSUE TITLE
Sort button is not intuitive

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#452]
This feedback comes from community that sort buttons are not so prominent to be interactive, so they didn't realize that the list could be sorted.

<img width="202" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/498a8e06-427a-4abe-a14b-bcac56ea7711">

The filter button is not conspicuous, too.

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/b77307f6-0002-4200-91c0-517ea006f616)

**Comment by Kirl70** [comment]
The sorting button has been adjusted previously after discussing with @Sven-TBD  It may not have been synchronized with development, leading to a discrepancy between the actual page and the design draft.
<img width="155" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/d8cc731e-9031-4f62-9040-ff03a5cf69dd">


The filtering button has been adjusted:
<img width="97" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/d795e941-7029-4e68-8067-8e29af934456">

Figma Link:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5696%3A25396&mode=design&t=1hzRHQYo6AZFiqdR-1

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/126

**Comment by FrederLu** [comment]
Verified.
