### ISSUE TITLE
The default sort could be "By 24 hr transactions"

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#453]
This feedback come from the community.

Now the token lists are sorted by issuance time by default, but newly issued tokens are not attractive. The advice is to sort tokens by "24 hours transactions" by default.

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/128

**Comment by FrederLu** [comment]
Verified.
