### ISSUE TITLE
Copy button doesn't work.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#454]
There is a prompt when clicking the copy button, but the information is not copied. Because using the paste function only displays the previously copied information.
https://explorer.nervos.org/transaction/0xda9f276ae76a1c588ca1770e692692a8170906c3f23644301e1c1a17887111ce
<img width="1385" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/80afccd9-3c8f-47b1-805d-349d0338f9c3">

https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq22xdj8q4jdql98qkdhnqzgrsk4nqyavdcratvu9
<img width="1280" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/242387ce-be53-4391-82e7-e669188c2863">

**Comment by Danie0918** [comment]
The copy button next to address/tx hash on address/transaction page doesn't work, although a successful message is prompted.

Address page: https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfz9rdwxs84saj8xcknrclsf4a9r7qk3hqqsv05e
Transaction page: https://explorer.nervos.org/transaction/0x61d94901a897406860b683103f79555987b6caf5ef3512f28ffb22e2f4b17df8

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/125
