### ISSUE TITLE
Copy button on address/tx page doesn't work

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#455]
The copy button next to address/tx hash on address/transaction page doesn't work, although a successful message is prompted.

Address page: https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfz9rdwxs84saj8xcknrclsf4a9r7qk3hqqsv05e
Transaction page: https://explorer.nervos.org/transaction/0x61d94901a897406860b683103f79555987b6caf5ef3512f28ffb22e2f4b17df8

**Comment by Keith-CY** [comment]
Duplicated to https://github.com/Magickbase/ckb-explorer-public-issues/issues/454#issuecomment-1772292874

**Comment by Danie0918** [comment]
This will be fixed in the issue below:
#454 https://github.com/Magickbase/ckb-explorer-public-issues/issues/454
