### ISSUE TITLE
Need to process data with non-8 decimal places.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#459]
Data with non-8 decimal places is displayed abnormally.
https://pudge.explorer.nervos.org/transaction/0x1d320432dbe19599eb752d835be9877a596870b46980dd68edad3abd1fd10111?layout=lite
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7a2375c3-86ab-419f-8591-33d7de80bd82">
https://pudge.explorer.nervos.org/transaction/0x8b9764422f9a8cdb2f1cadcd3c6dee006f442946ee60e67972503fd56745cc4b?layout=lite
<img width="1320" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/85337bc7-f503-4a03-8729-55fb7eeb77fb">

https://explorer.nervos.org/transaction/0xf7e4ead2242e204ff2e4797e6f3170dc289445593127896099867bacc0c01ecb?layout=lite
<img width="1436" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/99a2c291-b3c0-4682-9576-8475782b447b">
<img width="954" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e34ca8b3-17dc-4883-9623-37305b910a7b">

**Comment by FrederLu** [comment]
PR https://github.com/Magickbase/ckb-explorer-frontend/pull/129

**Comment by FrederLu** [comment]
>PR https://github.com/Magickbase/ckb-explorer-frontend/pull/129

Mainnet data shows that there are still abnormalities. Looking at the screenshot 0.2664 seems like there are too many 0s after it.
https://explorer.nervos.org/transaction/0xf7e4ead2242e204ff2e4797e6f3170dc289445593127896099867bacc0c01ecb?layout=lite
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/be22d12e-48fd-4090-89af-4a41cc163dd8)

**Comment by zhangyouxin** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/147
