### ISSUE TITLE
Incorrect capacity calculation in a transaction

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#46]
https://pudge.explorer.nervos.org/address/ckt1qyq9suqw8dlmfe9zfhpeapceypr3mmjax3msymwkae?page=10&size=10

![image](https://user-images.githubusercontent.com/7271329/174426557-8651f057-bfe2-49d0-8d5e-b07580131b05.png)

In this transaction, the address `ckt1qyq9suqw8dlmfe9zfhpeapceypr3mmjax3msymwkae`
offers 0 inputs while getting 1 output, the income should be positive but 0 is displayed, tracking the API and found `income` is `null`
![image](https://user-images.githubusercontent.com/7271329/174426614-ee7ff1e2-d8ae-4e67-8cf3-e377cd3d015d.png)

**Comment by Keith-CY** [comment]
It happens in other cases
![image](https://user-images.githubusercontent.com/7271329/174426804-307db4f7-fd07-4d26-9409-216b3c1dc356.png)

Historic data should be fixed

**Comment by Keith-CY** [comment]
Searching `0xdaf7d45eea1252ca2dea40eec11cc8408194e0b229e621f84b45ee35b1632480` in testnet returns 500 internal error, may be related to the error of historic data.

**Comment by ShiningRay** [comment]
该数据被称之为address 的 income，首先页面本身有一个缓存，其次，这个 income 数据会缓存在 TxDisplayInfo 表中，而这个表的字段 income，是一个 address hash => 数据的一个 kv 缓存
所以当 address 格式升级之后，缓存数据没有变化，导致无法获取到对应的 income。
线上已经将 transaction 对应的 TxDisplayInfo 记录删除，并且删除了页面缓存，修复了结果。
后续计划移除 TxDisplayInfo 表，对缓存架构做一次疏离。
