### ISSUE TITLE
Block's ckb_transactions_count not match real txs count

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/ckb-explorer-public-issues#460]
"10185709,10186317,10187475,10189864,10189914,10190005,10191443,10192843,10193731,10193811,10194286,10194309,10194400,10194401,10195363,10195364,10196342,10196779,10197224,10197398,10197399,10197787,10197895,10197896,10198047,10198447,10198580,10199216,10199388,10200308,10200661,10200738,10200794,10201492,10201718,10201976,10202562,10202782,10202908,10203165,10203355,10203576,10203815,10204111,10204304,10204508,10204673,10205396,10205501,10205556,10206345,10207377,10207378,10208507,10208851,10208956,10209075,10209259,10209964,10210257,10210258,10210627,10210853,10211297,10212063,10212608,10212723,10213279,10213415,10214338,10215607,10215608,10215849,10215919,10216441,10216778,10217240,10217879,10218433,10218947,10219220,10219398,10220278,10220359,10221665,10221775,10222769,10222770,10222812,10223309,10223463,10223567,10223698,10223946,10224246,10224319,10224555,10224778,10225639,10226678,10226776,10226826,10227026,10227626,10227949,10228513,10229470,10229585,10230128,10230452,10230622,10231330,10231702,10231899,10232133,10232340,10232513,10232628,10232671,10233298,10233548,10233625,10233626,10236080,10236375,10237270,10237493,10237811,10237974,10238177,10239225,10239275,10239306,10239570,10239893,10239930,10240183,10240233,10240538,10241121,10241306,10241307,10241541,10244460,10244516,10244547,10246060,10246106,10246445,10246446,10247156,10247214,10248165,10248344,10249150,10249193,10250203,10252224,10253403,10253736,10254048,10254157,10254263,10254414,10254781,10254820,10255279,10255403,10255499,10255650,10255883,10256140,10256307,10257153,10257796,10257898,10258312,10258408,10258740,10259455,10260994,10262120,10262190,10262280,10263131,10263158,10263188,10263212,10263386,10263474,10264076,10264369,10264588,10265783,10266298,10266598,10267185,10267502,10269403,10269692,10270461,10270661,10270994,10271396,10271524,10271594,10273230,10273287,10273448,10273852,10273909,10274276,10274477,10275113,10275412,10275577,10276098,10276546,10276768,10276892,10276893,10277079,10277746,10279022,10279154,10279246,10279527,10280086,10280682,10281387,10281903,10281978,10282500,10283391,10283945,10284149,10284509,10284870,10285234,10285323,10285688,10286075,10286204,10286682,10287240,10287752,10288552,10289210,10289236,10289263,10289791,10290129,10291888,10291985,10292573,10294000,10294384,10294605,10294824,10295753,10295754,10295882,10296470,10296654,10296655,10296771,10296896,10297090,10297155,10297255,10297511,10297605,10297997,10298704,10299101,10299821,10299936,10300383,10300803,10300932,10301098,10301099,10301224,10301895,10302735,10302864,10302973,10304692,10304768,10306307,10306368,10306471,10306799,10307756,10307918,10309440,10309760,10309965,10310287,10310289,10310613,10310649,10311322,10311354,10311455,10311662,10312178,10313322,10313563,10313564,10314136,10314562,10314591,10315416,10315551,10315898,10316107,10316872,10316908,10317276,10318135,10318697,10318827,10319205,10319244,10319682,10320094,10320438,10320912,10320972,10321524,10322079,10322209,10322657,10322702,10323319,10323870,10324123,10324153,10325643,10326178,10326322,10327661,10327690,10327691,10328130,10328901,10329177,10329233,10329289,10330316,10331835,10332430,10333123,10333244,10333891,10334457,10334548,10334981,10336010,10336220,10337266,10337508,10338076,10338242,10338296,10338829,10339051,10339059,10340999,10341797,10342273,10342274,10342397,10342656,10342658,10342856,10343008,10343328,10343891,10344011,10345290,10345410,10345606,10345879,10345909,10345910,10346021,10347175,10347379,10347905,10347983,10348029,10348106,10348107,10348306,10348307,10349058,10349135,10349658,10349999,10350028,10350650,10351368,10351906,10351936,10352078,10352278,10352439,10352536,10352929,10352974,10353122,10353485,10353986,10354086,10354799,10354899,10355417,10355418,10355479,10355540,10355638,10355965,10356049,10356166,10356419,10356660,10357096,10358003,10358267,10358386,10358478,10358868,10358989,10359958,10359992,10360484,10361030,10361152,10361601,10361680,10361681,10362354,10362452,10362474,10362625,10362690,10363015,10364103,10364563,10364982,10365614,10365659,10365713,10365824,10365856,10365991,10366117,10366679,10367078,10367994,10368133,10368327,10368512,10368542,10368781,10368939,10369787,10369813,10369996,10369997,10370255,10371130,10371234,10371310,10371468,10372194,10372216,10372677,10372985,10373218,10373219,10373775,10373959,10374215,10374305,10374524,10374776,10375114,10375173,10376025,10376453,10376487,10376676,10377550,10377551,10377599,10377624,10377816,10377928,10378092,10379236,10379433,10379611,10379703,10380318,10380730,10380856,10381223,10381332,10381487,10381629,10381761,10382444,10382445,10383014,10383063,10383796,10384293,10384395,10384427,10384632,10385147,10385171,10385320,10386098,10387330,10388030,10388160,10388192,10388486,10388549,10388614,10388677,10388845,10389058,10389292,10389887,10390966,10392059,10392321,10392759,10393041,10393187,10393228,10393699,10393805,10393867,10393956,10394112,10394916,10395099,10396096,10396156,10397650,10397739,10397813,10398208,10398562,10398708,10398941,10399201,10399874,10399875,10400097,10400187,10401032,10401351,10401505,10401699,10403265,10403529,10403977,10404318,10404506,10404626,10404627,10404628,10404630,10404631,10404632,10404633,10404635,10404636,10404637,10404638,10404640,10404641,10404643,10404644,10404646,10404649,10404650,10404651,10404653,10404654,10404655,10404657,10404658,10404659,10404660,10404662,10404664,10404665,10404666,10404667,10404669,10404672,10404787,10404942,10405158,10405224,10406103,10406581,10406651,10406668,10406892,10406977,10407028,10407029,10407724,10407916,10408127,10408341,10408367,10408515,10408916,10409640,10409936,10410091,10410477,10410601,10410724,10410811,10411060,10411365,10411612,10411743,10413485,10414079,10414111,10414848,10415076,10415261,10415380,10415574,10416505,10416531,10416902,10417099,10417100,10417210,10418731,10418889,10419367,10419778,10420025,10420051,10420162,10420163,10420517,10420673,10420780,10420844,10421145,10421162,10421225,10421306,10421336,10421394,10421683,10421855,10422105,10422489,10422490,10422492,10422493,10422839,10422840,10423054,10423333,10424136,10424629,10424745,10424819,10425013,10425723,10425906,10425959,10426320,10426946,10427032,10427033,10427137,10427791,10428089,10428122,10428848,10429034,10429092,10429093,10429155,10429529,10430134,10430587,10430679,10430860,10430861,10430862,10430863"

**Comment by rabbitz** [comment]
New Relic tracks deleted transactions with NRQL

```bash
SELECT `message` 
FROM Log 
WHERE allColumnSearch('Deleting CkbTransaction with tx_hash', insensitive: true)
AND entity.name ='ckb-explorer mainnet (production)'
SINCE 4 days ago
````



![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/990650/d9a0892f-078d-44be-a579-25646702d9a0)
