### ISSUE TITLE
[Bug] Chart freezes after clicking on bar.

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/ckb-explorer-public-issues#461]
When you try to see the address count of a specific group and you move over the bar, it freezes. No data visible and not possible to move the marker.

https://explorer.nervos.org/charts/balance-distribution

**Comment by FrederLu** [comment]
@Danie0918 
There is such a problem on the mainnet or testnet and needs to be fixed.
https://pudge.explorer.nervos.org/charts/balance-distribution


https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/ca69685c-615e-4667-8b8c-1cb68a0b0d62

**Comment by Keith-CY** [comment]
It's been reported again, how is it going?

**Comment by Daryl-L** [comment]
> It's been reported again, how is it going?

In progress, will be done not after tomorrow morning.

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/136

**Comment by FrederLu** [comment]
Verified.

**Comment by Keith-CY** [comment]
Still be frozen after interaction

https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/c01aeebc-3144-4cca-acc3-ab78c50fb23e

**Comment by Keith-CY** [comment]
> Still be frozen after interaction, e.g. click on the chart
> 
>  frozen.chart.mov

Should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/138

**Comment by Keith-CY** [comment]
Frozen **epoch time & epoch length** should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/139
