### ISSUE TITLE
[Feature request] Add calculator for DAO rewards

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/ckb-explorer-public-issues#462]
I wonder if it would be possible to add a calculator to calculate DAO rewards, that is, if I deposit X amount into the DAO today within X amount of time I will have X rewards.

![Screenshot_20231028-130916_Telegram](https://github.com/Magickbase/ckb-explorer-public-issues/assets/94946624/18e57a80-9011-41e6-9660-e260c7fafb88)

This tool could also show: "if you lock coins in the DAO today, your effective share of total supply would be...". Something I have noticed over the years in the community is that it is difficult to understand the fact that if you deposit in Nervos DAO your CKB expands at the same speed as the secondary issuance, therefore your share percentage with respect to the total supply is the same, you are not diluted by the secondary issuance and your CKBs are hardcaped Bitcoin style (you are only diluted by the primary issuance as long as it exists).

Finally we could add the option to apply a coin loss rate to the calculation (if the user wants to add it, so optional). We could also set the option to exclude from the calculation coins that have not been moved for X amount of time, for example Glassnode considers that Bitcoins that have not been transacted for 7 years are lost coins. The objective with this last functionality is to show that in addition to the fact that your CKB are hardcapped if you deposit in Nervos DAO, it is also defacto deflationary, that is, that you not only maintain the same percentage of share over time, but that share increases over time if you consider the irreparable loss of coins (See: #424)

Some reference links:

https://cardano.org/calculator/?calculator=delegator
https://www.stakingrewards.com/calculator

The ultimate goal of all this is to make it easier for the community, present and future, to understand the economic model through multiple tools. 

Complex math and RFCs are difficult, show me the calculator.

Edit: Also in this section we can add basic information about Nervos DAO, such as that it is a compound interest, or that it works in 30-day cycles (Ref; https://www.nervos.org/knowledge-base/nervosdao_withdrawal_process_explained)

**Comment by Sven-TBD** [comment]
Write a proposal to this issue for Neuron & Explorer.

@Keith-CY @Danie0918 You can check it [here](https://vs0cjf.axshare.com/?id=vsq6ym&g=14)

**Comment by Kirl70** [comment]
Design Draft:
CKB Explorer (2-1--2-2):
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=29237%3A24849&mode=design&t=0fzcMl9O1MCHtrS0-1
<img width="597" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/4f881eae-4447-423d-8073-111a07729549">


Neuron (6-7--6-9):
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=767%3A7135&mode=design&t=0fzcMl9O1MCHtrS0-1
<img width="604" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/3cd17f73-0185-435b-a605-f8f88f19d48c">

**Comment by devchenyan** [comment]
https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1517

**Comment by Keith-CY** [comment]
The calculator is available at 

<img width="832" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/443ec055-82da-4b5e-aed6-f0e41306c3dc">

slightly changed based on reviews from the community
