### ISSUE TITLE
Change the configuration of whether to display the deprecated format of the ckb address to be recorded in the URL

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/ckb-explorer-public-issues#467]
Refs: https://github.com/Magickbase/ckb-explorer-frontend/pull/134#discussion_r1379569175

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/259

**Comment by FrederLu** [comment]
Verified.
