### ISSUE TITLE
Spent cells in outputs seem to be incorrect

### ISSUE THREAD

**Issue by homura** [Magickbase/ckb-explorer-public-issues#468]
## Reproducing

1. go to https://explorer.nervos.org/transaction/0x6793bb6280ebe3d3972bbab947be2ac7ced724c9a50eae6846f9753a4422b25f
2. click the `OutPoint` arrow of the first input
<img width="524" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7511174/1f99d578-dd0b-4d5d-9af6-94563c03080f">

3. Check the first output
<img width="559" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7511174/e9377c8a-c4e0-4fc1-b335-5268a20f6355">

**Comment by rabbitz** [comment]
https://explorer.nervos.org/transaction/0xac6e37f73b94f1dd33a71527a0205a85b2e5fe1a2b19355a99965b59e5879676

<img width="1857" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/990650/c3a10351-a415-4ef0-ba09-3cbac182723e">


output cell status is already `dead`

**Comment by homura** [comment]
> output cell status is already `dead`, the disparity in display is caused by backend caching (with a 1-day expiration time).

Does it mean that all the dead cell arrow icons need to be delayed for 1 day?

**Comment by rabbitz** [comment]
> > output cell status is already `dead`, the disparity in display is caused by backend caching (with a 1-day expiration time).
> 
> Does it mean that all the dead cell arrow icons need to be delayed for 1 day?

No, if a piece of data has not been accessed for a long time, then the data stored in the cache will be the latest after it is requested. If a piece of data has been accessed within 1 day, but the status of the cell is updated again, you will have to wait for the cache to expire and be refreshed.

**Comment by homura** [comment]
> No, if a piece of data has not been accessed for a long time, then the data stored in the cache will be the latest after it is requested. If a piece of data has been accessed within 1 day, but the status of the cell is updated again, you will have to wait for the cache to expire and be refreshed.

Thanks for your explanation, but I suggest that it would be better if the cache becomes expired when an `OutPoint` of a transaction is consumed.
