### ISSUE TITLE
Transaction Data and its decode

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#469]
This issue is made to explore the best way to display the transaction data, and its goal is to unify the way CKB explorer display a transaction's information.

This proposal originally comes from #331.

Goal:
1. Explorer and try the latest transaction display format on the Portfolio page. #463 
2. Improve the way to show transaction data. #331

Links:
- [Axure for issue469](https://vs0cjf.axshare.com/?id=2vp573&p=%E4%BA%A4%E6%98%93%E8%AF%A6%E6%83%85%E5%B1%95%E7%A4%BA%E5%BD%A2%E5%BC%8F%E8%B0%83%E6%95%B4proposal&g=1)
- [Axure for issue 331](https://vs0cjf.axshare.com/?id=lhcxpc&p=_331_______data__decode_ux__&g=1)
- UI for issue469
- UI for issue331

**Comment by Keith-CY** [comment]
any update on this?

**Comment by Sven-TBD** [comment]
Yes, the UX proposal about the decode button is posed at #331

**Comment by Sven-TBD** [comment]
The following are the areas that need to be changed beyond Cell info component.


![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/01e0fb6c-313a-47fa-85df-d85679e152e3)


https://vs0cjf.axshare.com/?id=vaj3jf&p=_19_display_live_cells_of_a_specific_address&g=1
