### ISSUE TITLE
No response on this function.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#471]
No response on this function

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/73f95827-e9af-498f-b4d7-157dc057a90d)

**Comment by Keith-CY** [comment]
Duplicated with https://github.com/Magickbase/ckb-explorer-public-issues/issues/461#issuecomment-1793359738 and should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/138

**Comment by Keith-CY** [comment]
Close this issue because of duplication mentioned above
