### ISSUE TITLE
The search box disappears within a specific width.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#472]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/05c79289-96c3-4d5a-95b4-b90a58efef4b)

**Comment by Sven-TBD** [comment]
Confirmed with @Kirl70 , there should be no situation like that. When the whole page works for PC side, it should display the whole search box; and when it works for mobile side, it should hide all the labels, search box etc.

[Reference](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5782-25307&mode=design&t=vfJBlLXIJkpTuLDQ-4)

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/155

**Comment by Sven-TBD** [comment]
Copy that, @Kirl70 we should add the Fee Rate to the figma file as well. 
However, I think the rules of whether it shows All or hides all should be the same. The search icon and its display do not align with the UI design, the search rectangle hides when it shows all other tags.

<img width="1241" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/005f701c-2be1-4751-a18d-9fd611c37717">

**Comment by Daryl-L** [comment]
> Copy that, @Kirl70 we should add the Fee Rate to the figma file as well. However, I think the rules of whether it shows All or hides all should be the same. The search icon and its display do not align with the UI design, the search rectangle hides when it shows all other tags.
> 
> <img alt="image" width="1241" src="https://private-user-images.githubusercontent.com/85155313/287458808-005f701c-2be1-4751-a18d-9fd611c37717.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MzY5ODEsIm5iZiI6MTcwMTUzNjY4MSwicGF0aCI6Ii84NTE1NTMxMy8yODc0NTg4MDgtMDA1ZjcwMWMtMmJlMS00NzUxLWExOGQtOWZkNjExYzM3NzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAyVDE3MDQ0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNDAzOGNhOTAyOTZlYjU1MzJiZWU4Yjg5YmUwOWRlY2YzMDMzOWMwN2JiZWI4MTc0ODczMWYwZGNmNDNmMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZmDjDz6rjn18xlHbgzm8RQ8JsfROhy3JVeW34d7CU_0">

Based on the design, it is not enough for them in header, so the size of design should be changed

**Comment by Daryl-L** [comment]
> The design draft has added the `Fee Rate` entrance.
> 
> https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28879%3A28111&mode=design&t=OeRqt6vLAEdjb5sC-1 <img alt="image" width="990" src="https://private-user-images.githubusercontent.com/106060898/287494411-e1069f1a-b1a4-4584-84d2-dec3d353728b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0NDExLWUxMDY5ZjFhLWIxYTQtNDU4NC04NGQyLWRlYzNkMzUzNzI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGIzMmNjZDZhNDM5ZTQ0YmQzNDRjYjQwOTA4MWU4ZDNjOTFhZTY2YTAxYzUyYzUxODA0YjRmMDJhOTU1MmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihvoOCz2bp6qj_lZKHVgwvAYzVLNZDkBo5e3qClD7_o">
> 
> <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/106060898/287494390-1683a3cf-8852-4abc-9487-c8d10d45d886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0MzkwLTE2ODNhM2NmLTg4NTItNGFiYy05NDg3LWM4ZDEwZDQ1ZDg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTQwMmYzZWYzYTM4YWEyNjY2NDFiZjkzN2IxYmQ4MjBiYzJmMjVhMTNjNDQ4ZmFmMzJjMjM5ZjdjZTc2NjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DfLXqa2pOVcwQKf-iFaAzjliiXNBE_nJbZ9avqzegBw">

Not enough for the screen size smaller than 1412px, while the margin size is 56px, consider redesign for the size of screen between 1024px and 1412px

**Comment by Daryl-L** [comment]
> > > The design draft has added the `Fee Rate` entrance.
> > > https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28879%3A28111&mode=design&t=OeRqt6vLAEdjb5sC-1 <img alt="image" width="990" src="https://private-user-images.githubusercontent.com/106060898/287494411-e1069f1a-b1a4-4584-84d2-dec3d353728b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0NDExLWUxMDY5ZjFhLWIxYTQtNDU4NC04NGQyLWRlYzNkMzUzNzI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGIzMmNjZDZhNDM5ZTQ0YmQzNDRjYjQwOTA4MWU4ZDNjOTFhZTY2YTAxYzUyYzUxODA0YjRmMDJhOTU1MmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihvoOCz2bp6qj_lZKHVgwvAYzVLNZDkBo5e3qClD7_o">
> > > <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/106060898/287494390-1683a3cf-8852-4abc-9487-c8d10d45d886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0MzkwLTE2ODNhM2NmLTg4NTItNGFiYy05NDg3LWM4ZDEwZDQ1ZDg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTQwMmYzZWYzYTM4YWEyNjY2NDFiZjkzN2IxYmQ4MjBiYzJmMjVhMTNjNDQ4ZmFmMzJjMjM5ZjdjZTc2NjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DfLXqa2pOVcwQKf-iFaAzjliiXNBE_nJbZ9avqzegBw">
> > 
> > 
> > Not enough for the screen size smaller than 1412px, while the margin size is 56px, consider redesign for the size of screen between 1024px and 1412px
> 
> If the space is insufficient, then use the mobile layout:
> 
> <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/106060898/287497721-e8390070-b33e-482d-aadc-ae5b64475f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTU0ODAsIm5iZiI6MTcwMTU5NTE4MCwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk3NzIxLWU4MzkwMDcwLWIzM2UtNDgyZC1hYWRjLWFlNWI2NDQ3NWY0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwOTE5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzZkZTE4MmJlMTIyMDFhZTA3OWVjMjE3MmZjNDc4NGU5MDA2YzUxZGNmNDRhYzVmOTZlYmI1MTIxMTU5MjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nH5tF1a_gFEe5oGTx7dvh50TcxYCPSTIoetz-lzdd9s">

From 1024 to 1412 screen, should it be mobile layout either?

**Comment by Kirl70** [comment]
> > > > The design draft has added the `Fee Rate` entrance.
> > > > https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28879%3A28111&mode=design&t=OeRqt6vLAEdjb5sC-1 <img alt="image" width="990" src="https://private-user-images.githubusercontent.com/106060898/287494411-e1069f1a-b1a4-4584-84d2-dec3d353728b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0NDExLWUxMDY5ZjFhLWIxYTQtNDU4NC04NGQyLWRlYzNkMzUzNzI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGIzMmNjZDZhNDM5ZTQ0YmQzNDRjYjQwOTA4MWU4ZDNjOTFhZTY2YTAxYzUyYzUxODA0YjRmMDJhOTU1MmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihvoOCz2bp6qj_lZKHVgwvAYzVLNZDkBo5e3qClD7_o">
> > > > <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/106060898/287494390-1683a3cf-8852-4abc-9487-c8d10d45d886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0MzkwLTE2ODNhM2NmLTg4NTItNGFiYy05NDg3LWM4ZDEwZDQ1ZDg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTQwMmYzZWYzYTM4YWEyNjY2NDFiZjkzN2IxYmQ4MjBiYzJmMjVhMTNjNDQ4ZmFmMzJjMjM5ZjdjZTc2NjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DfLXqa2pOVcwQKf-iFaAzjliiXNBE_nJbZ9avqzegBw">
> > > 
> > > 
> > > Not enough for the screen size smaller than 1412px, while the margin size is 56px, consider redesign for the size of screen between 1024px and 1412px
> > 
> > 
> > If the space is insufficient, then use the mobile layout:
> > <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/106060898/287497721-e8390070-b33e-482d-aadc-ae5b64475f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTU0ODAsIm5iZiI6MTcwMTU5NTE4MCwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk3NzIxLWU4MzkwMDcwLWIzM2UtNDgyZC1hYWRjLWFlNWI2NDQ3NWY0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwOTE5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzZkZTE4MmJlMTIyMDFhZTA3OWVjMjE3MmZjNDc4NGU5MDA2YzUxZGNmNDRhYzVmOTZlYmI1MTIxMTU5MjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nH5tF1a_gFEe5oGTx7dvh50TcxYCPSTIoetz-lzdd9s">
> 
> From 1024 to 1412 screen, should it be mobile layout either?

The design draft provides an example effect with a minimum width of 1024 for the PC end. If the actual page width ranges from 1024 to 1412 and there isn't sufficient space, then only the mobile layout can be used.

**Comment by Daryl-L** [comment]
> > > > > The design draft has added the `Fee Rate` entrance.
> > > > > https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28879%3A28111&mode=design&t=OeRqt6vLAEdjb5sC-1 <img alt="image" width="990" src="https://private-user-images.githubusercontent.com/106060898/287494411-e1069f1a-b1a4-4584-84d2-dec3d353728b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0NDExLWUxMDY5ZjFhLWIxYTQtNDU4NC04NGQyLWRlYzNkMzUzNzI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGIzMmNjZDZhNDM5ZTQ0YmQzNDRjYjQwOTA4MWU4ZDNjOTFhZTY2YTAxYzUyYzUxODA0YjRmMDJhOTU1MmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihvoOCz2bp6qj_lZKHVgwvAYzVLNZDkBo5e3qClD7_o">
> > > > > <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/106060898/287494390-1683a3cf-8852-4abc-9487-c8d10d45d886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0MzkwLTE2ODNhM2NmLTg4NTItNGFiYy05NDg3LWM4ZDEwZDQ1ZDg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTQwMmYzZWYzYTM4YWEyNjY2NDFiZjkzN2IxYmQ4MjBiYzJmMjVhMTNjNDQ4ZmFmMzJjMjM5ZjdjZTc2NjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DfLXqa2pOVcwQKf-iFaAzjliiXNBE_nJbZ9avqzegBw">
> > > > 
> > > > 
> > > > Not enough for the screen size smaller than 1412px, while the margin size is 56px, consider redesign for the size of screen between 1024px and 1412px
> > > 
> > > 
> > > If the space is insufficient, then use the mobile layout:
> > > <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/106060898/287497721-e8390070-b33e-482d-aadc-ae5b64475f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTU0ODAsIm5iZiI6MTcwMTU5NTE4MCwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk3NzIxLWU4MzkwMDcwLWIzM2UtNDgyZC1hYWRjLWFlNWI2NDQ3NWY0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwOTE5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzZkZTE4MmJlMTIyMDFhZTA3OWVjMjE3MmZjNDc4NGU5MDA2YzUxZGNmNDRhYzVmOTZlYmI1MTIxMTU5MjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nH5tF1a_gFEe5oGTx7dvh50TcxYCPSTIoetz-lzdd9s">
> > 
> > 
> > From 1024 to 1412 screen, should it be mobile layout either?
> 
> The design draft provides an example effect with a minimum width of 1024 for the PC end. If the actual page width ranges from 1024 to 1412 and there isn't sufficient space, then only the mobile layout can be used.

So do you mean that, if the page is larger than 1412, the margin size between each item is 56px, if ranges from 1024 to 1412, use mobile page, if 1024px, use smaller margin size in the draft, for the smaller, use mobile page?

**Comment by Kirl70** [comment]
> > > > > > The design draft has added the `Fee Rate` entrance.
> > > > > > https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28879%3A28111&mode=design&t=OeRqt6vLAEdjb5sC-1 <img alt="image" width="990" src="https://private-user-images.githubusercontent.com/106060898/287494411-e1069f1a-b1a4-4584-84d2-dec3d353728b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0NDExLWUxMDY5ZjFhLWIxYTQtNDU4NC04NGQyLWRlYzNkMzUzNzI4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOGIzMmNjZDZhNDM5ZTQ0YmQzNDRjYjQwOTA4MWU4ZDNjOTFhZTY2YTAxYzUyYzUxODA0YjRmMDJhOTU1MmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihvoOCz2bp6qj_lZKHVgwvAYzVLNZDkBo5e3qClD7_o">
> > > > > > <img alt="image" width="1561" src="https://private-user-images.githubusercontent.com/106060898/287494390-1683a3cf-8852-4abc-9487-c8d10d45d886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1NzU3ODIsIm5iZiI6MTcwMTU3NTQ4MiwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk0MzkwLTE2ODNhM2NmLTg4NTItNGFiYy05NDg3LWM4ZDEwZDQ1ZDg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwMzUxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTQwMmYzZWYzYTM4YWEyNjY2NDFiZjkzN2IxYmQ4MjBiYzJmMjVhMTNjNDQ4ZmFmMzJjMjM5ZjdjZTc2NjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DfLXqa2pOVcwQKf-iFaAzjliiXNBE_nJbZ9avqzegBw">
> > > > > 
> > > > > 
> > > > > Not enough for the screen size smaller than 1412px, while the margin size is 56px, consider redesign for the size of screen between 1024px and 1412px
> > > > 
> > > > 
> > > > If the space is insufficient, then use the mobile layout:
> > > > <img alt="image" width="1211" src="https://private-user-images.githubusercontent.com/106060898/287497721-e8390070-b33e-482d-aadc-ae5b64475f4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1OTU0ODAsIm5iZiI6MTcwMTU5NTE4MCwicGF0aCI6Ii8xMDYwNjA4OTgvMjg3NDk3NzIxLWU4MzkwMDcwLWIzM2UtNDgyZC1hYWRjLWFlNWI2NDQ3NWY0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwM1QwOTE5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzZkZTE4MmJlMTIyMDFhZTA3OWVjMjE3MmZjNDc4NGU5MDA2YzUxZGNmNDRhYzVmOTZlYmI1MTIxMTU5MjgzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nH5tF1a_gFEe5oGTx7dvh50TcxYCPSTIoetz-lzdd9s">
> > > 
> > > 
> > > From 1024 to 1412 screen, should it be mobile layout either?
> > 
> > 
> > The design draft provides an example effect with a minimum width of 1024 for the PC end. If the actual page width ranges from 1024 to 1412 and there isn't sufficient space, then only the mobile layout can be used.
> 
> So do you mean that, if the page is larger than 1412, the margin size between each item is 56px, if ranges from 1024 to 1412, use mobile page, if 1024px, use smaller margin size in the draft, for the smaller, use mobile page?

How was the margin of 56 determined? On the actual page, the margin for the 1024 page is 45px, and for 1412, it's 100px. Therefore, the navigation bar for the 1024 PC size was designed based on a 45px margin, and the maximum width was designed according to the actual page's 120px margin.
