### ISSUE TITLE
The menu bar text overlaps at a specific width.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#473]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/cda7076c-70cf-41e6-9306-7d813a46fd93)

**Comment by Sven-TBD** [comment]
When the whole page works for PC side, it should display the whole search box; and when it works for mobile side, it should hide all the labels, search box etc. And the minimal width for PC side, I guess we could try like 1024 pixel (cc @Kirl70 ), when the width is larger than 1024 pixels but not BIG enough, we could shorten the search box, and keep the distance of labels fixed.
<img width="1145" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/00178d01-990c-4f67-82e6-eab29acced9a">

[Reference](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5782-25307&mode=design&t=vfJBlLXIJkpTuLDQ-4)

**Comment by Kirl70** [comment]
The design draft has been supplemented with a navigation bar for the PC version with a minimum width (1024px).
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28879%3A28111&mode=design&t=vr5cfDirf7ONYMox-1
<img width="1010" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/5ab6de6c-3d22-4621-9f7e-06cd306f8480">

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/155
