### ISSUE TITLE
The Nervos DAO page in English

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#474]
<img width="300" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/97968803-49a3-4c42-bed3-d8bc185d699c">

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5782%3A26073&mode=design&t=vr5cfDirf7ONYMox-1
<img width="396" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/6933ca28-5681-4cbc-b59b-b4176cf77482">
