### ISSUE TITLE
Transaction details page with UI modifications for Cell Deps.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#475]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/e552c0a8-f762-417f-a207-c988734de65a)

**Comment by Kirl70** [comment]
Design Draft:
PC:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=6102%3A26855&mode=design&t=vr5cfDirf7ONYMox-1
<img width="1250" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/56494da6-c50c-4ceb-9a99-67463ca24924">
Mobile:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28876%3A27837&mode=design&t=vr5cfDirf7ONYMox-1
<img width="303" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/fbcbe8e2-8659-4952-a3a1-7e87e030c940">

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/146
