### ISSUE TITLE
An exception occurred when quickly switching block heights.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#477]
Quickly click the next block height button `>`, the block height data will be displayed starting from 0 instead of displaying the normal next block height data.
Looking at the data, we see that "0" is the starting block data, but it is often displayed when switching block heights, causing abnormalities in subsequent fast switching.
https://pudge.explorer.nervos.org/block/11193249
<img width="1258" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a72a9785-6396-453d-92c8-d39b254c67c2">

https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/95e2513f-c5e0-47f4-a25e-04a6c1b6cb97

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/159

**Comment by FrederLu** [comment]
Verified.
