### ISSUE TITLE
Page of an address that has a lot of transactions loads too long

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#478]
This issue comes from https://github.com/nervosnetwork/ckb-explorer-frontend/issues/1373

E.g. https://pudge.explorer.nervos.org/address/ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqwhc5slwl9w88nss0gu6ej23yeetl39lkcs28h94

**Comment by Keith-CY** [comment]
Please pay attention to this issue @zmcNotafraid @rabbitz

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1498
