### ISSUE TITLE
Increase pagination for inputs and outputs on the transaction details page

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#484]
EN
The backend interface has been optimized for pagination mode.
https://github.com/nervosnetwork/ckb-explorer/pull/1496
A pagination component also needs to be added to the details list on the "Transaction Details Page". When the number of Inputs/Outputs in a transaction exceeds the number displayed per page, a pagination bar should be displayed.

zh_CN
后端接口优化为分页模式
https://github.com/nervosnetwork/ckb-explorer/pull/1496

因此，
对应《交易详情页》的详情列表处也需要加上分页组件，在交易内Inputs/Outputs 数量超过每页面展示数量时，展示分页栏。

<img width="818" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/6ec99fc5-9033-4cba-9638-86d10fae7db2">

@Kirl70

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=6102%3A26855&mode=design&t=PVDXXqHnNNJ6Khfy-1
<img width="998" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/cbba61e2-d86e-432d-aed8-9ca4ea724af1">

**Comment by Sven-TBD** [comment]
Latest UI updated [here](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679-26337&mode=design&t=97RNJIoCJtWHak1z-4)

Please note that this alarm will only show when the number of transactions for the current address exceeds the default limit.

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/3ed457f3-f58e-41cd-9234-54ef854eed45)

**Comment by WhiteMinds** [comment]
I think it would be best to allow users to control the pagination quantity per page, such as 5 / 25 / 100.

If single-page unlimited quantity is not provided, it may also require a filtering feature. Otherwise, it can be challenging to find specific inputs/outputs when there are a large number of pages.

**Comment by zhangyouxin** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/177

**Comment by Kirl70** [comment]
Adjust according to [PRD](https://vs0cjf.axshare.com/?id=a35xg7&g=14&p=%E4%BA%A4%E6%98%93%E8%AF%A6%E6%83%85%E9%A1%B5input_output%E5%A2%9E%E5%8A%A0%E5%88%86%E9%A1%B5%E5%8A%9F%E8%83%BD):
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=6102%3A26855&mode=design&t=p7mSfysOos1fmA3B-1
<img width="1196" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/43f0f160-b2fd-42d3-80ec-b9b64c905f64">

**Comment by FrederLu** [comment]
Verified.
