### ISSUE TITLE
Some charts have fixed range even they are scaled

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#485]
E.g. https://explorer.nervos.org/charts/uncle-rate

https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/c9d8da4d-8a15-412f-9d15-1817e1cf204c

which makes it hard to read the details

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/172

**Comment by FrederLu** [comment]
Verified.
