### ISSUE TITLE
Adjust the number of transaction displays on the page

### ISSUE THREAD

**Issue by rabbitz** [Magickbase/ckb-explorer-public-issues#486]
#### Problem:

https://github.com/Magickbase/ckb-explorer-public-issues/issues/478
https://github.com/nervosnetwork/ckb-explorer/pull/1498

After optimization, it was found that the number of transactions for some addresses was still too large, resulting in slow query counting and paging, so I wanted to optimize the query speed by limiting the number of queries.

#### Possible Solution:

1. Need to determine the maximum number of query transactions
2. Determine how to add prompts to the page, such as https://github.com/nervosnetwork/ckb-explorer/pull/1498#issuecomment-1811764463 

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/990650/d1ddaf36-e46b-4b21-a985-5da00a3e775e)

@Danie0918 @Sven-TBD 

### Related issues

Frontend: #484

**Comment by Kirl70** [comment]
We can provide users with a prompt next to the pagination component, which only appears on address pages that exceed the maximum transaction count:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679%3A26337&mode=design&t=CxmNtkb7XiJUOSgW-1
<img width="980" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/004fed7c-5d2f-44a6-8f16-ff528ca03152">

**Comment by Keith-CY** [comment]
> We can provide users with a prompt next to the pagination component, which only appears on address pages that exceed the maximum transaction count: [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679%3A26337&mode=design&t=CxmNtkb7XiJUOSgW-1](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679%3A26337&mode=design&t=CxmNtkb7XiJUOSgW-1) <img alt="image" width="980" src="https://user-images.githubusercontent.com/106060898/284161520-004fed7c-5d2f-44a6-8f16-ff528ca03152.png">

cc @Danie0918 @Sven-TBD

**Comment by Sven-TBD** [comment]
I had a conversation with @rabbitz  , where I asked some questions. Assuming a limit of 500K transactions and a certain address has 501K transactions:

Q1: If I switch to the last page, does it show the last page of the 500K transactions, not the last page of all transactions?
A1: Yes, the overall query is limited to 500K transactions, so it will show the last page of these 500K.

Q2: If so, will the front end continue to query the next 500K transactions?
A2: No. The total number (501K) will be displayed on the page, but only 500K will be shown.

Q3: If I use time sorting, does it also display the time sorting of 500K transactions?
A3: When using time sorting, it sorts the first 500K transactions after the sorting.

Q4: If our limit is 30K and an address has 31K transactions , will the browser be aware of this situation?
A4: Yes, it's easy to know that. 

-----
cc @Keith-CY @Kirl70 

So I think it's also important to notify users especially when they're going to use the function of Sort by time and go to the Last page.

-----

So my suggestion is that :
1. We either  add a separate notification for features like Sort on this [UI](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679%3A26337&mode=design&t=CxmNtkb7XiJUOSgW-1)

2. Or we provide a dismissible alert for the detail pages of addresses with a large number of transactions.
<img width="546" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/9aedce4c-56be-4a29-a7fe-0cc160c46bb5">

**Comment by Keith-CY** [comment]
> I had a conversation with @rabbitz , where I asked some questions. Assuming a limit of 500K transactions and a certain address has 501K transactions:
> 
> Q1: If I switch to the last page, does it show the last page of the 500K transactions, not the last page of all transactions? A1: Yes, the overall query is limited to 500K transactions, so it will show the last page of these 500K.
> 
> Q2: If so, will the front end continue to query the next 500K transactions? A2: No. The total number (501K) will be displayed on the page, but only 500K will be shown.
> 
> Q3: If I use time sorting, does it also display the time sorting of 500K transactions? A3: When using time sorting, it sorts the first 500K transactions after the sorting.
> 
> Q4: If our limit is 30K and an address has 31K transactions , will the browser be aware of this situation? A4: Yes, it's easy to know that.
> 
> cc @Keith-CY @Kirl70
> 
> So I think it's also important to notify users especially when they're going to use the function of Sort by time and go to the Last page.
> 
> So my suggestion is that :
> 
> 1. We either  add a separate notification for features like Sort on this [UI](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679%3A26337&mode=design&t=CxmNtkb7XiJUOSgW-1)
> 2. Or we provide a dismissible alert for the detail pages of addresses with a large number of transactions.
> 
> <img alt="image" width="546" src="https://user-images.githubusercontent.com/85155313/284456804-9aedce4c-56be-4a29-a7fe-0cc160c46bb5.png">

This prompt `该地址交易数量超过页面展示最大数, 排序, 分页, 筛选, 将以 30k(页面展示最大数)进行` should be updated

1. The limit is not of counts on (per) page, it's of a single query;
2. Only pagination (of sorting, filtering) is affected by the limit, the algorithm of sorting/filtering is not impacted;
3. The prompt can be displayed only when `total amount > limit`, which means, the an exact count will be displayed without prompt when `total amount <= limit`

**Comment by Sven-TBD** [comment]
> > I had a conversation with @rabbitz , where I asked some questions. Assuming a limit of 500K transactions and a certain address has 501K transactions:
> > Q1: If I switch to the last page, does it show the last page of the 500K transactions, not the last page of all transactions? A1: Yes, the overall query is limited to 500K transactions, so it will show the last page of these 500K.
> > Q2: If so, will the front end continue to query the next 500K transactions? A2: No. The total number (501K) will be displayed on the page, but only 500K will be shown.
> > Q3: If I use time sorting, does it also display the time sorting of 500K transactions? A3: When using time sorting, it sorts the first 500K transactions after the sorting.
> > Q4: If our limit is 30K and an address has 31K transactions , will the browser be aware of this situation? A4: Yes, it's easy to know that.
> > cc @Keith-CY @Kirl70
> > So I think it's also important to notify users especially when they're going to use the function of Sort by time and go to the Last page.
> > So my suggestion is that :
> > 
> > 1. We either  add a separate notification for features like Sort on this [UI](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679%3A26337&mode=design&t=CxmNtkb7XiJUOSgW-1)
> > 2. Or we provide a dismissible alert for the detail pages of addresses with a large number of transactions.
> > 
> > <img alt="image" width="546" src="https://user-images.githubusercontent.com/85155313/284456804-9aedce4c-56be-4a29-a7fe-0cc160c46bb5.png">
> 
> This prompt `该地址交易数量超过页面展示最大数, 排序, 分页, 筛选, 将以 30k(页面展示最大数)进行` should be updated
> 
> 1. The limit is not of counts on (per) page. It's of a single query;
> 2. Only pagination (of sorting, filtering) is affected by the limit, the algorithm of sorting/filtering is not impacted. How about `500,000 entries that best meet the condition are listed.`
> 3. The prompt can be displayed only when `total amount > limit`, which means an exact count will be displayed without a prompt when `total amount <= limit`

So I think it should work like this:

- When the number of transaction of current address is below 500,000, nothing happens;
- However , when the number is over 500,000, it says "The number of transactions for this address exceeds the maximum display limit for a single **query** result. Sorting and filtering will be conducted with a limit of 500k (the maximum number for page display)", and "该地址交易数量超过单次**查询**展示结果最大数, 排序, 筛选, 将以 500k(页面展示最大数)进行" in Chinese.

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=5679%3A26337&mode=design&t=xXRH2MROpEpbbscz-1
<img width="1546" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/b7302974-883f-46c6-bc43-abfd25788853">
