### ISSUE TITLE
Add an aggregated api of `circulating supply` and `total supply` for market service

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#493]
Now there are 2 independent APIs for market service
- https://api.explorer.nervos.org/api/v1/market_data/circulating_supply
- https://api.explorer.nervos.org/api/v1/market_data/total_supply

They are returned as plain text instead of a json object which is adopted generally.

Recently there's another market service(https://discord.com/channels/956765352514183188/992443379461926982/1179463144666562712) going to use these two metrics but find extra work should be done to accept plain texts.

So we would combine these two fields into a new API in JSON format and deprecate the plain text ones graduately.

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1520

**Comment by Keith-CY** [comment]
The newly added statistical interface, https://api.explorer.nervos.org/api/v1/market_data/, returns the following values:

```json
{
  "total_supply": "43727809074.75965271",
  "circulating_supply": "43058213189.83983109"
}
```

The calculated values do not match the results from https://explorer.nervos.org/charts/total-supply. The latest results from the chart are:

```json
{
  "circulating_supply": "4305266777489155395.0",
  "burnt": "1215957903712838727.0",
  "locked_capacity": "10300077100000000"
}
```

According to the "?" hint next to the chart title:

```
The circulating supply is equal to the total supply minus the burnt part and the unvested part.
```

In the chart, `total supply = circulating_supply + burnt + unvested(locked)_capacity`, which should be `5531524758301994122`.
