### ISSUE TITLE
Optimize chart data presentation and interaction.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#496]
En
On the [Cell Count Chart](https://explorer.nervos.org/charts/cell-count) page, three types of data are provided, and users can click on the legend to adjust data display. So here're two tasks: 

- [ ] The frontend should change the default setting to "All + live cell"
- [ ] Some enhance interaction on the UX level should be done to remind users that they can interact to change the chart's display.

ZH-CN:
[Cell 数量图表](https://explorer.nervos.org/charts/cell-count)页面中提供了三种数据，且可以点击图例调整数据显示。需要:

- 前端将默认值改成“全部+live cell”
- UX层面强化交互，以提醒用户可以通过交互来更改图表的展示

**Comment by Keith-CY** [comment]
Initial data of some charts are optimized by https://github.com/Magickbase/ckb-explorer-frontend/pull/173

Please noted that only live cells are displayed by default, the count of total cells is much larger than that of live cells, so displaying them together dims live cells.

**Comment by Sven-TBD** [comment]
And we can optimize this by replace with checkbox or something like that. 
@Kirl70 [Here](https://vs0cjf.axshare.com/?id=w3bul9&g=14&p=_496_optimize_chart_data_presentation_and_interact)'s some suggestion. can you help with a new UI on this issue?

**Comment by Kirl70** [comment]
Design Draft(5-3--5-4):
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=30422%3A27593&mode=design&t=Lu0VeeGjmytQYzyZ-1
<img width="1562" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/6d4effce-f11e-4876-8a54-d31c4048f7e6">

**Comment by zmcNotafraid** [comment]
Because this chart is use third party, so change icon's ui is difficult.The chart api provides these icon.
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/61b978c1-f8f1-4710-b5fc-9d81972b3b51)
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/51d33cd9-b403-43c7-a28b-c898d04846f3)

**Comment by Keith-CY** [comment]
Verified on mainnet
