### ISSUE TITLE
Page style is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#499]
https://pudge.explorer.nervos.org/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type?page=1&size=10
The styles in `Deployed Cells` and `Referring Cells` are abnormal, please refer to UI adjustment.
<img width="1337" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/c1931897-4c58-4415-a90a-d3b9aa463d73">
<img width="1268" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a3a04827-be1a-41cd-9685-7c8ced99913c">

UI style：
<img width="961" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/124aee07-d10c-4fd5-b168-a710fe933a6d">
<img width="963" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/4bb817b6-a0ab-4b8f-bbea-64f9a2103495">

**Comment by Sven-TBD** [comment]
最好基于Master修改

It's supposed be edited based on Master branch.

**Comment by WhiteMinds** [comment]
This might be due to a time gap between the implementation of this feature's PR and the PR at https://github.com/Magickbase/ckb-explorer-frontend/pull/162, resulting in a conflict between the two.

I will handle this issue.

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/182

**Comment by Keith-CY** [comment]
<img width="970" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/cab6e844-0a62-414a-acb9-4f2736fe5709">

Page: https://explorer.nervos.org/script/0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95/data1

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/217

**Comment by FrederLu** [comment]
> PR: [Magickbase/ckb-explorer-frontend#217](https://github.com/Magickbase/ckb-explorer-frontend/pull/217)

Verified.
