### ISSUE TITLE
Add a chart of how many resources are distributed in the ecosystem

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#500]
Inspired by https://github.com/Magickbase/ckb-explorer-public-issues/issues/424 and https://github.com/Magickbase/ckb-explorer-public-issues/issues/492, a chart of how capacities are distributed in the ecosystem would be helpful for dapp users to find the most attractive applications built on CKB.

In contrast to the supply chart(https://explorer.nervos.org/charts/total-supply), the capacity-distribution chart reveals how many CKBs are occupied/invested into some specific applications. The amount of deposited capacities represents how valuable the application is.

Simply speaking, each dapp has its own capacity of referring cells(https://explorer.nervos.org/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type), which means how many capacities are in the app. The `referring capacities` can be ordered and visualized.

In addition to the capacity-distribution, the address account is another index of the activity of an app.

So my idea is to add such a chart
<img width="696" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/1a9b5b4e-508f-4f89-b91f-bef6a6767f81">

X-axis for capacity-distribution, Y-axis for address-distribution, size and color for other metrics.

**Comment by Danie0918** [comment]
Do we need to distinguish between types? Something like the following case.

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/122437870/2ec324ed-302b-43f3-a819-d5f1ae4b3a80)

**Comment by Keith-CY** [comment]
> Do we need to distinguish between types? Something like the following case.
> 
> ![image](https://private-user-images.githubusercontent.com/122437870/290437673-2ec324ed-302b-43f3-a819-d5f1ae4b3a80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1Mzg3ODEsIm5iZiI6MTcwMjUzODQ4MSwicGF0aCI6Ii8xMjI0Mzc4NzAvMjkwNDM3NjczLTJlYzMyNGVkLTMwMmItNDNmMy1hODE5LWQ1ZjFhZTRiM2E4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQwNzIxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjU5NWM0YWU4MTUyNzM5NDk3MWViZjQ0ZGU5M2JlYzkwMDhhZmI1N2I0ZDAzZGNkYzc5NDA3ZjBjOWU1Nzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3OCJtg6iVDYUbSbE6A2tAGtTVM6V0lzTjAQ8-qDyF2E)

Great if possible, but it's hard to distinguish types because in UTXO model, a transaction can includes various types of actions. E.g., a transaction can achieve `deposit`, `withdraw` and `send` simultaneously.

**Comment by Sven-TBD** [comment]
Can we color these spots by their type and size them by their capacity-distribution? 
Then, the X-axis could be used as transaction-distribution which means how many transactions take this kind of cell as input/output, and the Y-axis for address-distribution.

Once decide, I'll promote this issue.

**Comment by Keith-CY** [comment]
> Can we color these spots by their type and size them by their capacity-distribution?

> Then, the X-axis could be used as transaction-distribution which means how many transactions take this kind of cell as input/output, and the Y-axis for address-distribution.

Coloring the spots by their types is fine. But I prefer indexing capacity-distribution on the axis while revealing how active the dapp is in size/color because heatmap is more suitable for activity(in 24h or 1 month).
<img width="1642" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/d818773d-6195-440e-8f8e-ff00b9558f4b">

BTW, there was a metaphor that cells in CKB are the blocks of a zone, dapp are the building built on the block. The heatmap of traffic is quite vivid.

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1612

**Comment by zmcNotafraid** [comment]
X: address count
Y: capacity amount
hover: contract name
circle size: tx count
