### ISSUE TITLE
 There is an exception in the right alignment of data on the address page.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#504]
There is an exception in the right alignment of the `Capacity Change` data in the Lite list on the address page.
https://pudge.explorer.nervos.org/address/ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0zl2pwwzcx9jryfwq26lk0dcq4uhe49as2gh56a?layout=lite
<img width="1263" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/34796fa9-e0d3-431f-92a4-4d561be9715a">

https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/cd269477-10df-4b79-b837-e1cbc490a9a5

**Comment by Keith-CY** [comment]
It should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/175#issuecomment-1864684065 but has not been merged into testnet yet

**Comment by FrederLu** [comment]
> It should be fixed by [Magickbase/ckb-explorer-frontend#175 (comment)](https://github.com/Magickbase/ckb-explorer-frontend/pull/175#issuecomment-1864684065) but has not been merged into testnet yet

OK, the corresponding data is displayed normally on PR, and will be verified on testnet later.

**Comment by Keith-CY** [comment]
> > It should be fixed by [Magickbase/ckb-explorer-frontend#175 (comment)](https://github.com/Magickbase/ckb-explorer-frontend/pull/175#issuecomment-1864684065) but has not been merged into testnet yet
> 
> OK, the corresponding data is displayed normally on PR, and will be verified on testnet later.

Has it been verified on testnet?

**Comment by FrederLu** [comment]
> > > It should be fixed by [Magickbase/ckb-explorer-frontend#175 (comment)](https://github.com/Magickbase/ckb-explorer-frontend/pull/175#issuecomment-1864684065) but has not been merged into testnet yet
> > 
> > 
> > OK, the corresponding data is displayed normally on PR, and will be verified on testnet later.
> 
> Has it been verified on testnet?

<img width="1252" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/59faed40-cbc8-43c3-a246-6439cd0d1241">

Now the same data is displayed normally. 
Verified.
