### ISSUE TITLE
Support indexing xUDT

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#508]
Document of xUDT: https://blog.cryptape.com/enhance-sudts-programmability-with-xudt#heading-xudt-cell

Use case of xUDT: https://omiga-core.notion.site/Omiga-Inscritption-885f9073c1a6499db08f5815b7de20d7

### How to index an xUDT cell:

xUDT script info

| code hash | 0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb |
| hash type | type |
| dep type | code |

If a cell has a `type script` in which the `code hash` and `hash type` match values above, it's an xUDT cell

### How to display an xUDT

It depends on the business logic. In the use case of Omiga, an xUDT should be treated as an inscription, and displayed with inscription info as `max supply`, `total supply`, `mint limit`

**Comment by Keith-CY** [comment]
Please prioritize this because Omiga is expected to be online next week

**Comment by Keith-CY** [comment]
Address that used in tests of Omiga: https://pudge.explorer.nervos.org/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq9sfrkfah2cj79nyp7e6p283ualq8779rscnjmrj

**Comment by Keith-CY** [comment]
How to index Omiga cells

### Indexing inscription info

The inscription info is a cell containing specific `type script` and `data` fields

The `type script` refer to `inscription info contract` in cell deps by

```yaml
code_hash: type script of inscription info contract
hash_type: type
args: type id
```

So a `inscription info cell` can be located by the specific `code_hash & hash_type`

Once the cell is located, the inscription info can be parsed from its cell data with schema

```yaml
// general
decimal u8
len u8
name variable max 255
len u8
symbol variable max 255

udt_hash 32bytes
// extra
expected_supply 16bytes
mint_limit 16bytes
mint_status u8
```

### Indexing inscription cells

Each inscription cell is actually a cell containing a specific `type script`, the data structure of `type script` is as follows

```yaml
code_hash: xUDT type_hash
hash_type: type
args: owner_script_hash
```

The `code_hash` and `hash type` are determined by `xUDT script`, so the key matter is the `owner script hash`, which is the hash of a virtual script `owner script` existing in the witness field with format as follows

```yaml
code_hash: type hash of Omiga Inscription 
hash_type: type
args: type hash of Inscription_Info
```

Once the `inscription info` is detected, `inscription cells` can be located by their witnesses.

Steps are as follows
1. If the cell is an xUDT cell, it's possibly an Omiga inscription cell;
2. If the cell is generated with a witness, and hash of witness is equal to its type_script.args, it's possibly an Omiga inscription cell;
3. If the witness is an owner lock, which means, the `code_hash` is `type hash of Omiga Inscription contract`, `hash_type` is `type`, it's an Omiga inscription cell;
4. The inscription info could be located by `owner_lock.args`. It's expected to be synced before the inscription cell is found.

**Comment by Keith-CY** [comment]
General operations of Omiga inscription could be found at https://github.com/duanyytop/joyid-omiga/tree/master/src/inscription

**Comment by Sven-TBD** [comment]
[PRD](https://vs0cjf.axshare.com/?id=co0s6a&g=14&p=%E6%94%AF%E6%8C%81xudt%E5%B1%95%E7%A4%BA) here. 
We can check and develop it this week.

**Comment by Sven-TBD** [comment]
This whole feature should be split into some independent small features, which are : 

- [ ] Update transaction list component（交易列表组件更新）
- [ ] Menu bar and inscription list page（菜单栏与铭文列表页）
- [ ] Inscription details page（铭文详情页）
- [ ] Address details page（地址详情页）
- [ ] Scripts page（Scripts页面）
- [ ] Update related rules in the search box（搜索框内相关规则更新）

And the way how to update these features is list [here](https://vs0cjf.axshare.com/?id=co0s6a&g=14&p=%E6%94%AF%E6%8C%81xudt%E5%B1%95%E7%A4%BA)

**Comment by zmcNotafraid** [comment]
PR: 
https://github.com/nervosnetwork/ckb-explorer/pull/1557
https://github.com/nervosnetwork/ckb-explorer/pull/1560
