### ISSUE TITLE
Deleting information on the mobile terminal should not switch pages.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#509]
When the input box information is deleted, the mobile terminal will return to the page above.
Just delete the entered information and stay on the current page.

https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/4dad8f9f-fe90-47de-afb8-4ce91450e7a0

**Comment by Sven-TBD** [comment]
@zhangyouxin  And if possible ,please check this bug while handling the related one

**Comment by FrederLu** [comment]
PR link   https://github.com/Magickbase/ckb-explorer-frontend/pull/262

**Comment by FrederLu** [comment]
> PR link [Magickbase/ckb-explorer-frontend#262](https://github.com/Magickbase/ckb-explorer-frontend/pull/262)

Verified.
