### ISSUE TITLE
Mark xUDT script in frontend

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#510]
Description of xUDT: https://blog.cryptape.com/enhance-sudts-programmability-with-xudt#heading-xudt-cell

### Mainnet

TODO

### Testnet

Parameter | Value
-- | --
code_hash | 0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb
hash_type | type
tx_hash | 0xbf6fb538763efec2a70a6a3dcb7242787087e1030c4e7d86585bc63a9d337f5f
index | 0x0
dep_type | code

**Comment by Keith-CY** [comment]
xUDT is expected to be deployed on mainnet next week

**Comment by XuJiandong** [comment]
mainnet:

| parameter   | value                                                                |
| ----------- | -------------------------------------------------------------------- |
| `code_hash` | 0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95   |
| `hash_type` | `data1`                                                              |
| `tx_hash`   | 0xc07844ce21b38e4b071dd0e1ee3b0e27afd8d7532491327f39b786343f558ab7   |
| `index`     | `0x0`                                                                |
| `dep_type`  | `code`

**Comment by Keith-CY** [comment]
> mainnet:
> 
> parameter	value
> `code_hash`	0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95
> `hash_type`	`data1`
> `tx_hash`	0xc07844ce21b38e4b071dd0e1ee3b0e27afd8d7532491327f39b786343f558ab7
> `index`	`0x0`
> `dep_type`	`code`

Should be added by https://github.com/Magickbase/ckb-explorer-frontend/pull/194

**Comment by Keith-CY** [comment]
> mainnet:
> 
> parameter	value
> `code_hash`	0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95
> `hash_type`	`data1`
> `tx_hash`	0xc07844ce21b38e4b071dd0e1ee3b0e27afd8d7532491327f39b786343f558ab7
> `index`	`0x0`
> `dep_type`	`code`

Do we have a transaction includes xUDT reference so we can verify the update on mainnet

**Comment by FrederLu** [comment]
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/306af45f-5785-4a70-afcb-599ad618a1cc)

Confirm that the data is now displayed normally.
