### ISSUE TITLE
Add a Tab of Live cell on address detail page.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#515]
This is a sub task of issue [#19](https://github.com/Magickbase/ckb-explorer-public-issues/issues/19)
[Figma Link](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=31495:29631&mode=design&t=yZJTO5TQ5sYnY7Bg-1)

[PRD detail](https://vs0cjf.axshare.com/?id=vaj3jf&g=1&p=_19_display_live_cells_of_a_specific_address)

The original SUDT box should be replaced by a multi-tab box which includes SUDT, Inscription and Live Cells.

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/7ebd0f03-237a-4433-ae5f-f7c10b5f9f62)

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1610

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1624
```
## extra_info
{type: "ckb", capacity: "xxxx"}
{type: "udt",  symbol: ,
      amount: ,
      decimal: ,
      type_hash:,
      published: ,
      display_name: ,
      uan: , }
{type: "m_nft", class_name: "", token_id: nil, total: "" }
{
        type: "nrc_721",
        symbol: ,
        amount: ,
        decimal: "",
        type_hash:,
        published: 
        display_name: ,
        uan: "",
 }
  {
        type: "omiga_inscription",
        symbol: udt.symbol,
        name: udt.full_name,
        decimal: udt.decimal,
        amount: udt_amount,
  }
 { 
   type: "cota", 
   symbol: "", 
   amount: udt_amount, 
   decimal: "",
   type_hash:,
   published: "true", 
   display_name: "", 
   uan: "", 
   code_hash:
}
```

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/252

**Comment by zmcNotafraid** [comment]
`https://ckb-explorer-api-staging.magickbase.com/api/v1/address_live_cells/ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0dnd72kh63g08574r38qkyph2ewl9ummcfp6znk?page=7&page_size=10&sort=block_timestamp.desc`
Got 504 error
