### ISSUE TITLE
Add a Tab of Inscription  on address detail page.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#516]
This is a sub task of [issue #512](https://github.com/Magickbase/ckb-explorer-public-issues/issues/508)

[PRD detail](https://vs0cjf.axshare.com/?id=co0s6a&g=14&p=%E6%94%AF%E6%8C%81xudt%E5%B1%95%E7%A4%BA&sc=3)

The original SUDT box should be replaced by a multi-tab box which includes SUDT, Inscription and Live Cells.

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=32165%3A53065&mode=design&t=PcoAqGqUs5n8wDpV-1
<img width="1204" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/57faf0c5-1a6a-499b-9838-0c92e3adfe7a">

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/208

**Comment by Daryl-L** [comment]
I think two points I need to confirm.
1. In the PRD, the name is sUDT, but in the design draft, the name of tab is User Defined Token, which to choose?
2. The name list of mint status for Chinese

**Comment by FrederLu** [comment]
> [Magickbase/ckb-explorer-frontend#208](https://github.com/Magickbase/ckb-explorer-frontend/pull/208)

Verified.
