### ISSUE TITLE
Add Inscription details page（铭文详情页）

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#517]
This issue is a sub task of #508 which aiming to support should the details of an Inscription.

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=32176%3A55124&mode=design&t=PcoAqGqUs5n8wDpV-1<img width="1107" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/c4d202c0-5d9f-49ec-933f-ffa3737a1623">

**Comment by Keith-CY** [comment]
We have defined 2 URLs for 2 kinds of inscription detail page

1. Inscription collection page: `/inscription/${inscription_collection_id}`. In the omiga case, `inscription_collection_id` is the `type script hash` of omiga info cell;
2. Inscription item page: `/inscription/${inscription_item_id}`. In the omiga case, `inscription_item_id` is the `type script hash` of the omiga item cell. It's a child of xUDT cell.

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/196
