### ISSUE TITLE
Adjust Menu bar and add inscription list page（菜单栏与铭文列表页）

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#518]

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=32169%3A54451&mode=design&t=PcoAqGqUs5n8wDpV-1
<img width="1136" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/f40cb01e-2f27-4abe-b8b2-b77762b4f255">

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/196
