### ISSUE TITLE
Enhance the UX of search box

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#519]
Search box will show all of result by different types together, and the "by Name" and "by ID" are no longer a necessary option but just a location where the specific type is. 

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/91e39c84-8f68-48c6-a9a3-14cc9d10c9d8)

**Comment by Sven-TBD** [comment]
PRD：https://vs0cjf.axshare.com/?id=908ssd&g=14&p=%E6%90%9C%E7%B4%A2%E4%BC%98%E5%8C%96%E8%AF%B4%E6%98%8E&sc=3

BTW，A **Not Found Page** is also needed when there is no result while searching a String without click on the dropbox.

**Comment by Keith-CY** [comment]
How is it going @PainterPuppets

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1790

```ruby
# single_query
GET /api/v1/suggest_queries?q=?

# aggregate_query
GET /api/v1/suggest_queries?q=?&filter_by=0
```

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/990650/37be0ebe-da49-4d5e-9a4b-7b4ea41016c8)

**Comment by PainterPuppets** [comment]
> @PainterPuppets How‘s it going with this feature

Just noticed that the backend is ready, I'll start working on this issue today and expect it to take 2 days

**Comment by Keith-CY** [comment]
> > @PainterPuppets How‘s it going with this feature
> 
> Just noticed that the backend is ready, I'll start working on this issue today and expect it to take 2 days

How is it going

**Comment by PainterPuppets** [comment]
> [nervosnetwork/ckb-explorer#1790](https://github.com/nervosnetwork/ckb-explorer/pull/1790)
> 
> ```ruby
> # single_query
> GET /api/v1/suggest_queries?q=?
> 
> # aggregate_query
> GET /api/v1/suggest_queries?q=?&filter_by=0
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/990650/322707297-37be0ebe-da49-4d5e-9a4b-7b4ea41016c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMjcyNTMsIm5iZiI6MTcxNTEyNjk1MywicGF0aCI6Ii85OTA2NTAvMzIyNzA3Mjk3LTM3YmUwZWJlLWRhNDktNGQ1ZS05YTRiLTdiNGVhNDEwMTZjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwMDA5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2FkZWQ4ZjM1Y2IzOTIxMDkwMTcxZDhkMzkxODE4M2IwOWVkZjhhMTAzY2I0NjFiNGM2OWE2Y2MwMGYzMDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jiwJTf04pSLlFj4jtNH0qMkhS03LCxakxxZ0eTeLAfk)

Hi @rabbitz 
I noticed that the search currently returns `token_collection` type data, but there's no `typehash` field  in the return data, so there's no way to make a jump
Do we have any plans to add the this fields?

<img width="763" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/22258327/3adcc524-0234-4039-b54a-b58a644d4726">

**Comment by rabbitz** [comment]
@PainterPuppets 

https://github.com/nervosnetwork/ckb-explorer/pull/1838

Field `sn` was added to token collection response.

**Comment by PainterPuppets** [comment]
> @PainterPuppets
> 
> [nervosnetwork/ckb-explorer#1838](https://github.com/nervosnetwork/ckb-explorer/pull/1838)
> 
> Field `sn` was added to token collection response.

Accessing https://testnet-api.explorer.nervos.org/api/v1/suggest_queries?q=Spore&filter_by=0 doesn't seem to have the `sn` field returned, which url should I use?

**Comment by Keith-CY** [comment]
> > @PainterPuppets
> > [nervosnetwork/ckb-explorer#1838](https://github.com/nervosnetwork/ckb-explorer/pull/1838)
> > Field `sn` was added to token collection response.
> 
> Accessing [testnet-api.explorer.nervos.org/api/v1/suggest_queries?q=Spore&filter_by=0](https://testnet-api.explorer.nervos.org/api/v1/suggest_queries?q=Spore&filter_by=0) doesn't seem to have the `sn` field returned, which url should I use?

Please check this @rabbitz

**Comment by PainterPuppets** [comment]
Hi @rabbitz  
There are some search keywords that do not seem to have any results at the moment, like:

Btc address: tb1qwq82nch2wc0jtymavfv2cxsju9trghn0ykhqx8
<img width="770" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/22258327/3927f40d-441f-4b67-8086-90e6fceda992">

BTC Tx :4ea970151577aff9f134bd50ce666d304c979f8d204c4fa8f4cd0a1bf7c3bbd1
<img width="745" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/22258327/e36a7191-2e4e-4a22-8e68-2b28141357d9">

.bit did: test.bit
<img width="654" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/22258327/9e1ca385-ef73-4cd4-9f5b-78aacc579147">

Can you check it out for me?

**Comment by Keith-CY** [comment]
> Hi @rabbitz There are some search keywords that do not seem to have any results at the moment, like:
> 
> Btc address: tb1qwq82nch2wc0jtymavfv2cxsju9trghn0ykhqx8 <img alt="image" width="770" src="https://private-user-images.githubusercontent.com/22258327/330349747-3927f40d-441f-4b67-8086-90e6fceda992.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzYwMzEsIm5iZiI6MTcxNTY3NTczMSwicGF0aCI6Ii8yMjI1ODMyNy8zMzAzNDk3NDctMzkyN2Y0MGQtNDQxZi00YjY3LTgwODYtOTBlNmZjZWRhOTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA4MzUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1YTU4ZGI2YWFhOTA2ZTBjNzQ0MGJmMDAyMWNmYzFjYmIxNjM5YWM0OTczMmM3YzllMDgwMWRiZjU2NmIwMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z4HcD6nU5FLh5m2ymTxizdyBYXhUQPzzzo__6eiPmMo">
> 
> BTC Tx :4ea970151577aff9f134bd50ce666d304c979f8d204c4fa8f4cd0a1bf7c3bbd1 <img alt="image" width="745" src="https://private-user-images.githubusercontent.com/22258327/330349636-e36a7191-2e4e-4a22-8e68-2b28141357d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzYwMzEsIm5iZiI6MTcxNTY3NTczMSwicGF0aCI6Ii8yMjI1ODMyNy8zMzAzNDk2MzYtZTM2YTcxOTEtMmU0ZS00YTIyLThlNjgtMmIyODE0MTM1N2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA4MzUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4MTY0NmY2ZGQ0MzRjM2M4NGZhMzZiZDkwYjBjMDA3MDJmYTcwYzhiNzhiMjBhZmM0ZjE5NmRlNDJkMWY5M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bknJZdEsKEEPhcpNGby6qxFBUlsN8uYhvzrgxuDxF_M">
> 
> .bit did: test.bit <img alt="image" width="654" src="https://private-user-images.githubusercontent.com/22258327/330349573-9e1ca385-ef73-4cd4-9f5b-78aacc579147.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NzYwMzEsIm5iZiI6MTcxNTY3NTczMSwicGF0aCI6Ii8yMjI1ODMyNy8zMzAzNDk1NzMtOWUxY2EzODUtZWY3My00Y2Q0LTlmNWItNzhhYWNjNTc5MTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA4MzUzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YWNmNWI1NzMzOGM5MzUwMmM0MmVhZWI4YmFlZjk4YTBlY2Y5ZWExMzNkODg2YWU5ZjQyNTI1YTg4YzNmODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tjx0rVz44Y22dK_yVXsNbTRAwIQ2Y48_PBoMpIziQzc">
> 
> Can you check it out for me?

`.bit` was not supported in the backend, so it's calling .bit indexer directly at https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/components/Search/index.tsx#L218-L227

**Comment by FrederLu** [comment]
Verified.
