### ISSUE TITLE
The mobile style needs to be modified.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#523]
1、The style on the inscription list page needs to be modified.

<img width="468" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/f5e44dbb-c2d1-49ce-9d5c-9e86814449f5"><img width="420" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/6a99fca8-e3a4-4c89-8476-faacf8dfbce6">

---
2、After the export button is hidden, redundant modules will be displayed at the bottom.
<img width="314" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/9def6286-facb-4e87-b98c-3ef195809567"><img width="312" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/a74ce113-ae0a-489b-ba2b-a237671d9c93">

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/245
