### ISSUE TITLE
The Inscription on the address page is blank.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#525]
https://pudge.explorer.nervos.org/address/ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq9cp3x9dky0u2c3n8mw8ldukkuv3w9mpn540s542
<img width="1305" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/a0358208-8060-49b5-a740-11f818aa6948">

**Comment by Sven-TBD** [comment]
I checked this URL, and I didn't see the same situation, is it fixed already? @FrederLu @Daryl-L

**Comment by FrederLu** [comment]
> I checked this URL, and I didn't see the same situation, is it fixed already? @FrederLu @Daryl-L

I just saw that the page display has returned to normal.
I will change the issue status.
