### ISSUE TITLE
Add a warning icon for same-name Inscriptions which are deployed later.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#527]
A warning icon should be mark ahead of the Inscriptions which are deployed later than the first one who share the same name.

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=32169%3A54451&mode=design&t=Ng942kf7SQ9q9pW6-1
<img width="382" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/0973c3fd-9dae-427d-9a26-69b6e3c64074">

**Comment by Sven-TBD** [comment]
@Keith-CY Hi Chen, In which situation should explorer show the mark icon? Same name or same Symbol?

**Comment by Sven-TBD** [comment]
Communicated with Chen , the tip should show up when the two or more inscriptions share one same name. So the tip should be "This inscription is a duplicate with an earlier release of the same symbol." cc @zmcNotafraid

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1649

**Comment by zmcNotafraid** [comment]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/17538c6d-7656-4e22-a9e3-0005c8650501)
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/68d27ccc-3b0b-44c4-bc5b-5f3ec9797511)

**Comment by zmcNotafraid** [comment]
Before we use udt's  published attribute to mark a omiga inscription is repeated symbol or not. But the published value was used in other code and confused us. So we add a new attribute in omiga inscription info table to check omiga inscription was repeated or not.
- - -
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1675
