### ISSUE TITLE
View Original Inscriptions.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#528]

**Comment by Sven-TBD** [comment]
Update：

UI：https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=32176-55124&mode=design&t=jkTIWc8ZcrTrfH1v-4

PRD：https://vs0cjf.axshare.com/?id=3ggqs0&g=14&p=inscription____1&sc=3

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/236
