### ISSUE TITLE
The script page switches tab links abnormally.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#529]
The page jump is type and should jump to data1.
<img width="1088" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/86c8eb77-a11b-431f-b96c-4bddd51c2a52">

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/c56e6c14-5340-494b-92f3-86d9e36ffde4)

The link displayed when switching `tab` is incorrect.
Now jump to `https://explorer.nervos.org/script/0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95/type/deployed_cells?page=1&size=10`

Need similar link
`https://explorer.nervos.org/script/0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95/data1/deployed_cells?page=1&size=10`

**Comment by Keith-CY** [comment]
Should be fixed by https://github.com/Magickbase/ckb-explorer-frontend/pull/253

**Comment by FrederLu** [comment]
> Should be fixed by [Magickbase/ckb-explorer-frontend#253](https://github.com/Magickbase/ckb-explorer-frontend/pull/253)

Verified.
