### ISSUE TITLE
The `Show Rows` selection will be obscured.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#533]
The options that appear when modifying Show Rows on the output are blocked. Of course, you can manually slide the page upward at this time, but it is not very user-friendly.
https://ckb-explorer-frontend-in-magickbase-repo-1dml98b50-magickbase.vercel.app/transaction/0x1d320432dbe19599eb752d835be9877a596870b46980dd68edad3abd1fd10111
<img width="1404" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/89db34d2-bba4-43bf-b528-bb446bf1442d">

**Comment by PainterPuppets** [comment]
> Assigned this to @PainterPuppets based on https://github.com/Magickbase/ckb-explorer-public-issues?tab=readme-ov-file#project-modules-and-responsible-persons. Please have a look at this and provide the estimated Start and end date.

Ok, I'll check it

**Comment by FrederLu** [comment]
Verified.
