### ISSUE TITLE
`occupied` calculations need to be optimized.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#538]
<img width="802" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/90e5e269-1232-4130-92a3-006dc28712ad">
<img width="793" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/9fd99cb0-3a81-4f77-9462-94434e819994">

https://pudge.explorer.nervos.org/address/ckt1qpyn2yx4f6q4vydxgwhe0ddvjwlmk3wac24wpukuala0xsytfl8u6q2tqqqqqyqqqqqrqqqqqqcsqqqq6gmkrvmyyyrntsvuvptp6gflkwl2ut7kzun5xuv7la5jpcpqh2kqz9sqqqqqqq20kdflh25ymakugpf2z32t3lx0glhy5tgqqqqqqqqqqqqqqqqqqqf2qheqqqq73n2a

There is a secondary calculation `occupied` phenomenon here.
When the transaction is stored in the database in `Pending`, it will be calculated once as occupied, and then the status will change to committed and calculated again.  When data is pending, it may be that the data has not been obtained yet.

**Comment by rabbitz** [comment]
The error might be occurring during the update of `cell_datum`. When calculating the `occupied_capacity` of the output cell, the bytesize of cell_datum might not have been updated yet, resulting in it being 0, which is exactly 16 bytes less.

https://github.com/nervosnetwork/ckb-explorer/blob/f65e75b39af3015cab0fd752888dc2b1d3f98eaf/app/jobs/import_transaction_job.rb#L99-L111

https://github.com/nervosnetwork/ckb-explorer/blob/8bb8267fad258bbe1d000067ad27065180de99bf/app/models/cell_output.rb#L175-L178

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1630

**Comment by FrederLu** [comment]
> [nervosnetwork/ckb-explorer#1630](https://github.com/nervosnetwork/ckb-explorer/pull/1630)

Verified.
