### ISSUE TITLE
Contact email of existent sudt should be updated to ckb-explorer@magickbase.com

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#539]
The feature of `submit token info through API`(https://github.com/Magickbase/ckb-explorer-public-issues/issues/374) is going to be online and a field `contact email` is required when users try to update info of an existent token.

But those submitted by e-mail don't have a contact email, which blocks them being updated on the page.

Here I suggest setting all existent sudts with a contact email `ckb-explorer@magickbsae.com`, the one that belongs to the project maintainer.

By doing so, the information can be updated by the maintainer without updating database directly.

**Comment by zmcNotafraid** [comment]
Finished.
