### ISSUE TITLE
API to fetch txs times out

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#54]
https://testnet-api.explorer.nervos.org/api/v1/address_transactions/ckt1qq3ylcn557cqtnffnaez8tag4d97yngdw4x0je2algayedyh7rejkqv9v9dswes4x97gpu2vhtt9q8hvqvwd28qrvj8gk?page=1&page_size=10

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/177269791-ab20e4d9-715f-4a34-b88c-8ef7468e706e.png)

**Comment by ShiningRay** [comment]
该地址上有约10万笔交易，因此可能导致SQL执行较慢
经查验相关 SQL  会使用错误的索引进行扫描

```sql
SELECT "ckb_transactions"."id", "ckb_transactions"."tx_hash", "ckb_transactions"."block_id", "ckb_transactions"."block_number", "ckb_transactions"."block_timestamp", "ckb_transactions"."is_cellbase", "ckb_transactions"."updated_at" FROM "ckb_transactions" WHERE (contained_address_ids @> array[6510]::bigint[]) ORDER BY block_timestamp desc nulls last, id desc
```

SQL中 WHERE 和 ORDER 无法分别使用不同索引，考虑新建索引或者是将contained address ids这个复合字段单独建表

**Comment by ShiningRay** [comment]
由于 `ckb_transactions` 表的相关字段是 `contained_address_ids` 是数组，在其上建立的索引属于 gin 索引，无法和单纯的整数进行索引，改成了使用中间表进行相关索引

**Comment by ShiningRay** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/955/files

**Comment by ShiningRay** [comment]
https://ckb-explorer.staging.layerview.io/address/ckt1qq3ylcn557cqtnffnaez8tag4d97yngdw4x0je2algayedyh7rejkqv9v9dswes4x97gpu2vhtt9q8hvqvwd28qrvj8gk

**Comment by Keith-CY** [comment]
@FrederLu please have a test

**Comment by FrederLu** [comment]
https://ckb-explorer.staging.layerview.io/address/ckt1qq3ylcn557cqtnffnaez8tag4d97yngdw4x0je2algayedyh7rejkqv9v9dswes4x97gpu2vhtt9q8hvqvwd28qrvj8gk

@Keith-CY @ShiningRay 
The above url request is now normal and no longer timed out, and the verification is passed. However, when using the format?page=1&page_size=10, it is found that only 10 pieces of data are displayed on the page when the page_size is modified to 20 or 30.

**Comment by Keith-CY** [comment]
It seems that `page_size` doesn't work on this page, maybe by design because it's not working on mainnet production too https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq22xdj8q4jdql98qkdhnqzgrsk4nqyavdcratvu9?page_size=2

But better to be confirmed in the code by @ShiningRay

**Comment by Keith-CY** [comment]
It is a bug that `page_size` doesn't work since it's handled in the code. We should add a new issue about it and mark this issue passed @FrederLu
