### ISSUE TITLE
Refactor display_outputs_count and display_inputs_count

### ISSUE THREAD

**Issue by rabbitz** [Magickbase/ckb-explorer-public-issues#541]
When the number of cells in a transaction is substantial, calculating through `display_inputs.count` and `display_outputs.count` is too slow, leading to API requests timing out.

https://explorer.nervos.org/address/ckb1qyqgeh7kh2m8erhq44ss8lkhcsmdtcu5287sqzwcxn

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1621

**Comment by FrederLu** [comment]
> [nervosnetwork/ckb-explorer#1621](https://github.com/nervosnetwork/ckb-explorer/pull/1621)

Verified.
