### ISSUE TITLE
Display spore id in hex string format

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#546]
https://a-simple-demo.spore.pro/spore/0xfa5c0998f04daf57d5804280edd37718d80f4c0f3ad1419f5195a291e8db9c9a

It's displayed in hex string format in Spore demo
<img width="896" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/7811e878-9b1b-4986-80fd-0caa8873714a">

while it's transformed into an integer on Explorer
https://pudge.explorer.nervos.org/nft-info/0xbcd8f0b0a69759e297a1c4992fc4b3f29e2a53b07fcb3152f684913f631d5bd0/113240828314712130702306823095114940240734532880443248983913725567253488573594

<img width="1260" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/e6a85844-e166-43e0-bee8-001f451c85b4">

It's expected to be displayed in the same format

**Comment by FrederLu** [comment]
Verified.
