### ISSUE TITLE
Support display spore item with no cluster

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/ckb-explorer-public-issues#548]
Spore support mint cell with no cluster. But in explorer needs to display item under a collection.

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/commit/822b82f94c97a26b9d11b5ef8b7506b2365d1e37
In this code it will remove no creator token_collection. So no cluster collection was removed by it. It's a mistake.

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1643
https://github.com/nervosnetwork/ckb-explorer/pull/1645

**Comment by FrederLu** [comment]
Verified.
