### ISSUE TITLE
Layout for mobile is not correct

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#55]
![image](https://user-images.githubusercontent.com/7271329/177289784-e558999c-713f-49fb-925f-4ef1891b244f.png)
![image](https://user-images.githubusercontent.com/7271329/177289898-b9698640-71a5-4a7d-b785-8bb83cddf6f6.png)
![image](https://user-images.githubusercontent.com/7271329/177289950-7bf79039-f51b-4607-95dc-83dc2c1a6244.png)

**Comment by Keith-CY** [comment]
Hotfixed by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/fd9b0988c1dbf9479bd18f7649381b4a74026798

**Comment by FrederLu** [comment]
![Image](https://user-images.githubusercontent.com/25676576/177460762-5fe12a2f-a40b-4244-8c5c-16ab28c4bc11.png)



![Image](https://user-images.githubusercontent.com/25676576/177460819-34c18362-a1e8-4086-8b7d-06ea3e9c2e6a.png)


The hash display style has been fixed. It has been verified on the main network https://explorer.nervos.org/ and the test network https://pudge.explorer.nervos.org/ using an android phone, and the display is normal.

**Comment by Cedar67** [comment]
All three of the above pages are working properly.

There is a display exception at the following page size: @Keith-CY 

https://explorer.nervos.org/nervosdao?tab=depositors

<img width="576" alt="image" src="https://user-images.githubusercontent.com/64718893/177472296-6e7c6ad4-c761-41f6-b7a7-428b2f1bec02.png">

**Comment by Keith-CY** [comment]
> The second and third pages above show up fine now. The first page is not pretty, but it does not affect the correct identification of information. And it only reappears at the iPad screen size. <img alt="image" width="575" src="https://user-images.githubusercontent.com/64718893/177473314-914b1b59-083a-4ffd-a175-0bc520ad1797.png">
> 
> **`There is a display exception at the following page size:`** @Keith-CY
> 
> [explorer.nervos.org/nervosdao?tab=depositors](https://explorer.nervos.org/nervosdao?tab=depositors)
> 
> <img alt="image" width="576" src="https://user-images.githubusercontent.com/64718893/177472296-6e7c6ad4-c761-41f6-b7a7-428b2f1bec02.png">

Got it, but we're going to keep it as the first screenshot shows because it's not serious in usage.
