### ISSUE TITLE
The detial information of output needs to be modified.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#550]
<img width="1300" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/572e30cb-7e09-419e-84a0-ded30888701e">
<img width="1251" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/363b1891-0d7d-48c0-a678-d0a3079343f6">

The output `detial` information of pending tx displays abnormally.If there is `Spore` information that needs to be displayed as shown in screenshot 2, it cannot just be displayed`CKB Capacity`.

**Comment by zmcNotafraid** [comment]
For pending tx, we only save tx's raw info from rpc, no processing of information
