### ISSUE TITLE
`Holder/Minted` information modifies `Holders/Items`.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#554]
<img width="1227" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7b9b85f3-0fbf-4b34-9986-c8c88cba6a46">
<img width="1205" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7156ec62-9a8c-4f67-be79-5837873ca02a">
<img width="1208" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/be0d1ca7-bc26-442b-8a2a-19170e0aecf8">
<img width="1216" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/0b359dae-3fbc-4fe8-ae3d-3ed2a55c7fda">

The `Holder/Minted` information under `NFT Collection` is modified to `Holders/Items`.

**Comment by zmcNotafraid** [comment]
Current minted value was from database's items_count attribute.The items_count was token item's record's count. When a tx's outputs contain a nft cell, it will create an item record and items_count + 1.So when you transfer an nft, the items_count + 1 either. There no code to decrease items_count.So when you burn a nft , the items_count will not changed.

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1665

**Comment by FrederLu** [comment]
> [nervosnetwork/ckb-explorer#1665](https://github.com/nervosnetwork/ckb-explorer/pull/1665)

https://pudge.explorer.nervos.org/nft-collections/0xcf9e0cdbd169550492b29d3d1181d27048ab80126b797840965d2864607a892d

<img width="1242" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/9c002c29-e29d-4758-b741-ef041e55f027">

It was found that there is a problem in `Unique items` that the data does not conform to `minted = mint - burn`.

**Comment by FrederLu** [comment]
Verified.
