### ISSUE TITLE
Cell list on transaction page is scrollable which is unexpected

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#559]
https://explorer.nervos.org/transaction/0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c

![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/0517457f-a583-4a1b-8740-fcd9833991fe)

**Comment by Keith-CY** [comment]
https://mainnet-api.explorer.nervos.org/api/v2/ckb_transactions/0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c/display_outputs?page=1&page_size=10

`Page_size` doesn't work when the transaction is in block 0. The list should be paginated before the `scroll` is removed. cc @Sven-TBD

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/341

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1886

**Comment by Keith-CY** [comment]
Verified

https://explorer.nervos.org/transaction/0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c

<img width="1314" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/1885ff28-b537-443c-bfe1-32bf1b47c4c0">
