### ISSUE TITLE
SUDT page's addresses should be long addresses.

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/ckb-explorer-public-issues#56]
https://explorer.nervos.org/sudt/0x38928268eaffd58e25605a923cf61602e914cb8365ba00131ec0bc004cc753d1

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/12881040/177440064-1a53674e-db41-46d0-a3a4-154ca73b05c3.png">

**Comment by yanguoyu** [comment]
@Keith-CY Should we need to add a switch to show long or short addresses for this page?

**Comment by Keith-CY** [comment]
> @Keith-CY Should we need to add a switch to show long or short addresses for this page?

I think the new format is fine on pages other than transaction detail, user can visit the tx if deprecated address is necessary

**Comment by yanguoyu** [comment]
That's fine for transaction addresses. What about the issuer's address?

**Comment by Keith-CY** [comment]
> That's fine for transaction addresses. What about the issuer's address?

Keep it in the new format too, there's a link to its deprecated address page on its info page, just next to its new format address

**Comment by yanguoyu** [comment]
Got it.

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1010

**Comment by FrederLu** [comment]
@yanguoyu 
<img width="1329" alt="image" src="https://user-images.githubusercontent.com/25676576/178203629-1a63edaa-4df7-478a-a123-10df502e1317.png">
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/25676576/178203995-573804b6-e915-4dbf-ab64-f45b868e5535.png">

The address in the screenshot on mainnet does not show the latest address.

**Comment by yanguoyu** [comment]
> @yanguoyu <img alt="image" width="1329" src="https://user-images.githubusercontent.com/25676576/178203629-1a63edaa-4df7-478a-a123-10df502e1317.png"> <img alt="image" width="1063" src="https://user-images.githubusercontent.com/25676576/178203995-573804b6-e915-4dbf-ab64-f45b868e5535.png">
> 
> The address in the screenshot on mainnet does not show the latest address.

User can visit the tx if deprecated address is necessary. The tx page has switch button to show long address

**Comment by FrederLu** [comment]
> > @yanguoyu <img alt="image" width="1329" src="https://user-images.githubusercontent.com/25676576/178203629-1a63edaa-4df7-478a-a123-10df502e1317.png"> <img alt="image" width="1063" src="https://user-images.githubusercontent.com/25676576/178203995-573804b6-e915-4dbf-ab64-f45b868e5535.png">
> > The address in the screenshot on mainnet does not show the latest address.
> 
> User can visit the tx if deprecated address is necessary. The tx page has switch button to show long address

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/25676576/179652217-2ebf50e9-3507-4650-9c12-0c257fe2ccf0.png">

The latest address is now displayed on the mainnet. 
Verified.
