### ISSUE TITLE
Switching tabs should not change the page language style.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#560]
After clicking the `Depositors` tab in `Nervos DAO`, the language of the page will be changed (from Chinese to English), which should continue the language before the switch.

https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7f91ee25-9956-4de4-847f-cc0b2a6581ee

**Comment by Keith-CY** [comment]
Filtering data in the list, e.g. https://explorer.nervos.org/zh/nervosdao changes the language too.

**Comment by Keith-CY** [comment]
I've just pushed a  hotfix(https://github.com/nervosnetwork/ckb-explorer-frontend/commit/a82d8d783294529afab3de65a5f4ae088e513523) to production to fix this issue

but my pc is out of battery, @FrederLu please do me a favor to check if all links are fixed

**Comment by FrederLu** [comment]
> I've just pushed a hotfix([nervosnetwork/ckb-explorer-frontend@a82d8d7](https://github.com/nervosnetwork/ckb-explorer-frontend/commit/a82d8d783294529afab3de65a5f4ae088e513523)) to production to fix this issue
> 
> but my pc is out of battery, @FrederLu please do me a favor to check if all links are fixed

This issue has been fixed after verification on `Testnet` and `Mainnet`.   
Verified.
