### ISSUE TITLE
Show spore cluster id in spore info page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#567]
The url of Spore cluster was identified by its `type hash`, which is unified with other token.

However, Spore cluster has its own `cluster id` from its business perspective

> The cluster's ID is equivalent to the type script args of the cluster.
docs: https://docs.spore.pro/recipes/Create/create-clustered-spore#create-clustered-spore-with-cluster-agent

Some dev team expected `cluster id` to be displayed on the page, e.g. 

Spore **Spore NFT TEST (JoyID)** at https://pudge.explorer.nervos.org/nft-collections/0x6bb42907f37e9ab6ecf5ecd62d65ab2c16a4ff04a48728d1802889147a2a3c17 should display its `cluster id` `0x8648bff56526a201759e235f63f4509d5444fea15ebeee152e94685eef7ea48f`(https://pudge.explorer.nervos.org/transaction/0xc1c44bc0bbd266efd8ef46183f09884bebdc4e7de28519f32612ab854eab901a)

Besides, I would suggest adding an alias for the url of `unified class id/class type hash`, e.g. `/spore/{cluster_id}` equals to `/nft-collections/{type_hash}`

**Comment by zmcNotafraid** [comment]
Current spore info api support  `/api/v2/nft/collections/{sn}/items/{spore id}`

**Comment by Keith-CY** [comment]
Updated in frontend, https://pudge.explorer.nervos.org/nft-collections/0x6bb42907f37e9ab6ecf5ecd62d65ab2c16a4ff04a48728d1802889147a2a3c17

<img width="859" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/7e7a80fd-bed0-4b12-ab17-a1bc42611d39">

**Comment by FrederLu** [comment]
> Updated in frontend, https://pudge.explorer.nervos.org/nft-collections/0x6bb42907f37e9ab6ecf5ecd62d65ab2c16a4ff04a48728d1802889147a2a3c17
> 
> <img alt="image" width="859" src="https://private-user-images.githubusercontent.com/7271329/313685698-7e7a80fd-bed0-4b12-ab17-a1bc42611d39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDE2MjUsIm5iZiI6MTcxMDg0MTMyNSwicGF0aCI6Ii83MjcxMzI5LzMxMzY4NTY5OC03ZTdhODBmZC1iZWQwLTRiMTItYWIxNy1hMWJjNDI2MTFkMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMDk0MjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA2ZDIwZWVkMWJiOTQ1NWJjNjRkMDliZTMxZWQ1MmNmYTNkY2I2YzMxYTBlYjUzN2FkYTEzOTRmZTRhNjkxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aeu-FlRQbyWR7u-LHeosOFEJSxJre-Ku0ItgFgPWJ2M">

Verified.
