### ISSUE TITLE
Missing data under Simple User Defined Token.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#568]
<img width="1315" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/940e3de5-89f6-42b1-ab67-a97ec409c69a">
<img width="1282" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/72e2ef0d-a329-467f-afed-1cb687ff47e3">

https://explorer.nervos.org/en/nft-collections/0xcae4e45e3af135d5dd51ee0dfea27ff4249426f056935d9473f1bdfd37668037?tab=transfers

https://explorer.nervos.org/en/address/ckb1qrgp752jcfnm0uemj723grpyva6zappyuj0tuge3etkpjlmjsxmq5qgd0wtzp48uj24z28nfl4l9ce7u6adrncq2rlf4r
<img width="1257" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/5d3a930e-6f40-40c8-993c-f83ca5155cd2">

Missing data under simple user defined token on address details page.

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/289

**Comment by FrederLu** [comment]
> [Magickbase/ckb-explorer-frontend#289](https://github.com/Magickbase/ckb-explorer-frontend/pull/289)

https://github.com/Magickbase/ckb-explorer-frontend/pull/289#issuecomment-2084435298

Now the data has been displayed, but as mentioned in pr, the data is not parsed and displayed as `? `.
@Sven-TBD   needs to confirm the data display style.

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/298

**Comment by FrederLu** [comment]
Verified.
