### ISSUE TITLE
Support searching `code_hash`

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#569]
When the searching keyword hits a `code_hash`, the API service should return its paired `hash type`, so a complete url to the `/script/{code_hash}/{hash_type}` can be constructed in the frontend and lead users to the script page

**Comment by zmcNotafraid** [comment]
PR: 
https://github.com/nervosnetwork/ckb-explorer/pull/1689
https://github.com/Magickbase/ckb-explorer-frontend/pull/270

**Comment by Keith-CY** [comment]
I've verified this function in staging, is it ready to be on testnet and mainnet?
