### ISSUE TITLE
`page_size `doesn't work on this page.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#57]
https://ckb-explorer.staging.layerview.io/address/ckt1qq3ylcn557cqtnffnaez8tag4d97yngdw4x0je2algayedyh7rejkqv9v9dswes4x97gpu2vhtt9q8hvqvwd28qrvj8gk?page_size=20
It seems that page_size doesn't work on this page that page_size is modified to non-10, 10 pieces of data are always displayed on the page.

**Comment by ShiningRay** [comment]
这个可能是前端没有处理这个参数 @Keith-CY

**Comment by yanguoyu** [comment]
https://ckb-explorer.staging.layerview.io/address/ckt1qq3ylcn557cqtnffnaez8tag4d97yngdw4x0je2algayedyh7rejkqv9v9dswes4x97gpu2vhtt9q8hvqvwd28qrvj8gk?page=20&size=10
It seems like transfer `page` and `size` like this.

**Comment by Keith-CY** [comment]
After checking the source code I found the query word is `size` but not `page_size`
Ref: https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/src/pages/Address/AddressComp.tsx#L249
