### ISSUE TITLE
Categorize "Spore" into "DOB" for marketing

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#570]
DOB: https://www.theblockbeats.info/flash/237408

**Comment by Keith-CY** [comment]
It's been done by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/c6d9dc0964921d034f594c3181d9298467419ac9

**Comment by FrederLu** [comment]
> It's been done by [nervosnetwork/ckb-explorer-frontend@c6d9dc0](https://github.com/nervosnetwork/ckb-explorer-frontend/commit/c6d9dc0964921d034f594c3181d9298467419ac9)

Verified.
