### ISSUE TITLE
Keyboard buttons will fail to submit data.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#573]
<img width="357" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/498d4dcd-f36d-4d2f-8cfc-db202d6a348b">

When the keyboard is invoked on the page, the bottom button is not `OK` which will affect data submission.

Refer to the button at the bottom of the homepage
<img width="361" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/1ed9053e-90f6-45a3-8364-9b87479b1ba9">

**Comment by FrederLu** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/278
The PR was approved by me by mistake.
Now the button text has been replaced with `Search`, but entering information and clicking the button still doesn't trigger search when using `by Id` on mobile.
When there are multiple options for inputting information when using `by Name`, clicking the button will jump to the details of the first option.

**Comment by PainterPuppets** [comment]
> [Magickbase/ckb-explorer-frontend#278](https://github.com/Magickbase/ckb-explorer-frontend/pull/278) The PR was approved by me by mistake. @PainterPuppets Now the button text has been replaced with `Search`, but entering information and clicking the button still doesn't trigger search when using `by Id` on mobile. When there are multiple options for inputting information when using `by Name`, clicking the button will jump to the details of the first option.

ok, i'll check it

**Comment by FrederLu** [comment]
Verified.
