### ISSUE TITLE
Add a chart of CKB full node distribution

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#579]
Data source: https://github.com/cryptape/Marci

Charts: 
- geographic projection
- Nodes distribution by Country/Region

Style: 
- Geo: 
	- https://echarts.apache.org/v4/examples/en/editor.html?c=lines3d-airline-on-globe&gl=1
	- https://echarts.apache.org/v4/examples/en/editor.html?c=lines3d-flights-gl&gl=1
	- https://echarts.apache.org/v4/examples/en/editor.html?c=lines3d-flights&gl=1
- Distribution: 
	- https://echarts.apache.org/v4/examples/en/editor.html?c=pie-custom

**Comment by Keith-CY** [comment]
> PRD:[ybbzk8.axshare.com](https://ybbzk8.axshare.com)
> 
> Requirements:
> 
> 1. Add 2 charts to the 'Charts' page:[explorer.nervos.org/charts](https://explorer.nervos.org/charts)
> 2. Supports 'Mirana Mainnet' and 'Pudge Testnet'.
> 3. Click to view details
>    
>    * Node Tracker Map:[echarts.apache.org/v4/examples/en/editor.html?c=lines3d-flights-gl&gl=1&theme=light](https://echarts.apache.org/v4/examples/en/editor.html?c=lines3d-flights-gl&gl=1&theme=light)
>    * Nodes distribution by Country/Region:[echarts.apache.org/v4/examples/en/editor.html?c=pie-custom](https://echarts.apache.org/v4/examples/en/editor.html?c=pie-custom)

For point 2, charts of mainnet and testnet can be displayed in mainnet explorer and testnet explorer, respectively.

---

For point 3, the earch is so awesome that we can display it in full window, like http://globe.cid.harvard.edu/?mode=productsphere&id=1702

<img width="3008" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/c94984b7-3c6a-43cd-8b94-b516feb046cb">

**Comment by Danie0918** [comment]
> For point 3, the earch is so awesome that we can display it in full window, like http://globe.cid.harvard.edu/?mode=productsphere&id=1702
> 

OK, let's change style to https://echarts.apache.org/v4/examples/en/editor.html?c=lines3d-airline-on-globe&gl=1.
@zmcNotafraid

**Comment by zmcNotafraid** [comment]
Node Country Chart PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/279

**Comment by Keith-CY** [comment]
I'll take over 
<img width="1274" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/2b034e43-3e0c-4d13-8195-7090520ee0d8">
If @zmcNotafraid is working on other issues

**Comment by Keith-CY** [comment]
Geo distribution should be added by https://github.com/Magickbase/ckb-explorer-frontend/pull/283
