### ISSUE TITLE
Script info is missing on an inscription page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#586]
Page: https://pudge.explorer.nervos.org/inscription/0x7337d2075479d5c6789564516be1db11478e1d3ca70ad88050fe0bf3ff05acc2

API: https://testnet-api.explorer.nervos.org/api/v1/omiga_inscriptions/0x7337d2075479d5c6789564516be1db11478e1d3ca70ad88050fe0bf3ff05acc2

**Comment by zmcNotafraid** [comment]
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/6780c931-8d87-4c4b-8f9c-9b2f328dfcae)
Seems returned now
