### ISSUE TITLE
RGB++ data to be processed.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#590]
https://ckb-explorer-frontend-in-magickbase-repo-4xjbl68j8-magickbase.vercel.app/address/tb1qvt7p9g6mw70sealdewtfp0sekquxuru6j3gwmt
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/bf255611-78fe-49db-beb6-a8365c2b179c">
1、The data of this API is total: 48, but there are only 21 details.

---
https://ckb-explorer-frontend-in-magickbase-repo-4xjbl68j8-magickbase.vercel.app/transaction/0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/5d0cfb98-71af-4063-b649-f41b9c3b453a">

2、Api prompt 500.

---
https://ckb-explorer-frontend-in-magickbase-repo-4xjbl68j8-magickbase.vercel.app/transaction/0x0c6cfe38089214edbe31b4a229e1fb5682c2c6c5d4453aa32a1cbd7148df9734
3、Transactions with the same address need to be aggregated.

---
https://ckb-explorer-frontend-in-magickbase-repo-4xjbl68j8-magickbase.vercel.app/transaction/0x5faa0a0d14970f29c384840a348d124d8dcbc1226eea7db614a4af6c363f2e18
<img width="1427" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/8157587b-840b-4dd7-9b6e-7c4d4af95974">

4、This transaction is converted from a general CKB asset to an RGB++ asset. It is not recognized as an RGB++ transaction and requires a `leap in` tag.

---
https://ckb-explorer-frontend-in-magickbase-repo-4xjbl68j8-magickbase.vercel.app/transaction/0x08bcaabdb59c502f00405f4ba2d485720d821905fc0de1e21fe3cd3ed62ac46a
<img width="1417" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/58950f49-475f-4c3b-97de-0c7070b9b26c">
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e508c5a3-084a-4eee-9f5a-b683e574b4fa">

5、There is data that needs to be aggregated. At the same time, it is found through the cell information that RGB++ transactions are stored and there is no `leap in/leap out` asset conversion. There is no need to display labels.

**Comment by Daryl-L** [comment]
Error display "no" in issue 2 fixed in 14d1dc40afc16b7fe740d6a472912462bdb07e59

**Comment by rabbitz** [comment]
API 500 error fixed in https://github.com/nervosnetwork/ckb-explorer/pull/1706

**Comment by FrederLu** [comment]
> 0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91

<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/32403e17-5c54-478c-94e4-fffcfdfad744">
https://ckb-explorer-frontend-in-magickbase-repo-ig7wikfc0-magickbase.vercel.app/transaction/0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91
Exception NaN occurred.

**Comment by Keith-CY** [comment]
> > 0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91
> 
> <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/25676576/317615759-32403e17-5c54-478c-94e4-fffcfdfad744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDY3NjYsIm5iZiI6MTcxMTYwNjQ2NiwicGF0aCI6Ii8yNTY3NjU3Ni8zMTc2MTU3NTktMzI0MDNlMTctNWM1NC00NzhjLTk0ZTQtZmZmY2ZkZmFkNzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA2MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjVjODc5NTdhOTAzZWIzNTkyZWZjNjNkOWI2ZTA2ZmRiYTM0YTdlYWJjNjI0NDU2MThkYWZmZjY0MTgyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qJSKc9Q_4eB9CPKXiwE05L51GV0BN2cEPgD5-dYPEUM"> https://ckb-explorer-frontend-in-magickbase-repo-ig7wikfc0-magickbase.vercel.app/transaction/0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91 Exception NaN occurred.

The info of xUDT is missing, I will fix it by displaying it `Unknown`

**Comment by Keith-CY** [comment]
> > > 0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91
> > 
> > 
> > <img alt="image" width="1439" src="https://private-user-images.githubusercontent.com/25676576/317615759-32403e17-5c54-478c-94e4-fffcfdfad744.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MDY3NjYsIm5iZiI6MTcxMTYwNjQ2NiwicGF0aCI6Ii8yNTY3NjU3Ni8zMTc2MTU3NTktMzI0MDNlMTctNWM1NC00NzhjLTk0ZTQtZmZmY2ZkZmFkNzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA2MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZjVjODc5NTdhOTAzZWIzNTkyZWZjNjNkOWI2ZTA2ZmRiYTM0YTdlYWJjNjI0NDU2MThkYWZmZjY0MTgyOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qJSKc9Q_4eB9CPKXiwE05L51GV0BN2cEPgD5-dYPEUM"> [ckb-explorer-frontend-in-magickbase-repo-ig7wikfc0-magickbase.vercel.app/transaction/0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91](https://ckb-explorer-frontend-in-magickbase-repo-ig7wikfc0-magickbase.vercel.app/transaction/0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91) Exception NaN occurred.
> 
> The info of xUDT is missing, I will fix it by displaying it `Unknown`

It's been fixed and preview at https://ckb-explorer-frontend-in-magickbase-repo-git-7cb256-magickbase.vercel.app/transaction/0xe508411949658f37b0d22ff0a57389ff0a2601934994f540a5937fffd8322b91
<img width="1888" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/dd884b2c-5f74-4233-af98-ed9f438c7e6f">

**Comment by FrederLu** [comment]
[12674452, 12674946, 12675043, 12675162, 12675226, 12675347, 12675713, 12676447, 12676891, 12677107] The txids of these blocks are abnormal.

https://ckb-explorer-frontend-in-magickbase-repo-o25lzuely-magickbase.vercel.app/address/tb1q93nrfpmfz0h2u4ef94eew37qvmvrks4ataf42c?layout=lite

Data parsing exception not in exception block:
https://ckb-explorer-frontend-in-magickbase-repo-o25lzuely-magickbase.vercel.app/transaction/0xc97445356f57d232ef10d7c460f6804c89476e9d1f58275ac146ec48bc795645
<img width="1294" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/23576b81-9ea0-44e4-8690-a71a954d6f1d">
https://mempool.space/testnet/tx/eb33671679ce60163ef41609dcfd2eb0e6a042305c29e60b04131040d4276564

https://ckb-explorer-frontend-in-magickbase-repo-o25lzuely-magickbase.vercel.app/transaction/0x54a4b23d27044a7df926b0f827f12892f80af6b6fcdc263779d66069b0244bc3
<img width="1261" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/6189021a-152e-4c3c-8b72-5cf9e4ca22ef">
https://mempool.space/testnet/tx/8afc7c76e9de5191f0ec8ed451ef6ae6b90c38d7f9775a2c6784ebfeedc3874e

https://ckb-explorer-frontend-in-magickbase-repo-o25lzuely-magickbase.vercel.app/transaction/0x74980fedb8cac35ecac19b1370176d2221dc37107d96d7d801d8ffa752ddd7a6
<img width="1319" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/7984ce29-0f21-4809-8505-46f5b33a0706">
https://mempool.space/testnet/tx/c036d610d39ea2bdfc4b9ab4f44236d9dc2bcb5a9f53447b27a2e97c121644fe

---
https://ckb-explorer-frontend-in-magickbase-repo-o25lzuely-magickbase.vercel.app/address/tb1q93nrfpmfz0h2u4ef94eew37qvmvrks4ataf42c?layout=lite&page=2
The second page of data loading and display takes too long.

**Comment by FrederLu** [comment]
https://pudge.explorer.nervos.org/address/tb1q93nrfpmfz0h2u4ef94eew37qvmvrks4ataf42c?tx_status=committed
<img width="1305" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/26cdb44e-fda9-4458-a4d5-cfcad2f6e5cf">
The overview is missing the RGB++ tab.

---
https://pudge.explorer.nervos.org/transaction/0xcb609bde6668eaaf60e4f183516f1c69942868be56f780d3aa380170f3c877c1
<img width="1268" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/89aa8874-a828-4259-808f-9c31f5b86269">
Duplicate abnormal text appears.

**Comment by Daryl-L** [comment]
> https://pudge.explorer.nervos.org/address/tb1q93nrfpmfz0h2u4ef94eew37qvmvrks4ataf42c?tx_status=committed <img alt="image" width="1305" src="https://private-user-images.githubusercontent.com/25676576/317945077-26cdb44e-fda9-4458-a4d5-cfcad2f6e5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODU2NDAsIm5iZiI6MTcxMTY4NTM0MCwicGF0aCI6Ii8yNTY3NjU3Ni8zMTc5NDUwNzctMjZjZGI0NGUtZmRhOS00NDU4LWE0ZDUtY2ZjYWQyZjZlNWNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA0MDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzZGQxZTNiMTAzYjJhNjRkZDI3ZDUzNmI1OTQ0MjBiNTJlZmUwZjU5M2EyZTlhOTA5N2FmMjJkMTBkMjQwYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bI0klMEBhjzLeTLXJRY5k4mJJok9Zbh18JYZYKyYya4"> The overview is missing the RGB++ tab.
> 
> https://pudge.explorer.nervos.org/transaction/0xcb609bde6668eaaf60e4f183516f1c69942868be56f780d3aa380170f3c877c1 <img alt="image" width="1268" src="https://private-user-images.githubusercontent.com/25676576/317945245-89aa8874-a828-4259-808f-9c31f5b86269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2ODU2NDAsIm5iZiI6MTcxMTY4NTM0MCwicGF0aCI6Ii8yNTY3NjU3Ni8zMTc5NDUyNDUtODlhYTg4NzQtYTgyOC00MjU5LTgwOGYtOWMzMWY1Yjg2MjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA0MDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiYjUzMmU2ZTU1ZmNhYWE2OWY3N2M1YTNlZTVmODg4MDcyY2JiZGI3MTg3OGU4ZTY0MjZhZmM0YWZhZGE0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sVS02OmW5GwEaTtv58OqCdeyEwmWLfSeowModv8aI64"> Duplicate abnormal text appears.

The inscription data is not responded from the testnet for issue 1

**Comment by Keith-CY** [comment]
Visit https://pudge.explorer.nervos.org/inscription/0xeb107da63b6a9cecf4dbb1f26d87b5cb4b8de4ec862c639d1c1397f62287f811?filter=tb1p0ymszeygwhzkhn3ga2j34s7tevfae04rc4ykuyrwfdzl39fmhlcqcrmj8a

Click on `RGB++ Digest` to pop the RGB++ digest modal up, adjust the window width and will find that a `search icon` is over the modal
<img width="1895" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/51947c6b-0e22-473d-9049-eb33af5206e5">

Click on the `search` icon will dismiss the modal
@Daryl-L

**Comment by FrederLu** [comment]
https://pudge.explorer.nervos.org/transaction/0x2dd839b3b71ecadd2223553fd38100c613fb9fabdb0f5a898979f17574b2c76a
<img width="1257" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/309772a0-7bdd-4c19-90de-38cde25f8de6">
Discovered by inputting/outputting cell information, this is a pure RGB++ transaction, no labels required.

---
https://pudge.explorer.nervos.org/address/tb1q90zlhjg9leu0l87xzuknyq9aryt4d054hxx0gl
<img width="1340" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/68b9ef6b-f947-4a54-a9e1-afbc13e8336a">
Commitment information exists in RGB++ Digest, but the `envelope` tag is missing from the transaction.

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/277
