### ISSUE TITLE
Mark block time lock and unique cell in Frontend

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#595]
Testnet:
- Unique Cell: https://github.com/ckb-cell/unique-cell/blob/master/deloyments/testnet/deloyments/info-2024-03-28.json#L2-L17
- BTC Lock Time: 

Mainnet:
- Unique Cell: https://github.com/ckb-cell/unique-cell/blob/master/deloyments/mainnet/deloyments/info-2024-03-30.json#L3-L24n
- BTC Lock Time: revealed in private note

**Comment by Flouse** [comment]
https://github.com/ckb-cell/rgbpp-sdk/blob/110615b5cc824d83fe44170bd0d7013b52287b4d/packages/ckb/src/constants/index.ts#L36-L50

**Comment by Keith-CY** [comment]
Done as 
- Unique cell: https://explorer.nervos.org/scripts#Unique%20Cell
- BTC Time Lock: https://explorer.nervos.org/scripts#BTC%20Time%20Lock
