### ISSUE TITLE
RGB++ Transaction List

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#597]
Users could check the RGB++ transaction list on CKB explorer. 
He/she can view the chart of New address and Transaction of RGB++ on it everyday
- PRD： https://vs0cjf.axshare.com/?id=bn9z8h&p=transaction_list&g=1
https://vs0cjf.axshare.com/?id=q5x402&p=%E6%B5%8F%E8%A7%88%E5%99%A8%E5%A2%9E%E5%8A%A0_rgb____tab_%E6%94%AF%E6%8C%81&g=1

- [ ] UI design @Kirl70 
- [ ] Backend @rabbitz 
- [ ] Front-end @Daryl-L

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=36461%3A21289&mode=design&t=uDBdTbujz6yQKL9l-1

<img width="656" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/59789941-947c-45f5-845c-bdc885041e46">

**Comment by Keith-CY** [comment]
> Estimated Time for Joint debugging
> 
> * Backend Apr 08 Api
> * Front-end Apr 08 Api

Is it OK to start on Apr 08

**Comment by Daryl-L** [comment]
> > Estimated Time for Joint debugging
> > 
> > * Backend Apr 08 Api
> > * Front-end Apr 08 Api
> 
> Is it OK to start on Apr 08

I think will be OK. 
By the way, could we use the same list styles for mobile used in the transaction page before?
https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq22xdj8q4jdql98qkdhnqzgrsk4nqyavdcratvu9

**Comment by Keith-CY** [comment]
> > > Estimated Time for Joint debugging
> > > 
> > > * Backend Apr 08 Api
> > > * Front-end Apr 08 Api
> > 
> > 
> > Is it OK to start on Apr 08
> 
> I think will be OK. By the way, could we use the same list styles for mobile used in the address page before? [explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq22xdj8q4jdql98qkdhnqzgrsk4nqyavdcratvu9](https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq22xdj8q4jdql98qkdhnqzgrsk4nqyavdcratvu9)

It's fine if this feature can be delivered on time.

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1754

**Comment by Daryl-L** [comment]
> [nervosnetwork/ckb-explorer#1754](https://github.com/nervosnetwork/ckb-explorer/pull/1754)
> 
> #### bitcoin statistics
> * GET `/api/v2/bitcoin_statistics`
> 
> ```ruby
> {
>    "data": [
>        ...
>        {
>            "id": 786,
>            "timestamp": 1712449800, # UTC timestamp
>            "transactions_count": 0,
>            "addresses_count": 0
>        },
>        {
>            "id": 787,
>            "timestamp": 1712451600,
>            "transactions_count": 0,
>            "addresses_count": 0
>        },
>        {
>            "id": 788,
>            "timestamp": 1712453400,
>            "transactions_count": 0,
>            "addresses_count": 0
>        },
>        {
>            "id": 789,
>            "timestamp": 1712455200,
>            "transactions_count": 0,
>            "addresses_count": 0
>        },
>        {
>            "id": 790,
>            "timestamp": 1712457000,
>            "transactions_count": 2,
>            "addresses_count": 1
>        },
>        ...
>    ]
> }
> ```
> 
> #### rgb transaction
> * GET `/api/v2/rgb_transactions`
> 
> ```ruby
> {
>   "data": {
>     "ckb_transactions": [
>       {
>         "id": 59092903,
>         "tx_hash": "0xb4aeecc36b622f0d1945d6b9cc34833759349526038f0dadca1250d383fdda5a",
>         "block_id": 12789172,
>         "block_number": 12750536,
>         "block_timestamp": 1711707115623,
>         "leap_direction": "in",
>         "rgb_cell_changes": -2,
>         "tgb_txid": "0f54c6ed3b644515bae3f50825d1d5168f5e3a842988c972c3c5ed635aeaf486"
>       }...
>     ]
>   },
>   "meta": {
>     "total": 33,
>     "page_size": 25
>   }
> }
> ```
> 
> * sort by block number: `number.asc` or `number.desc`
> * sort by block time: `time.asc` or `time.desc`
> * filter by leap_direction: `in` or `out`

There are three directions for leap, in, out and no leap. As result, four types of value should be given for leap direction.

**Comment by Daryl-L** [comment]
> [nervosnetwork/ckb-explorer#1754](https://github.com/nervosnetwork/ckb-explorer/pull/1754)
> 
> #### bitcoin statistics
> * GET `/api/v2/bitcoin_statistics`
> 
> ```ruby
> {
>    "data": [
>        ...
>        {
>            "id": 786,
>            "timestamp": 1712449800, # UTC timestamp
>            "transactions_count": 0,
>            "addresses_count": 0
>        },
>        {
>            "id": 787,
>            "timestamp": 1712451600,
>            "transactions_count": 0,
>            "addresses_count": 0
>        },
>        {
>            "id": 788,
>            "timestamp": 1712453400,
>            "transactions_count": 0,
>            "addresses_count": 0
>        },
>        {
>            "id": 789,
>            "timestamp": 1712455200,
>            "transactions_count": 0,
>            "addresses_count": 0
>        },
>        {
>            "id": 790,
>            "timestamp": 1712457000,
>            "transactions_count": 2,
>            "addresses_count": 1
>        },
>        ...
>    ]
> }
> ```
> 
> #### rgb transaction
> * GET `/api/v2/rgb_transactions`
> 
> ```ruby
> {
>   "data": {
>     "ckb_transactions": [
>       {
>         "id": 59092903,
>         "tx_hash": "0xb4aeecc36b622f0d1945d6b9cc34833759349526038f0dadca1250d383fdda5a",
>         "block_id": 12789172,
>         "block_number": 12750536,
>         "block_timestamp": 1711707115623,
>         "leap_direction": "in",
>         "rgb_cell_changes": -2,
>         "tgb_txid": "0f54c6ed3b644515bae3f50825d1d5168f5e3a842988c972c3c5ed635aeaf486"
>       }...
>     ]
>   },
>   "meta": {
>     "total": 33,
>     "page_size": 25
>   }
> }
> ```
> 
> * sort by block number: `number.asc` or `number.desc`
> * sort by block time: `time.asc` or `time.desc`
> * filter by leap_direction: `in` or `out`

`tgb_txid` should be renamed to `rgb_txid`

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/285

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/285#discussion_r1556769251

Translation needed here. @Sven-TBD 
Including the title of the page, title in the chart and title in the table for each columns

**Comment by Keith-CY** [comment]
I would suggest limiting the initial period of the chart to the last 2 weeks so recent activities could be highlighted.

<img width="1312" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/559fd957-cde0-45db-a653-255f4cd811d5">

**Comment by FrederLu** [comment]
https://pudge.explorer.nervos.org/rgbpp/transaction/list

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/ebdf4b55-0b4b-4b72-a48e-fe18ca5b0743)

The text and filtering styles mentioned here need to be confirmed by @Sven-TBD .
