### ISSUE TITLE
Order of token list is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#6]
WBTC|eth https://explorer.nervos.org/sudt/0x3d077c897d2a6903acb2ee2d7f92c0175f93d033d89fcb53a32e39a6954dc018
 was registered but not found in the token list https://explorer.nervos.org/tokens

But it appears in the first page when I set page size to 100
![image](https://user-images.githubusercontent.com/7271329/162862680-3b8a3ae3-36e5-46e0-9c02-1c9a66a66056.png)
It's placed 22nd

Another mistake is that when page size is 100, the 18-21 tokens are 
![image](https://user-images.githubusercontent.com/7271329/162862821-b4c5d07f-42d1-4c53-aa3b-7fb402496890.png)
But when I visit with page size 10 https://explorer.nervos.org/tokens?page=2&size=10 , the order changes
![image](https://user-images.githubusercontent.com/7271329/162863216-d2cb0a49-cd29-4a11-b560-09686857ff89.png)

**Comment by Keith-CY** [comment]
The missing WBTC is related to this issue @yixyxiu

**Comment by ShiningRay** [comment]
这个问题复现不了

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/916
