### ISSUE TITLE
Issuer of xUDT is not returned

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#600]
Page: https://explorer.nervos.org/xudt/0x1b2c5f414541d81a19d6b70621779479911987d080fd9e3223b84f561e08ce3d

API: https://mainnet-api.explorer.nervos.org/api/v1/xudts/0x1b2c5f414541d81a19d6b70621779479911987d080fd9e3223b84f561e08ce3d

<img width="1492" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/5c6fbbee-2bd8-4aba-bcf4-159fcaa35bf0">

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1798

**Comment by zmcNotafraid** [comment]
Udt's issuer was first cell_output's lock, except xudt.
Xudt's owner script hash was in type script args first 32 bytes.
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/f8d10b5c-c5b7-4ea4-9dc0-98d01aa3c4f3)

Such as this [tx](https://pudge.explorer.nervos.org/transaction/0x741f94296a1042902444715a50e54b0cda28a2be968b8bd9f745d736d28565)59, there were two same xudt outputs in same tx, but lock script was different.
