### ISSUE TITLE
Amount of inscription is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#601]
Token Info:
https://pudge.explorer.nervos.org/transaction/0x715ef3d1e2034726ff3efb672d2a7710a4d0e4ec3866b106530892c7df2cf5d3

<img width="1198" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/90df81e9-bdf4-4fc3-a21c-ae68a1b26f53">

Mint: https://pudge.explorer.nervos.org/transaction/0x895b51fbe9ba4f2837a62a26d1f42ae3224aed9fc47fff53af715e09a7fa759c
<img width="1194" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/aba6833c-e078-4990-9c80-c39f5f23df6b">

The decimal is `18`, the value of `21000000000000000000000000`, expected to be displayed as `21000000`, but displayed as `5.185560161925726208`

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1737
