### ISSUE TITLE
Limit actions by IP for Faucet

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#602]
There's a script at https://github.com/mohanson/pyckb/blob/master/example/faucet.py that requests test tokens sequentially.

The limit of 300k CKB/month can also be circumvented by generating infinite addresses and finally aggregating them into a specific address.

So here I would suggest adding IP validation before each test token claim to restrict those requests.

For instance, each IP can claim at most 300k test tokens a day.

Please share any ideas if you have handled/learned such cases @zmcNotafraid @rabbitz @Danie0918 @Sven-TBD

**Comment by zmcNotafraid** [comment]
PR: https://github.com/Magickbase/ckb-testnet-faucet/pull/19
