### ISSUE TITLE
Transactions are not cancelled along with rollback

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#61]
https://pudge.explorer.nervos.org/transaction/0xadb4d687d4084eac21aeb3445c8971d057270ea8a451c32446094567d38f0be3
![Pasted Graphic 20](https://user-images.githubusercontent.com/7271329/187405423-a3c02e98-f45e-4d64-aaa0-25c7d736042b.png)

https://pudge.explorer.nervos.org/transaction/0xefc98405b521a5e6d784881d539388ad23a872069bd001e079ef15a550971b23
![image](https://user-images.githubusercontent.com/7271329/187405475-5bac1596-a89d-41a9-9099-ba1ebdf1de21.png)

Tx `0xadb4d687d4084eac21aeb3445c8971d057270ea8a451c32446094567d38f0be3` should be like this
![image](https://user-images.githubusercontent.com/7271329/187405822-5ff7aa39-be9f-4124-9b3d-a08f71d4e874.png)

![image](https://user-images.githubusercontent.com/7271329/187406020-95df6b26-c06d-4b7b-b4ba-06521b21a4c2.png)

**Comment by Keith-CY** [comment]
Caused by cache

**Comment by Keith-CY** [comment]
@ShiningRay please add detailed explanation

**Comment by ShiningRay** [comment]
代码对CkbTransaction进行查询的时候，会先使用tx hash作为缓存key，查找缓存，如果缓存中有对应数据则直接返回。缓存中保存的是回滚之前的交易 tx1。

而这笔交易后来又被重新打包了，所以最后在数据库中存的交易是tx1’，其数据库 id 与之前不同，tx hash相同。而此时有另外一个tx2.id 则与 tx1.id 相等
tx1.id != tx1’.id，tx1.id == tx2.id
列表页面的cell inputs和cell outputs 作为一个单独的缓存被保存，这个缓存绑定的是交易的数据库id
所以列表页面展示出了tx2的cell inputs和cell outputs

理论上来说，在CkbTransaction被删除的时候，代码会删除缓存，具体为什么没有触发成功，目前还没有时间研究
以后会重新梳理一下缓存的用法
