### ISSUE TITLE
Transactions repeated on xUDT/Inscription page when filtered by BTC address

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#610]
Page: https://pudge.explorer.nervos.org/xudt/0x7337d2075479d5c6789564516be1db11478e1d3ca70ad88050fe0bf3ff05acc2?filter=tb1ppavy0ekqk3mur37zvhqje0smauqa523tnrccynzlya5hkxy75nrqcfntth

<img width="1318" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/380514c4-7ae2-4119-a811-045bdcf2ec5f">

This is probably caused by `multiple CKB addresses are mapped to the same BTC address, and these CKB addresses are revealed in the same transaction`, so this transaction is loaded multiple times by different CKB addresses.

E.g. CKB Addresses `A`, `B`, `C` are all mapped to BTC address `D`, when the transaction list is filtered by `D`, it's actually filtered by `A | B | C`. If there is a transaction like

```
A -> C
B -> C
```

It will be indexed by `A`, `B`, `C`, respectively, thus 3 transactions are returned.

**Comment by rabbitz** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1764

**Comment by Keith-CY** [comment]
Is this fix ready for testnet?

**Comment by rabbitz** [comment]
> Is this fix ready for testnet?

It has been deployed to the testnet.

**Comment by FrederLu** [comment]
Verified.
