### ISSUE TITLE
Incremental release of xUDT data cannot be parsed.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#612]
https://pudge.explorer.nervos.org/transaction/0x62b0e8cef2e94debed58c5eb9d611e394fedd203b21076a866f04c02319d3f00
<img width="1312" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/958ddcb9-00c9-4f6b-aa06-c16454d9d76c">

https://pudge.explorer.nervos.org/transaction/0x9dac154a56451e14ac75702fce529a736f110d5b60e519a3adf87f188ab868c2
<img width="1338" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/9cedcab7-40a3-4cc0-a3ac-76d24053e185">

The current rule for parsing xUDT (decimal/symbol) is that the data will be parsed only when xudt and unique cell appear for the first time. If xudt has been published separately before, it will not be parsed if it is published later.

In this case, subsequent incrementally published xUDT data (decimal/symbol) cannot be parsed.

**Comment by rabbitz** [comment]
```ruby
{"id"=>3374261,
 "code_hash"=>"0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
 "hash_type"=>"type",
 "args"=>"0x641238cd95b9f5e6224da1963a0bcaa2e972dc87e56eb1ded9a35dcebbc37ff4",
 "type_hash"=>"0x93c361f9426865c614b219c92e49bc5c4f7c7491f99c79fe2099fa8c87de8a00",
 "full_name"=>nil,
 "symbol"=>nil,
 "decimal"=>nil,
 "description"=>nil,
 "icon_file"=>nil,
 "operator_website"=>nil,
 "addresses_count"=>5,
 "total_amount"=>2000000120000,
 "udt_type"=>"xudt",
 "published"=>false,
 "created_at"=>"2024-04-15T00:42:15.883+08:00",
 "updated_at"=>"2024-04-17T17:47:30.533+08:00",
 "block_timestamp"=>1712578089766,
 "issuer_address"=>"ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0zl2pwwzcx9jryfwq26lk0dcq4uhe49as2gh56a",
 "ckb_transactions_count"=>22,
 "nrc_factory_cell_id"=>nil,
 "display_name"=>nil,
 "uan"=>nil,
 "h24_ckb_transactions_count"=>0,
 "email"=>nil}
```

The xudt information is incomplete so it is not parsed. It may be created by a script.

**Comment by FrederLu** [comment]
https://github.com/Magickbase/ckb-explorer-public-issues/issues/620

The parsing information of token info for additional xudt issuance has been processed in the above issue.

**Comment by zmcNotafraid** [comment]
Only First time xudt cell and unique cell appear in a transaction will parse the xudt info.Below two cases don't parse.
1. Only Xudt cell appear in earliest transaction, then xudt cell and unique cell appear in later transaction.
2. Xudt cell and unique cell appear in earliest transaction, at this time we parse udt info. Then xudt with another unique cell appear in later transaction, we don't parse them anymore.
@FrederLu @Sven-TBD
