### ISSUE TITLE
Show hot zone in contract resource distribution

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#613]
Page: https://explorer.nervos.org/charts/contract-resource-distributed

The index of `transaction count/24hr` can be added with a visual map to reveal which contract is currently hottest.

<img width="835" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/fa04e2b7-a18c-42fb-92fe-462f820be399">

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1831

**Comment by PainterPuppets** [comment]
Is there something wrong with this page? The page seems to be displaying fine

**Comment by PainterPuppets** [comment]
Currently the charts is not colored, expect it to be colored according to the hot
