### ISSUE TITLE
Update testnet deployment info of spore script

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#619]
Deployment info: https://github.com/sporeprotocol/spore-contract/blob/master/docs/VERSIONS.md#tag-022-beta2-testnet

**Comment by Keith-CY** [comment]
Should be updated by https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1563/commits/6844c9676b4e30594f32d58bac7287bdb6b73d25

**Comment by Keith-CY** [comment]
It should be updated in backend too.

**Comment by zmcNotafraid** [comment]
> It should be updated in backend too. @zmcNotafraid

PR: https://github.com/nervosnetwork/ckb-explorer/pull/1788

**Comment by Keith-CY** [comment]
DOBs are recognized correctly

https://pudge.explorer.nervos.org/transaction/0xa3577247266402cdf78a70815cad99f973811504c4da9072e25bf311dd70657b

<img width="1956" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/1c9af83b-4af6-4e7b-8534-755e1d38a874">
