### ISSUE TITLE
Three charts are failed to load

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#62]
![image](https://user-images.githubusercontent.com/7271329/187579096-9de188d4-3ad4-4437-b5ca-2a6081046089.png)
![image](https://user-images.githubusercontent.com/7271329/187579149-60f39766-b538-41b9-9c3e-5bc95c99587f.png)
![image](https://user-images.githubusercontent.com/7271329/187579119-09c635d2-9f4e-47da-b2c5-bf0579c38019.png)
Seems that `http2` is used and not handled properly

**Comment by Keith-CY** [comment]
Please add the reason and solution briefly @ShiningRay

**Comment by ShiningRay** [comment]
此次问题是由于http2的一些兼容性问题导致的，目前由于对http2协议和cloudflare、nginx的一些机制不够了解，所以尚未能确定根本原因。
首先这几个响应都是返回全量数量，其中average block time数据量超过了2.9M，其他两个也有几百K
在这种情况下，nginx作为反向代理，会进行buffer并分段发送给前端服务cloudflare
然而可能由于ruby-nginx-cloudflare三者在发送数据的数据和时间间隔上存在一些不匹配，并与http2的一些配置产生了冲突，导致cloudflare不能收到完整的响应而导致客户端浏览器请求出错。
中间曾经尝试过将average block time的响应静态化，直接从nginx进行服务的方案，确实可以解决问题。
最后的解决方式是在nginx端将buffer调大，一次性将Ruby端发送的所有数据都存下来然后一次性发送给前端clouldflare
便解决了问题
