### ISSUE TITLE
Support tags of xudt

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#620]
This feature request comes from the community as xUDTs of duplicated `token info` could be issued, which is quite misleading to users.

A convention of how to display duplicated/invalid assets was designed at https://talk.nervos.org/t/xudt-information-convention-rfc/8030

It defines the rule that in what condition will a token be treated as duplicated, and the following tags should be appended.

#### Conditions

- Condition 1: First occurrence of **token symbol**(case-insensitive);
- Condition 2: Invisible char detected
- Condition 3: Invalid char detected
- Condition 4: Out of range
- Condition 5: Issued on Layer 1(BTC), namely issued by RGB++ Lock
- Condition 6: Issued by omnilock with `supply mode`(https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0042-omnilock/0042-omnilock.md#supply-mode) enabled

#### Tags and Display(by mark on Explorer)

```yml
tags:
  - invalid
  - suspicious
  - out-of-length-range
  - duplicate
  - rgbpp-compatible
  - layer-1-asset
  - layer-2-asset
  - verified-on-{platform}
  - supply-limited
  - supply-unlimited
```

```ruby
if Condition 3
  # invalid char
  Tag: invalid
  Display: Invalid

else if Condition 2
  # invisible char
  Tag: suspicious
  Display: Suspicious icon with a tooltip of the rule it breaks

else if Condition 4
  # out of length range
  Tag: out-of-length-range

else if Condition 1
  # valid and first token symbol
  if Condition 5
    Tag: rgbpp-compatible, layer-1-asset, supply-limited
  else if Condition 6
    Tag: rgbpp-compatible, layer-2-asset, supply-limited
  else
    Tag: rgbpp-compatible, layer-2-asset, supply-unlimited

else
  # valid but not first
  if Condition 5
    Tag: duplicate, layer-1-asset, supply-limited
  else if Condition 6
    Tag: duplicate, layer-2-asset, supply-limited
  else
    Tag: duplicate, layer-2-asset, supply-unlimited
```

`verified-on-{platform}` tag should be marked manually.

Filtered by `symbol and specific tags` should be supported for the xUDT list API(https://ckb-explorer.readme.io/reference/xudt-list)

**Comment by Keith-CY** [comment]
Set this high priority @Sven-TBD

**Comment by Kirl70** [comment]
Design Draft(12-2--12-3):
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=36828%3A30133&mode=design&t=ONlHWCyI76w1j2ff-1
<img width="900" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/11fa03a0-6632-4116-aef5-4085ee884308">
<img width="825" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/648228f6-8676-4097-938b-1682a0c9e448">

**Comment by Daryl-L** [comment]
> @Daryl-L I assigned this issue to you, its about a modification based on the UI above , could you please check it and provide the ETA?

This is signed "Done". Maybe another issue should be opened?

**Comment by Keith-CY** [comment]
> > @Daryl-L I assigned this issue to you, its about a modification based on the UI above , could you please check it and provide the ETA?
> 
> This is signed "Done". Maybe another issue should be opened?

Yes, we can open a new issue for how to display/interact with tags on the page @Sven-TBD
