### ISSUE TITLE
Ignore btc tx in rgbpp digest if it doesn't have commitment

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#621]
Transaction such as https://explorer.nervos.org/transaction/0xfbb5a8141b32b5730828d4bc1029a060fa44b3ddac0c8343ecf1a789c320d4d5

<img width="1344" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/7d0f9346-b099-4580-b230-e99ec2823736">

is mapped from btc tx https://mempool.space/tx/226770e273f4b804a30f9dcd841b6289a2d02b5e1f12d372512143700e54c637

<img width="1210" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/0d3a215b-a518-4408-a51b-3bc3d0fcf942">

but the btc tx doesn't have a commitment, so it's not an isomorphic transaction, the btc tx should be hidden to avoid misleading.

**Comment by Keith-CY** [comment]
Should be fixed by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/ca66c00ba8e7dc0969dfc7f2cecde476ab215c98 and https://github.com/nervosnetwork/ckb-explorer-frontend/commit/d543750fae719d8c93acda2dfd2633c170784308

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1828/files#diff-575d62e9ef895b2b6e64603bbb28e7d76efde80d2ffc40a1f3240c02b4af8b1eR66-R77

**Comment by rabbitz** [comment]
1. When there is no commitment, the front end should determine whether to display it, as there are rgbpp cells in the outputs.

2. The rgb_digest interface returns a `commitment_verified` field. The front end should determine how to display it accordingly.

```json
{
    "data": {
        "txid": "7141d712c3edefd147386fd1a1a39a277d57629712c334013a16832d8c241f73",
        "confirmations": 73617,
        "commitment": "1e8e9e880610d511a0490e1597e10dfe2799d14f3e1909ada17bef110f89b9da",
        "leap_direction": null,
        "transfer_step": null,
        "transfers": [
            {
                "address": "tb1qd5q7hs0q0px6qj55j2nkkhjgm2zep7765zjyhs",
                "transfers": [
                    {
                        "capacity": "10000000000.0",
                        "cell_type": "normal"
                    }
                ]
            }
        ],
        "commitment_verified": false
    }
}
```
