### ISSUE TITLE
Modify the term of RGB++ Tag from "Leap In" to "L2 -> L1"

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#625]
The Tag and its tooltip should be modified in following pages:

- RGB++ Transaction detail page 
- RGB++ Digest
- RGB++ Transaction List Page
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/d3d40b64-eec9-4f6e-9bb4-ce410c330cf5)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/66a4093a-f251-4251-86a9-bc08fbe70830)
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/d0ed55a1-f9b2-4a3f-af42-831262b55a80)

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/293

**Comment by FrederLu** [comment]
Verified.
