### ISSUE TITLE
`Confirmations on Bitcoin` data anomaly.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#633]
<img width="1207" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/5a4466a9-bb2b-400f-9ebf-96aca233b5cb">

https://pudge.explorer.nervos.org/transaction/0x48164bdb3a0c9cd62a4802006dfb7b3557610acd19c9a57aef555f008c512f44
<img width="1361" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/2e702dc3-ffac-4109-a692-ea43cb377a33">

There is an exception when synchronizing the transaction confirmation data on btc on the ckb browser.
Considering that the synchronization time difference should be equal to or lagging behind the data on Bitcoin.

**Comment by rabbitz** [comment]
`confirmations` are calculated as `tip_block_height - block_height`

The `headers` value returned by the `getblockchaininfo` RPC interface used by tip_block_height

```json
{
    "result": {
        "chain": "test",
        "blocks": 2808212,
        "headers": 2808212,
        "bestblockhash": "00000000000001b50976903cb9d97e4e51766b62cf96edc1d1d36a4329501c64",
        "difficulty": 1048576,
        "time": 1714462318,
        "mediantime": 1714462222,
        "verificationprogress": 0.9999998621612268,
        "initialblockdownload": false,
        "chainwork": "000000000000000000000000000000000000000000000d983ff2e0c14649e5e6",
        "size_on_disk": 57109617636,
        "pruned": false,
        "warnings": "Unknown new rules activated (versionbit 28)"
    },
    "error": null,
    "id": "curltest"
}
```

The `height` value returned by the `getblockheader` RPC interface used by block_height

```json
{
    "result": {
        "hash": "00000000000001edf8fc56974d0ccd75e6647c7beb38b0c0f7c05ae6557233ea",
        "confirmations": 63007,
        "height": 2745203,
        "version": 743022592,
        "versionHex": "2c49a000",
        "merkleroot": "52bd08c20f07fa339b406e557af79912fd2659c199146ffd2bb03fd343bdf4bf",
        "time": 1714283223,
        "mediantime": 1714283169,
        "nonce": 1328995432,
        "bits": "1a03fffc",
        "difficulty": 4194304,
        "chainwork": "000000000000000000000000000000000000000000000d9660208b28f0b19836",
        "nTx": 4664,
        "previousblockhash": "000000000000000b4f40a5c5b1b2bd948b6c48bc488d6bab612ed4e8ec21794c",
        "nextblockhash": "00000000000001fda1b5ac2c71f83d29854cc8e49ae6813bc9fff49e99de7cc8"
    },
    "error": null,
    "id": null
}
```

The confirmations cache time displayed by `mempool.space` is a bit long and lags behind the real-time calculated values.

**Comment by FrederLu** [comment]
<img width="1196" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/5c489986-8b2f-4dd1-93a9-af2ee7fc4b0a">

<img width="1270" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/49a7f206-a5bc-42df-99bc-b8510c110c8e">

It is confirmed that the out of sync between CKB Explorer and `mempool.space` is a delay issue on mempool. The data on reference `https://blockstream.info/testnet/tx/7141d712c3edefd147386fd1a1a39a277d57629712c334013a16832d8c241f73` are basically the same.
