### ISSUE TITLE
[RGB++]Wrong direction for this link

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#634]
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/5fde1a0e-adc2-463c-9c1e-6b90379fab77)

Link： https://pudge.explorer.nervos.org/transaction/0xf45545410a73441e4d7046e041650d488616c7e680da703f6cdcfacef758a68f

**Comment by Daryl-L** [comment]
The left links are to jump to the utxo transaction page, right are to jump to the address page, which should be reserved?

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/338

**Comment by FrederLu** [comment]
Verified.
