### ISSUE TITLE
A question about the 0 BTC here

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#636]
I have a question about the "0 BTC " here.

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/79da4c4b-c978-4b20-b7ef-3fc120e9aa43)

Is this a bug ?

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/347

**Comment by FrederLu** [comment]
Verified.
