### ISSUE TITLE
The number of `Live cells` does not match the data.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#637]
https://pudge.explorer.nervos.org/address/ckt1qpuljza4azfdsrwjzdpea6442yfqadqhv7yzfu5zknlmtusm45hpuqgqcfn63wfumts4lvrryhc35u43q3aaf5euqq6zeas9
<img width="1267" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e933ab30-36df-474d-ad71-64f22a1851d7">

The displayed `Live cells` data is 1260, but the actual number is much larger than this data.
This data needs to be confirmed.

**Comment by Keith-CY** [comment]
This could be an online bug, please check @Sven-TBD

**Comment by zmcNotafraid** [comment]
1. Query the databsae data was 1265 cells
2. Query the html element also 1265 elements
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/b3b26d90-0592-4a3c-a356-c36376f5f94b)
![image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/7496bf9e-e087-47e8-ba80-eb4fac241492)
