### ISSUE TITLE
Live BTC UTXO service

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#638]
This issue is used to track the service of live BTC RGB++ UTXO which is also a key indicator of this [issue](https://github.com/Magickbase/ckb-explorer-public-issues/issues/583#issuecomment-2066200192). Meanwhile, this indicator will serve for other CKB team.

**Comment by Daryl-L** [comment]
## 设计草案

### 数据库

使用 KV 存储每个 BTC 区块被消耗的 utxo，其中
key: vin
value: block number
expiration: 1 day

### 流程

1. 每个 BTC 的区块同步一次被消费的且 op return 与 commitment 规则相同的 vin，将其存入 kv 中
2. 每个 CKB 区块同步 CKB 的交易
3. 如果交易中 input cell 中存在有 RGB++ Cell，则从 kv 中删除对应的 vin
4. 在下一个 BTC 区块开始后，将上一个区块中 kv 还存在的记录，同步给浏览器，确认是否解绑

**Comment by Keith-CY** [comment]
> ## 设计草案
> ### 数据库
> 使用 KV 存储每个 BTC 区块被消耗的 utxo，其中 key: vin value: block number expiration: 1 day
> 
> ### 流程
> 1. 每个 BTC 的区块同步一次被消费的且 op return 与 commitment 规则相同的 vin，将其存入 kv 中
> 2. 每个 CKB 区块同步 CKB 的交易
> 3. 如果交易中 input cell 中存在有 RGB++ Cell，则从 kv 中删除对应的 vin
> 4. 在下一个 BTC 区块开始后，将上一个区块中 kv 还存在的记录，同步给浏览器，确认是否解绑
> 
> ### 初始化
> 鉴于目前 RGB++ Cell 量较少，一次性查询每个 Cell 对应的 utxo 是否被消费

不需要存储 vin, 以及校验 OP_RETURN, commitment. 流程可以简化如下

1. 在 BTC 出块前, 同步 CKB 的 RGB++ Live Cells, 存下 RGB++ Lock, 通过 Indexer 可以做到, 也可以从浏览器 API 获取;
2. 在 BTC 出块后, 遍历其 vin, 查看是否命中 RGB++ Lock 里的 args
3. 将命中的 `[RGB++ Lock, vin]` 批量发给浏览器

这个服务是探测 BTC UTXO 是否消费, 无需订阅 CKB 节点

**Comment by Daryl-L** [comment]
> > ## 设计草案
> 
> > ### 数据库
> 
> > 使用 KV 存储每个 BTC 区块被消耗的 utxo，其中 key: vin value: block number expiration: 1 day
> 
> > 
> 
> > ### 流程
> 
> > 1. 每个 BTC 的区块同步一次被消费的且 op return 与 commitment 规则相同的 vin，将其存入 kv 中
> 
> > 2. 每个 CKB 区块同步 CKB 的交易
> 
> > 3. 如果交易中 input cell 中存在有 RGB++ Cell，则从 kv 中删除对应的 vin
> 
> > 4. 在下一个 BTC 区块开始后，将上一个区块中 kv 还存在的记录，同步给浏览器，确认是否解绑
> 
> > 
> 
> > ### 初始化
> 
> > 鉴于目前 RGB++ Cell 量较少，一次性查询每个 Cell 对应的 utxo 是否被消费
> 
> 
> 
> 不需要存储 vin, 以及校验 OP_RETURN, commitment. 流程可以简化如下
> 
> 
> 
> 1. 在 BTC 出块前, 同步 CKB 的 RGB++ Live Cells, 存下 RGB++ Lock, 通过 Indexer 可以做到, 也可以从浏览器 API 获取;
> 
> 2. 在 BTC 出块后, 遍历其 vin, 查看是否命中 RGB++ Lock 里的 args
> 
> 3. 将命中的 `[RGB++ Lock, vin]` 批量发给浏览器
> 
> 
> 
> 这个服务是探测 BTC UTXO 是否消费, 无需订阅 CKB 节点

我之前这么考虑，每一次都全量匹配的话，未来 CKB 的 RGB++ Lock 数量越来越多，消耗也会越来越大

**Comment by rabbitz** [comment]
#### Verify output cell utxo binding status

```ruby
# api
POST /api/v2/bitcoin_vouts/verify

# params
{
  "pointer": {
    "tx_hash": xxx,
    "index": xxx, 
  },
  "txid": xxx, 
  "consumed_by_txid": xxx
}

pointer: 用于定位需要校验的 output cell
txid: output cell lock script args 中绑定的 utxo txid
consumed_by_txid: 消费 utxo 的 btc txid
```

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1839

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/bitcoin-service

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2081
Readme: https://dash.readme.com/project/ckb-explorer/v1.0/refs/rgb-live-cell-outpoint
