### ISSUE TITLE
Add an external icon for BTC tx id here

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#639]
Add an external icon here which could lead user to the BTC TX detail on a external website.

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/bb8b5fc5-e7ee-49a1-ae41-9ddaf764b532)

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=35067%3A20864&mode=design&t=IR21qeeOHqipmjAQ-1
<img width="1191" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/08f4bad1-c579-4dcd-b2e3-4e2db0d98f3d">

**Comment by Daryl-L** [comment]
> Add an external icon here which could lead user to the BTC TX detail on a external website.
> 
> ![Image](https://private-user-images.githubusercontent.com/85155313/326347537-bb8b5fc5-e7ee-49a1-ae41-9ddaf764b532.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyOTkzMDcsIm5iZiI6MTcxNTI5OTAwNywicGF0aCI6Ii84NTE1NTMxMy8zMjYzNDc1MzctYmI4YjVmYzUtZTdlZS00OWExLWFlNDEtOWRkYWY3NjRiNTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDIzNTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZDQ4MzdhMTQyMmFiZGNhYjg1NDVlODZiZDkyZmZhODUxYWIyN2E5N2QyNDc4ZGYyMjNmMmY1M2EwZDcxYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aKCEWgD9NFwdEXFLRiEDstXnDomKJD-XTbmRoLY-oLs)

I remember that the conclusion was when we clicked the `hash`, we would jump to the page in Nervos Explorer, and the direct link here is the current page, so nothing happend when click it.

**Comment by Keith-CY** [comment]
> > Add an external icon here which could lead user to the BTC TX detail on a external website.
> > ![Image](https://private-user-images.githubusercontent.com/85155313/326347537-bb8b5fc5-e7ee-49a1-ae41-9ddaf764b532.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyOTkzMDcsIm5iZiI6MTcxNTI5OTAwNywicGF0aCI6Ii84NTE1NTMxMy8zMjYzNDc1MzctYmI4YjVmYzUtZTdlZS00OWExLWFlNDEtOWRkYWY3NjRiNTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDIzNTY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiZDQ4MzdhMTQyMmFiZGNhYjg1NDVlODZiZDkyZmZhODUxYWIyN2E5N2QyNDc4ZGYyMjNmMmY1M2EwZDcxYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aKCEWgD9NFwdEXFLRiEDstXnDomKJD-XTbmRoLY-oLs)
> 
> I remember that the conclusion was when we clicked the `hash`, we would jump to the page in Nervos Explorer, and the direct link here is the current page, so nothing happend when click it.

@Sven-TBD please check

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/346

**Comment by FrederLu** [comment]
Verified.
