### ISSUE TITLE
Cover of kollect nft is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#64]
https://mainnet-api.explorer.nervos.org/api/v2/nft/collections?page=2
![image](https://user-images.githubusercontent.com/7271329/189865238-2033fadd-9a78-497e-87e4-46cebf1a05e4.png)

Returned icon url is `kollect.me/tokens` which is incorrect

**Comment by Keith-CY** [comment]
Add icon url from Kollect website @Keith-CY

**Comment by Keith-CY** [comment]
https://res.cloudinary.com/kollect-me/image/fetch/f_auto,c_limit,w_800,q_auto/https%3A%2F%2F912139745222-production-files.s3.amazonaws.com%2Fuploads%2FMDmRvlHmtb1Uy.jpg
https://res.cloudinary.com/kollect-me/image/fetch/f_auto,c_limit,w_800,q_auto/https%3A%2F%2F912139745222-production-files.s3.amazonaws.com%2Fuploads%2FMnk2sBFTGPtKz.png

@ShiningRay

**Comment by Keith-CY** [comment]
Let's confirm whether the on-chain data are the same or not, if yes, I'll ask Kollect for help, they may use a gateway to serve media.

**Comment by ShiningRay** [comment]
The icon url is saved in cell's data field. `0x24ff5a9ab8c38d195ce2b4ea75ca8987000c4275726e696e67204265617200084275726e696e672000116b6f6c6c6563742e6d652f746f6b656e73000000010000000000000000`

I have checked that collection's cell, the parsed result is the same as that in image.

**Comment by Keith-CY** [comment]
> 0x24ff5a9ab8c38d195ce2b4ea75ca8987000c4275726e696e67204265617200084275726e696e672000116b6f6c6c6563742e6d652f746f6b656e73000000010000000000000000

Data parsed by js sdk is
```json
{
  name: 'Burning Bear',
  symbol: 'Burning ',
  baseTokenUri: 'kollect.me/tokens',
  extraData: '000000010000000000000000'
}
```

I'm gonna check with the kollect team

**Comment by Keith-CY** [comment]
Has opened a ticket-0126 in Kollect's discord for support

**Comment by Keith-CY** [comment]
Close first, the result from Kollect team will be appended once they reply.
