### ISSUE TITLE
the way to display the info of NRC721 lacking factory cell.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#642]
This is the issue on this PR:
https://github.com/Magickbase/ckb-explorer-frontend/pull/289

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1833

**Comment by Kirl70** [comment]
Design Draft(1-6--1-7):
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=33413%3A37177&mode=design&t=TEvs96okul87NWEn-1
<img width="1090" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/51f01d4b-35de-4f51-b6e4-573f724305ca">
