### ISSUE TITLE
The xudt label style is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#646]
Design Draft(12-2--12-3):
https://github.com/Magickbase/ckb-explorer-public-issues/issues/620#issuecomment-2060752134

Staging:
https://ckb-explorer-frontend-in-magickbase-repo-g9u2mzhhy-magickbase.vercel.app/xudts
<img width="485" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/f8b36666-2180-46a8-a848-59c7d8a28133">
<img width="572" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/e5aa7b4a-d525-4deb-bad9-3de3299cde1c">
The style and UI on Staging are consistent.

Testnet:
https://pudge.explorer.nervos.org/xudts?page=2
<img width="538" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/95dbe920-971e-4bb5-8ff1-9395bc1d3fc4">
<img width="527" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/55947ea7-4848-420b-920d-7ee71e2a1911">
<img width="498" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/598845ca-9308-4703-955a-bc5fdd539fb1">

Mainnet:
https://explorer.nervos.org/xudts?page=10
<img width="537" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/2fb97adc-df45-4644-b2b6-ed49b04ae108">

There are differences in xudt tags and staging on `testnet/mainnet`.

**Comment by Keith-CY** [comment]
I've updated 2 points

1. The style of `layer 1 asset` and `layer 2 asset` was the same

<img width="440" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/48a280c6-da7c-4204-b773-3e5bedb5820d">

I made them different, in their own primary colors, respectively

Bitcoin: 
<img width="107" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/59edbbaa-976b-4730-89fe-9cfae80440ea">
CKB Mainnet:
<img width="105" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/876c13eb-475f-440d-ae40-bd2d74dec798">
CKB Testnet:
<img width="95" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/9213c979-d5f4-4137-8613-03aed85c560b">

2. Tag is now interactive, e.g. https://pudge.explorer.nervos.org/xudts?tags=layer-2-asset
