### ISSUE TITLE
The `RGB++` page style on the mobile terminal needs to be adjusted.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#648]
Leap In（L1 -> L2）:
https://pudge.explorer.nervos.org/transaction/0x5639d2f490a742b81ef01743cba7096b95187bc9da0d38025fb0261463c82d87
<img width="1285" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/bade8877-884f-4a23-8d07-b0910f25dc1a">
<img width="1245" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/884fbb0e-d21f-4e38-98d2-afb8f87b805f">

Leap Out（L2 -> L1）:
https://pudge.explorer.nervos.org/transaction/0xf034c04f08a324c2c9d26ae9cac535ee82945d240051cde5ece2700e0bfcf9f9
/:https://pudge.explorer.nervos.org/transaction/0x2d67d93c9f6dbf86d4cfd7228ff4b9b383cea8f4c82673b7d1e3b6c3f5257994

UI：
<img width="354" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/ccd1e67a-b934-4bdb-8747-5f29aa968a3a"><img width="320" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/f91d624d-2d08-4f24-822d-5e23d81a462e">

The style of the RGB++ page on the mobile terminal needs to be adjusted:
Transaction / Address  page:
1、 The left and right spacing of `RGB++ Digest` is too small and needs to be adjusted;
2、 Labels like `Leap In (L1 -> L2)/Leap Out（L2 -> L1）` are not displayed;
3、`Seal Tx On Bitcoin 02a21...5e11 (557 Confirmations on Bitcoin)` Such data needs to be displayed in full, and is now partially obscured.

<img width="309" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/c8464a0d-5ca2-4509-ad26-f499bc177810">
<img width="304" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b9c2a632-a7ac-486c-bb94-0cf400133895">

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/302

**Comment by FrederLu** [comment]
> [Magickbase/ckb-explorer-frontend#302](https://github.com/Magickbase/ckb-explorer-frontend/pull/302)

Verified.
