### ISSUE TITLE
Some NFTs are missing in holder's asset list

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#65]
https://explorer.nervos.org/address/ckb1qqypm0l63rdt2jayymfrrjnyadmqe630a8skwcdpmfqqmgdje0sjsqw4jlwxmgcmeu2se39y3ucmrh87uy2eahssxeave
![image](https://user-images.githubusercontent.com/7271329/189868885-825e6e4b-18a9-438d-aff7-2ed288fb7102.png)
https://explorer.token.city/holder/tokens/ckb1qqypm0l63rdt2jayymfrrjnyadmqe630a8skwcdpmfqqmgdje0sjsqw4jlwxmgcmeu2se39y3ucmrh87uy2eahssxeave
![image](https://user-images.githubusercontent.com/7271329/189868950-3d702f2c-c124-46a2-99b4-898732e39227.png)
"未物主意" 高合 NFT 碎片 is missing in the list

**Comment by ShiningRay** [comment]
这个应该是扫描CoTA的时候漏掉了。
检查了Log，CoTA Syncer 因为数据库配置停了，重新配置之后重启并同步，数据已经恢复。

**Comment by Keith-CY** [comment]
> 这个应该是扫描CoTA的时候漏掉了。 检查了Log，CoTA Syncer 因为数据库配置停了，重新配置之后重启并同步，数据已经恢复。

Got it
