### ISSUE TITLE
`NRC 721` Asset data is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#653]
https://explorer.nervos.org/address/ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0thsh28ajrny2wu9pvvg9j8xe2k39tuvc3wm452
<img width="1281" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/afad644f-0ee3-4c29-8cf7-3c60f9a11ab7">

https://explorer.nervos.org/nft-collections/0x93650dc7b9c71e2dd396b030ae06ba54fc692be6e64fc6c9e7e62a185669b7ab
<img width="1261" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/4a43f83a-654d-4de6-9170-32fe92b57db4">

 There is screenshot NRC721 data under the `User Defined Token` of `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0thsh28ajrny2wu9pvvg9j8xe2k39tuvc3wm452`, but the user information is missing when clicking NRC721 to jump to the page.

**Comment by zmcNotafraid** [comment]
The reason was the token_item was not created because the nrc 721 token's verfied is false before.After we change the token's verified to true, I forgot to run TokenTransferDetectWorker to fix data.

**Comment by FrederLu** [comment]
`Rocket Fred [A2` cell is nrc_721_factory_cell, which is just a collection. There is no item, so there is no holder.
