### ISSUE TITLE
Add RGB++ Attribution for a RGB++ transaction.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#656]
Add RGB++ transaction attributes to the BTC TX detail page & adjust the direction field judgment rules for L1<->L2 on this page;

Axure: https://vs0cjf.axshare.com/?g=1&id=q205n4&p=support_rgb___v1_3
UI: https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-23035&t=z1rPtVwxhjKhe5ho-4

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1843

1. Add an enumerated field `rgb_transfer_step` to the details and list interfaces of CKB transactions.
2. Add enumerated fields `leap_direction` and `rgb_transfer_step` to the RGB digest interface.
3. Adjust the RGB transactions list interface to return `leap_direction`.

##### Remarks:

- Possible values for `rgb_transfer_step` include NULL, isomorphic, and unlock.
- Possible values for `leap_direction` include NULL, in, and withinBTC.

**Comment by Daryl-L** [comment]
Which feature should be added in this issue?

**Comment by Daryl-L** [comment]
1. 为 CKB 交易增加 RGB++ 属性
2. RGB++ 摘要更新
3. 交易列表页改动
4. 支持 BTC TX 区块确认数量展示

https://github.com/Magickbase/ckb-explorer-frontend/pull/348

**Comment by Daryl-L** [comment]
> PR: [nervosnetwork/ckb-explorer#1843](https://github.com/nervosnetwork/ckb-explorer/pull/1843)
> 
> 1. Add an enumerated field `rgb_transfer_step` to the details and list interfaces of CKB transactions.
> 2. Add enumerated fields `leap_direction` and `rgb_transfer_step` to the RGB digest interface.
> 3. Adjust the RGB transactions list interface to return `leap_direction`.
> 
> ##### Remarks:
> * Possible values for `rgb_transfer_step` include NULL, isomorphic, and unlock.
> * Possible values for `leap_direction` include NULL, in, and withinBTC.

I saw `leapoutBTC` in response, does it mean "L2 -> L1"?
