### ISSUE TITLE
Update the RGB++ tab of address detail page.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#658]
In this requirement, we need to slightly adjust the RGB++ Tab style on the BTC address details page. Each green bar represents one UTXO, it may include one or more assets.

在这个需求中，我们需要给稍微调整 BTC地址详情页的 RGB++ Tab 样式。一个绿条条就是一个UTXO，一个UTXO 下面可能包括一个或多个资产（Cell）。

- 原型
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/a5cf7e49-1110-40bd-a70a-16e0135f82bc)
- 原型链接：
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/d37ad9b1-2b75-4b98-b966-a014cf905d33)
- UI 链接：https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=37720-23788&t=EhT8uPdpRUfUtbi8-4
- UI展示：

cc @rabbitz @Daryl-L

**Comment by Daryl-L** [comment]
I don't find the multiple assets from current API, could you please check whether it is deployed on staging environment?

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1910/commits/29b361d0e5ceaf9a02fed6e0f8350220d4c26887

```ruby
```

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/384

**Comment by FrederLu** [comment]
Related issues to be addressed:  #719  #720

**Comment by FrederLu** [comment]
> Related issues to be addressed: [#719](https://github.com/Magickbase/ckb-explorer-public-issues/issues/719) [#720](https://github.com/Magickbase/ckb-explorer-public-issues/issues/720)

Verified.
