### ISSUE TITLE
Remove old caching mechenism

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#66]
由于之前的缓存机制较为激进，对业务代码逻辑侵入较多
为了方便未来的缓存重构，本次先降原有的缓存逻辑去掉

**Comment by iamyates** [comment]
This is the PR:    https://github.com/nervosnetwork/ckb-explorer/pull/1020
( this PR is based on pr#1019:  https://github.com/nervosnetwork/ckb-explorer/pull/1019  , so please merge 1019 first, then merge 1020 , otherwise there may be conflicts)

**Comment by Keith-CY** [comment]
> This is the PR: [nervosnetwork/ckb-explorer#1020](https://github.com/nervosnetwork/ckb-explorer/pull/1020) ( this PR is based on pr#1019: [nervosnetwork/ckb-explorer#1019](https://github.com/nervosnetwork/ckb-explorer/pull/1019) , so please merge 1019 first, then merge 1020 , otherwise there may be conflicts)

We can set the PR a draft if it relies on another one to be merged
![image](https://user-images.githubusercontent.com/7271329/192706408-111483e7-ec7b-47a5-9c46-14c7fdaddbb5.png)

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1022
