### ISSUE TITLE
Add list view for XUDT and RGB++ List

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#661]
The list view of Live Cells has been added in #19 

We could add list view for XUDT tab and RGB++ Tab

[Prototype](https://vs0cjf.axshare.com/?id=uvehzk&p=%E5%9C%B0%E5%9D%80%E8%AF%A6%E6%83%85%E9%A1%B5&g=1)

1. XUDT List View
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/b16a0391-0043-496e-b467-80d6698c9729)

2. RGB++ Tab Grid View

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/1a5c8bdf-3310-4a4f-9e9e-622ec002de6b)

3. RGB++ Tab List View(default)

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/7dd499c2-494a-41a0-b7fa-831464a2f292)

[PRD Link](https://vs0cjf.axshare.com/?id=lwf0z4&p=_661_add_list_view_for_xudt_and_rgb___list&g=1)

UI : https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=33413-37788&t=dJrYDVWSRTHVzg30-4

**Comment by Kirl70** [comment]
XUDT List:
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=9669%3A32557&t=YZ6cLpNnPR2Wpb0D-1
<img width="1005" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/a9245dfe-9aa1-4ef2-95ba-76242e48192e">

RGB++ Tab(1-10--1-11):
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=37720%3A23788&t=YZ6cLpNnPR2Wpb0D-1
<img width="976" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/f9407dfd-2c94-4839-9df8-dbceb9e44c41">
<img width="984" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/59f6279b-939e-41ee-a8df-957bee52369a">

**Comment by FrederLu** [comment]
Verified.
