### ISSUE TITLE
Sort NFT collection by created time

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#664]
This feature request comes from the community

---

Users want to see the new project in the NFT section and hope the list can be ordered by created time.

NFT List Page: https://explorer.nervos.org/nft-collections

**Comment by zmcNotafraid** [comment]
- [ ] api
- [ ] frontend
- [ ] DataFix(cota cell missed)

**Comment by FrederLu** [comment]
Verified.
