### ISSUE TITLE
Fee rate history is not updated timely

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#665]
I've pushed numerous transactions with fee_rate `2,816 shannons/kB`
<img width="658" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/12acb140-bb17-4b06-990f-b500ec45b9b3">
<img width="265" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/20fc6e1c-8723-44be-a93b-10093469f72b">

Almost all transactions in blocks are mine.

But there are always hundreds of transactions with fee_rate `1,000 shannons/kB` in the recent 10,000 transactions

<img width="746" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/2067bf9c-a299-4da0-9af7-34be354c90f6">

**Comment by zmcNotafraid** [comment]
Current calculate query condition is:  ` CkbTransaction.tx_committed.where("bytes > 0 and transaction_fee > 0 and confirmation_time > 0")`.
When I query above txs from database, these confirmation_time is nil, so they can't calcuate.
Only fetch by websocket pending txs have set confirmation time.

**Comment by zmcNotafraid** [comment]
related issue: https://github.com/Magickbase/ckb-explorer-public-issues/issues/704
