### ISSUE TITLE
Search keyword should be case-insensitive

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#666]
Now `Seal` and `seal` return different results.

<img width="1175" alt="Pasted Graphic 4" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/d5412827-f009-4946-9d1c-e87bfe74e5bd">
<img width="1308" alt="Pasted Graphic 5" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/c666ea81-3385-4ef6-8975-580037701a41">

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1867

**Comment by FrederLu** [comment]
> PR: [nervosnetwork/ckb-explorer#1867](https://github.com/nervosnetwork/ckb-explorer/pull/1867)

Verified.
