### ISSUE TITLE
Partition `cell_outputs` table

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#67]
The `cell_outputs` tables has more than 60,000,000 records.
The RDBMS usually has performance drop significantly after a table exceeds 20,000,000 records.
This is because the algorithm of B-Tree index, which has limit according to the layers in B-Tree.
So we can utilize the "partition" mechenism of RDBMS, to split big table into small partitions while not affecting the higher codes.

**Comment by Keith-CY** [comment]
By 11/09

**Comment by Keith-CY** [comment]
Blocked by migration of k8s

**Comment by Keith-CY** [comment]
Waiting for support of @mdzh521

**Comment by ShiningRay** [comment]
Suggested partition column:
- cell status: active or dead (maybe pending when `ckb_transactions` and `pool_transaction_entries` are merged)
- range(epoch) ( missing epoch column, add a epoch column )
- range(block_number)
- hash(transaction_id)
