### ISSUE TITLE
Provider a interface to get the transaction that use appointed cell

### ISSUE THREAD

**Issue by yanguoyu** [Magickbase/ckb-explorer-public-issues#671]
For https://github.com/Magickbase/ckb-explorer-public-issues/issues/354, we need to create a graph that links the cell from created to used. So we need to get the transaction that uses the appointed cell.

This interface may be like this:
- params: OutPoint
- result: If this cell is dead, return the transaction hash that uses the `OutPoint` cell, otherwise return null.

**Comment by Keith-CY** [comment]
This API works

https://mainnet-api.explorer.nervos.org/api/v2/ckb_transactions/0xd3125f76d7d6a83ba73d0fbaf2104b3ca1c3643122b0df373af0be4e07da2f75/display_outputs?page=1&page_size=10
