### ISSUE TITLE
Add `token.type_script` in `udt_account` so users can fetch script info and use it with ckb-indexer

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#673]
> https://ckb-explorer.readme.io/reference/address
希望能够在 udt_accounts 中增加 udt 的 typeScript 字段，类型为 CKBComponents.Script ，方便获取 cell

**Comment by rabbitz** [comment]
PR:https://github.com/nervosnetwork/ckb-explorer/pull/1880
