### ISSUE TITLE
DailyStatistic execution exception

### ISSUE THREAD

**Issue by rabbitz** [Magickbase/ckb-explorer-public-issues#675]

**Comment by zmcNotafraid** [comment]
- mining_reward 
- address_balance_distribution
- occupied_capacity
The above three attr is slow, run about one minute

**Comment by zmcNotafraid** [comment]
Today we found the scheduler job was not finished.First we query the log, from the below yesterday log we can see this job runs about 30 mintues.But today's log shows only start no finished.Then we found the scheduler container has restarted many times in these time.And the rufu-scheduler gem run job in memory not persist them.So I guess the container stoped after the job start,it caused the job lost.
<img width="514" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/12708910/0ddbde82-0ff3-4764-835f-37bc92d1a182">

**Comment by zmcNotafraid** [comment]
After the databse timeout set to 60s, these attrs will timeout:  addresses_count, mining_reward, address_balance_distribution, occupied_capacity, ckb_hodl_wave, holder_count

**Comment by Keith-CY** [comment]
> After the databse timeout set to 60s, these attrs will timeout: addresses_count, mining_reward, address_balance_distribution, occupied_capacity, ckb_hodl_wave, holder_count

How about running these statistics works in independent services to reduce the pressure on the single/current service.

**Comment by zmcNotafraid** [comment]
![image](https://github.com/user-attachments/assets/e25d40f2-7fa8-4384-8c07-4c0544e4b08b)
After cell_outputs table's partitioned current only needs 5 minutes.
