### ISSUE TITLE
Add "note" like "Powered by MagicKBase " for CKB explorer.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#677]

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5653-23133&t=a8jiANqtjvlLIJpk-1
<img width="940" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/5f892869-a3e8-4998-9b53-58607a269143">

**Comment by Keith-CY** [comment]
> Design Draft: [figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5653-23133&t=a8jiANqtjvlLIJpk-1](https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5653-23133&t=a8jiANqtjvlLIJpk-1) <img alt="image" width="940" src="https://private-user-images.githubusercontent.com/106060898/341696415-5f892869-a3e8-4998-9b53-58607a269143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNjkxOTUsIm5iZiI6MTcxOTM2ODg5NSwicGF0aCI6Ii8xMDYwNjA4OTgvMzQxNjk2NDE1LTVmODkyODY5LWEzZTgtNDk5OC05YjUzLTU4NjA3YTI2OTE0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwMjI4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWNiNGU4NmMxODQxMWQ5NWMwMzEyNDkzOTVjMTlkZjhhNzA0NGE2MjFhZGMyZmE0ZmE1YjI4MzY2N2FjMjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ezw30eXBvU_ky2EsKspDeZl3ZaJS8sm-NaHst1o1Sk">

It's less common to align `powered/build by team` and `all rights reserved` to the left/right end, are there any cases for reference?

Besides, I think `Magickbase` in the footer could be a link to https://www.magickbase.com

**Comment by Kirl70** [comment]
> > Design Draft: [figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5653-23133&t=a8jiANqtjvlLIJpk-1](https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5653-23133&t=a8jiANqtjvlLIJpk-1) <img alt="image" width="55.1475715637207" height="20.99826431274414" src="https://private-user-images.githubusercontent.com/106060898/341696415-5f892869-a3e8-4998-9b53-58607a269143.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNjkxOTUsIm5iZiI6MTcxOTM2ODg5NSwicGF0aCI6Ii8xMDYwNjA4OTgvMzQxNjk2NDE1LTVmODkyODY5LWEzZTgtNDk5OC05YjUzLTU4NjA3YTI2OTE0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwMjI4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOWNiNGU4NmMxODQxMWQ5NWMwMzEyNDkzOTVjMTlkZjhhNzA0NGE2MjFhZGMyZmE0ZmE1YjI4MzY2N2FjMjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8ezw30eXBvU_ky2EsKspDeZl3ZaJS8sm-NaHst1o1Sk">
> 
> It's less common to align `powered/build by team` and `all rights reserved` to the left/right end, are there any cases for reference?
> 
> Besides, I think `Magickbase` in the footer could be a link to https://www.magickbase.com

<img width="1352" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/d603bf71-9b5f-4915-9557-a145ef8fcd56">
Perhaps adding a horizontal line would be better, as the etherscan does.

<img width="1413" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/8bcde125-db85-40ec-85fb-f83c6d1067ef">
