### ISSUE TITLE
Add "New" or "Hot" tag for new features.

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#678]
Add a 'Hot' or 'New' tag for newly launched features, and consider adding red dot notifications for secondary menu selections (if any).

Description:
The display time can be configured. For example, the 'New' feature's tag is displayed by default for one month and will disappear automatically after one month.

- PRD：https://vs0cjf.axshare.com/?id=4sx6zs&g=14

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=36828-30345&t=a8jiANqtjvlLIJpk-1
<img width="1404" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/9d85f312-c6a6-4a05-958e-6ac2f47fd502">
