### ISSUE TITLE
Deprecate UAN

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#683]
The name convention at https://github.com/janx/rfcs/blob/universal-asset-notation/rfcs/0000-universal-asset-notation/0000-universal-asset-notation.md will be deprecated.

There are two groups of token named in UAN

1. Tokens issued before UAN, their UANs are marked by the explorer team;
2. Tokens issued after UAN, their UANs are specified by their issuers;

For type 1, their display name could be reset to the original one;
For type 2, their display name can remain unchanged because they are specified by the owners/issuers.

**Comment by Keith-CY** [comment]
> @Keith-CY Hi, Chen, Is there any announcement for this change by CKB official channel? Coz some assets' name may change following the explorer which I think worth an announcement. We can help change the name backend here. cc @zmcNotafraid

It can be held on until the PR of this proposal is closed
https://github.com/nervosnetwork/rfcs/pull/335

**Comment by zmcNotafraid** [comment]
PR: https://github.com/Magickbase/ckb-explorer-frontend/pull/380
https://github.com/nervosnetwork/ckb-explorer/pull/1969/files

**Comment by Keith-CY** [comment]
Updated on the mainnet
