### ISSUE TITLE
Parameters of pagination are missing in readme.io

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#684]
E.g. https://ckb-explorer.readme.io/reference/rgb-transaction-list
<img width="655" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/7bce01f0-f9e3-4fd7-85d7-16d11b9663c5">
This API support `page` and `page_size` but they are not listed.

**Comment by rabbitz** [comment]
readme: checked interfaces, missing fields have been added
