### ISSUE TITLE
API waiting time is long.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#688]
https://pudge.explorer.nervos.org/address/tb1qd5q7hs0q0px6qj55j2nkkhjgm2zep7765zjyhs?page=3
<img width="1436" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/d1962a87-8f27-4781-ad43-0845debb6eb9">

The api waits for a long time and the page cannot display data.

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2163

**Comment by FrederLu** [comment]
The api query has been optimized.
However, if the address query contains a lot of data, it will still be slow. For example there are 600+ data under the `tb1qssu8pscsuevnmvhnr08840wvuzdan27k9m46ja` address, the loading time will still be relatively long.

**Comment by rabbitz** [comment]
https://docs.aws.amazon.com/zh_cn/AmazonRDS/latest/UserGuide/wait-event.iobuffile.html

Increasing the `work_mem` parameter from 4MB to 20MB

**Comment by FrederLu** [comment]
> https://docs.aws.amazon.com/zh_cn/AmazonRDS/latest/UserGuide/wait-event.iobuffile.html
> 
> Increasing the `work_mem` parameter from 4MB to 200MB

https://pudge.explorer.nervos.org/address/tb1qssu8pscsuevnmvhnr08840wvuzdan27k9m46ja

Before：
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/92555af4-2d05-47ba-8dc3-4bd24200e04e">

Now：
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/12371515-1401-42a1-8033-ad0b32a8af71">

The same data has been significantly improved in API response after adjustment compared with the previous one.  Verification passed.
