### ISSUE TITLE
Submit xUDT Token Info

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#689]
There's a form to submit token info of a sUDT

<img width="1319" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/a202a913-50f5-42db-a2c9-cf09da504930">

Among these fields, `symbol`, `decimal` and `name` can be decoded from xUDT-paired unique cell(https://talk.nervos.org/t/xudt-information-convention-rfc/8030/6)

The rest, `description`, `website`, `logo` are still useful for a token.

I suggest adding `xudt` type in the `submit token info` form to enrich the info on the explorer

**Comment by zmcNotafraid** [comment]
@PainterPuppets  The API was same, you only need to do is add an xudt type to Token Type field.

**Comment by Keith-CY** [comment]
I'll take over this issue

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1979

**Comment by FrederLu** [comment]
Verified.
