### ISSUE TITLE
Add RGB++ L2->L1 Transaction Tag

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#692]
The definition of L2->L1 could be conducted from the statement [here](https://www.notion.so/RGB-eac7823cdb024e8991940299a8f67488), which could be described as following:

Every non-null Type Cells of input cells are without RGB_lock, every non-null Type Cells of output cells are with RGB_lock;
输入侧非null Type Cell 没有 RGB_lock，输出侧非null Type Cell 有 RGB_lock.

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1952/commits/10dee3eff21079cffaa28f134ad5a9118c1c1545

**Comment by FrederLu** [comment]
> PR: [nervosnetwork/ckb-explorer@10dee3e](https://github.com/nervosnetwork/ckb-explorer/commit/10dee3eff21079cffaa28f134ad5a9118c1c1545)

Staging verified.

**Comment by Keith-CY** [comment]
> > PR: [nervosnetwork/ckb-explorer@10dee3e](https://github.com/nervosnetwork/ckb-explorer/commit/10dee3eff21079cffaa28f134ad5a9118c1c1545)
> 
> Staging verified.

Please deploy it to the testnet at your convenience. @rabbitz

**Comment by rabbitz** [comment]
> > > PR: [nervosnetwork/ckb-explorer@10dee3e](https://github.com/nervosnetwork/ckb-explorer/commit/10dee3eff21079cffaa28f134ad5a9118c1c1545)
> > 
> > 
> > Staging verified.
> 
> Please deploy it to the testnet at your convenience. [@rabbitz](https://github.com/rabbitz)

Already deployed to testnet

**Comment by FrederLu** [comment]
> > > > PR: [nervosnetwork/ckb-explorer@10dee3e](https://github.com/nervosnetwork/ckb-explorer/commit/10dee3eff21079cffaa28f134ad5a9118c1c1545)
> > > 
> > > 
> > > Staging verified.
> > 
> > 
> > Please deploy it to the testnet at your convenience. [@rabbitz](https://github.com/rabbitz)
> 
> Already deployed to testnet

Testnet verified.
