### ISSUE TITLE
The `confirmations` data in the `rgb_digest` api is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#693]
Testnet request URL:  https://testnet-api.explorer.nervos.org/api/v2/ckb_transactions/0x57c3944a8db143c9b1bc5402a2b2ddabbf3fa668d75495a90b1f9485b5769530/rgb_digest
<img width="1439" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b79238e9-d115-49a1-85c7-999b4a6638d7">

Staging request URL:
https://ckb-explorer-api-staging.magickbase.com/api/v2/ckb_transactions/0x57c3944a8db143c9b1bc5402a2b2ddabbf3fa668d75495a90b1f9485b5769530/rgb_digest
<img width="1349" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/fc2ad2c1-6815-441d-aee6-ea09a9bf7611">

The `confirmations` information in the `rgb_digest` interface on Testnet is abnormal compared to the staging data.

**Comment by rabbitz** [comment]
Directly obtain confirmations from a raw Bitcoin transaction (the transaction may come from testnet or signet), with a cache expiration time of 30 seconds. You can observe further.

**Comment by FrederLu** [comment]
> Directly obtain confirmations from a raw Bitcoin transaction (the transaction may come from testnet or signet), with a cache expiration time of 30 seconds. You can observe further.

Now the data of the two are synchronized. If it is a cache problem, I will pay attention to it later.
