### ISSUE TITLE
Out-of-dated script cell deps info

### ISSUE THREAD

**Issue by Hanssen0** [Magickbase/ckb-explorer-public-issues#695]
For the Omni lock script, the explorer currently shows a cell dep that was dead in January 2024.

We should consider:
A. Update the cell dep out point manually.
B. Update the cell dep out point automatically using the type script.
C. Remove the cell dep out point information, keep only document links.

**Comment by Keith-CY** [comment]
Hi, @Hanssen0 could you add a reference to the latest deployment info? A git commit of updating the deployment info would be great.

**Comment by Hanssen0** [comment]
> Hi, @Hanssen0 could you add a reference to the latest deployment info? A git commit of updating the deployment info would be great.

See https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0042-omnilock/0042-omnilock.md#notes

**Comment by Keith-CY** [comment]
Should be updated by https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1650
