### ISSUE TITLE
Add sync service for BTC Time Lock Cell

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#698]
对于RGB交易，多数情况Output 中含有 RGB++ Lock，这是因为在转账的时候通常会有找零到原地址的情况。
当一笔L1->L1交易 Input的BTC地址 转完所有的XUDT的时候，就会出现 Output中只有BTC Time Lock 的交易，对于这种交易，应该也进行类型判断。因此，对当前的RGB++ 交易作出如下调整：

1. 对于Output 或 Input 中含有  RGB++ Lock 或 BTC Time Lock 的交易都进行如下图所示的类型判断：

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/85155313/a9f35504-b78f-43ad-b652-e7f3331052b0)

2. 对于 L1->L1 ismorphic 和 L1->L2 ismorphic 两种类型的交易展示 RGB++ digest，其内容为RGB++ Lock Cell Commitment 对应的BTC 交易，与当前保持一致。

**Comment by FrederLu** [comment]
Leave a message and attach `Btc time lock` data information.
https://ckb-explorer-frontend-in-magickbase-repo-okomdwwgi-magickbase.vercel.app/transaction/0x57872f2f13d1b0e583d66d5c2ee5b9ce10d775427eddcc988d413e6a873ec72f
