### ISSUE TITLE
Detect CoTA Cell and mark label

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#70]

**Comment by iamyates** [comment]
refer:  https://www.cotadev.io/docs/guides/contract-deployment

There are two cota types:  
1. cota registry cell
2. cota regular cell 

PR to develop branch.  https://github.com/nervosnetwork/ckb-explorer/pull/1028

**Comment by Keith-CY** [comment]
UI design: https://github.com/Magickbase/visual-style-guide/issues/8

**Comment by Keith-CY** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1042/commits/877338cc708a568d8f267ffae12e4e607c2679a1

**Comment by iamyates** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1048
