### ISSUE TITLE
Mark RGB++ Info for Signet

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#700]
This feature request comes from the community

There will be one more BTC testnet, named `signet`(https://mempool.space/signet) for the RGB++ application because the performance of BTC testnet was impacted.

The following updates are required:

1. verify the transaction on BTC testnet and BTC signet simultaneously when an RGB++ transaction is synced @rabbitz 
2. deploy one more BTC live UTXO monitor for the signet @Daryl-L 
3. Mark the new cell config in the frontend @Keith-CY 

---
Ref: 
- Support BTC signet network: https://github.com/ckb-cell/typeid-contract-cell-deps/pull/4/files#diff-66c441555523cc5f71a1d1badbb91da5184b9177882553b34fdc593af3931648R17-R20

**Comment by Keith-CY** [comment]
3. Mark new cell config in the frontend will by updated by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/18f54cbfe236826b242b1d190b458abaeabaa59f

**Comment by Daryl-L** [comment]
bitcoin check service has already been deployed for signet, testnet and the mainnet.

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/1966

**Comment by FrederLu** [comment]
Testnet verified.
