### ISSUE TITLE
The  pending transaction's rate limit of  CKB node websocket push from pool 

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/ckb-explorer-public-issues#704]
In explorer infra,  we have a websocket process to subscribe pending tx from ckb node. And another process to sync latest block.
  In our latest test we push about 10k transaction to the pending tx pool, but from explorer's websocket process, we only receive about 3k transaction and save them to our database. Others were direct synced with latest block.
  So does websocket can push all pending transactions in realtime and  before these transaction merge into committed tx?

**Comment by Keith-CY** [comment]
Issue opened at https://talk.nervos.org/t/performance-issue-about-websocket-of-ckb-node/8248

**Comment by zmcNotafraid** [comment]
use https://github.com/faye/faye-websocket-ruby replace current websocket client

**Comment by zmcNotafraid** [comment]
After test, the ckb node cpu has recached limit.So the pool syner only receiver 20k+ transactions then hang out.

**Comment by Keith-CY** [comment]
Is this done?

**Comment by zmcNotafraid** [comment]
> Is this done?

Wait https://github.com/Magickbase/ckb-explorer-public-issues/issues/419 to fix data firstly.

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2176
