### ISSUE TITLE
`Done` button functionality is missing.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#709]
https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/fe084bb9-e517-4c7a-8d0e-49aa11c8a845

<img width="1285" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/9b970e20-d260-447f-82ec-c72c2a210fe0">
<img width="1323" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/d7d16a34-2ece-4f33-ae31-b056335da818">

I found that the `Done` button does not work when selecting `Language` and `Node`. After making the corresponding selection, it will take effect without confirmation.

**Comment by PainterPuppets** [comment]
It feels like switching states directly should be intuitive to use. Is this `finish` more like the `close`?

I'm not sure, can you decide on the exact interaction logic? @Sven-TBD

**Comment by FrederLu** [comment]
Verified.
