### ISSUE TITLE
The `RGB++ Digest` popup window can be optimized.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#712]
https://explorer.nervos.org/xudt/0x178fb47b597a56d48b549226aff59f750b4784250c7f40f781b64ef090a8a0a7?page=2306

https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/510a4896-edc4-4c79-abac-eb1dfc9d0a62

When `RGB++ Digest` displays a large amount of data, two points can be optimized:
1. It takes about 5 seconds to open the `RGB++ Digest` window on the list page for the first time. At this time, the page does not display any information or prompts. Here, you can consider having a transition style when the data is not displayed.
2. The `RGB++ Digest` window is opened and tilted downward as a whole. It can be vertically centered.

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/411

**Comment by FrederLu** [comment]
> [Magickbase/ckb-explorer-frontend#411](https://github.com/Magickbase/ckb-explorer-frontend/pull/411)

Verified.
