### ISSUE TITLE
Add `DID` Cell

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#716]
Mainnet: DID_CELL_TYPE_ID=0xcfba73b58b6f30e70caed8a999748781b164ef9a1e218424a6fb55ebf641cb33
Testnet: DID_CELL_TYPE_ID=0x0b1f412fbae26853ff7d082d422c2bdd9e2ff94ee8aaec11240a5b34cc6e890f

`DID Cell` is a variant of `Spore Cell`, its cluster is exactly the same as `Spore Cluster`, resuing `Spore Cluster Script`, but its item cell is different from `Spore Cell`.

`DID Cell` uses its own `code_hash` and `hash_type`, while its `args` and `data` can be treated as a `Spore Cell`

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2000
