### ISSUE TITLE
Issue with RGB++ tab on `Cell info`.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#718]
https://ckb-explorer-frontend-in-magickbase-repo-1y5fq4lp3-magickbase.vercel.app/address/tb1qd5q7hs0q0px6qj55j2nkkhjgm2zep7765zjyhs

<img width="1384" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/31a1d82d-46f1-47e7-89ac-e54bf20f99ff">

1、There is a problem with the external link jump under the newly added RGB++ tab. It needs to jump to Signet/Testnet. Currently it jumps to Mainnet.

---
UI：

![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/2542aa05-5efe-4751-967a-7a63a7f88981)

<img width="1369" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/8e69aa19-edee-4e69-ba12-10e20d0bc871">
<img width="1271" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/6fc1fc38-9b49-4fa4-a0af-dfd698e610fe">

2、RGB++ tooltip is now the same as `Capacity Usage`.

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/402

**Comment by FrederLu** [comment]
> [Magickbase/ckb-explorer-frontend#402](https://github.com/Magickbase/ckb-explorer-frontend/pull/402)

Verified.
