### ISSUE TITLE
The size of the `View Asset Distribution` card needs to be adjusted.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#719]
<img width="1251" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/eb11944c-2e75-4c9f-a2ba-b03ca8080450">

<img width="1245" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/1dfc8b14-d121-4259-ac5c-f1a5db9fed87">

The size of the `View Asset Distribution` card under the RGB++ tab must be consistent with the `View Asset Amounts (CKB excluded)`.

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/401

**Comment by FrederLu** [comment]
> [Magickbase/ckb-explorer-frontend#401](https://github.com/Magickbase/ckb-explorer-frontend/pull/401)

Verified.
