### ISSUE TITLE
Add page of a script/contract

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#72]
Similar to tracing data of a contract account on [etherscan](https://etherscan.io/), the page of a specific script/contract is necessary on [ckb explorer](https://explorer.nervos.org/). But there's a difference between locating a script on CKB and locating a contract on Ethereum.

On Ethereum, a contract is also an account so it can be located by its address as [USDT](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7).

But on CKB, a user account is located by an address that is a representation of `lock script`, namely a combination of `code hash`, `hash type`, `args`, while a `script/contract` is located by `code hash` and `hash type`.

So the feature request is as follows:
1. the page could be located by a combination of `code hash` and `hash type`. Compared to the location of an address, the `args` of the `script` doesn't matter.
2. the page could be located by `type id: {args}` which equals to `code hash of type id script` + `hash type of type id script` + `args as type id`, it's a special use case on CKB
	- Refs: 
		- https://github.com/Magickbase/ckb-wallet-and-explorer/wiki/type-id-%E5%90%88%E7%BA%A6
		- https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0022-transaction-structure/0022-transaction-structure.md#type-id
3. display
	- list of live cells used as deployment of the script: notice that the same script could be deployed multiple times
		- outpoint
		- capacity
		- data
		- lock script
		- type script
	- list of live cells using this script
		- outpoint
		- capacity
		- data
		- lock script
		- type script
	- total capacity of live cells using this script
	- transaction list: transactions which have input/output using this script, returned data structure is the same as transactions on an address page

---

Take the `secp256k1_blake160` lock script(default lock script) as an example.

The default lock script could be referenced by `code hash: 0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8` and `hash type: type`

Supposed the script page is located by `/script/{code_hash}/{hash_type}`, the default script page would be `/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type`

Since the default lock script is deployed in the genesis block, **list of live cells used as deployment of the script** will have one cell which is pointed by `tx hash: 0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c` and `index: 0x0` as RFC said https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0024-ckb-genesis-script-list/0024-ckb-genesis-script-list.md

Because addresses `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfz9rdwxs84saj8xcknrclsf4a9r7qk3hqqsv05e` and `ckb1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdy46j0t82lw0pwlc4y3m8w5mp2k5c633c34jr96` are both using the default lock script, all of their cells will be listed in **list of live cells using this script** and all of their transactions will be included in **transaction list of the script**

**Comment by Keith-CY** [comment]
Here's a new feature request to show data of a specific script, quite similar to the page of a specific address except `address` is located by `code hash + hash type + args` while `script` is located by `code hash + hash type`.

Any questions could be appended to this issue.

**Comment by Keith-CY** [comment]
Should we finish the refactoring of migrating indices from `address` to `lock script` before supporting this feature? @ShiningRay

**Comment by Keith-CY** [comment]
- ? Active addresses

**Comment by zgayjjf** [comment]
Looks great!

Only have one little suggestion: the URL format `/script/{code_hash}_{hash_type}` seems a bit strange. `/script/{code_type}/{hash_type}` seems better to me.

This way, we can parse the `code_hash` easily from the URL, and users can simply copy & paste `code_hash`.

However, it's only a personal opinion. The whole idea is great!

**Comment by Keith-CY** [comment]
> Looks great!
> 
> Only have one little suggestion: the URL format `/script/{code_hash}_{hash_type}` seems a bit strange. `/script/{code_type}/{hash_type}` seems better to me.
> 
> This way, we can parse the `code_hash` easily from the URL, and users can simply copy & paste `code_hash`.
> 
> However, it's only a personal opinion. The whole idea is great!

It was designed to be `{code_hash}_{hash_type}` because they are at the same level in terms of a script, but `{code_hash}/{hash_type}` is clear enough too while it's more efficient for programming.

I'll replace `{code_hash}_{hash_type}` with `{code_hash}/{hash_type}`

**Comment by Keith-CY** [comment]
It's confirmed that all product requirements will be met by this feature so we're going to add a PRD for it.

**Comment by Keith-CY** [comment]
The wireframe of PRD has been updated at https://qxbhb0.axshare.com/#id=nu5nri please have a review @ShiningRay @iamyates @Kirl70

**Comment by Kirl70** [comment]
> The wireframe of PRD has been updated at https://qxbhb0.axshare.com/#id=nu5nri please have a review @ShiningRay @iamyates @Kirl70

Draft design based on wireframe drawing, please review 

Script/Contract Transactions Page :
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A44725
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/106060898/200124096-29f06f46-d761-4f33-90d7-f24f9fe5bf2b.png">

Deployed Cells : 
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45389
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/106060898/200123293-a33a4494-a4b4-4e4c-9490-bc46af838d90.png">

Deployed Cell Info :
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45704
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/106060898/200124222-85772993-8abe-4216-afde-ae9ab5756c1a.png">

Referring Cells :
https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45592
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/106060898/200123892-e153e98a-dc10-46c0-8bfe-4b62a0e76f2a.png">

One more question, where is the entrance to the page?

**Comment by Keith-CY** [comment]
> > The wireframe of PRD has been updated at [qxbhb0.axshare.com/#id=nu5nri](https://qxbhb0.axshare.com/#id=nu5nri) please have a review @ShiningRay @iamyates @Kirl70
> 
> Draft design based on wireframe drawing, please review
> 
> Script/Contract Transactions Page : [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A44725](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A44725) <img alt="image" width="1185" src="https://user-images.githubusercontent.com/106060898/200124096-29f06f46-d761-4f33-90d7-f24f9fe5bf2b.png">
> 
> Deployed Cells : [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45389](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45389) <img alt="image" width="1014" src="https://user-images.githubusercontent.com/106060898/200123293-a33a4494-a4b4-4e4c-9490-bc46af838d90.png">
> 
> Deployed Cell Info : [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45704](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45704) <img alt="image" width="1042" src="https://user-images.githubusercontent.com/106060898/200124222-85772993-8abe-4216-afde-ae9ab5756c1a.png">
> 
> Referring Cells : [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45592](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45592) <img alt="image" width="1049" src="https://user-images.githubusercontent.com/106060898/200123892-e153e98a-dc10-46c0-8bfe-4b62a0e76f2a.png">
> 
> One more question, where is the entrance to the page?

There would be 2 entries
1. From `lock/type script info` in cell info dialog on Transaction page, maybe a button next to the `Copy`
![image](https://user-images.githubusercontent.com/7271329/200135619-fd277644-6551-4b2a-b008-11224bce6da1.png)
2. From registered script list at https://explorer.nervos.org/scripts

**Comment by Keith-CY** [comment]
> > The wireframe of PRD has been updated at [qxbhb0.axshare.com/#id=nu5nri](https://qxbhb0.axshare.com/#id=nu5nri) please have a review @ShiningRay @iamyates @Kirl70
> 
> Draft design based on wireframe drawing, please review
> 
> Script/Contract Transactions Page : [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A44725](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A44725) <img alt="image" width="1185" src="https://user-images.githubusercontent.com/106060898/200124096-29f06f46-d761-4f33-90d7-f24f9fe5bf2b.png">
> 
> Deployed Cells : [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45389](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45389) <img alt="image" width="1014" src="https://user-images.githubusercontent.com/106060898/200123293-a33a4494-a4b4-4e4c-9490-bc46af838d90.png">
> 
> Deployed Cell Info : [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45704](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45704) <img alt="image" width="1042" src="https://user-images.githubusercontent.com/106060898/200124222-85772993-8abe-4216-afde-ae9ab5756c1a.png">
> 
> Referring Cells : [figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45592](https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=6172%3A45592) <img alt="image" width="1049" src="https://user-images.githubusercontent.com/106060898/200123892-e153e98a-dc10-46c0-8bfe-4b62a0e76f2a.png">
> 
> One more question, where is the entrance to the page?

The style of tabs is different from that on NFT page(https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5730%3A24719)
Will the tabs on NFT page be updated too?

**Comment by Kirl70** [comment]
Entry design on the transaction page, make the entrance into a button display, more convenient for users to view

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5653%3A25054

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/106060898/200162718-8eb74b2a-b122-49dd-ae04-4d3e078831fb.png">

**Comment by Kirl70** [comment]
Yes, due to historical legacy issues resulting in inconsistent label styles, it is now necessary to unify the style, and note that there are two areas that need to be adjusted, as shown in the figure

Before:
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/106060898/200162156-a68750f6-cd8e-4904-8fcc-054e5e96ed6e.png">

After:
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/106060898/200162198-2d58d91b-8c1e-4013-9633-9c6b74e0a633.png">

https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=5730%3A24719

**Comment by iamyates** [comment]
@Keith-CY  what about this api response format?  

### API usage: 

GET `localhost:3000/api/v1/scripts/details?code_hash=0x00000000000000000000000000000000000000000000000000545950455f4944&hash_type=type`

### response json: 

```
{
    "data": {
        "id": "1",
        "type": "script",
        "attributes": {
            "code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944",
            "hash_type": "type",
            "capacity_of_deployed_cells": "10000000000000.0",
            "capacity_of_referring_cells": "126496300000000.0",
            "deployed_cells": [
                {
                    "data": {
                        "id": "2",
                        "type": "data",
                        "attributes": {
                            "data": "0x7f454c46"
                        }
                    }
                }
            ],
            "referring_cells": [
                {
                    "data": {
                        "id": "1",
                        "type": "data",
                        "attributes": {
                            "data": "0x6c696e61"
                        }
                    }
                },
                {
                    "data": {
                        "id": "2",
                        "type": "data",
                        "attributes": {
                            "data": "0x7f454c46"
                        }
                    }
                },
                {
                    "data": {
                        "id": "3",
                        "type": "data",
                        "attributes": {
                            "data": "0x7f454c46"
                        }
                    }
                },
                {
                    "data": {
                        "id": "4",
                        "type": "data",
                        "attributes": {
                            "data": "0x9817f816"
                        }
                    }
                },
                {
                    "data": {
                        "id": "5",
                        "type": "data",
                        "attributes": {
                            "data": "0x7f454c46"
                        }
                    }
                },
                {
                    "data": {
                        "id": "672",
                        "type": "data",
                        "attributes": {
                            "data": "0x02000000"
                        }
                    }
                },
                {
                    "data": {
                        "id": "673",
                        "type": "data",
                        "attributes": {
                            "data": "0x02000000"
                        }
                    }
                }
            ],
            "transactions": [
                {
                    "data": {
                        "id": "2",
                        "type": "ckb_transaction",
                        "attributes": {
                            "is_cellbase": false,
                            "witnesses": [
                                "0x3ed693609d3ff7049415d33a2fff8eed581cf2790fae4785e27793330cfd55a6109b84a94494eae64217339bc9aafdf4e6453964c90e6752d96e20d127ca874901"
                            ],
                            "cell_deps": [
                                {
                                    "dep_type": "code",
                                    "out_point": {
                                        "index": 3,
                                        "tx_hash": "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c"
                                    }
                                },
                                {
                                    "dep_type": "code",
                                    "out_point": {
                                        "index": 1,
                                        "tx_hash": "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c"
                                    }
                                }
                            ],
                            "header_deps": null,
                            "tx_status": "committed",
                            "detailed_message": null,
                            "transaction_hash": "0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c",
                            "transaction_fee": "0",
                            "block_number": "0",
                            "version": "0",
                            "block_timestamp": "1573852190812",
                            "display_inputs": [
                                {
                                    "id": "6",
                                    "from_cellbase": false,
                                    "capacity": "23400000000.0",
                                    "address_hash": "ckb1qpcf7076zt6krnavly3883t6nrlduxy28ud9nv0c3rg387wvuzryjq9h89s7gmv7kyvd8hsar68npva00wlnzcqgh76tz",
                                    "generated_tx_hash": "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c",
                                    "cell_index": "5",
                                    "cell_type": "normal",
                                    "since": {
                                        "raw": "0x0000000000000000",
                                        "median_timestamp": "1573852190812"
                                    }
                                }
                            ],
                            "display_outputs": [
                                {
                                    "id": "672",
                                    "capacity": "11700000000.0",
                                    "address_hash": "ckb1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq4maw7d",
                                    "status": "live",
                                    "consumed_tx_hash": "",
                                    "cell_type": "normal"
                                },
                                {
                                    "id": "673",
                                    "capacity": "11700000000.0",
                                    "address_hash": "ckb1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq4maw7d",
                                    "status": "live",
                                    "consumed_tx_hash": "",
                                    "cell_type": "normal"
                                }
                            ],
                            "income": null,
                            "bytes": 0
                        }
                    }
                }
            ]
        }
    }
}
```

**Comment by iamyates** [comment]
please review this PR: https://github.com/nervosnetwork/ckb-explorer/pull/1070

**Comment by Keith-CY** [comment]
> here are some request examples:
> 
> [ckb-explorer-api.staging.layerview.io/api/v2/scripts/deployed_cells?code_hash=0x00000000000000000000000000000000000000000000000000545950455f4944&hash_type=type](https://ckb-explorer-api.staging.layerview.io/api/v2/scripts/deployed_cells?code_hash=0x00000000000000000000000000000000000000000000000000545950455f4944&hash_type=type)
> 
> ![image](https://user-images.githubusercontent.com/105087155/208897973-8890169a-72c9-4bb8-a925-0f585c9b86e8.png)
> 
> [ckb-explorer-api.staging.layerview.io/api/v2/scripts/ckb_transactions?code_hash=0x00000000000000000000000000000000000000000000000000545950455f4944&hash_type=type](https://ckb-explorer-api.staging.layerview.io/api/v2/scripts/ckb_transactions?code_hash=0x00000000000000000000000000000000000000000000000000545950455f4944&hash_type=type)
> 
> ![image](https://user-images.githubusercontent.com/105087155/208897811-54e7ef72-6b07-4fff-b160-3ceb28ab50f4.png)
> 
> [ckb-explorer-api.staging.layerview.io/api/v2/scripts/referring_cells?code_hash=0x00000000000000000000000000000000000000000000000000545950455f4944&hash_type=type](https://ckb-explorer-api.staging.layerview.io/api/v2/scripts/referring_cells?code_hash=0x00000000000000000000000000000000000000000000000000545950455f4944&hash_type=type)
> 
> ![image](https://user-images.githubusercontent.com/105087155/208897891-f8dac6e5-9af8-4953-8a59-d98e8ec4fcb7.png)

The example of `referring cells` returns an empty array

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1158

**Comment by pygman** [comment]
This is the implementation of frontend, please review 
https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1158

**Comment by pygman** [comment]
The commit to hide `Capacity Of Referring Cells` and `Referring Cells` tab
https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1158/commits/af5687103f627fe1ccdf70ddc309032af36fc87f

**Comment by Keith-CY** [comment]
> After discussion, we think that the `referring_cells` function seems very complex, so I suggest that let's make other functions deployed to production:
> 
> 1. general_info
> 2. transactions
> 3. deployed_cells
> 
> ![Image](https://user-images.githubusercontent.com/105087155/211712574-b69521a5-6111-4058-9ed6-2d1b956d45c0.png)
> 
> for the last function: `referring_cells` ( in the picture above, in blue rectangle), we need to finish these 3 issues firstly and then make this feature done.
> 
> related issues: (and maybe more)
> 
> 1. [Create Contract model #157](https://github.com/Magickbase/ckb-explorer-public-issues/issues/157)
> 2. [Create DeployedCell model and fill hash_type:'type' records #156](https://github.com/Magickbase/ckb-explorer-public-issues/issues/156)
> 3. [Extract script details to a unified model #158](https://github.com/Magickbase/ckb-explorer-public-issues/issues/158)

Could we deploy the `overview`, `transaction list`, and `deployed cells` now? @iamyates

**Comment by Keith-CY** [comment]
How is the `referring cells` going @Danie0918 @Sven-TBD

**Comment by rabbitz** [comment]
Related PR: https://github.com/nervosnetwork/ckb-explorer/pull/1416

**Comment by FrederLu** [comment]
Record it.
![Image](https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/d173c98c-b5e3-4292-80ca-9e428602cdef)

**Comment by Keith-CY** [comment]
> Record it. ![Image](https://user-images.githubusercontent.com/25676576/266548084-d173c98c-b5e3-4292-80ca-9e428602cdef.png)

Add detail of `type id`

The `type id` field is only valid when the script is referred to by `type id script`.

`type id script` is a special `script`, its code_hash and hash_type are hard-coded in ckb node. Specifically, its code_hash is semantic because it derives from text `TYPE ID` 

Try `TYPE ID` at https://onlinehextools.com/convert-utf8-to-hex and compare the result with `0x00000000000000000000000000000000000000000000000000545950455f4944`, the `type script code hash` of omnilock(https://explorer.nervos.org/script/0xa4398768d87bd17aea1361edc3accd6a0117774dc4ebc813bfa173e8ac0d086d/type/deployed_cells?page=1&size=10)

When the `type id script` is detected in CKB-VM, the code built-in CKB node will be executed instead of locating a live cell containing the execution code. So `type id script` can be treated as an internal script.

Back to the display of `type id` field. If the script has specific `code_hash: 0x00000000000000000000000000000000000000000000000000545950455f4944` and `hash_type: type`. It should be treated as a `type id script` and the `type id` can be calculated by `computeScriptHash` function at https://github.com/ckb-js/lumos/blob/ed5dc56de240c31b803dcd3cf849a89466f101ed/packages/base/src/utils.ts#L53

Ref: 
- type id contract: https://github.com/Magickbase/shaping/wiki/type-id-%E5%90%88%E7%BA%A6

**Comment by rabbitz** [comment]
typeID related pr: https://github.com/nervosnetwork/ckb-explorer/pull/1451

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/105
