### ISSUE TITLE
`View Asset Distribution` External link jump no transaction found.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#720]
https://pudge.explorer.nervos.org/address/tb1qdj3cv8jktgvl4ey4h7v24xuthc8ta99gj4a6pf

<img width="1230" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/f6b63a90-0492-4645-8be4-50a691fce649">

<img width="1308" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/25dadfe7-6e32-4af5-baf6-6d3657556e82">

The card jump link `Transaction Not Found` on `View Asset Distribution`.

**Comment by Daryl-L** [comment]
Wrong data from the API @rabbitz

**Comment by rabbitz** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2061

rgb cells API should return BTC transaction txid.

**Comment by FrederLu** [comment]
> PR: [nervosnetwork/ckb-explorer#2061](https://github.com/nervosnetwork/ckb-explorer/pull/2061)
> 
> rgb cells API should return BTC transaction txid.

Verified.
