### ISSUE TITLE
Open sources script could be lightspotted to get more attention

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#722]
This feature request comes from the community.

---

A link to the source code will be available on the script list page if the script is open-sourced
<img width="792" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/ea0d23e2-c35d-475a-a0cb-7252a4e4f7cd">

If the open-sourced script and its tag are more noticeable and attract more attention, more teams would be inclined to reveal the source code.

**Comment by Kirl70** [comment]
We can add an `Open Source` tag to the list and place an `open source icon` in front of the tag.

https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=40117-52876&t=IYZtnwKd8IA9SeYA-1
<img width="1394" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/b03f95a5-efd2-4ac1-a5d8-0d4c82dd96a2">

<img width="450" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/106060898/ed3cc980-f3a4-4744-a112-0d52fd32e5e3">

**Comment by Keith-CY** [comment]
I think the intention is to highlight `open-sourced` script in other places because the `source code` link already implies that this one is open-sourced.

BTW, general users won't visit the script list page. Most visitors are developers.

The highlight could be added, e.g.
<img width="1079" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/b7110bfa-153c-4161-9d53-bcff9c705d85">
<img width="1035" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/56f2d411-a1b6-42a9-b5dc-dbde38a6fa01">
<img width="1246" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/3f9a3f74-1323-42b3-9248-4a533f4e1585">
<img width="1304" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/7271329/76f5f1a9-f025-407b-9fac-d4e09253339c">

A token will be more reliable when its code is open-sourced.

cc @Sven-TBD

**Comment by Kirl70** [comment]
Can you create a PRD to explain how the adjustments should be made? @Sven-TBD

**Comment by Kirl70** [comment]
Display the open-source icon in the specified location with the corresponding tooltip. 
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=33413-35843&t=kMIJoxafkCj1AINj-1
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/d3f2da2f-a783-4406-988f-18825d90bc50">

Show the open-source tag in the XUDT list header.
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=36828-30133&t=kMIJoxafkCj1AINj-1
<img width="333" alt="image" src="https://github.com/user-attachments/assets/6c7ba349-039f-458b-875b-300a5ab024b1">

**Comment by Keith-CY** [comment]
I found another page that should be marked with `open source`
Script detail page: https://explorer.nervos.org/script/0x70d64497a075bd651e98ac030455ea200637ee325a12ad08aff03f1a117e5a62/type

**Comment by Keith-CY** [comment]
> I would recommend to put it here <img alt="image" width="1327" src="https://private-user-images.githubusercontent.com/85155313/352378786-64ac8036-f57c-4675-9721-ae3fa07b94c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzI1NDMsIm5iZiI6MTcyMTk3MjI0MywicGF0aCI6Ii84NTE1NTMxMy8zNTIzNzg3ODYtNjRhYzgwMzYtZjU3Yy00Njc1LTk3MjEtYWUzZmEwN2I5NGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA1MzcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYWNkNjQ3ZTE5OTU0ZGZhOWE4ZGY0ZTQ2M2Q1MmQ2YzU1Yjc2ZjdhOWViNGViM2RhNDZkNjIzMTcxYTQ2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gH2d0UvMKIntc6FeiR0SK3x0zT2CUPWJxF1_AlFP4Qk"> @Kirl70 cc @Keith-CY

Not every script has its `type id`, only those can be referenced by `type script` have `type id`.

Maybe we can add a new field for the script to denote its feature, e.g. `open-sourced`, `token`, `swap`, `stake`, etc.

**Comment by Keith-CY** [comment]
> > > I would recommend to put it here <img alt="image" width="1327" src="https://private-user-images.githubusercontent.com/85155313/352378786-64ac8036-f57c-4675-9721-ae3fa07b94c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzI1NDMsIm5iZiI6MTcyMTk3MjI0MywicGF0aCI6Ii84NTE1NTMxMy8zNTIzNzg3ODYtNjRhYzgwMzYtZjU3Yy00Njc1LTk3MjEtYWUzZmEwN2I5NGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA1MzcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYWNkNjQ3ZTE5OTU0ZGZhOWE4ZGY0ZTQ2M2Q1MmQ2YzU1Yjc2ZjdhOWViNGViM2RhNDZkNjIzMTcxYTQ2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gH2d0UvMKIntc6FeiR0SK3x0zT2CUPWJxF1_AlFP4Qk"> @Kirl70 cc @Keith-CY
> > 
> > 
> > Not every script has its `type id`, only those can be referenced by `type script` have `type id`.
> > Maybe we can add a new field for the script to denote its feature, e.g. `open-sourced`, `token`, `swap`, `stake`, etc.
> 
> Yes, we can add an other field for script. open-sourced is easy to added currently, however, about the other tags, should we add it by a vote function as well? @Keith-CY

These scripts are submitted or collected manually(almost all scripts come from partners) so the tags can be added based on their feedbacks.

**Comment by Keith-CY** [comment]
> > > > I would recommend to put it here <img alt="image" width="1327" src="https://private-user-images.githubusercontent.com/85155313/352378786-64ac8036-f57c-4675-9721-ae3fa07b94c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzI1NDMsIm5iZiI6MTcyMTk3MjI0MywicGF0aCI6Ii84NTE1NTMxMy8zNTIzNzg3ODYtNjRhYzgwMzYtZjU3Yy00Njc1LTk3MjEtYWUzZmEwN2I5NGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA1MzcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYWNkNjQ3ZTE5OTU0ZGZhOWE4ZGY0ZTQ2M2Q1MmQ2YzU1Yjc2ZjdhOWViNGViM2RhNDZkNjIzMTcxYTQ2NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gH2d0UvMKIntc6FeiR0SK3x0zT2CUPWJxF1_AlFP4Qk"> @Kirl70 cc @Keith-CY
> > > 
> > > 
> > > Not every script has its `type id`, only those can be referenced by `type script` have `type id`.
> > > Maybe we can add a new field for the script to denote its feature, e.g. `open-sourced`, `token`, `swap`, `stake`, etc.
> > 
> > 
> > Yes, we can add an other field for script. open-sourced is easy to added currently, however, about the other tags, should we add it by a vote function as well? @Keith-CY
> 
> These scripts are submitted or collected manually(almost all scripts come from partners) so the tags can be added based on their feedback.

`scripts` are kinda different from `assets`, `scripts` are actually `protocols`, and it's always easy to find `protocols` authors.

**Comment by Kirl70** [comment]
> I found another page that should be marked with `open source` Script detail page: https://explorer.nervos.org/script/0x70d64497a075bd651e98ac030455ea200637ee325a12ad08aff03f1a117e5a62/type

Placement on the Script detail page
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=25191-24146&t=HUCa5F03ljf1xP9R-1
<img width="1171" alt="image" src="https://github.com/user-attachments/assets/ad9fbfb8-1aa9-4791-a80a-a69f41d85b29">
