### ISSUE TITLE
Support script filters on API of getting contract resource distribution

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#729]
This feature request comes from the community

---

Now there's an API(https://mainnet-api.explorer.nervos.org/api/v2/statistics/contract_resource_distributed) to get the contract resource distribution

It covers 80 scripts.

The user want to focus on a set of scripts, so they wonder if a filter of code hashes can be supported for the API, e.g.

https://mainnet-api.explorer.nervos.org/api/v2/statistics/contract_resource_distributed?code_hashes=code_hash_1,code_hash_2

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2042
