### ISSUE TITLE
The font color and label color of the label need to be optimized and adjusted.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#737]
<img width="311" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/a7af566a-3637-4caf-b2d4-4061166831ec"><img width="347" alt="image" src="https://github.com/Magickbase/ckb-explorer-frontend/assets/25676576/fd5d04ce-9479-40ee-9976-792a02343bbd">

It is found that the font color of the current label is different from the UI and needs to be adjusted according to the UI. Some labels have incorrect fonts and label colors (such as Verified on Platform).

<img width="1175" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/9593d9af-26cc-46eb-be68-bd2e98d026f2">
<img width="579" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/11a46588-90fa-488d-9044-00c31a238f33">

At the same time, the label font displayed by the page xudt also needs to be adjusted.

**Comment by Daryl-L** [comment]
Only 3 tags left, they are the same as the desgin draft

**Comment by FrederLu** [comment]
Verified.
