### ISSUE TITLE
Individual data in the `Depositors` list requires confirmation.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#744]
https://ckb-explorer-frontend-in-magickbase-repo-njk190r6m-magickbase.vercel.app/en/nervosdao/depositor/export?end-date=2024-07-10&start-date=2020-01-01&tab=date

https://ckb-explorer-frontend-in-magickbase-repo-njk190r6m-magickbase.vercel.app/en/nervosdao?tab=depositors
<img width="1430" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/69d5cb23-67db-42f1-ab11-6a80ad4a5c65">
<img width="1260" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/fe9ed16f-67e0-4818-9d9c-461c2e9ddf30">
<img width="1437" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/52c51600-d65e-4121-9254-99f0e58ee28e">
<img width="1244" alt="image" src="https://github.com/Magickbase/ckb-explorer-public-issues/assets/25676576/b2b8a1e1-d2c6-442e-958f-a408d999d531">

After exporting all the data, I found that `ckt1qz965q043w4tpj6clscezdh2fa5xdm2ecv3l499l044h904zr36duqqps28tt4wpw70ulcf7ylhtlqr5zqz9pke4kkx62n8wee34k3lkpvxshjmm3s`
`ckt1qrejnmlar3r452tcg57gvq8patctcgy8acync0hxfnyka35ywafvkqgjzu0pgf4exdyj73untn5svekv9xvjgta5qq8696wg`
these two data are different from the data displayed on the page.   Need to confirm.

**Comment by rabbitz** [comment]
The DAO record for this address `ckt1qrejnmlar3r452tcg57gvq8patctcgy8acync0hxfnyka35ywafvkqgjzu0pgf4exdyj73untn5svekv9xvjgta5qq8696wg` is:

```ruby
[{"tx_hash"=>"0xeb18375e5675f5ab39b0ecaf0a368aae89a8b7bed93225560306e338e83e3ade", "event_type"=>"deposit_to_dao", "value"=>10000000000000, "created_at"=>"2024-06-23 21:41:01 +0800"},
 {"tx_hash"=>"0xeb18375e5675f5ab39b0ecaf0a368aae89a8b7bed93225560306e338e83e3ade", "event_type"=>"new_dao_depositor", "value"=>1, "created_at"=>"2024-06-23 21:41:01 +0800"},
 {"tx_hash"=>"0x7d65b22227b730efad4df7e8d9277427a757585669c784e61ef4df4e933761f9", "event_type"=>"deposit_to_dao", "value"=>5000000000000, "created_at"=>"2024-06-23 21:53:33 +0800"},
 {"tx_hash"=>"0x2e6018ab42bc8f63800223a0217c44f7dafe41913b9b999bcfe1b8ea5a765b8a", "event_type"=>"deposit_to_dao", "value"=>10400000000, "created_at"=>"2024-06-23 22:11:13 +0800"},
 {"tx_hash"=>"0xbeb8ee1f9813dfbfaeaca539f1d9fee9dbc1a4abea7e6489c760c3acf95dc16f", "event_type"=>"withdraw_from_dao", "value"=>10400000000, "created_at"=>"2024-06-23 22:17:03 +0800"},
 {"tx_hash"=>"0x60900375dfb77cc7a482b71eb52e76280e5ceac04ef1c1c1bc8051f2a438f83d", "event_type"=>"deposit_to_dao", "value"=>200000000000, "created_at"=>"2024-06-23 22:19:37 +0800"},
 {"tx_hash"=>"0x81ceac8e29a92785ed69eeeacc74d010717aee9fde2252349b1f76e2164ebecd", "event_type"=>"deposit_to_dao", "value"=>14700000000000, "created_at"=>"2024-06-24 08:36:05 +0800"},
 {"tx_hash"=>"0x2783fadc16b875dc0a0cb4e29a11b80b9ca5ff0b5686998b3c6fc4c061f2f01c", "event_type"=>"deposit_to_dao", "value"=>20000000000, "created_at"=>"2024-06-24 18:37:58 +0800"},
 {"tx_hash"=>"0xab3640ba0131b56f73883ee0b04f87cd95f99c725c484e8cbc89c159d1845833", "event_type"=>"deposit_to_dao", "value"=>20000000000, "created_at"=>"2024-06-30 15:55:12 +0800"},
 {"tx_hash"=>"0x30520c07fd27a61f3f10fda024fb3837836af4f34bbe942aa20756bdec806a22", "event_type"=>"deposit_to_dao", "value"=>34500000000, "created_at"=>"2024-06-30 15:59:24 +0800"}]
```

Thus, `sum(deposit_to_dao) - sum(withdraw_from_dao)` is `29974500000000`.

However, according to the provided export rules, `0x2e6018ab42bc8f63800223a0217c44f7dafe41913b9b999bcfe1b8ea5a765b8a` and `0x2e6018ab42bc8f63800223a0217c44f7dafe41913b9b999bcfe1b8ea5a765b8a` are both dead cells.

The final export result is the sum of `deposit_to_dao` live cells plus `10400000000` from `0x2e6018ab42bc8f63800223a0217c44f7dafe41913b9b999bcfe1b8ea5a765b8a`.

@FrederLu @Sven-TBD

**Comment by rabbitz** [comment]
The address `ckt1qz965q043w4tpj6clscezdh2fa5xdm2ecv3l499l044h904zr36duqqps28tt4wpw70ulcf7ylhtlqr5zqz9pke4kkx62n8wee34k3lkpvxshjmm3s` is affected because, in transactions such as `https://pudge.explorer.nervos.org/transaction/0xa827c41f919de8713ba38479c4869025d43673b623042f0dcae159f37a9bfb55`, the deposit and withdrawal addresses are not the same. In the database, the values are incremented or decremented while synchronizing blocks. However, the export report calculates the values based on the address.
