### ISSUE TITLE
Update the rule of xudt/dob tags

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#749]
The original rules are defined at https://github.com/Magickbase/ckb-explorer-public-issues/issues/620

The following updates will be adopted:

1. Remove `duplicate` tag
2. Exclude single `whitespace` from `invisible` characters set
	2.1 `word_1 word_2` is valid
	2.2 `word_1  word2` is invalid

**Comment by zmcNotafraid** [comment]
IS UTXO SWAP LP Token  THEN show `utility`, Not UTXO SWAP LP Token but duplicated SHOW `suspicious`

**Comment by zmcNotafraid** [comment]
xudt tags : ["unnamed", "invalid", "suspicious", "out-of-length-range", "rgb++", "layer-1-asset", "supply-limited", "utility", "layer-2-asset", "supply-unlimited"]
nft tags: ["invalid", "suspicious", "out-of-length-range", "rgb++", "layer-1-asset", "layer-2-asset"]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2084

**Comment by FrederLu** [comment]
Verified.

**Comment by Keith-CY** [comment]
Rule updated, `duplicate name` will be considered valid

**Comment by Keith-CY** [comment]
> Rule updated, `duplicate name` will be considered valid

Updated by https://github.com/nervosnetwork/ckb-explorer/pull/2167
