### ISSUE TITLE
An abnormal 404 request occurred.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#753]
https://pudge.explorer.nervos.org/block/13937252
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/e086a8c1-19f2-4d9c-a6a8-a2e172f8868b">

Request URL:
https://testnet-api.explorer.nervos.org/api/v1/block_transactions/?page=1&page_size=10

Refresh the page on the `Block` page and a 404 request will appear every time.

**Comment by Daryl-L** [comment]
https://github.com/Magickbase/ckb-explorer-frontend/pull/408

**Comment by FrederLu** [comment]
I saw this issue in Testing, but didn't see the link to the related PR. @Daryl-L

**Comment by FrederLu** [comment]
> [Magickbase/ckb-explorer-frontend#409](https://github.com/Magickbase/ckb-explorer-frontend/pull/409)

Verified.
