### ISSUE TITLE
Consider all xUDT as RGB++ Assets

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#754]
This feature request comes from the devrel team

---

At the current stage, the most powerful asset on CKB is RGB++, but the definition of RGB++ is kinda different between technique and market.

From a technical view, an asset can be considered as `RGB++ Asset` when it's owned by a `RGB++ Lock Script`.

But from the perspective of the market, all xUDT assets are potential `RGB++ Asset`.

Thus comes the feature request:

1. Rename tag `RGB++ Compatible` to `RGB++`
2. Mark all xUDT Assets as RGB++ Asset
3. Since All xUDT Assets are RGB++ Assets, the tag `RGB++` can be hidden at https://explorer.nervos.org/xudts, but the tag should remain on the page of a specific xUDT.

**Comment by Keith-CY** [comment]
`xUDT compatible` assets are not covered in this update.

**Comment by Keith-CY** [comment]
Please prioritize this issue @Sven-TBD

**Comment by Keith-CY** [comment]
1. rename `rgbpp-compatible` to `RGB++`
2. hide `RGB++` in xudt token list
3. display `RGB++` on xudt detail page
are updated by https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1716/commits/3dd5604c7b6279fc641a659414c7055bbe5702be

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2084

**Comment by FrederLu** [comment]
Verified.
