### ISSUE TITLE
Time series based "Balance distribution"

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#756]
This feature comes from the marketing team

---

Now we have a chart showing "current balance distribution" at https://explorer.nervos.org/charts/balance-distribution

The marketing team hopes to have a data set of "balance distribution on each day" to reflect the trending of balance distribution.

It could be delivered with an API without a chart.

**Comment by zmcNotafraid** [comment]
```
curl --request GET \
  --url https://mainnet-api.explorer.nervos.org/api/v1/daily_statistics/address_balance_distribution \
  --header 'Accept: application/vnd.api+json' \
  --header 'content-type: application/vnd.api+json'
```
Visit this API  @Keith-CY
