### ISSUE TITLE
Support `single-use-lock` script

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#759]
**Is your feature request related to a problem? Please describe.**
A new pattern named `single use lock`(https://talk.nervos.org/t/en-cn-misc-single-use-seals/8279/2), which is inspired by `RGB++`, was introduced on CKB.

They are now deployed on 

```json
# mainnet
    {
      "name": "single-use-lock",
      "tx_hash": "0x10d63a996157d32c01078058000052674ca58d15f921bec7f1dcdac2160eb66b",
      "index": 4,
      "occupied_capacity": 2783700000000,
      "data_hash": "0x8290467a512e5b9a6b816469b0edabba1f4ac474e28ffdd604c2a7c76446bbaf",
      "type_id": null,
      "hash_type": "data1"
    }
```

```json
# testnet
    {
      "name": "single-use-lock",
      "tx_hash": "0xb4f171c9c9caf7401f54a8e56225ae21d95032150a87a4678eac3f66a3137b93",
      "index": 4,
      "occupied_capacity": 2783700000000,
      "data_hash": "0x8290467a512e5b9a6b816469b0edabba1f4ac474e28ffdd604c2a7c76446bbaf",
      "type_id": null,
      "hash_type": "data1"
    }
```

The source code can be found at https://github.com/ckb-ecofund/ckb-proxy-locks

When an xUDT was issued by a `single-use-lock`, the token cannot be minted more because the owner is ephemeral, works as xUDT issued by an RGB++ Lock.

On-chain cases:

Mainnet: https://explorer.nervos.org/xudt/0x27ab2471d79c4953a614a7d60d0ad1d376e8110a6ac6046f4bd6b012533bdf2d
Testnet: https://pudge.explorer.nervos.org/xudt/0xcef135ddca02a931e5b21235fe42f81fe93b01a2161699db4b3a1ae0ac795ec8

**Describe the solution you'd like**
1. Mark as `limited supply` when a token(xudt, xudt-compatible, inscription, dob/spore) is issued with `single-use`lock`
2. Mark `single-use-lock` in script info

**Additional context**

Issue xudt with single-use-lock on testnet: https://ckbccc-demo.vercel.app/

**Comment by Keith-CY** [comment]
`Single use lock` marked on the page by https://github.com/nervosnetwork/ckb-explorer-frontend/commit/f5d844fc8f8a4528461c79d2bccf2a559ba48e3f
![image](https://github.com/user-attachments/assets/b054f401-f92e-44e3-bd0d-91a7e82ed117)
<img width="1143" alt="image" src="https://github.com/user-attachments/assets/b7a630b2-c9ca-42dc-9504-7081b41acc63">
<img width="933" alt="image" src="https://github.com/user-attachments/assets/fdcf5989-a065-42b0-a88a-ab5fc7fd2138">

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2122

**Comment by FrederLu** [comment]
Verified.
