### ISSUE TITLE
Add Google Analytics to frontend code

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#76]
In order to know our users better, I suggest add Google Analytics

**Comment by Keith-CY** [comment]
It was added before https://github.com/nervosnetwork/ckb-explorer-frontend/blob/develop/public/index.html#L42 I'm going to check with the developer who maintained it.

**Comment by Keith-CY** [comment]
The previous account is lost so we'll create a new one

**Comment by Keith-CY** [comment]
GA was updated by https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1083

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/195277951-0a6e94ad-e381-46ba-b27a-c06902598ab3.png)
