### ISSUE TITLE
Jumping to the udt list page displays an exception.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#760]
https://pudge.explorer.nervos.org/address/ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqfhw0xngm6d7vlfq6avlghle86emcjd7wcqzeta4

https://github.com/user-attachments/assets/e0e43364-ff56-4618-8393-4a7ebcd543ae

There was an abnormality when clicking on the udt jump page in the video.

**Comment by Daryl-L** [comment]
According to the code which written before, the description should only include the string, not the object. Is there any documents for this change?

![image](https://github.com/user-attachments/assets/a205b735-21b7-48e6-82ac-a73cbe16d2a3)


curl 'https://ckb-explorer-api-staging.magickbase.com/api/v2/nft/collections/0x3a45f82f87010a5e66861d6ece30bbc0fda98dce06b3f10c172e6819ad5716ab' \
  -H 'accept: application/vnd.api+json' \
  -H 'accept-language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
  -H 'if-none-match: W/"9534ee76567612f43415761651e2b521"' \
  -H 'origin: http://localhost:3000' \
  -H 'priority: u=1, i' \
  -H 'referer: http://localhost:3000/' \
  -H 'sec-ch-ua: "Not)A;Brand";v="99", "Microsoft Edge";v="127", "Chromium";v="127"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0'

**Comment by FrederLu** [comment]
> [Magickbase/ckb-explorer-frontend#419](https://github.com/Magickbase/ckb-explorer-frontend/pull/419)

Verified.
