### ISSUE TITLE
Clicking on the xudt detail page label has no effect.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#762]
**Describe the bug**
Clicking on the xudt detail page label has no effect.

**To Reproduce**
https://pudge.explorer.nervos.org/xudt/0xe6396293287fefb9f26d98eb0318fe80890908f0849226ad0c8cab2d62f1e351
When you hover the mouse over the screenshot label, it will become a click state, but clicking has no effect.

**Expected behavior**
Clicking a tag will return to the xudt list page and display the data filtered by the tag just clicked.

**Screenshots**
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/91b68b10-3b67-4a2d-8588-e923c5b96314">

**Comment by Kirl70** [comment]
Design Draft:
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=36828-30345&t=HUCa5F03ljf1xP9R-1
<img width="1177" alt="image" src="https://github.com/user-attachments/assets/bd413b55-5d7b-4cad-953f-0e8cb93d430b">
