### ISSUE TITLE
Script Detail page keeps loading the data

### ISSUE THREAD

**Issue by Sven-TBD** [Magickbase/ckb-explorer-public-issues#767]
**Describe the bug**
While landing on Script details [page](https://explorer.nervos.org/en/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type), the transaction data should be loaded here, but it either keeps loading all the time or shows no records.

**To Reproduce**
Click [This link](https://explorer.nervos.org/en/script/0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8/type)

**Expected behavior**
Transaction data should be displayed

**Screenshots**

![Image](https://github.com/user-attachments/assets/fdd14bcf-74c7-4b4d-b943-4afa007e52cd)

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2128
