### ISSUE TITLE
Add a new xudt-compatible script and token

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#775]
**Is your feature request related to a problem? Please describe.**

There's a new token issued with `xudt-compatible` script

```json
{
  "name": "RUSD",
  "symbol": "RUSD",
  "logo": "https://github.com/stablepp/media-kit/blob/main/stablecoin-RUSD.svg",
  "decimals": 8,
  "typeHash": "0x45b32a2bc4285d0a09678eb11960ddc8707bc2779887a09d482e9bfe9a2cdf52",
  "cmcId": "1",
  "typeScript": {
    "args": "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b",
    "codeHash": "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a",
    "hashType": "type"
  },
  "typeCellDep": {
    "outPoint": {
      "txHash": "0xf33fb0a7eb5c93530ab687ac8144599f295ff32e1db57085ee65b25d4381aa40",
      "index": 0
    },
    "depType": "code"
  },
  "extensions": {
    "links": {
      "official": "https://www.stablepp.xyz/",
      "twitter": "https://x.com/stablepp",
      "discord": "https://discord.com/invite/uwnMswHrgj",
      "telegram": "https://t.me/Stablepp",
      "github": "",
      "medium": "https://medium.com/@Stablepp",
      "youtube": ""
    }
  }
}
```

**But,** the token was not issued with `token info`, so its info should be added manually.

**Describe the solution you'd like**

1. add the new script as a `xudt-compatible` script, so tokens issued with this script will be regarded as `xudt-compatible` token
```json
  "typeCellDep": {
    "outPoint": {
      "txHash": "0xf33fb0a7eb5c93530ab687ac8144599f295ff32e1db57085ee65b25d4381aa40",
      "index": 0
    },
    "depType": "code"
  },
```
<del>2. mark the new script as `xudt-compatible`, which will be labeled on page(cell info, etc.)</del>other xudt-compatible scripts are not marked.
3. add token info of `RUSD` manually in the backend, thus transactions including the `RUSD` will be parsed clearly.

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2137

**Comment by Keith-CY** [comment]
Token can be visited directly at https://pudge.explorer.nervos.org/xudt/0x45b32a2bc4285d0a09678eb11960ddc8707bc2779887a09d482e9bfe9a2cdf52

But it doesn't appear in the search result

<img width="824" alt="image" src="https://github.com/user-attachments/assets/9d6d76bd-1dda-4fd9-ab3d-e2e5bd316b69">

**Comment by Keith-CY** [comment]
Mainnet info

```
script: 
	code_hash: 0x26a33e0815888a4a0614a0b7d09fa951e0993ff21e55905510104a0b1312032b
	hash_type: type
	args: 0x360c9d87b2824c357958c23e8878f686001e88e9527a08ea229e7d9ba7fe39a7

out_point:
	tx_hash: 0x8ec1081bd03e5417bb4467e96f4cec841acdd35924538a35e7547fe320118977
	index: 0x0
```

**Comment by Keith-CY** [comment]
Logo should be updated: 
![stablecoin-RUSD2](https://github.com/user-attachments/assets/3959cf8c-cf7f-4fa0-895a-e7505dd35d11)

**Comment by Keith-CY** [comment]
Please add RUSD in mainnet @zmcNotafraid 
script info: https://github.com/Magickbase/ckb-explorer-public-issues/issues/775#issuecomment-2403563599
new logo: https://github.com/Magickbase/ckb-explorer-public-issues/issues/775#issuecomment-2403567117

**Comment by Keith-CY** [comment]
RUSD on mainnet https://explorer.nervos.org/xudt/0x71ff665b40ba044b1981ea9a8965189559c8e01e8cdfa34a3cc565e1f870a95c
