### ISSUE TITLE
Leading RGB++ Users to RGB++ Explorer

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#776]
**Is your feature request related to a problem? Please describe.**

RGB++ Explorer https://explorer.rgbpp.io/ is a professional explorer specific for RGB++ Tokens, thus it will provide more detailed and comprehensive info for RGB++ users. It should be treated as the primary entry of RGB++ ecosystem.

Now, most RGB++ users are still tracking RGB++ data on CKB Explorer via the menu in the header. Traffic should be gradually led to RGB++ Explorer.

However, removing the RGB++ menu from the top of the CKB Explorer or redirecting it to the RGB++ Explorer might feel abrupt, especially since the user experience of the RGB++ Explorer is still being improved.

**Describe the solution you'd like**

1.  Add a guide on the RGB++ page of the CKB Explorer to inform users about the dedicated RGB++ Explorer.
2. 	Once the RGB++ Explorer experience meets expectations, notify users that on [insert date], this page will be redirected to the RGB++ Explorer.
3. 	After the specified date, users can still access this page, but a dialog box will notify them, and after a few seconds, they will be redirected to the RGB++ Explorer.
4. 	After a period of redirection, remove the RGB++ menu from the top.

**Describe alternatives you've considered**

**Additional context**

This way, the RGB++ Explorer can start gaining traffic from the CKB Explorer early, while also maintaining flexibility in the timing of the overall function/entry switch.

**Comment by Kirl70** [comment]
According to the requirements, a banner has been added to the RGB++ list page
Design draft:
https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-20864&t=lZeXa6z0fJplEuUu-1
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/bbc7d936-910c-461b-b79d-d3179a16328e">

**Comment by Keith-CY** [comment]
> According to the requirements, a banner has been added to the RGB++ list page Design draft: [figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-20864&t=lZeXa6z0fJplEuUu-1](https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-20864&t=lZeXa6z0fJplEuUu-1) <img alt="image" width="1048" src="https://private-user-images.githubusercontent.com/106060898/362174502-bbc7d936-910c-461b-b79d-d3179a16328e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTQ0NTAsIm5iZiI6MTcyNDkxNDE1MCwicGF0aCI6Ii8xMDYwNjA4OTgvMzYyMTc0NTAyLWJiYzdkOTM2LTkxMGMtNDYxYi1iNzlkLWQzMTc5YTE2MzI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzBiODNkMWU0OGUzMDk0NTQxOTE3YjcxN2YwMjMwNTVjOWU3YjQyMjFlYWJiNWM0YzI0MTE5MGM4NTZmZTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sREPdJPD7bZ5Jet2H0RwMrIP4S2KEb6lNx2u3Ab_nEw">

Will `BTC`, `RGB++` and `UTXO` scroll automatically?

**Comment by Kirl70** [comment]
> > According to the requirements, a banner has been added to the RGB++ list page Design draft: [figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-20864&t=lZeXa6z0fJplEuUu-1](https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-20864&t=lZeXa6z0fJplEuUu-1) <img alt="image" width="1048" src="https://private-user-images.githubusercontent.com/106060898/362174502-bbc7d936-910c-461b-b79d-d3179a16328e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTQ0NTAsIm5iZiI6MTcyNDkxNDE1MCwicGF0aCI6Ii8xMDYwNjA4OTgvMzYyMTc0NTAyLWJiYzdkOTM2LTkxMGMtNDYxYi1iNzlkLWQzMTc5YTE2MzI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzBiODNkMWU0OGUzMDk0NTQxOTE3YjcxN2YwMjMwNTVjOWU3YjQyMjFlYWJiNWM0YzI0MTE5MGM4NTZmZTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sREPdJPD7bZ5Jet2H0RwMrIP4S2KEb6lNx2u3Ab_nEw">
> 
> Will `BTC`, `RGB++` and `UTXO` scroll automatically? Like this https://magicui.design/docs/components/word-rotate

If performance is not an issue, a scrolling effect would be better

**Comment by Keith-CY** [comment]
> > > According to the requirements, a banner has been added to the RGB++ list page Design draft: [figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-20864&t=lZeXa6z0fJplEuUu-1](https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-20864&t=lZeXa6z0fJplEuUu-1) <img alt="image" width="1048" src="https://private-user-images.githubusercontent.com/106060898/362174502-bbc7d936-910c-461b-b79d-d3179a16328e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTQ0NTAsIm5iZiI6MTcyNDkxNDE1MCwicGF0aCI6Ii8xMDYwNjA4OTgvMzYyMTc0NTAyLWJiYzdkOTM2LTkxMGMtNDYxYi1iNzlkLWQzMTc5YTE2MzI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzBiODNkMWU0OGUzMDk0NTQxOTE3YjcxN2YwMjMwNTVjOWU3YjQyMjFlYWJiNWM0YzI0MTE5MGM4NTZmZTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sREPdJPD7bZ5Jet2H0RwMrIP4S2KEb6lNx2u3Ab_nEw">
> > 
> > 
> > Will `BTC`, `RGB++` and `UTXO` scroll automatically? Like this [magicui.design/docs/components/word-rotate](https://magicui.design/docs/components/word-rotate)
> 
> If performance is not an issue, a scrolling effect would be better

It wouldn't be a problem. I will take over this issue @Sven-TBD

**Comment by Keith-CY** [comment]
I found that the banner only appears on the RGB++ transaction page(https://www.figma.com/design/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=35067-20864&node-type=FRAME&t=g9N6jwaWtXC2fuCQ-0), won't it be displayed on RGB++ page(from the top menu) and BTC address page? @Sven-TBD

**Comment by Keith-CY** [comment]
Basically enabled by PR https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1766
