### ISSUE TITLE
After the node is enabled, the interception service interface page should not report an exception.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#777]
**Describe the bug**
After turning on Node mode, some pages should be able to be previewed normally when intercepting the service interface.

**To Reproduce**
1、After turning on Node mode, visit the home/transaction/block/address page；
2、Enter cmd + shift + P in the browser console, enter Show Network request blocking, and enter the window for blocking the network;
3、Click Add Pattern, enter https://mainnet-api.explorer.nervos.org to intercept the server interface；

**Expected behavior**
The home/transaction/block/address page can preview data in Node mode without relying on the server interface..

**Screenshots**
<img width="1439" alt="image" src="https://github.com/user-attachments/assets/cdc0ccdf-7c66-4f57-b691-791feca2ba23">

**Comment by Keith-CY** [comment]
How is this going @PainterPuppets

**Comment by PainterPuppets** [comment]
> How is this going @PainterPuppets

A little tricky. still working on it.
