### ISSUE TITLE
Rack cache with dalli caused max body error

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/ckb-explorer-public-issues#781]
cache error: Value for body:9ffde88a435e3b77ae94fa0d7a0708771fa680b8 over max size: 1048576
Maybe caused by this PR:https://github.com/nervosnetwork/ckb-explorer/commit/ffedb624be57253c8f862db41d537245aedf89a9

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2149

**Comment by zmcNotafraid** [comment]
Many requests of rgb_live_cells  caused this problem

**Comment by zmcNotafraid** [comment]
cache: [GET /api/v1/addresses/ckb1qrgqep8saj8agswr30pls73hra28ry8jlnlc3ejzh3dl2ju7xxpjxqgqq9anc9wda5fc0d0fjngrvfahpumy5qatxs5vjqaf] miss
cache error: Response error 130: Out of memory

**Comment by zmcNotafraid** [comment]
> cache: [GET /api/v1/addresses/ckb1qrgqep8saj8agswr30pls73hra28ry8jlnlc3ejzh3dl2ju7xxpjxqgqq9anc9wda5fc0d0fjngrvfahpumy5qatxs5vjqaf] miss cache error: Response error 130: Out of memory

Fragmentation causing memory to become unavailable

Memcached’s memory management allocates fixed-size memory blocks to store data. If the size of the stored data varies significantly, it can lead to memory fragmentation. As a result, some memory may be free but unusable for storing new data, eventually leading to an “Out of memory” error.

**Comment by guomaoqiu** [comment]
> > cache: [GET /api/v1/addresses/ckb1qrgqep8saj8agswr30pls73hra28ry8jlnlc3ejzh3dl2ju7xxpjxqgqq9anc9wda5fc0d0fjngrvfahpumy5qatxs5vjqaf] miss cache error: Response error 130: Out of memory
> 
> Fragmentation causing memory to become unavailable
> 
> Memcached’s memory management allocates fixed-size memory blocks to store data. If the size of the stored data varies significantly, it can lead to memory fragmentation. As a result, some memory may be free but unusable for storing new data, eventually leading to an “Out of memory” error.
> 
> After restart it seems work.

The memcached service has been monitored. When the available memory is less than 2G, an alarm will be issued and it will be manually restarted.
![image](https://github.com/user-attachments/assets/f37306a0-289d-48fe-8812-81a5e628bc1b)
