### ISSUE TITLE
RGB++ transaction details page Some of the original logic is abnormal.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#783]
**Describe the bug**
RGB++ transaction details page Some of the original logic is abnormal.

**To Reproduce**
1. https://pudge.explorer.nervos.org/transaction/0xccda0d3af3c9e44fde3f7c447fad82390da39ac65b28eae105904255cf4656e4
2. Click the Copy/Download button on the RGB++ transaction details page to retain the original functionality without redirecting to another page.
3. Now click on the red box area in the screenshot and it will jump to https://testnet.explorer.rgbpp.io/en/transaction/0xccda0d3af3c9e44fde3f7c447fad82390da39ac65b28eae105904255cf4656e4

**Expected behavior**
Clicking the red frame area of ​​the screenshot does not require jumping, and clicking the Copy/Download button maintains the original logic.

**Screenshots**
<img width="1307" alt="image" src="https://github.com/user-attachments/assets/546491b1-7d81-4b29-8988-ffa515bbe95c">

**Comment by Keith-CY** [comment]
Should be fixed by https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1773/commits/10387a015127cd0deead5aae9f6bc698f91428a5 and the fix has been deployed on mainnet and testnet
