### ISSUE TITLE
The status in cell info on the address list is not updated.

### ISSUE THREAD

**Issue by FrederLu** [Magickbase/ckb-explorer-public-issues#786]
**Describe the bug**
The status in cell info on the address list is not updated.

**To Reproduce**
https://ckb-explorer-frontend-in-magickbase-repo-feqaaxzn0-magickbase.vercel.app/address/tb1qy69508yfgydz27q2vg9dml9xtsxva2v85n9k6y
output[0]  status is Bound.

**Expected behavior**
https://ckb-explorer-frontend-in-magickbase-repo-feqaaxzn0-magickbase.vercel.app/transaction/0xb3f45daf2b9717a754b6156bfaccaa9c1b56b799fd93976ad39b699344fb0a39
<img width="1279" alt="image" src="https://github.com/user-attachments/assets/6fb2c8e8-6998-490f-8cba-c176429f37f7">
output[0]  status is  abnormal unbind.

**Screenshots**
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/b608bc83-2937-4da8-a43a-0a4e3b3cad4b">

**Comment by rabbitz** [comment]
PR：https://github.com/nervosnetwork/ckb-explorer/pull/2228

**Comment by FrederLu** [comment]
> PR：[nervosnetwork/ckb-explorer#2228](https://github.com/nervosnetwork/ckb-explorer/pull/2228)

Verified.
