### ISSUE TITLE
Mark Stable++ Pool

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#796]
**Is your feature request related to a problem? Please describe.**

Follows are script info of Stable++ pool that can be used for identification

```js
export const stablepp_pool_typescript_main: Script = {
  codeHash:
    "0x26622198b66240e437e323e0fecf1c26ba3c8c28a45f03ed3ebb9f7f2bdc0055",
  hashType: "type" as HashType,
  args: "0x",
};
export const stablepp_pool_typescript_main_out_point: OutPoint = {
  txHash: "0xb22fd5c56a642f2e8447f7fb2bbd4faa85ce09ec9393113b9bdeec2b17cd4f95",
  index: "0x0",
};
export const stablepp_pool_typescript_main_dep: CellDep = {
  outPoint: stablepp_pool_typescript_main_out_point,
  depType: "code" as DepType,
};
```

**Describe the solution you'd like**

1. Add script label in the frontend
2. Mark as pool(name, and tag) in the backend

**Comment by zmcNotafraid** [comment]
All cell's cell_type has set to stablepp_pool @Keith-CY

**Comment by Keith-CY** [comment]
> Just wanna check following with ZMC: @Keith-CY
> 
> 1. Any script info for testnet?
> 2. Stable++ Pool info is just a script rather than a XUDT or UDT right?

Yes, it's neither xUDT nor UDT, just a special cell storing meta info
