### ISSUE TITLE
Data field of a pending cell is incorrect

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#799]
**Describe the bug**
When a cell is pending, its data field is different from the on-chain data
<img width="1044" alt="392702542-e024745a-e412-43a2-8114-a811f9eeb143" src="https://github.com/user-attachments/assets/008e5a2f-e166-4a11-a05f-795201b56526">

It will be correct when the cell is committed.

**Additional context**
Not everyone is incorrect, happens occasionally.

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2325
