### ISSUE TITLE
Support DAS

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#8]
- [ ] display das alias
- [ ] support searching das alias

**Comment by ShiningRay** [comment]
How to display DAS alias. UI/UX design should be provided ahead.
Shall we display search hint while searching das alias?

**Comment by ShiningRay** [comment]
https://docs.did.id/developers

**Comment by Keith-CY** [comment]
There're 3 types to adopt das indexer

1. front-end requests das indexer with one address and requests multiple times;
2. front-end requests das indexer with a batch of addresses;
3. backend returns addresses with das alias.

**Comment by Keith-CY** [comment]
> There're 3 schemas to adopt das indexer
> 
> 1. front-end requests das indexer with one address and requests multiple times;
> 2. front-end requests das indexer with a batch of addresses;
> 3. backend returns addresses with das alias.

I prefer 2 or 3

Specifically for the option 2,front-end can combine two requests(1 to explorer backend and 1 to das indexer) into one and everything works as before.

**Comment by Keith-CY** [comment]
Backend PR: https://github.com/Magickbase/ckb-explorer-public-issues/issues/8

**Comment by ShiningRay** [comment]
由于缺乏CKB相应的签名工具，所以DAS没有对CKB地址做直接的反向解析

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/9770/200801289-f7ace0c9-9c8e-47a2-93a5-bf6d4dab2ed6.png">

以上面这个 ckb 地址为例，算法 id 为 3 和5 的都属于 evm 链的签名算法，3是 personal sign ，5 是 eip712 ，这两种算法id 后面跟的地址就是 eth 的地址了

遇到这种 lock 查 reverse 接口的时候，chainid 参数填 1  coin type 就留空，然后 key 就填 owner 地址

例如 https://explorer.nervos.org/address/ckb1qzfhdsa4syv599s2s3nfrctwga70g0tu07n9gpnun9ydlngf5vsnwqg98fk2kversvl4xa2dkssz746pw4kyxmk7q5axe2enywpn75m4fk6zqt6hg96kcsmwmctledq6

```
curl -X POST https://indexer-basic.da.systems/v1/reverse/record -d'{"type": "blockchain","key_info":{"coin_type": "","chain_id": "1","key": "0x3a6cab3323833f53754db4202f5741756c436ede"}}'
```

**Comment by ShiningRay** [comment]
@Keith-CY The DAS related API is deployed to the staging environment. 
You can start the frontend job.

**Comment by Keith-CY** [comment]
@Keith-CY add detailed PRD

**Comment by Keith-CY** [comment]
I found the description in [Support .bit resolution](https://github.com/Magickbase/godwoken_explorer/issues/1170) is straight enough, so paste it here

---

.bit is a did service running on CKB which is similar to [ENS](https://ens.domains/) but much more powerful.

In this feature, only the domain function of .bit will be considered so we can learn the design from **ENS on etherscan.io**


### Display

If an address has a .bit domain
1. show the .bit domain prior to the address
Some details on page https://etherscan.io/address/0xd8da6bf26964af9d7eed9e03e53415d37aa96045
![image](https://user-images.githubusercontent.com/7271329/205018857-80b177aa-06b5-49b2-a5e2-a56d6c73cab4.png)
![image](https://user-images.githubusercontent.com/7271329/205018902-e833a40a-da9a-4f6b-a2c5-ae621e88f18b.png)
Some details on the transaction page
![image](https://user-images.githubusercontent.com/7271329/205019476-21e6e8c4-a9cd-422f-a094-9846e5e05bd6.png)

2. show the .bit domain on the account page
Some details on page https://etherscan.io/address/0xd8da6bf26964af9d7eed9e03e53415d37aa96045
![image](https://user-images.githubusercontent.com/7271329/205019089-75400220-0ccb-4e83-ac58-91f6f0991879.png)

The .bit domain will be displayed on the account page and a .bit page(e.g. https://data.did.id/dear.bit) will be opened in a new tab by clicking on it

PS: the tooltip on hovering the domain varies on different pages, some display `domain(address)` and some display `address`, on gwscan it could be simply `address`

### Search
If a .bit domain is found by searching, gwscan will navigate to the account page directly, which is different from etherscan.io, on etherscan there's a [ens lookup` page](https://etherscan.io/enslookup-search?search=vitalik.eth), we'll not add a page

---

UI design will be added later

**Comment by Keith-CY** [comment]
FIY, .bit domain has its own avatar/icon, which may be used in UI design

Ref: 
1. random avatar: https://github.com/Magickbase/visual-style-guide/issues/15
2. user-defined avatar: https://github.com/Magickbase/godwoken_explorer/issues/1170#issuecomment-1352731152

**Comment by WhiteMinds** [comment]
I have a few questions I want to confirm:
1. Can one address correspond to two DAS names? Like when two domain names resolve to the same ip address? If so, what does the api return?
2. The DAS name corresponding to the address should be cached. What is the expected caching period? Same as the page lifecycle or persisted to storage?

My thinking goes something like this, implement a high-level (presumably global) DAS name cache management that might provide several such apis:
```
// Return the cache hit directly, or if it is missed, return null and start the request (the batch request may be implemented internally with a throttling or other policy.
useDASName(address: string): string | null
// or useDASProfile(address: string): { avatar?: string; name: string } | null

// Manually assign a batch request policy
useDASPrefetch(addresses: string[]): void
```

**Comment by Keith-CY** [comment]
> 1. Can one address correspond to two DAS names? Like when two domain names resolve to the same ip address? If so, what does the api return?

No, one address points to at most one domain.
![image](https://user-images.githubusercontent.com/7271329/209263328-5abb1a4d-ee4f-40ea-ba94-112060755dcf.png)
One address can only pick one of its owned domains as its alias(which can be resolved reversely)
Ref: https://www.did.id/bit-alias

> 2. The DAS name corresponding to the address should be cached. What is the expected caching period? Same as the page lifecycle or persisted to storage?

Same as page lifecycle is enough, it doesn't cost too much

**Comment by Keith-CY** [comment]
Blocked by a refactoring on displaying truncated address: https://github.com/Magickbase/ckb-explorer-public-issues/issues/134

**Comment by WhiteMinds** [comment]
The bit avatars obtained via `https://display.did.id/identicon/{alias}` all have a white background, according to the design, we need one with a transparent background, and I am now asking in the DAS community if there is a corresponding api.

**Comment by WhiteMinds** [comment]
> The bit avatars obtained via `https://display.did.id/identicon/{alias}` all have a white background, according to the design, we need one with a transparent background, and I am now asking in the DAS community if there is a corresponding api.

This is simply handled by the `border-radius: 50%`.

**Comment by WhiteMinds** [comment]
https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1164

**Comment by Keith-CY** [comment]
![image](https://user-images.githubusercontent.com/7271329/212817028-4f39f512-1283-441f-a404-9dfe3f121149.png)

FYI:
A .bit name is bound to an `owner address` which derives from a private key. And a CKB address derives from `code_hash + hash_type + args`.

In this case, `args` consists of `owner address algorithm id` + owner address` + `manager address algorithm id` + `manager address`

So a .bit name is bound to multiple CKB addresses because `algorithm id` is an enum(03, 05).

The advice from .bit team is that only id algorithm 05 is massively adopted and 03 is rare.

So on ckb explorer, only `args = 05 + owner address + 05 + manager address` will be parsed to a .bit name
