### ISSUE TITLE
On mainnet, click search on the navigation bar, other navigation labels disappear

### ISSUE THREAD

**Issue by Dawn-githup** [Magickbase/ckb-explorer-public-issues#80]
## **Describe the bug**
On mainnet, click search on the navigation bar, other navigation labels disappear

1. Click Search on the navigation bar on mainnet

![image](https://user-images.githubusercontent.com/77844990/195310526-44ba4e6d-a8af-4334-b12b-bfa3f634d498.png)

**Comment by Keith-CY** [comment]
> ## **Describe the bug**
> On mainnet, click search on the navigation bar, other navigation labels disappear
> 
> Steps to reproduce the behavior:
> 
> 1. Click Search on the navigation bar on mainnet
> 
> ![image](https://user-images.githubusercontent.com/77844990/195310526-44ba4e6d-a8af-4334-b12b-bfa3f634d498.png)

I think it's by design for pad layout
![image](https://user-images.githubusercontent.com/7271329/195311220-70fcdbed-4b0f-407f-b46a-4af4a572a2d6.png)

But it's indeed a problem that is unable to blur the search field to recover navigators in the header.

**Comment by Keith-CY** [comment]
Please set `project` to `Nervos Wallet/Explorer` so it will appear in https://github.com/orgs/Magickbase/projects/1/views/11

And a `bug` label could be marked

**Comment by Dawn-githup** [comment]
> Please set `project` to `Nervos Wallet/Explorer` so it will appear in https://github.com/orgs/Magickbase/projects/1/views/11
> 
> And a `bug` label could be marked

> ok
