### ISSUE TITLE
Add token info of USDI

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#803]
**Is your feature request related to a problem? Please describe.**
USDI is another xUDT-compatible token that conforms to regulation.

The team want to add token info on mainnet/testnet explorer

```
# mainnet
script: {
    "code_hash": "0xbfa35a9c38a676682b65ade8f02be164d48632281477e36f8dc2f41f79e56bfc",
    "args": "0xd591ebdc69626647e056e13345fd830c8b876bb06aa07ba610479eb77153ea9f",
    "hash_type": "type"
}
name:  USDI
symbol: USDI
decimal: 6
```
Icon
![usdi-logo](https://github.com/user-attachments/assets/a85dc508-e840-48d8-b336-4235793b52d0)

testnet: https://testnet.explorer.nervos.org/xudt/0x07ac97b5ff3df4b49f59a59f4d80d33d22c1263a57467c512c93b9c29b7a0de3

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2360
