### ISSUE TITLE
Remove TxDisplayInfo table, refactor display info cache.

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#82]
This table is used for caching transactions' inputs/outputs used for frontend.
IMHO, this is redudent and can be stored in Rails.cache.
And in order to avoid inconsistence and reduce code complexity, I suggest to remove this table and refactor "display_info" cache in json serialization.

**Comment by iamyates** [comment]
1. TxDisplayInfo is a table, but acts like a `view`, and also acts like cache. It has 400+w records.
2. so step1 let just remove this table ( don't use the cache )
3. it everything works well, then add new cache , to related `serializers`, e.g. `app/serializers/ckb_transaction_serializer.rb`

**Comment by zmcNotafraid** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1265

**Comment by zmcNotafraid** [comment]
Selftest:
Ckb transaction detail page can display and have cache.
<img width="1748" alt="image" src="https://user-images.githubusercontent.com/12708910/236819452-a62f338c-4905-4eb0-a8a8-c1ba76df8434.png">
