### ISSUE TITLE
Split block processor script into smaller pieces.

### ISSUE THREAD

**Issue by ShiningRay** [Magickbase/ckb-explorer-public-issues#83]
the `new_node_data_processor.rb` is too large with 1396 lines, and the `ckb_utils.rb` has 431 lines.
They are too complex to maintain.
So we want to refactor these codes into smaller pieces for future extension.
The possible approaches:
1. split process and revert logic into different classes
2. use local instance variables to store processing context like "local_block", instead of passing parameters into method. Remove LocalCache.
3. split process logics into smaller "steps", putting each step into its own class. Maybe we should set up a base class for step.
4. don't use bulk insert. this may cause unpredictable behaviors easily. Put the creation/deletion logic of records with association relation into models or separate task/action class.
5. put some callbacks like count increment/decrement into database, using triggers.

**Comment by iamyates** [comment]
remove LocalCache PR: https://github.com/nervosnetwork/ckb-explorer/pull/1057

**Comment by Sven-TBD** [comment]
I'm closing this issue coz it's done in the PR above. @zmcNotafraid
