### ISSUE TITLE
Show rejected transaction with detailed message

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#86]
Currently, if a transaction is rejected, it will be shown with `status: rejected` with a question mark next to it, the message is obscure `At least one input is invalid`

But the reason why a transaction is rejected can be fetched by rpc `get_transaction` and the result is as follows
```
{"jsonrpc":"2.0","result":{"transaction":null,"tx_status":{"block_hash":null,"reason":"{"type":"Resolve","description":"Resolve failed Dead(OutPoint(0x8dbf552ea6278ee765421e288acbf0489c8d55172954a10d8fec2257a76e713f00000000))"}","status":"rejected"}},"id":42}
```

The real message could be stored and delivered with the rejected transaction to locate the underlying reason.

Ref:
A rejected transaction: https://explorer.nervos.org/transaction/0xed2049c21ffccfcd26281d60f8f77ff117adb9df9d3f8cbe5fe86e893c66d359

**Comment by iamyates** [comment]
We can do this by changing `workers/PoolTransactionCheckWorker.rb`:

from: 

![image](https://user-images.githubusercontent.com/105087155/197127853-18230743-c577-431b-a285-75be95b201b0.png)

to : 
```
class PoolTransactionCheckWorker
  include Sidekiq::Worker

  def perform
    pool_tx_entry_attributes = []
    # TODO: query from RPC server for the rejected-detailed-message, then save it to DB
    # PoolTransactionEntry.upsert_all ... 
  end
end
```

need to add a `detailed_message` column to the table.

**Comment by iamyates** [comment]
related PR:  https://github.com/nervosnetwork/ckb-explorer/pull/1044

**Comment by Keith-CY** [comment]
Front-end PR: https://github.com/nervosnetwork/ckb-explorer-frontend/pull/1099

**Comment by Keith-CY** [comment]
For now, only the transactions rejected in the future will contain the message, am I right?

**Comment by iamyates** [comment]
> For now, only the transactions rejected in the future will contain the message, am I right?

Yes , you are right ~

**Comment by Keith-CY** [comment]
`Reject reason` of a rejected transaction has been enabled at the same place where the constant prompt `At least one input is invalid` was

![image](https://user-images.githubusercontent.com/7271329/200503061-9a9606c0-07e6-42dc-927f-ccdce85ed47a.png)
https://explorer.nervos.org/transaction/0x34c8901be944cbc847f46dea36d3590c69a4e514e031111c91b110205f3f2901

Historic data will be updated soon @zhangsoledad
