### ISSUE TITLE
NRC 721's token id is shown mistakenly in scientific notation

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#88]
Page: https://pudge.explorer.nervos.org/nft-collections/16717
API result
![image](https://user-images.githubusercontent.com/7271329/196617997-ea74df38-8f3a-4539-a939-8bd9fee2127d.png)

**Comment by Keith-CY** [comment]
Please add the PR link here and close this issue @ShiningRay

**Comment by ShiningRay** [comment]
https://github.com/nervosnetwork/ckb-explorer/pull/1039 already merged
