### ISSUE TITLE
run unit test with pg correct version(14) when a PR is triggered 

### ISSUE THREAD

**Issue by iamyates** [Magickbase/ckb-explorer-public-issues#90]
The postgres released v15 and the latest official docker image is also upgraded to v15.
The version of our postgres image specify in github action is omitted so Github Action will pull the latest version of pg.
But the `pg_dump` in our rails test image is not compatible with pg15 and raised error to cause CI error.

**Comment by ShiningRay** [comment]
Finished in https://github.com/nervosnetwork/ckb-explorer/pull/1043
