### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#94]
![image](https://user-images.githubusercontent.com/7271329/197672217-de6a4268-8ea1-4910-88b4-bc9352c90144.png)
https://github.com/Magickbase/ckb-explorer/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

Renovate will check dependencies periodically and has proposed many updates, but some of them are breaking changes so we have to update codes for compatibility.

**Comment by iamyates** [comment]
job done. 

After upgrade to rails7, it's 2.1.0 now (latest version) 

```
spring-watcher-listen (2.1.0)
```

**Comment by iamyates** [comment]
in this PR: https://github.com/nervosnetwork/ckb-explorer/pull/1059
