### ISSUE TITLE
Upgrade ckb node to v0.105.0

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/ckb-explorer-public-issues#95]
ckb@0.105.0(https://github.com/nervosnetwork/ckb/releases/tag/v0.105.0)

Notice that `ckb-indexer` has been integrated into `ckb-node`, if ckb explorer depends on `ckb-indexer`, it may have changes.

**Comment by ShiningRay** [comment]
Meng is planning the migration to K8S. I suggest to make him setup this new version of ckb node on our future K8S platform.

**Comment by Keith-CY** [comment]
> Meng is planning the migration to K8S. I suggest to make him setup this new version of ckb node on our future K8S platform.

Got it
