### ISSUE TITLE
ckb explorer 增加ckb gas 和ckb txspending 数据显示

### ISSUE THREAD

**Issue by jiangxianliang007** [Magickbase/ckb-explorer-public-issues#99]
1、增加 ckb gas 显示 类似 https://etherscan.io/gastracker

2、增加 ckb  txspending 显示，类似https://etherscan.io/txsPending

**Comment by ShiningRay** [comment]
第二点： 目前我们已经有tx pool的数据，需要进行前端的数据和开发，相对简单

第一点， gas tracker是一个比较庞大和复杂的需求
首先gas tracker不仅要统计过去的gas 使用和gas price记录，还要对未来的gas price进行预测和推荐
这里有使用的gas price的价格和预计被打包的时间
我们是不是需要做这么复杂的功能？

**Comment by jiangxianliang007** [comment]
可以先简单点，比如能显示网络中过去一段时间的 gas 变化， 以及当前的 gas ,这样可以参考 explorer 上的数据 设置合理的 gas 

再提个需求：
3、explorer 能否增加图表显示过去一段时间内/一定数量的区块，旷工的版本号？
![image](https://user-images.githubusercontent.com/24754263/199183257-20be20c2-fee8-4ff5-ac7f-a85bd1181c10.png)

**Comment by ShiningRay** [comment]
矿工版本号我不知道现在的explorer有没有记录过
我只在数据库的Block表里面看到一个version字段，不清楚是不是ckb版本号

**Comment by jiangxianliang007** [comment]
有记录的，
![image](https://user-images.githubusercontent.com/24754263/199186327-a95cb50b-d2c7-4790-9ed0-3b7336f4132c.png)

**Comment by ShiningRay** [comment]
ok 那没啥问题

**Comment by Keith-CY** [comment]
Details will be added in 3 separate issues @Keith-CY

**Comment by Keith-CY** [comment]
PRD of pending transactions: https://github.com/Magickbase/ckb-explorer-public-issues/issues/130

**Comment by Keith-CY** [comment]
PRD of fee rate tracker: https://github.com/Magickbase/ckb-explorer-public-issues/issues/131

**Comment by Keith-CY** [comment]
PRD of miner versions: https://github.com/Magickbase/ckb-explorer-public-issues/issues/137
